//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mandante.Home {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tabla {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tabla() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Mandante.Home.Tabla", typeof(Tabla).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a.
        /// </summary>
        public static string Lbl_A {
            get {
                return ResourceManager.GetString("Lbl_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ant.
        /// </summary>
        public static string Lbl_Anterior {
            get {
                return ResourceManager.GetString("Lbl_Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        public static string Lbl_De {
            get {
                return ResourceManager.GetString("Lbl_De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrando.
        /// </summary>
        public static string Lbl_Mostrando {
            get {
                return ResourceManager.GetString("Lbl_Mostrando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar.
        /// </summary>
        public static string Lbl_Mostrar {
            get {
                return ResourceManager.GetString("Lbl_Mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros.
        /// </summary>
        public static string Lbl_Registros {
            get {
                return ResourceManager.GetString("Lbl_Registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sig.
        /// </summary>
        public static string Lbl_Siguiente {
            get {
                return ResourceManager.GetString("Lbl_Siguiente", resourceCulture);
            }
        }
    }
}
