//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.Empresa {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CrearEditar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrearEditar() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.Empresa.CrearEditar", typeof(CrearEditar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Empresa.
        /// </summary>
        public static string Lnk_Datos_Empresa {
            get {
                return ResourceManager.GetString("Lnk_Datos_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos.
        /// </summary>
        public static string Lnk_Documentos {
            get {
                return ResourceManager.GetString("Lnk_Documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Msg_Btn_Cancel {
            get {
                return ResourceManager.GetString("Msg_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si, Eliminar.
        /// </summary>
        public static string Msg_Btn_Eliminar {
            get {
                return ResourceManager.GetString("Msg_Btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar este documento?.
        /// </summary>
        public static string Msg_ConfirmarEliminar {
            get {
                return ResourceManager.GetString("Msg_ConfirmarEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos guardados correctamente.
        /// </summary>
        public static string Msg_GuardarInformacionOk {
            get {
                return ResourceManager.GetString("Msg_GuardarInformacionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email Hotel incorrecto.
        /// </summary>
        public static string Val_Email_Hotel_Email {
            get {
                return ResourceManager.GetString("Val_Email_Hotel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acrónimo debe tener 50 caracteres com máximo.
        /// </summary>
        public static string Val_MaxLength_Acronimo {
            get {
                return ResourceManager.GetString("Val_MaxLength_Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueo Casino debe tener 2 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Bloqueo_Casino {
            get {
                return ResourceManager.GetString("Val_MaxLength_Bloqueo_Casino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Ciudad {
            get {
                return ResourceManager.GetString("Val_MaxLength_Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comite Paritario debe tener 2 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Comite_Paritario {
            get {
                return ResourceManager.GetString("Val_MaxLength_Comite_Paritario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Direccion {
            get {
                return ResourceManager.GetString("Val_MaxLength_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email Administrador debe tener 150 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Email_Administrador {
            get {
                return ResourceManager.GetString("Val_MaxLength_Email_Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email de Contacto Licitaciones debe tener 150 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Email_Contacto_Licitaciones {
            get {
                return ResourceManager.GetString("Val_MaxLength_Email_Contacto_Licitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email Representante Legal debe tener 150 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Email_Representante_Legal {
            get {
                return ResourceManager.GetString("Val_MaxLength_Email_Representante_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fax debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Fax {
            get {
                return ResourceManager.GetString("Val_MaxLength_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Bloqueo debe tener 8 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Fecha_Bloqueo {
            get {
                return ResourceManager.GetString("Val_MaxLength_Fecha_Bloqueo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fono Administrador debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Fono_Administrador {
            get {
                return ResourceManager.GetString("Val_MaxLength_Fono_Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fono Faena debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Fono_Faena {
            get {
                return ResourceManager.GetString("Val_MaxLength_Fono_Faena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto Hotel debe tener 100 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Hotel_Contacto {
            get {
                return ResourceManager.GetString("Val_MaxLength_Hotel_Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Hotel_Email {
            get {
                return ResourceManager.GetString("Val_MaxLength_Hotel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres debe tener 100 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Hotel_Nombres {
            get {
                return ResourceManager.GetString("Val_MaxLength_Hotel_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Hotel_Telefono {
            get {
                return ResourceManager.GetString("Val_MaxLength_Hotel_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Administrador debe tener 10 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_ID_Administrador {
            get {
                return ResourceManager.GetString("Val_MaxLength_ID_Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Hotel debe tener 10 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_ID_Hotel {
            get {
                return ResourceManager.GetString("Val_MaxLength_ID_Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUT Representante Legal debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_ID_Representante_Legal {
            get {
                return ResourceManager.GetString("Val_MaxLength_ID_Representante_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Empresa debe tener 11 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_IDEmpresa {
            get {
                return ResourceManager.GetString("Val_MaxLength_IDEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Administrador debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Nombre_Administrador {
            get {
                return ResourceManager.GetString("Val_MaxLength_Nombre_Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Empresa debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Nombre_Empresa {
            get {
                return ResourceManager.GetString("Val_MaxLength_Nombre_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Representante Legal debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Nombre_Representante_Legal {
            get {
                return ResourceManager.GetString("Val_MaxLength_Nombre_Representante_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Pais {
            get {
                return ResourceManager.GetString("Val_MaxLength_Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regíon debe tener 5 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Region {
            get {
                return ResourceManager.GetString("Val_MaxLength_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reglamento Interno debe tener 2 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Reglamento_Interno {
            get {
                return ResourceManager.GetString("Val_MaxLength_Reglamento_Interno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rubro debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Rubro {
            get {
                return ResourceManager.GetString("Val_MaxLength_Rubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Telefono {
            get {
                return ResourceManager.GetString("Val_MaxLength_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación Faena debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Ubicacion_Faena {
            get {
                return ResourceManager.GetString("Val_MaxLength_Ubicacion_Faena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fax solo números.
        /// </summary>
        public static string Val_Number_Fax {
            get {
                return ResourceManager.GetString("Val_Number_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fono Administrador solo números.
        /// </summary>
        public static string Val_Number_Fono_Administrador {
            get {
                return ResourceManager.GetString("Val_Number_Fono_Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fono Faena solo números.
        /// </summary>
        public static string Val_Number_Fono_Faena {
            get {
                return ResourceManager.GetString("Val_Number_Fono_Faena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Hotel solo números.
        /// </summary>
        public static string Val_Number_Hotel_Telefono {
            get {
                return ResourceManager.GetString("Val_Number_Hotel_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Hotel solo números.
        /// </summary>
        public static string Val_Number_ID_Hotel {
            get {
                return ResourceManager.GetString("Val_Number_ID_Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Empresa solo números.
        /// </summary>
        public static string Val_Number_IDEmpresa {
            get {
                return ResourceManager.GetString("Val_Number_IDEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono solo números.
        /// </summary>
        public static string Val_Number_Telefono {
            get {
                return ResourceManager.GetString("Val_Number_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acrónimo es requerido.
        /// </summary>
        public static string Val_Required_Acronimo {
            get {
                return ResourceManager.GetString("Val_Required_Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Bloqueo Casino.
        /// </summary>
        public static string Val_Required_Bloqueo_Casino {
            get {
                return ResourceManager.GetString("Val_Required_Bloqueo_Casino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Ciudad.
        /// </summary>
        public static string Val_Required_Ciudad {
            get {
                return ResourceManager.GetString("Val_Required_Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Comite Paritario.
        /// </summary>
        public static string Val_Required_Comite_Paritario {
            get {
                return ResourceManager.GetString("Val_Required_Comite_Paritario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección es requerido.
        /// </summary>
        public static string Val_Required_Direccion {
            get {
                return ResourceManager.GetString("Val_Required_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email Administrador es requerido.
        /// </summary>
        public static string Val_Required_Email_Administrador {
            get {
                return ResourceManager.GetString("Val_Required_Email_Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email de Contacto Licitaciones es requerido.
        /// </summary>
        public static string Val_Required_Email_Contacto_Licitaciones {
            get {
                return ResourceManager.GetString("Val_Required_Email_Contacto_Licitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email Representante Legal es requerido.
        /// </summary>
        public static string Val_Required_Email_Representante_Legal {
            get {
                return ResourceManager.GetString("Val_Required_Email_Representante_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fax es requerido.
        /// </summary>
        public static string Val_Required_Fax {
            get {
                return ResourceManager.GetString("Val_Required_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Fecha Bloqueo.
        /// </summary>
        public static string Val_Required_Fecha_Bloqueo {
            get {
                return ResourceManager.GetString("Val_Required_Fecha_Bloqueo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fono Administrador es requerido.
        /// </summary>
        public static string Val_Required_Fono_Administrador {
            get {
                return ResourceManager.GetString("Val_Required_Fono_Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fono Faena es requerido.
        /// </summary>
        public static string Val_Required_Fono_Faena {
            get {
                return ResourceManager.GetString("Val_Required_Fono_Faena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto Hotel es requerido.
        /// </summary>
        public static string Val_Required_Hotel_Contacto {
            get {
                return ResourceManager.GetString("Val_Required_Hotel_Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email es requerido.
        /// </summary>
        public static string Val_Required_Hotel_Email {
            get {
                return ResourceManager.GetString("Val_Required_Hotel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres es requerido.
        /// </summary>
        public static string Val_Required_Hotel_Nombre {
            get {
                return ResourceManager.GetString("Val_Required_Hotel_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono es requerido.
        /// </summary>
        public static string Val_Required_Hotel_Telefono {
            get {
                return ResourceManager.GetString("Val_Required_Hotel_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Administrador es requerido.
        /// </summary>
        public static string Val_Required_ID_Administrador {
            get {
                return ResourceManager.GetString("Val_Required_ID_Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Hotel es requerido.
        /// </summary>
        public static string Val_Required_ID_Hotel {
            get {
                return ResourceManager.GetString("Val_Required_ID_Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUT Representate Legal es requerido.
        /// </summary>
        public static string Val_Required_ID_Representante_Legal {
            get {
                return ResourceManager.GetString("Val_Required_ID_Representante_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Empresa es requerido.
        /// </summary>
        public static string Val_Required_IDEmpresa {
            get {
                return ResourceManager.GetString("Val_Required_IDEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Administrador es requerido.
        /// </summary>
        public static string Val_Required_Nombre_Administrador {
            get {
                return ResourceManager.GetString("Val_Required_Nombre_Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Empresa es requerido.
        /// </summary>
        public static string Val_Required_Nombre_Empresa {
            get {
                return ResourceManager.GetString("Val_Required_Nombre_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Representante Legal es requerido.
        /// </summary>
        public static string Val_Required_Nombre_Representante_Legal {
            get {
                return ResourceManager.GetString("Val_Required_Nombre_Representante_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione País.
        /// </summary>
        public static string Val_Required_Pais {
            get {
                return ResourceManager.GetString("Val_Required_Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Región.
        /// </summary>
        public static string Val_Required_Region {
            get {
                return ResourceManager.GetString("Val_Required_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Reglamento Interno.
        /// </summary>
        public static string Val_Required_Reglamento_Interno {
            get {
                return ResourceManager.GetString("Val_Required_Reglamento_Interno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rubro es requerido.
        /// </summary>
        public static string Val_Required_Rubro {
            get {
                return ResourceManager.GetString("Val_Required_Rubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono es requerido.
        /// </summary>
        public static string Val_Required_Telefono {
            get {
                return ResourceManager.GetString("Val_Required_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación Faena es requerido.
        /// </summary>
        public static string Val_Required_Ubicacion_Faena {
            get {
                return ResourceManager.GetString("Val_Required_Ubicacion_Faena", resourceCulture);
            }
        }
    }
}
