//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.InformesEmpresas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InformeFichaEmpresa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformeFichaEmpresa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.InformesEmpresas.InformeFichaEmpresa", typeof(InformeFichaEmpresa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha Empresa.
        /// </summary>
        public static string Lbl_FichaEmpresa {
            get {
                return ResourceManager.GetString("Lbl_FichaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Usuarios.
        /// </summary>
        public static string Lnk_VerUsuarios {
            get {
                return ResourceManager.GetString("Lnk_VerUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        public static string Msg_Nota {
            get {
                return ResourceManager.GetString("Msg_Nota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos del reporte corresponden a la Fecha Actual que se muestra en la parte superior del informe.
        /// </summary>
        public static string Msg_NotaMensaje {
            get {
                return ResourceManager.GetString("Msg_NotaMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrónimo.
        /// </summary>
        public static string Tblb_Datos_Acronimo {
            get {
                return ResourceManager.GetString("Tblb_Datos_Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaboradores.
        /// </summary>
        public static string Tblb_Datos_Colaboradores {
            get {
                return ResourceManager.GetString("Tblb_Datos_Colaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string Tblb_Datos_Direccion {
            get {
                return ResourceManager.GetString("Tblb_Datos_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Tblb_Datos_Email {
            get {
                return ResourceManager.GetString("Tblb_Datos_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giro.
        /// </summary>
        public static string Tblb_Datos_Giro {
            get {
                return ResourceManager.GetString("Tblb_Datos_Giro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Tblb_Datos_ID {
            get {
                return ResourceManager.GetString("Tblb_Datos_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón Social.
        /// </summary>
        public static string Tblb_Datos_RazonSocial {
            get {
                return ResourceManager.GetString("Tblb_Datos_RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonos.
        /// </summary>
        public static string Tblb_Datos_Telefonos {
            get {
                return ResourceManager.GetString("Tblb_Datos_Telefonos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratos Activos.
        /// </summary>
        public static string Tblh_Grid_ContratosActivos {
            get {
                return ResourceManager.GetString("Tblh_Grid_ContratosActivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionarios Autorizados y Acreditados.
        /// </summary>
        public static string Tblh_Grid_FuncionariosAutorizadosyAcreditados {
            get {
                return ResourceManager.GetString("Tblh_Grid_FuncionariosAutorizadosyAcreditados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionarios En Nómina.
        /// </summary>
        public static string Tblh_Grid_FuncionariosEnNomina {
            get {
                return ResourceManager.GetString("Tblh_Grid_FuncionariosEnNomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación.
        /// </summary>
        public static string Tblh_Grid_Operacion {
            get {
                return ResourceManager.GetString("Tblh_Grid_Operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehículos.
        /// </summary>
        public static string Tblh_Grid_Vehículos {
            get {
                return ResourceManager.GetString("Tblh_Grid_Vehículos", resourceCulture);
            }
        }
    }
}
