//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mandante.Certificacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CertificarTransporteEditar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CertificarTransporteEditar() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Mandante.Certificacion.CertificarTransporteEditar", typeof(CertificarTransporteEditar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Btn_Guardar {
            get {
                return ResourceManager.GetString("Btn_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Datos Vehiculo.
        /// </summary>
        public static string Btn_GuardarDatosVehiculo {
            get {
                return ResourceManager.GetString("Btn_GuardarDatosVehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Btn_GuardarDesautorizacion {
            get {
                return ResourceManager.GetString("Btn_GuardarDesautorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Chk_Empresa {
            get {
                return ResourceManager.GetString("Chk_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona.
        /// </summary>
        public static string Chk_Persona {
            get {
                return ResourceManager.GetString("Chk_Persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acronimo.
        /// </summary>
        public static string Lbl_Acronimo {
            get {
                return ResourceManager.GetString("Lbl_Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        public static string Lbl_Advertencia {
            get {
                return ResourceManager.GetString("Lbl_Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string Lbl_Anio {
            get {
                return ResourceManager.GetString("Lbl_Anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Lbl_ApellidosFuncionario {
            get {
                return ResourceManager.GetString("Lbl_ApellidosFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        public static string Lbl_Color {
            get {
                return ResourceManager.GetString("Lbl_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisiones.
        /// </summary>
        public static string Lbl_Divisiones {
            get {
                return ResourceManager.GetString("Lbl_Divisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento Sustento.
        /// </summary>
        public static string Lbl_DocumentoSustento {
            get {
                return ResourceManager.GetString("Lbl_DocumentoSustento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dueño.
        /// </summary>
        public static string Lbl_Duenio {
            get {
                return ResourceManager.GetString("Lbl_Duenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acronimo Empresa.
        /// </summary>
        public static string Lbl_DuenioAcronimoEmpresa {
            get {
                return ResourceManager.GetString("Lbl_DuenioAcronimoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Lbl_DuenioApellidos {
            get {
                return ResourceManager.GetString("Lbl_DuenioApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string Lbl_DuenioId {
            get {
                return ResourceManager.GetString("Lbl_DuenioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Empresa.
        /// </summary>
        public static string Lbl_DuenioIdEmpresa {
            get {
                return ResourceManager.GetString("Lbl_DuenioIdEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Lbl_DuenioNombres {
            get {
                return ResourceManager.GetString("Lbl_DuenioNombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificacion Transporte.
        /// </summary>
        public static string Lbl_Editar {
            get {
                return ResourceManager.GetString("Lbl_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Lbl_Empresa {
            get {
                return ResourceManager.GetString("Lbl_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipamiento ADAS.
        /// </summary>
        public static string Lbl_EquipamientoADAS {
            get {
                return ResourceManager.GetString("Lbl_EquipamientoADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia Vehiculo.
        /// </summary>
        public static string Lbl_Familia {
            get {
                return ResourceManager.GetString("Lbl_Familia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Femenino.
        /// </summary>
        public static string Lbl_Femenino {
            get {
                return ResourceManager.GetString("Lbl_Femenino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historico de Bloqueos.
        /// </summary>
        public static string Lbl_HistoricoBloqueos {
            get {
                return ResourceManager.GetString("Lbl_HistoricoBloqueos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string Lbl_IDEmpresa {
            get {
                return ResourceManager.GetString("Lbl_IDEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string Lbl_IDFuncionario {
            get {
                return ResourceManager.GetString("Lbl_IDFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificacion Index.
        /// </summary>
        public static string Lbl_IndexPrincipal_Titulo {
            get {
                return ResourceManager.GetString("Lbl_IndexPrincipal_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion.
        /// </summary>
        public static string Lbl_Informacion {
            get {
                return ResourceManager.GetString("Lbl_Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string Lbl_Marca {
            get {
                return ResourceManager.GetString("Lbl_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Masculino.
        /// </summary>
        public static string Lbl_Masculino {
            get {
                return ResourceManager.GetString("Lbl_Masculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        public static string Lbl_Modelo {
            get {
                return ResourceManager.GetString("Lbl_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Lbl_NombreEmpresa {
            get {
                return ResourceManager.GetString("Lbl_NombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Lbl_NombresFuncionario {
            get {
                return ResourceManager.GetString("Lbl_NombresFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string Lbl_Observacion {
            get {
                return ResourceManager.GetString("Lbl_Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente.
        /// </summary>
        public static string Lbl_Patente {
            get {
                return ResourceManager.GetString("Lbl_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RFID.
        /// </summary>
        public static string Lbl_RFID {
            get {
                return ResourceManager.GetString("Lbl_RFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo.
        /// </summary>
        public static string Lbl_Sexo {
            get {
                return ResourceManager.GetString("Lbl_Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Bloqueo ?.
        /// </summary>
        public static string Lbl_SolicitudBloqueo {
            get {
                return ResourceManager.GetString("Lbl_SolicitudBloqueo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene Pibox.
        /// </summary>
        public static string Lbl_TienePibox {
            get {
                return ResourceManager.GetString("Lbl_TienePibox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Lbl_Tipo {
            get {
                return ResourceManager.GetString("Lbl_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificacion Transporte.
        /// </summary>
        public static string Lbl_Titulo {
            get {
                return ResourceManager.GetString("Lbl_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno.
        /// </summary>
        public static string Lbl_Turno {
            get {
                return ResourceManager.GetString("Lbl_Turno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultima Modificacion.
        /// </summary>
        public static string Lbl_UltimaModificacion {
            get {
                return ResourceManager.GetString("Lbl_UltimaModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor Modificacion.
        /// </summary>
        public static string Lbl_UltimoAutor {
            get {
                return ResourceManager.GetString("Lbl_UltimoAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa y Divisiones.
        /// </summary>
        public static string Lgn_DatosEmpresaDivisiones {
            get {
                return ResourceManager.GetString("Lgn_DatosEmpresaDivisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Funcionario.
        /// </summary>
        public static string Lgn_DatosFuncionario {
            get {
                return ResourceManager.GetString("Lgn_DatosFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Vehiculo.
        /// </summary>
        public static string Lgn_DatosVehiculo {
            get {
                return ResourceManager.GetString("Lgn_DatosVehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desautorizacion.
        /// </summary>
        public static string Lgn_Desautorizacion {
            get {
                return ResourceManager.GetString("Lgn_Desautorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los Campos Obligatorios estan marcados con asterisco.
        /// </summary>
        public static string Msg_CamposAsterisco {
            get {
                return ResourceManager.GetString("Msg_CamposAsterisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de archivos excede al maximo: {{maxFiles}} .
        /// </summary>
        public static string Msg_Dropzone_CantidadArchivosExcedida {
            get {
                return ResourceManager.GetString("Msg_Dropzone_CantidadArchivosExcedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño actual {{filesize}} excede el maximo: {{maxFilesize}}.
        /// </summary>
        public static string Msg_Dropzone_ExcedeTamanioMaximo {
            get {
                return ResourceManager.GetString("Msg_Dropzone_ExcedeTamanioMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extension invalida.
        /// </summary>
        public static string Msg_Dropzone_ExtensionInvalida {
            get {
                return ResourceManager.GetString("Msg_Dropzone_ExtensionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de archivo excede longitud maxima: ___MAX_LEN.
        /// </summary>
        public static string Msg_Dropzone_LongMaxExcedida {
            get {
                return ResourceManager.GetString("Msg_Dropzone_LongMaxExcedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;strong&gt;Soltar archivos aqui o hacer click. &lt;/strong&gt;&lt;/br&gt;.
        /// </summary>
        public static string Msg_Dropzone_PorDefecto {
            get {
                return ResourceManager.GetString("Msg_Dropzone_PorDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar.
        /// </summary>
        public static string Msg_Dropzone_Quitar {
            get {
                return ResourceManager.GetString("Msg_Dropzone_Quitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionario guardado exitosamente.
        /// </summary>
        public static string Msg_EntidadGuardadaCtte {
            get {
                return ResourceManager.GetString("Msg_EntidadGuardadaCtte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anio.
        /// </summary>
        public static string Phl_Anio {
            get {
                return ResourceManager.GetString("Phl_Anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar ID.
        /// </summary>
        public static string Phl_DuenioId {
            get {
                return ResourceManager.GetString("Phl_DuenioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Empresa.
        /// </summary>
        public static string Phl_IdEmpresa {
            get {
                return ResourceManager.GetString("Phl_IdEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string Phl_NombreEmpresa {
            get {
                return ResourceManager.GetString("Phl_NombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Observaciones.
        /// </summary>
        public static string Phl_Observacion {
            get {
                return ResourceManager.GetString("Phl_Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Sexo.
        /// </summary>
        public static string Phl_Sexo {
            get {
                return ResourceManager.GetString("Phl_Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar tipo.
        /// </summary>
        public static string Phl_Tipo {
            get {
                return ResourceManager.GetString("Phl_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acronimo requerido.
        /// </summary>
        public static string Val_Required_Acronimo {
            get {
                return ResourceManager.GetString("Val_Required_Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos son requeridos.
        /// </summary>
        public static string Val_Required_Apellidos {
            get {
                return ResourceManager.GetString("Val_Required_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo adjunto requerido.
        /// </summary>
        public static string Val_Required_Archivo {
            get {
                return ResourceManager.GetString("Val_Required_Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa es requerida.
        /// </summary>
        public static string Val_Required_Empresa {
            get {
                return ResourceManager.GetString("Val_Required_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre requerido.
        /// </summary>
        public static string Val_Required_NombreEmpresa {
            get {
                return ResourceManager.GetString("Val_Required_NombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre es requerido.
        /// </summary>
        public static string Val_Required_Nombres {
            get {
                return ResourceManager.GetString("Val_Required_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones requeridas.
        /// </summary>
        public static string Val_Required_Observaciones {
            get {
                return ResourceManager.GetString("Val_Required_Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo es requerido.
        /// </summary>
        public static string Val_Required_Sexo {
            get {
                return ResourceManager.GetString("Val_Required_Sexo", resourceCulture);
            }
        }
    }
}
