//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mandante.Certificacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Mandante.Certificacion.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificar Empresa.
        /// </summary>
        public static string Btn_CertificarEmpresa {
            get {
                return ResourceManager.GetString("Btn_CertificarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificar Funcionario.
        /// </summary>
        public static string Btn_CertificarFuncionario {
            get {
                return ResourceManager.GetString("Btn_CertificarFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificar Pase.
        /// </summary>
        public static string Btn_CertificarPase {
            get {
                return ResourceManager.GetString("Btn_CertificarPase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificar Transporte.
        /// </summary>
        public static string Btn_CertificarTransporte {
            get {
                return ResourceManager.GetString("Btn_CertificarTransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Lbl_Apellidos {
            get {
                return ResourceManager.GetString("Lbl_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificacion Empresa.
        /// </summary>
        public static string Lbl_CertificacionEmpresa {
            get {
                return ResourceManager.GetString("Lbl_CertificacionEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificacion Funcionario.
        /// </summary>
        public static string Lbl_CertificacionFuncionario {
            get {
                return ResourceManager.GetString("Lbl_CertificacionFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificacion Pase.
        /// </summary>
        public static string Lbl_CertificacionPase {
            get {
                return ResourceManager.GetString("Lbl_CertificacionPase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificacion Transporte.
        /// </summary>
        public static string Lbl_CertificacionTransporte {
            get {
                return ResourceManager.GetString("Lbl_CertificacionTransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard.
        /// </summary>
        public static string Lbl_Dashboard {
            get {
                return ResourceManager.GetString("Lbl_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Empresa.
        /// </summary>
        public static string Lbl_IdEmpresa {
            get {
                return ResourceManager.GetString("Lbl_IdEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Lbl_IdFuncionario {
            get {
                return ResourceManager.GetString("Lbl_IdFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificacion.
        /// </summary>
        public static string Lbl_IndiceCertificacion {
            get {
                return ResourceManager.GetString("Lbl_IndiceCertificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string Lbl_Marca {
            get {
                return ResourceManager.GetString("Lbl_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        public static string Lbl_Modelo {
            get {
                return ResourceManager.GetString("Lbl_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Empresa.
        /// </summary>
        public static string Lbl_NombreEmpresa {
            get {
                return ResourceManager.GetString("Lbl_NombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Lbl_Nombres {
            get {
                return ResourceManager.GetString("Lbl_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro Pase.
        /// </summary>
        public static string Lbl_NroPase {
            get {
                return ResourceManager.GetString("Lbl_NroPase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente.
        /// </summary>
        public static string Lbl_Patente {
            get {
                return ResourceManager.GetString("Lbl_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Lbl_Tipo {
            get {
                return ResourceManager.GetString("Lbl_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Id Empresa.
        /// </summary>
        public static string Phl_IdEmpresa {
            get {
                return ResourceManager.GetString("Phl_IdEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Id.
        /// </summary>
        public static string Phl_IdFuncionario {
            get {
                return ResourceManager.GetString("Phl_IdFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro Pase.
        /// </summary>
        public static string Phl_NroPase {
            get {
                return ResourceManager.GetString("Phl_NroPase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Patente.
        /// </summary>
        public static string Phl_Patente {
            get {
                return ResourceManager.GetString("Phl_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id de Empresa No Valido.
        /// </summary>
        public static string Val_EmpresaIdNoValido {
            get {
                return ResourceManager.GetString("Val_EmpresaIdNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id de Empresa es requerido.
        /// </summary>
        public static string Val_EmpresaIdRequerido {
            get {
                return ResourceManager.GetString("Val_EmpresaIdRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La empresa ingresada no existe  (validacion remota).
        /// </summary>
        public static string Val_EmpresaRemoteIdNoValido {
            get {
                return ResourceManager.GetString("Val_EmpresaRemoteIdNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id de Funcionario No Valido.
        /// </summary>
        public static string Val_FuncionarioIdInvalido {
            get {
                return ResourceManager.GetString("Val_FuncionarioIdInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id de Funcionario debe tener 2 caracteres como minimo.
        /// </summary>
        public static string Val_FuncionarioIdMinLength {
            get {
                return ResourceManager.GetString("Val_FuncionarioIdMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El funcionario ingresado no existe  (validacion remota).
        /// </summary>
        public static string Val_FuncionarioIdRemoteInvalido {
            get {
                return ResourceManager.GetString("Val_FuncionarioIdRemoteInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id de Funcionario es requerido.
        /// </summary>
        public static string Val_FuncionarioIdRequerido {
            get {
                return ResourceManager.GetString("Val_FuncionarioIdRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pase ingresado no existe (validacion remota).
        /// </summary>
        public static string Val_PaseNroPaseRemoteNoValida {
            get {
                return ResourceManager.GetString("Val_PaseNroPaseRemoteNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro de Pase requerido.
        /// </summary>
        public static string Val_PaseNroPaseRequerido {
            get {
                return ResourceManager.GetString("Val_PaseNroPaseRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro Pase debe esta compuesto solo de digitos.
        /// </summary>
        public static string Val_PaseNroPaseSoloEntero {
            get {
                return ResourceManager.GetString("Val_PaseNroPaseSoloEntero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente ingresada no valida.
        /// </summary>
        public static string Val_TransportePatenteNoValida {
            get {
                return ResourceManager.GetString("Val_TransportePatenteNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El vehiculo ingresado no puede ingresar.
        /// </summary>
        public static string Val_TransportePatenteRemoteNoValida {
            get {
                return ResourceManager.GetString("Val_TransportePatenteRemoteNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente requerida.
        /// </summary>
        public static string Val_TransportePatenteRequerida {
            get {
                return ResourceManager.GetString("Val_TransportePatenteRequerida", resourceCulture);
            }
        }
    }
}
