//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.EmpresaUsuarios {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _InfoColab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _InfoColab() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.EmpresaUsuarios._InfoColab", typeof(_InfoColab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Btn_Guardar {
            get {
                return ResourceManager.GetString("Btn_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string Chk_Activo_No {
            get {
                return ResourceManager.GetString("Chk_Activo_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string Chk_Activo_Si {
            get {
                return ResourceManager.GetString("Chk_Activo_Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string Chk_EnvioAlertas_No {
            get {
                return ResourceManager.GetString("Chk_EnvioAlertas_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string Chk_EnvioAlertas_Si {
            get {
                return ResourceManager.GetString("Chk_EnvioAlertas_Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string Lbl_Activo {
            get {
                return ResourceManager.GetString("Lbl_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Lbl_Apellidos {
            get {
                return ResourceManager.GetString("Lbl_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmacion Contraseña.
        /// </summary>
        public static string Lbl_ConfirmacionContrasenia {
            get {
                return ResourceManager.GetString("Lbl_ConfirmacionContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Lbl_Contrasenia {
            get {
                return ResourceManager.GetString("Lbl_Contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Personales.
        /// </summary>
        public static string Lbl_DatosPersonales {
            get {
                return ResourceManager.GetString("Lbl_DatosPersonales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Lbl_Email {
            get {
                return ResourceManager.GetString("Lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envio Alertas.
        /// </summary>
        public static string Lbl_Envio_Alertas {
            get {
                return ResourceManager.GetString("Lbl_Envio_Alertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Lbl_Nombres {
            get {
                return ResourceManager.GetString("Lbl_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUT.
        /// </summary>
        public static string Lbl_RUT {
            get {
                return ResourceManager.GetString("Lbl_RUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Usuario.
        /// </summary>
        public static string Lbl_TipoUsuario {
            get {
                return ResourceManager.GetString("Lbl_TipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos marcados con (*) son obligatorios.
        /// </summary>
        public static string Msg_CamposAsterisco {
            get {
                return ResourceManager.GetString("Msg_CamposAsterisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion.
        /// </summary>
        public static string Msg_Informacion {
            get {
                return ResourceManager.GetString("Msg_Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Apellidos.
        /// </summary>
        public static string Phl_Apellidos {
            get {
                return ResourceManager.GetString("Phl_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Confirmacion Contraseña.
        /// </summary>
        public static string Phl_ConfirmacionContrasenia {
            get {
                return ResourceManager.GetString("Phl_ConfirmacionContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Contraseña.
        /// </summary>
        public static string Phl_Contrasenia {
            get {
                return ResourceManager.GetString("Phl_Contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Email.
        /// </summary>
        public static string Phl_Email {
            get {
                return ResourceManager.GetString("Phl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Nombres.
        /// </summary>
        public static string Phl_Nombres {
            get {
                return ResourceManager.GetString("Phl_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar RUT.
        /// </summary>
        public static string Phl_RUT {
            get {
                return ResourceManager.GetString("Phl_RUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE TIPO DE USUARIO.
        /// </summary>
        public static string Phl_TipoUsuario {
            get {
                return ResourceManager.GetString("Phl_TipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email no tiene el formato requerido.
        /// </summary>
        public static string Val_Email_Email {
            get {
                return ResourceManager.GetString("Val_Email_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave no es igual a confirmacion.
        /// </summary>
        public static string Val_EqualTo_Clave {
            get {
                return ResourceManager.GetString("Val_EqualTo_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos deben tener  50 caracteres como maximo.
        /// </summary>
        public static string Val_MaxLength_Apellidos {
            get {
                return ResourceManager.GetString("Val_MaxLength_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave debe tener  50 caracteres como maximo.
        /// </summary>
        public static string Val_MaxLength_Clave {
            get {
                return ResourceManager.GetString("Val_MaxLength_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email debe tener  50 caracteres como maximo.
        /// </summary>
        public static string Val_MaxLength_Email {
            get {
                return ResourceManager.GetString("Val_MaxLength_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres deben tener  50 caracteres como maximo.
        /// </summary>
        public static string Val_MaxLength_Nombres {
            get {
                return ResourceManager.GetString("Val_MaxLength_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUT debe tener  10 caracteres como maximo.
        /// </summary>
        public static string Val_MaxLength_RUT {
            get {
                return ResourceManager.GetString("Val_MaxLength_RUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos deben tener  3 caracteres como mínimo.
        /// </summary>
        public static string Val_MinLength_Apellidos {
            get {
                return ResourceManager.GetString("Val_MinLength_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave debe tener  3 caracteres como mínimo.
        /// </summary>
        public static string Val_MinLength_Clave {
            get {
                return ResourceManager.GetString("Val_MinLength_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email debe tener  5 caracteres como mínimo.
        /// </summary>
        public static string Val_MinLength_Email {
            get {
                return ResourceManager.GetString("Val_MinLength_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres deben tener  3 caracteres como mínimo.
        /// </summary>
        public static string Val_MinLength_Nombres {
            get {
                return ResourceManager.GetString("Val_MinLength_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUT debe tener  8 caracteres como mínimo.
        /// </summary>
        public static string Val_MinLength_RUT {
            get {
                return ResourceManager.GetString("Val_MinLength_RUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una opcion para Activo.
        /// </summary>
        public static string Val_Required_Activo {
            get {
                return ResourceManager.GetString("Val_Required_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos son requeridos.
        /// </summary>
        public static string Val_Required_Apellidos {
            get {
                return ResourceManager.GetString("Val_Required_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave es requerido.
        /// </summary>
        public static string Val_Required_Clave {
            get {
                return ResourceManager.GetString("Val_Required_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email es requerido.
        /// </summary>
        public static string Val_Required_Email {
            get {
                return ResourceManager.GetString("Val_Required_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una opcion para Envio de Alerta.
        /// </summary>
        public static string Val_Required_Env_Alerta {
            get {
                return ResourceManager.GetString("Val_Required_Env_Alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres son requeridos.
        /// </summary>
        public static string Val_Required_Nombres {
            get {
                return ResourceManager.GetString("Val_Required_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUT es requerido.
        /// </summary>
        public static string Val_Required_RUT {
            get {
                return ResourceManager.GetString("Val_Required_RUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una opcion para Tipo de Usuario.
        /// </summary>
        public static string Val_Required_Select_TipoUsr {
            get {
                return ResourceManager.GetString("Val_Required_Select_TipoUsr", resourceCulture);
            }
        }
    }
}
