//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.Vehiculos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Documentacion_SubeDocumentos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Documentacion_SubeDocumentos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.Vehiculos._Documentacion_SubeDocumentos", typeof(_Documentacion_SubeDocumentos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Btn_Guardar {
            get {
                return ResourceManager.GetString("Btn_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aquí.
        /// </summary>
        public static string Lbl_Aqui {
            get {
                return ResourceManager.GetString("Lbl_Aqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar archivo.
        /// </summary>
        public static string Lbl_Buscar_Archivo {
            get {
                return ResourceManager.GetString("Lbl_Buscar_Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacidad Cilindro.
        /// </summary>
        public static string Lbl_Capacidad_Cilindro {
            get {
                return ResourceManager.GetString("Lbl_Capacidad_Cilindro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        public static string Lbl_Color {
            get {
                return ResourceManager.GetString("Lbl_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combustible.
        /// </summary>
        public static string Lbl_Combustible {
            get {
                return ResourceManager.GetString("Lbl_Combustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        public static string Lbl_Documento {
            get {
                return ResourceManager.GetString("Lbl_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fechas.
        /// </summary>
        public static string Lbl_Fechas {
            get {
                return ResourceManager.GetString("Lbl_Fechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Potencia.
        /// </summary>
        public static string Lbl_Potencia {
            get {
                return ResourceManager.GetString("Lbl_Potencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede ver los requisitos de validación del documento.
        /// </summary>
        public static string Lbl_Requisitos_Validacion_De {
            get {
                return ResourceManager.GetString("Lbl_Requisitos_Validacion_De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Archivo.
        /// </summary>
        public static string Lbl_Subir_Archivo {
            get {
                return ResourceManager.GetString("Lbl_Subir_Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tracción.
        /// </summary>
        public static string Lbl_Traccion {
            get {
                return ResourceManager.GetString("Lbl_Traccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Requisitos.
        /// </summary>
        public static string Lbl_Ver_Requisitos {
            get {
                return ResourceManager.GetString("Lbl_Ver_Requisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos Almacenados.
        /// </summary>
        public static string Lgn_Archivos_Almacenados {
            get {
                return ResourceManager.GetString("Lgn_Archivos_Almacenados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos / Datos.
        /// </summary>
        public static string Lgn_Archivos_Datos {
            get {
                return ResourceManager.GetString("Lgn_Archivos_Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo cargar. El nombre del archivo s-upera el maximo de caracteres permitidos de 45 caracteres.
        /// </summary>
        public static string Msg_MaximoCaracteres {
            get {
                return ResourceManager.GetString("Msg_MaximoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño del archivo que ha subido supera los 4MB permitidos,debería de realizar un proceso de compresión mayor.
        /// </summary>
        public static string Msg_MaximoTamaño {
            get {
                return ResourceManager.GetString("Msg_MaximoTamaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de formato de extensión que posee el archivo no está permitido en el tipo de documento seleccionado.
        /// </summary>
        public static string Msg_TipoFormato {
            get {
                return ResourceManager.GetString("Msg_TipoFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede cargar el documento, debe tener validados los siguientes documentos para poder realizar la carga.
        /// </summary>
        public static string Msg_Validar_Documentos {
            get {
                return ResourceManager.GetString("Msg_Validar_Documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Tipo Combustible.
        /// </summary>
        public static string Phl_Combustible {
            get {
                return ResourceManager.GetString("Phl_Combustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccine Tipo Tracción.
        /// </summary>
        public static string Phl_Traccion {
            get {
                return ResourceManager.GetString("Phl_Traccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string Tblb_Historico_Ver {
            get {
                return ResourceManager.GetString("Tblb_Historico_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Tblh_Historico_Eliminar {
            get {
                return ResourceManager.GetString("Tblh_Historico_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Tblh_Historico_Estado {
            get {
                return ResourceManager.GetString("Tblh_Historico_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Tblh_Historico_Fecha {
            get {
                return ResourceManager.GetString("Tblh_Historico_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora.
        /// </summary>
        public static string Tblh_Historico_Hora {
            get {
                return ResourceManager.GetString("Tblh_Historico_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente.
        /// </summary>
        public static string Tblh_Historico_Patente {
            get {
                return ResourceManager.GetString("Tblh_Historico_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por.
        /// </summary>
        public static string Tblh_Historico_Por {
            get {
                return ResourceManager.GetString("Tblh_Historico_Por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string Tblh_Historico_Ver {
            get {
                return ResourceManager.GetString("Tblh_Historico_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string Tblh_Vehiculo_Año {
            get {
                return ResourceManager.GetString("Tblh_Vehiculo_Año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        public static string Tblh_Vehiculo_Color {
            get {
                return ResourceManager.GetString("Tblh_Vehiculo_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cumple Certificación.
        /// </summary>
        public static string Tblh_Vehiculo_Cumple_Certificacion {
            get {
                return ResourceManager.GetString("Tblh_Vehiculo_Cumple_Certificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Tblh_Vehiculo_Empresa {
            get {
                return ResourceManager.GetString("Tblh_Vehiculo_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string Tblh_Vehiculo_Marca {
            get {
                return ResourceManager.GetString("Tblh_Vehiculo_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        public static string Tblh_Vehiculo_Modelo {
            get {
                return ResourceManager.GetString("Tblh_Vehiculo_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente.
        /// </summary>
        public static string Tblh_Vehiculo_Patente {
            get {
                return ResourceManager.GetString("Tblh_Vehiculo_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propietario.
        /// </summary>
        public static string Tblh_Vehiculo_Propietario {
            get {
                return ResourceManager.GetString("Tblh_Vehiculo_Propietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Tblh_Vehiculo_Tipo {
            get {
                return ResourceManager.GetString("Tblh_Vehiculo_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Propietario.
        /// </summary>
        public static string Tblh_Vehiculo_Tipo_Propietario {
            get {
                return ResourceManager.GetString("Tblh_Vehiculo_Tipo_Propietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo es requerido.
        /// </summary>
        public static string Val_Required_Archivo {
            get {
                return ResourceManager.GetString("Val_Required_Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cilindrada es requerido.
        /// </summary>
        public static string Val_Required_Cilindrada {
            get {
                return ResourceManager.GetString("Val_Required_Cilindrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color es requerido.
        /// </summary>
        public static string Val_Required_Color {
            get {
                return ResourceManager.GetString("Val_Required_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Combustible.
        /// </summary>
        public static string Val_Required_Combustible {
            get {
                return ResourceManager.GetString("Val_Required_Combustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Fin es requerido.
        /// </summary>
        public static string Val_Required_Fecha_Fin {
            get {
                return ResourceManager.GetString("Val_Required_Fecha_Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio es requerido.
        /// </summary>
        public static string Val_Required_Fecha_Inicio {
            get {
                return ResourceManager.GetString("Val_Required_Fecha_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Potencia es requerido.
        /// </summary>
        public static string Val_Required_Potencia {
            get {
                return ResourceManager.GetString("Val_Required_Potencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Tracción.
        /// </summary>
        public static string Val_Required_Traccion {
            get {
                return ResourceManager.GetString("Val_Required_Traccion", resourceCulture);
            }
        }
    }
}
