//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.Vehiculos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CrearEditar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrearEditar() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.Vehiculos.CrearEditar", typeof(CrearEditar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos.
        /// </summary>
        public static string Lbl_Datos {
            get {
                return ResourceManager.GetString("Lbl_Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentación.
        /// </summary>
        public static string Lbl_Documentacion {
            get {
                return ResourceManager.GetString("Lbl_Documentacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Lbl_Editar {
            get {
                return ResourceManager.GetString("Lbl_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string Lbl_Nuevo {
            get {
                return ResourceManager.GetString("Lbl_Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehículo.
        /// </summary>
        public static string Lbl_Vehiculo {
            get {
                return ResourceManager.GetString("Lbl_Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Vehículos.
        /// </summary>
        public static string Lnk_Listado_Vehiculos {
            get {
                return ResourceManager.GetString("Lnk_Listado_Vehiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehículo.
        /// </summary>
        public static string Lnk_Vehiculo {
            get {
                return ResourceManager.GetString("Lnk_Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos actualizados correctamente.
        /// </summary>
        public static string Msg_ActualizacionCorrecta {
            get {
                return ResourceManager.GetString("Msg_ActualizacionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acrónimo Propietario debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Acronimo_Propietario {
            get {
                return ResourceManager.GetString("Val_MaxLength_Acronimo_Propietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año de Fabricación debe tener 4 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Año_Fabricacion {
            get {
                return ResourceManager.GetString("Val_MaxLength_Año_Fabricacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Apellidos {
            get {
                return ResourceManager.GetString("Val_MaxLength_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color debe tener 30 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Color {
            get {
                return ResourceManager.GetString("Val_MaxLength_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Propietario debe tener 10 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_ID_Propietario {
            get {
                return ResourceManager.GetString("Val_MaxLength_ID_Propietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Marca {
            get {
                return ResourceManager.GetString("Val_MaxLength_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Modelo {
            get {
                return ResourceManager.GetString("Val_MaxLength_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres debe tener 50 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Nombres {
            get {
                return ResourceManager.GetString("Val_MaxLength_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string Val_MaxLength_Tipo_Propietario {
            get {
                return ResourceManager.GetString("Val_MaxLength_Tipo_Propietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acrónimo Propietario es requerido.
        /// </summary>
        public static string Val_Required_Acronimo_Propietario {
            get {
                return ResourceManager.GetString("Val_Required_Acronimo_Propietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Año de Fabricación.
        /// </summary>
        public static string Val_Required_Año_Fabricacion {
            get {
                return ResourceManager.GetString("Val_Required_Año_Fabricacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos es requerido.
        /// </summary>
        public static string Val_Required_Apellidos {
            get {
                return ResourceManager.GetString("Val_Required_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color es requerido.
        /// </summary>
        public static string Val_Required_Color {
            get {
                return ResourceManager.GetString("Val_Required_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID propietario es requerido.
        /// </summary>
        public static string Val_Required_ID_Propietario {
            get {
                return ResourceManager.GetString("Val_Required_ID_Propietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca es requerido.
        /// </summary>
        public static string Val_Required_Marca {
            get {
                return ResourceManager.GetString("Val_Required_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo es requerido.
        /// </summary>
        public static string Val_Required_Modelo {
            get {
                return ResourceManager.GetString("Val_Required_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres es requerido.
        /// </summary>
        public static string Val_Required_Nombres {
            get {
                return ResourceManager.GetString("Val_Required_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Tipo de Vehículo.
        /// </summary>
        public static string Val_Required_Tipo {
            get {
                return ResourceManager.GetString("Val_Required_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Propietario es requerido.
        /// </summary>
        public static string Val_Required_Tipo_Propietario {
            get {
                return ResourceManager.GetString("Val_Required_Tipo_Propietario", resourceCulture);
            }
        }
    }
}
