//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.InformesCertificacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InformeFechaFuncDivision {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformeFechaFuncDivision() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.InformesCertificacion.InformeFechaFuncDi" +
                            "vision", typeof(InformeFechaFuncDivision).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Actual.
        /// </summary>
        public static string Lbl_FechaActual {
            get {
                return ResourceManager.GetString("Lbl_FechaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Condición de Fechas controladas por Funcionarios.
        /// </summary>
        public static string Lbl_Titulo {
            get {
                return ResourceManager.GetString("Lbl_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operacion.
        /// </summary>
        public static string Tblb_Filtros_Division {
            get {
                return ResourceManager.GetString("Tblb_Filtros_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Tblb_Filtros_Empresa {
            get {
                return ResourceManager.GetString("Tblb_Filtros_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se hallaron resultados.
        /// </summary>
        public static string Tblb_Resultados_Lbl_NoResultados {
            get {
                return ResourceManager.GetString("Tblb_Resultados_Lbl_NoResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros del Informe.
        /// </summary>
        public static string Tblh_Filtros_Titulo {
            get {
                return ResourceManager.GetString("Tblh_Filtros_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acronimo.
        /// </summary>
        public static string Tblh_Resultados_Acronimo {
            get {
                return ResourceManager.GetString("Tblh_Resultados_Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Tblh_Resultados_Apellidos {
            get {
                return ResourceManager.GetString("Tblh_Resultados_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        public static string Tblh_Resultados_Cargo {
            get {
                return ResourceManager.GetString("Tblh_Resultados_Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato.
        /// </summary>
        public static string Tblh_Resultados_Contrato {
            get {
                return ResourceManager.GetString("Tblh_Resultados_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cumple Cert. Conduc.
        /// </summary>
        public static string Tblh_Resultados_CumpleCertConduc {
            get {
                return ResourceManager.GetString("Tblh_Resultados_CumpleCertConduc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cumple Cert. Trabajo.
        /// </summary>
        public static string Tblh_Resultados_CumpleCertTrabajo {
            get {
                return ResourceManager.GetString("Tblh_Resultados_CumpleCertTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Tblh_Resultados_Empresa {
            get {
                return ResourceManager.GetString("Tblh_Resultados_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ex.Preocup.
        /// </summary>
        public static string Tblh_Resultados_ExPreocup {
            get {
                return ResourceManager.GetString("Tblh_Resultados_ExPreocup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F.Fin.Cont.
        /// </summary>
        public static string Tblh_Resultados_FFinContrato {
            get {
                return ResourceManager.GetString("Tblh_Resultados_FFinContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F.Vence Examen.
        /// </summary>
        public static string Tblh_Resultados_FVenceExamen {
            get {
                return ResourceManager.GetString("Tblh_Resultados_FVenceExamen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string Tblh_Resultados_ID {
            get {
                return ResourceManager.GetString("Tblh_Resultados_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Empresa.
        /// </summary>
        public static string Tblh_Resultados_IDEmpresa {
            get {
                return ResourceManager.GetString("Tblh_Resultados_IDEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro..
        /// </summary>
        public static string Tblh_Resultados_Index {
            get {
                return ResourceManager.GetString("Tblh_Resultados_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Tblh_Resultados_Nombres {
            get {
                return ResourceManager.GetString("Tblh_Resultados_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operacion.
        /// </summary>
        public static string Tblh_Resultados_Operacion {
            get {
                return ResourceManager.GetString("Tblh_Resultados_Operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pase Autorizado.
        /// </summary>
        public static string Tblh_Resultados_PaseAutorizado {
            get {
                return ResourceManager.GetString("Tblh_Resultados_PaseAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicita Conduc.
        /// </summary>
        public static string Tblh_Resultados_SolicitaConduc {
            get {
                return ResourceManager.GetString("Tblh_Resultados_SolicitaConduc", resourceCulture);
            }
        }
    }
}
