//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.Pases {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaseVisita {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaseVisita() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.Pases.PaseVisita", typeof(PaseVisita).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Funcionario.
        /// </summary>
        public static string Btn_AgregarFuncionario {
            get {
                return ResourceManager.GetString("Btn_AgregarFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Vehículo.
        /// </summary>
        public static string Btn_AgregarVehiculo {
            get {
                return ResourceManager.GetString("Btn_AgregarVehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Pase Visita.
        /// </summary>
        public static string Btn_Guardar_Pase {
            get {
                return ResourceManager.GetString("Btn_Guardar_Pase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area Visitada.
        /// </summary>
        public static string Lbl_AreaVisitada {
            get {
                return ResourceManager.GetString("Lbl_AreaVisitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorizador.
        /// </summary>
        public static string Lbl_Autorizador {
            get {
                return ResourceManager.GetString("Lbl_Autorizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Visitante.
        /// </summary>
        public static string Lbl_CorreoVisitante {
            get {
                return ResourceManager.GetString("Lbl_CorreoVisitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Funcionario.
        /// </summary>
        public static string Lbl_EditarFuncionario {
            get {
                return ResourceManager.GetString("Lbl_EditarFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Vehiculo.
        /// </summary>
        public static string Lbl_EditarVehiculo {
            get {
                return ResourceManager.GetString("Lbl_EditarVehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final.
        /// </summary>
        public static string Lbl_FechaFinal {
            get {
                return ResourceManager.GetString("Lbl_FechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        public static string Lbl_FechaInicio {
            get {
                return ResourceManager.GetString("Lbl_FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Solicita Visita.
        /// </summary>
        public static string Lbl_IDSolicitaVisita {
            get {
                return ResourceManager.GetString("Lbl_IDSolicitaVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Funcionario.
        /// </summary>
        public static string Lbl_NuevoFuncionario {
            get {
                return ResourceManager.GetString("Lbl_NuevoFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Vehículo.
        /// </summary>
        public static string Lbl_NuevoVehiculo {
            get {
                return ResourceManager.GetString("Lbl_NuevoVehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pase Visita.
        /// </summary>
        public static string Lbl_PaseVisita {
            get {
                return ResourceManager.GetString("Lbl_PaseVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Vehículos en Pase.
        /// </summary>
        public static string Lgn_DatosVehiculosPase {
            get {
                return ResourceManager.GetString("Lgn_DatosVehiculosPase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrantes del Pase Visita.
        /// </summary>
        public static string Lgn_IntegrantesVisita {
            get {
                return ResourceManager.GetString("Lgn_IntegrantesVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Mdl_CasinoPermitido_Btn_Cancelar {
            get {
                return ResourceManager.GetString("Mdl_CasinoPermitido_Btn_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Mdl_CasinoPermitido_Btn_Guardar {
            get {
                return ResourceManager.GetString("Mdl_CasinoPermitido_Btn_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locales de Casino Permitidos.
        /// </summary>
        public static string Mdl_CasinoPermitido_Lbl_CasinoPermitido {
            get {
                return ResourceManager.GetString("Mdl_CasinoPermitido_Lbl_CasinoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locales de Casino Permitidos  (LOCAL/SERVICIO).
        /// </summary>
        public static string Mdl_CasinoPermitido_Lgn_CasinoPermitido {
            get {
                return ResourceManager.GetString("Mdl_CasinoPermitido_Lgn_CasinoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Mdl_Funcionario_Btn_Cancelar {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Btn_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Mdl_Funcionario_Btn_Guardar {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Btn_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Mdl_Funcionario_Lbl_Apellidos {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Lbl_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casino.
        /// </summary>
        public static string Mdl_Funcionario_Lbl_Casino {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Lbl_Casino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conduce.
        /// </summary>
        public static string Mdl_Funcionario_Lbl_Conduce {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Lbl_Conduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string Mdl_Funcionario_Lbl_ID {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Lbl_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Mdl_Funcionario_Lbl_Nombres {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Lbl_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos deben tener 50 caracteres como máximo.
        /// </summary>
        public static string Mdl_Funcionario_MaxLength_Apellidos {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_MaxLength_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID deben tener 11 caracteres como máximo.
        /// </summary>
        public static string Mdl_Funcionario_MaxLength_ID {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_MaxLength_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres deben tener 50 caracteres como máximo.
        /// </summary>
        public static string Mdl_Funcionario_MaxLength_Nombres {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_MaxLength_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID deben tener 3 caracteres como mínimo.
        /// </summary>
        public static string Mdl_Funcionario_MinLength_ID {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_MinLength_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos marcados con (*) son requeridos.
        /// </summary>
        public static string Mdl_Funcionario_Msg_CamposMarcados {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Msg_CamposMarcados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string Mdl_Funcionario_Msg_Informacion {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Msg_Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Apellidos.
        /// </summary>
        public static string Mdl_Funcionario_Phl_Apellidos {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Phl_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese ID.
        /// </summary>
        public static string Mdl_Funcionario_Phl_ID {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Phl_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Nombres.
        /// </summary>
        public static string Mdl_Funcionario_Phl_Nombres {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Phl_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos es requerido.
        /// </summary>
        public static string Mdl_Funcionario_Val_Apellidos {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Val_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID es requerido.
        /// </summary>
        public static string Mdl_Funcionario_Val_ID {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Val_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres es requerido.
        /// </summary>
        public static string Mdl_Funcionario_Val_Nombre {
            get {
                return ResourceManager.GetString("Mdl_Funcionario_Val_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Mdl_Vehiculo_Btn_Cancelar {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Btn_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Mdl_Vehiculo_Btn_Guardar {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Btn_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string Mdl_Vehiculo_Lbl_Anio {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Lbl_Anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string Mdl_Vehiculo_Lbl_Marca {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Lbl_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        public static string Mdl_Vehiculo_Lbl_Modelo {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Lbl_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente.
        /// </summary>
        public static string Mdl_Vehiculo_Lbl_Patente {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Lbl_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Mdl_Vehiculo_Lbl_Tipo {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Lbl_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca deben tener 50 caracteres como máximo.
        /// </summary>
        public static string Mdl_Vehiculo_MaxLength_Marca {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_MaxLength_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo deben tener 50 caracteres como máximo.
        /// </summary>
        public static string Mdl_Vehiculo_MaxLength_Modelo {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_MaxLength_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente deben tener 10 caracteres como máximo.
        /// </summary>
        public static string Mdl_Vehiculo_MaxLength_Patente {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_MaxLength_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente deben tener 6 caracteres como mínimo.
        /// </summary>
        public static string Mdl_Vehiculo_MinLength_Patente {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_MinLength_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos marcados con (*) son requeridos.
        /// </summary>
        public static string Mdl_Vehiculo_Msg_CamposRequeridos {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Msg_CamposRequeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string Mdl_Vehiculo_Msg_Informacion {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Msg_Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Año.
        /// </summary>
        public static string Mdl_Vehiculo_Phl_Anio {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Phl_Anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Marca.
        /// </summary>
        public static string Mdl_Vehiculo_Phl_Marca {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Phl_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Modelo.
        /// </summary>
        public static string Mdl_Vehiculo_Phl_Modelo {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Phl_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Patente.
        /// </summary>
        public static string Mdl_Vehiculo_Phl_Patente {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Phl_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE TIPO.
        /// </summary>
        public static string Mdl_Vehiculo_Phl_Tipo {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Phl_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Año.
        /// </summary>
        public static string Mdl_Vehiculo_Val_Anio {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Val_Anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca es requerido.
        /// </summary>
        public static string Mdl_Vehiculo_Val_Marca {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Val_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo es requerido.
        /// </summary>
        public static string Mdl_Vehiculo_Val_Modelo {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Val_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente es requerido.
        /// </summary>
        public static string Mdl_Vehiculo_Val_Patente {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Val_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Tipo.
        /// </summary>
        public static string Mdl_Vehiculo_Val_Tipo {
            get {
                return ResourceManager.GetString("Mdl_Vehiculo_Val_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos marcados con (*) son requeridos.
        /// </summary>
        public static string Msg_CamposMarcados {
            get {
                return ResourceManager.GetString("Msg_CamposMarcados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pase no puede superar los 5 dias de duracion..
        /// </summary>
        public static string Msg_DuracionPase {
            get {
                return ResourceManager.GetString("Msg_DuracionPase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha inicio debe ser mayor o igual a fecha final.
        /// </summary>
        public static string Msg_FechaFinal_Menor_FechaInicio {
            get {
                return ResourceManager.GetString("Msg_FechaFinal_Menor_FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha Final es menor a hoy.
        /// </summary>
        public static string Msg_FechaFinal_Menor_Hoy {
            get {
                return ResourceManager.GetString("Msg_FechaFinal_Menor_Hoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha Inicio es menor a hoy.
        /// </summary>
        public static string Msg_FechaInicio_Menor_Hoy {
            get {
                return ResourceManager.GetString("Msg_FechaInicio_Menor_Hoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El funcionario ya fue agregado.
        /// </summary>
        public static string Msg_Funcionario_Agregado {
            get {
                return ResourceManager.GetString("Msg_Funcionario_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar funcionario?.
        /// </summary>
        public static string Msg_Funcionario_Eliminar {
            get {
                return ResourceManager.GetString("Msg_Funcionario_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si, eliminar.
        /// </summary>
        public static string Msg_Funcionario_SI {
            get {
                return ResourceManager.GetString("Msg_Funcionario_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El funcionario no puede ser añadido en el pase esta bloqueado su acceso a faena..
        /// </summary>
        public static string Msg_Funcionario_Val_01 {
            get {
                return ResourceManager.GetString("Msg_Funcionario_Val_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El funcionario no puede ser añadido en el pase ya se encuentra autorizado..
        /// </summary>
        public static string Msg_Funcionario_Val_02 {
            get {
                return ResourceManager.GetString("Msg_Funcionario_Val_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea generar un pase visita?.
        /// </summary>
        public static string Msg_GenerarPase {
            get {
                return ResourceManager.GetString("Msg_GenerarPase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID  es incorrecto.
        /// </summary>
        public static string Msg_IDIncorrecto {
            get {
                return ResourceManager.GetString("Msg_IDIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string Msg_Informacion {
            get {
                return ResourceManager.GetString("Msg_Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO.
        /// </summary>
        public static string Msg_LiteralNO {
            get {
                return ResourceManager.GetString("Msg_LiteralNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SI.
        /// </summary>
        public static string Msg_LiteralSI {
            get {
                return ResourceManager.GetString("Msg_LiteralSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se envió un correo de aviso , debera esperar a que este autorize su lote de Pase N°:.
        /// </summary>
        public static string Msg_Pase_Enviado_01 {
            get {
                return ResourceManager.GetString("Msg_Pase_Enviado_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cual contiene la información del pase con glosa PASE VISITA de fecha de inicio.
        /// </summary>
        public static string Msg_Pase_Enviado_02 {
            get {
                return ResourceManager.GetString("Msg_Pase_Enviado_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a y fecha final.
        /// </summary>
        public static string Msg_Pase_Enviado_03 {
            get {
                return ResourceManager.GetString("Msg_Pase_Enviado_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error.
        /// </summary>
        public static string Msg_Pase_Error {
            get {
                return ResourceManager.GetString("Msg_Pase_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pase generado correctamente.
        /// </summary>
        public static string Msg_PaseEnviadoCorrectamente {
            get {
                return ResourceManager.GetString("Msg_PaseEnviadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si, proceder.
        /// </summary>
        public static string Msg_Proceder {
            get {
                return ResourceManager.GetString("Msg_Proceder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pase requiere al menos un funcionario.
        /// </summary>
        public static string Msg_RequiereFuncionario {
            get {
                return ResourceManager.GetString("Msg_RequiereFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El vehiculo Patente :.
        /// </summary>
        public static string Msg_Val_Patente_01 {
            get {
                return ResourceManager.GetString("Msg_Val_Patente_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ya se encuentra autorizado, no puede agregarlo en el pase..
        /// </summary>
        public static string Msg_Val_Patente_02 {
            get {
                return ResourceManager.GetString("Msg_Val_Patente_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea Eliminar vehículo?.
        /// </summary>
        public static string Msg_Vehiculo_Eliminar {
            get {
                return ResourceManager.GetString("Msg_Vehiculo_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La patente es incorrecta, debe ingresar la parte literal y numerica de forma correcta.
        /// </summary>
        public static string Msg_Vehiculo_PatenteIncorrecta {
            get {
                return ResourceManager.GetString("Msg_Vehiculo_PatenteIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si, eliminar.
        /// </summary>
        public static string Msg_Vehiculo_Si {
            get {
                return ResourceManager.GetString("Msg_Vehiculo_Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Vehiculo ya fué agregado.
        /// </summary>
        public static string Msg_Vehiculo_YaAgregado {
            get {
                return ResourceManager.GetString("Msg_Vehiculo_YaAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE AREA VISITADA.
        /// </summary>
        public static string Phl_AreaVisitada {
            get {
                return ResourceManager.GetString("Phl_AreaVisitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Autorizador.
        /// </summary>
        public static string Phl_Autorizador {
            get {
                return ResourceManager.GetString("Phl_Autorizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Correo Visitante.
        /// </summary>
        public static string Phl_CorreoVisitante {
            get {
                return ResourceManager.GetString("Phl_CorreoVisitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Fecha Final.
        /// </summary>
        public static string Phl_FechaFinal {
            get {
                return ResourceManager.GetString("Phl_FechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Fecha Inicio.
        /// </summary>
        public static string Phl_FechaInicio {
            get {
                return ResourceManager.GetString("Phl_FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese ID Solicita Visita.
        /// </summary>
        public static string Phl_IDSolicitaVisita {
            get {
                return ResourceManager.GetString("Phl_IDSolicitaVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Nombre Autorizador.
        /// </summary>
        public static string Phl_NombreAutorizador {
            get {
                return ResourceManager.GetString("Phl_NombreAutorizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Nombre Solicita Visita.
        /// </summary>
        public static string Phl_NombreSolicitaVisita {
            get {
                return ResourceManager.GetString("Phl_NombreSolicitaVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Tblb_Funcionarios_Btn_Editar {
            get {
                return ResourceManager.GetString("Tblb_Funcionarios_Btn_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Tblb_Funcionarios_Btn_Eliminar {
            get {
                return ResourceManager.GetString("Tblb_Funcionarios_Btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se hallaron resultados.
        /// </summary>
        public static string Tblb_Funcionarios_NoResultados {
            get {
                return ResourceManager.GetString("Tblb_Funcionarios_NoResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Tblb_Vehiculos_Btn_Editar {
            get {
                return ResourceManager.GetString("Tblb_Vehiculos_Btn_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Tblb_Vehiculos_Btn_Eliminar {
            get {
                return ResourceManager.GetString("Tblb_Vehiculos_Btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se hallaron resultados.
        /// </summary>
        public static string Tblb_Vehiculos_NoResultados {
            get {
                return ResourceManager.GetString("Tblb_Vehiculos_NoResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Tblh_Funcionarios_Apellidos {
            get {
                return ResourceManager.GetString("Tblh_Funcionarios_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conduce.
        /// </summary>
        public static string Tblh_Funcionarios_Conduce {
            get {
                return ResourceManager.GetString("Tblh_Funcionarios_Conduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Tblh_Funcionarios_Editar {
            get {
                return ResourceManager.GetString("Tblh_Funcionarios_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Tblh_Funcionarios_Eliminar {
            get {
                return ResourceManager.GetString("Tblh_Funcionarios_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string Tblh_Funcionarios_ID {
            get {
                return ResourceManager.GetString("Tblh_Funcionarios_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Tblh_Funcionarios_Nombres {
            get {
                return ResourceManager.GetString("Tblh_Funcionarios_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string Tblh_Vehiculos_Anio {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Tblh_Vehiculos_Editar {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Tblh_Vehiculos_Eliminar {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string Tblh_Vehiculos_Marca {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        public static string Tblh_Vehiculos_Modelo {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente.
        /// </summary>
        public static string Tblh_Vehiculos_Patente {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Tblh_Vehiculos_Tipo {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Area Visita.
        /// </summary>
        public static string Val_AreaVisita {
            get {
                return ResourceManager.GetString("Val_AreaVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Visitante es requerido.
        /// </summary>
        public static string Val_Email {
            get {
                return ResourceManager.GetString("Val_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email incorrecto.
        /// </summary>
        public static string Val_Email_incorrecto {
            get {
                return ResourceManager.GetString("Val_Email_incorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Fecha Final.
        /// </summary>
        public static string Val_Fecha_Final {
            get {
                return ResourceManager.GetString("Val_Fecha_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Fecha Inicio.
        /// </summary>
        public static string Val_Fecha_Inicio {
            get {
                return ResourceManager.GetString("Val_Fecha_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Autorizador es requerido.
        /// </summary>
        public static string Val_IDAutorizador {
            get {
                return ResourceManager.GetString("Val_IDAutorizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Solicita Visita es requerido.
        /// </summary>
        public static string Val_IDSolicita {
            get {
                return ResourceManager.GetString("Val_IDSolicita", resourceCulture);
            }
        }
    }
}
