//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mandante.CursosResultados {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CursosResultados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CursosResultados() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Mandante.CursosResultados.CursosResultados", typeof(CursosResultados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Cursos Resultados.
        /// </summary>
        public static string Lbl_CursosResultados_Listado {
            get {
                return ResourceManager.GetString("Lbl_CursosResultados_Listado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos - Calificaciones.
        /// </summary>
        public static string Lbl_CursosResultados_Titulo {
            get {
                return ResourceManager.GetString("Lbl_CursosResultados_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes Actual.
        /// </summary>
        public static string Tab_CursosResultados_MesActual {
            get {
                return ResourceManager.GetString("Tab_CursosResultados_MesActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meses Anteriores.
        /// </summary>
        public static string Tab_CursosResultados_MesesAnteriores {
            get {
                return ResourceManager.GetString("Tab_CursosResultados_MesesAnteriores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meses Posteriores.
        /// </summary>
        public static string Tab_CursosResultados_MesesPosteriores {
            get {
                return ResourceManager.GetString("Tab_CursosResultados_MesesPosteriores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificar.
        /// </summary>
        public static string Tblh_CursosResultados_Calificar {
            get {
                return ResourceManager.GetString("Tblh_CursosResultados_Calificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrado.
        /// </summary>
        public static string Tblh_CursosResultados_Cerrado {
            get {
                return ResourceManager.GetString("Tblh_CursosResultados_Cerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charla.
        /// </summary>
        public static string Tblh_CursosResultados_Charla {
            get {
                return ResourceManager.GetString("Tblh_CursosResultados_Charla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cupos.
        /// </summary>
        public static string Tblh_CursosResultados_Cupos {
            get {
                return ResourceManager.GetString("Tblh_CursosResultados_Cupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisiones.
        /// </summary>
        public static string Tblh_CursosResultados_Divisiones {
            get {
                return ResourceManager.GetString("Tblh_CursosResultados_Divisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Tblh_CursosResultados_Fecha {
            get {
                return ResourceManager.GetString("Tblh_CursosResultados_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string Tblh_CursosResultados_Hora {
            get {
                return ResourceManager.GetString("Tblh_CursosResultados_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libres.
        /// </summary>
        public static string Tblh_CursosResultados_Libres {
            get {
                return ResourceManager.GetString("Tblh_CursosResultados_Libres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar.
        /// </summary>
        public static string Tblh_CursosResultados_Lugar {
            get {
                return ResourceManager.GetString("Tblh_CursosResultados_Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservas.
        /// </summary>
        public static string Tblh_CursosResultados_Reservas {
            get {
                return ResourceManager.GetString("Tblh_CursosResultados_Reservas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala.
        /// </summary>
        public static string Tblh_CursosResultados_Sala {
            get {
                return ResourceManager.GetString("Tblh_CursosResultados_Sala", resourceCulture);
            }
        }
    }
}
