//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mandante.Vehiculos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Documentacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Documentacion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Mandante.Vehiculos._Documentacion", typeof(_Documentacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string Lbl_Año {
            get {
                return ResourceManager.GetString("Lbl_Año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Lbl_Color {
            get {
                return ResourceManager.GetString("Lbl_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Vehículo.
        /// </summary>
        public static string Lbl_Datos_Vehiculo {
            get {
                return ResourceManager.GetString("Lbl_Datos_Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dueño.
        /// </summary>
        public static string Lbl_Dueño {
            get {
                return ResourceManager.GetString("Lbl_Dueño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string Lbl_Empresa {
            get {
                return ResourceManager.GetString("Lbl_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipamiento ADAS.
        /// </summary>
        public static string Lbl_Equipamiento_ADAS {
            get {
                return ResourceManager.GetString("Lbl_Equipamiento_ADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionario.
        /// </summary>
        public static string Lbl_Funcionario {
            get {
                return ResourceManager.GetString("Lbl_Funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string Lbl_Marca {
            get {
                return ResourceManager.GetString("Lbl_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string Lbl_Modelo {
            get {
                return ResourceManager.GetString("Lbl_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patente.
        /// </summary>
        public static string Lbl_Patente {
            get {
                return ResourceManager.GetString("Lbl_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Lbl_Tipo {
            get {
                return ResourceManager.GetString("Lbl_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Dueño.
        /// </summary>
        public static string Lbl_Tipo_Dueño {
            get {
                return ResourceManager.GetString("Lbl_Tipo_Dueño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificación de Documentos Vehículo.
        /// </summary>
        public static string Lbl_Verificacion_Documentos_Vehiculo {
            get {
                return ResourceManager.GetString("Lbl_Verificacion_Documentos_Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos del Vehiculo.
        /// </summary>
        public static string Lgn_Datos_Vehiculo {
            get {
                return ResourceManager.GetString("Lgn_Datos_Vehiculo", resourceCulture);
            }
        }
    }
}
