//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mandante.Vehiculos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Mandante.Vehiculos.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string Lbl_A {
            get {
                return ResourceManager.GetString("Lbl_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ant.
        /// </summary>
        public static string Lbl_Ant {
            get {
                return ResourceManager.GetString("Lbl_Ant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string Lbl_de {
            get {
                return ResourceManager.GetString("Lbl_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Vehículos.
        /// </summary>
        public static string Lbl_ListadoVehiculos {
            get {
                return ResourceManager.GetString("Lbl_ListadoVehiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrando.
        /// </summary>
        public static string Lbl_Mostrando {
            get {
                return ResourceManager.GetString("Lbl_Mostrando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sig.
        /// </summary>
        public static string Lbl_Pos {
            get {
                return ResourceManager.GetString("Lbl_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        public static string Lbl_Registros {
            get {
                return ResourceManager.GetString("Lbl_Registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehículos.
        /// </summary>
        public static string Lbl_Vehiculos {
            get {
                return ResourceManager.GetString("Lbl_Vehiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehículos.
        /// </summary>
        public static string Lnk_Vehiculos {
            get {
                return ResourceManager.GetString("Lnk_Vehiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Mdl_NuevoVehiculo_Btn_Cancelar {
            get {
                return ResourceManager.GetString("Mdl_NuevoVehiculo_Btn_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        public static string Mdl_NuevoVehiculo_Btn_Consultar {
            get {
                return ResourceManager.GetString("Mdl_NuevoVehiculo_Btn_Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Mdl_NuevoVehiculo_Btn_Editar {
            get {
                return ResourceManager.GetString("Mdl_NuevoVehiculo_Btn_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string Mdl_NuevoVehiculo_Btn_Nuevo {
            get {
                return ResourceManager.GetString("Mdl_NuevoVehiculo_Btn_Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Mdl_NuevoVehiculo_Lbl_Description {
            get {
                return ResourceManager.GetString("Mdl_NuevoVehiculo_Lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Vehículo.
        /// </summary>
        public static string Mdl_NuevoVehiculo_Lbl_Nuevo_Vehiculo {
            get {
                return ResourceManager.GetString("Mdl_NuevoVehiculo_Lbl_Nuevo_Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patente.
        /// </summary>
        public static string Mdl_NuevoVehiculo_Lbl_Patente {
            get {
                return ResourceManager.GetString("Mdl_NuevoVehiculo_Lbl_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La patente debe ingresarse en su totalidad , sin puntos ni guiones.
        /// </summary>
        public static string Mdl_NuevoVehiculo_Msg_Nueva_Descripcion {
            get {
                return ResourceManager.GetString("Mdl_NuevoVehiculo_Msg_Nueva_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este vehiculo se encuentra registrado en otra empresa.
        /// </summary>
        public static string Mdl_NuevoVehiculo_Msg_Registrado_Nomina {
            get {
                return ResourceManager.GetString("Mdl_NuevoVehiculo_Msg_Registrado_Nomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Msg_Cancelar {
            get {
                return ResourceManager.GetString("Msg_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Msg_ConfirmarEliminar {
            get {
                return ResourceManager.GetString("Msg_ConfirmarEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminación Correcta.
        /// </summary>
        public static string Msg_EliminacionCorrecta {
            get {
                return ResourceManager.GetString("Msg_EliminacionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea eliminar el vehículo seleccionado de su nómina?.
        /// </summary>
        public static string Msg_Eliminar_Vehiculo {
            get {
                return ResourceManager.GetString("Msg_Eliminar_Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error.
        /// </summary>
        public static string Msg_GuardarInformacionError {
            get {
                return ResourceManager.GetString("Msg_GuardarInformacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patente.
        /// </summary>
        public static string Msg_NuevoVehiculo_Phl_Patente {
            get {
                return ResourceManager.GetString("Msg_NuevoVehiculo_Phl_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Tblb_Vehiculos_Btn_Editar {
            get {
                return ResourceManager.GetString("Tblb_Vehiculos_Btn_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Tblb_Vehiculos_Btn_Eliminar {
            get {
                return ResourceManager.GetString("Tblb_Vehiculos_Btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string Tblf_Vehiculos_Empresa {
            get {
                return ResourceManager.GetString("Tblf_Vehiculos_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string Tblf_Vehiculos_Marca {
            get {
                return ResourceManager.GetString("Tblf_Vehiculos_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string Tblf_Vehiculos_Modelo {
            get {
                return ResourceManager.GetString("Tblf_Vehiculos_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patente.
        /// </summary>
        public static string Tblf_Vehiculos_Patente {
            get {
                return ResourceManager.GetString("Tblf_Vehiculos_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Tblh_Vehiculos_Editar {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Tblh_Vehiculos_Eliminar {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string Tblh_Vehiculos_Empresa {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string Tblh_Vehiculos_Marca {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string Tblh_Vehiculos_Modelo {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patente.
        /// </summary>
        public static string Tblh_Vehiculos_Patente {
            get {
                return ResourceManager.GetString("Tblh_Vehiculos_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite la patente correctamente,&lt;br&gt; Algunos de los caracteres no está en su posición debida, parte numérica y alfabética de la patente.
        /// </summary>
        public static string Val_LettersNumber_Patente {
            get {
                return ResourceManager.GetString("Val_LettersNumber_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patente debe tener 6 caracteres como máximo.
        /// </summary>
        public static string Val_MaxLength_Patente {
            get {
                return ResourceManager.GetString("Val_MaxLength_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patente debe tener 6 caracteres como mínimo.
        /// </summary>
        public static string Val_MinLength_Patente {
            get {
                return ResourceManager.GetString("Val_MinLength_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo números, letras y sin espacios en blanco.
        /// </summary>
        public static string Val_OnlyNumber_Patente {
            get {
                return ResourceManager.GetString("Val_OnlyNumber_Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patente es requerido.
        /// </summary>
        public static string Val_Required_Patente {
            get {
                return ResourceManager.GetString("Val_Required_Patente", resourceCulture);
            }
        }
    }
}
