//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.Polizas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ModalPagoPoliza {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _ModalPagoPoliza() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.Polizas._ModalPagoPoliza", typeof(_ModalPagoPoliza).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago Poliza.
        /// </summary>
        public static string Lbl_Pago_Poliza {
            get {
                return ResourceManager.GetString("Lbl_Pago_Poliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultimos 6 pagos.
        /// </summary>
        public static string Lbl_ultimos_pagos {
            get {
                return ResourceManager.GetString("Lbl_ultimos_pagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Mdl_PagoPoliza_Btn_Cerrar {
            get {
                return ResourceManager.GetString("Mdl_PagoPoliza_Btn_Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        public static string Mdl_PagoPoliza_Btn_GuardarCambios {
            get {
                return ResourceManager.GetString("Mdl_PagoPoliza_Btn_GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acronimo.
        /// </summary>
        public static string Mdl_PagoPoliza_Tblb_Datos_Acronimo {
            get {
                return ResourceManager.GetString("Mdl_PagoPoliza_Tblb_Datos_Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        public static string Mdl_PagoPoliza_Tblb_Datos_Archivo {
            get {
                return ResourceManager.GetString("Mdl_PagoPoliza_Tblb_Datos_Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Mdl_PagoPoliza_Tblb_Datos_Empresa {
            get {
                return ResourceManager.GetString("Mdl_PagoPoliza_Tblb_Datos_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        public static string Mdl_PagoPoliza_Tblb_Datos_FechaInicio {
            get {
                return ResourceManager.GetString("Mdl_PagoPoliza_Tblb_Datos_FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Termino.
        /// </summary>
        public static string Mdl_PagoPoliza_Tblb_Datos_FechaTermino {
            get {
                return ResourceManager.GetString("Mdl_PagoPoliza_Tblb_Datos_FechaTermino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin Periodo Pago.
        /// </summary>
        public static string Mdl_PagoPoliza_Tblb_Datos_FinPeriodoPago {
            get {
                return ResourceManager.GetString("Mdl_PagoPoliza_Tblb_Datos_FinPeriodoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio Periodo Pago.
        /// </summary>
        public static string Mdl_PagoPoliza_Tblb_Datos_InicioPeriodoPago {
            get {
                return ResourceManager.GetString("Mdl_PagoPoliza_Tblb_Datos_InicioPeriodoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ost.
        /// </summary>
        public static string Mdl_PagoPoliza_Tblb_Datos_Ost {
            get {
                return ResourceManager.GetString("Mdl_PagoPoliza_Tblb_Datos_Ost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poliza Nro.
        /// </summary>
        public static string Mdl_PagoPoliza_Tblb_Datos_PolizaNro {
            get {
                return ResourceManager.GetString("Mdl_PagoPoliza_Tblb_Datos_PolizaNro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Poliza.
        /// </summary>
        public static string Mdl_PagoPoliza_Tblh_Datos_DatosDePoliza {
            get {
                return ResourceManager.GetString("Mdl_PagoPoliza_Tblh_Datos_DatosDePoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Msg_Btn_Cancelar {
            get {
                return ResourceManager.GetString("Msg_Btn_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si, Eliminar.
        /// </summary>
        public static string Msg_Btn_Eliminar {
            get {
                return ResourceManager.GetString("Msg_Btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos eliminados.
        /// </summary>
        public static string Msg_Datos_Eliminados {
            get {
                return ResourceManager.GetString("Msg_Datos_Eliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos guardados correctamente.
        /// </summary>
        public static string Msg_DatosGuardados {
            get {
                return ResourceManager.GetString("Msg_DatosGuardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar pago de poliza?.
        /// </summary>
        public static string Msg_Eliminar_Pago_Poliza {
            get {
                return ResourceManager.GetString("Msg_Eliminar_Pago_Poliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos eliminados correctamente.
        /// </summary>
        public static string Msg_EliminarDatos {
            get {
                return ResourceManager.GetString("Msg_EliminarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo cargar. El nombre del archivo supera el maximo de caracteres permitidos de 45 caracteres.
        /// </summary>
        public static string Msg_MaximoCaracteres {
            get {
                return ResourceManager.GetString("Msg_MaximoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Tblb_Pagos_Eliminar {
            get {
                return ResourceManager.GetString("Tblb_Pagos_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string Tblb_Pagos_Ver {
            get {
                return ResourceManager.GetString("Tblb_Pagos_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Tblh_Pagos_Eliminar {
            get {
                return ResourceManager.GetString("Tblh_Pagos_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Tblh_Pagos_Estado {
            get {
                return ResourceManager.GetString("Tblh_Pagos_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Ingreso.
        /// </summary>
        public static string Tblh_Pagos_Fecha_Ingreso {
            get {
                return ResourceManager.GetString("Tblh_Pagos_Fecha_Ingreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin Periodo.
        /// </summary>
        public static string Tblh_Pagos_Fin_Periodo {
            get {
                return ResourceManager.GetString("Tblh_Pagos_Fin_Periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio Periodo.
        /// </summary>
        public static string Tblh_Pagos_Inicio_Periodo {
            get {
                return ResourceManager.GetString("Tblh_Pagos_Inicio_Periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subido por.
        /// </summary>
        public static string Tblh_Pagos_Subido_Por {
            get {
                return ResourceManager.GetString("Tblh_Pagos_Subido_Por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string Tblh_Pagos_Ver {
            get {
                return ResourceManager.GetString("Tblh_Pagos_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo es requerido.
        /// </summary>
        public static string Val_ArchivoEsRequerido {
            get {
                return ResourceManager.GetString("Val_ArchivoEsRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Fin Periodo Pago.
        /// </summary>
        public static string Val_SeleccioneFinPeriodoPago {
            get {
                return ResourceManager.GetString("Val_SeleccioneFinPeriodoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Inicio Periodo Pago.
        /// </summary>
        public static string Val_SeleccioneInicioPeriodoPago {
            get {
                return ResourceManager.GetString("Val_SeleccioneInicioPeriodoPago", resourceCulture);
            }
        }
    }
}
