//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.Polizas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ModalDuplicarPoliza {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _ModalDuplicarPoliza() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.Polizas._ModalDuplicarPoliza", typeof(_ModalDuplicarPoliza).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Btn_Eliminar {
            get {
                return ResourceManager.GetString("Btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar la poliza seleccionada?.
        /// </summary>
        public static string ConfirmMsgDelete {
            get {
                return ResourceManager.GetString("ConfirmMsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copia poliza.
        /// </summary>
        public static string Lbl_Copia_Poliza {
            get {
                return ResourceManager.GetString("Lbl_Copia_Poliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poliza duplicada correctamente.
        /// </summary>
        public static string Lbl_Poliza_Duplicada_Correctamente {
            get {
                return ResourceManager.GetString("Lbl_Poliza_Duplicada_Correctamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE OST.
        /// </summary>
        public static string Lbl_Seleccione_OST {
            get {
                return ResourceManager.GetString("Lbl_Seleccione_OST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Btn_Agregar {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Btn_Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Btn_Cerrar {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Btn_Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duplicar Poliza.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Btn_DuplicarPoliza {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Btn_DuplicarPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Btn_Eliminar {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acronimo.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblb_Datos_Acronimo {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblb_Datos_Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblb_Datos_Archivo {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblb_Datos_Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblb_Datos_Empresa {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblb_Datos_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblb_Datos_FechaInicio {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblb_Datos_FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Termino.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblb_Datos_FechaTermino {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblb_Datos_FechaTermino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ost.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblb_Datos_Ost {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblb_Datos_Ost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poliza Nro.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblb_Datos_PolizaNro {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblb_Datos_PolizaNro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblb_Polizas_Apellidos {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblb_Polizas_Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblb_Polizas_ID {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblb_Polizas_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblb_Polizas_Nombres {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblb_Polizas_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Poliza.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblh_Datos_DatosDePoliza {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblh_Datos_DatosDePoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblh_Polizas_Apellido {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblh_Polizas_Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblh_Polizas_Eliminar {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblh_Polizas_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblh_Polizas_Id {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblh_Polizas_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblh_Polizas_Nombre {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblh_Polizas_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro.
        /// </summary>
        public static string Mdl_DuplicarPoliza_Tblh_Polizas_Nro {
            get {
                return ResourceManager.GetString("Mdl_DuplicarPoliza_Tblh_Polizas_Nro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Msg_Bnt_Cancelar {
            get {
                return ResourceManager.GetString("Msg_Bnt_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si, Eliminar.
        /// </summary>
        public static string Msg_Btn_Eliminar {
            get {
                return ResourceManager.GetString("Msg_Btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos guardados correctamente.
        /// </summary>
        public static string Msg_DatosGuardados {
            get {
                return ResourceManager.GetString("Msg_DatosGuardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea continuar con la eliminacion?.
        /// </summary>
        public static string Msg_EliminarContinuar {
            get {
                return ResourceManager.GetString("Msg_EliminarContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo cargar. El nombre del archivo supera el maximo de caracteres permitidos de 45 caracteres.
        /// </summary>
        public static string Msg_MaximoCaracteres {
            get {
                return ResourceManager.GetString("Msg_MaximoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Poliza Nro.
        /// </summary>
        public static string Phl_IngresePoliza {
            get {
                return ResourceManager.GetString("Phl_IngresePoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a APELLIDOS es requerido.
        /// </summary>
        public static string Val_APELLIDOSEsRequerido {
            get {
                return ResourceManager.GetString("Val_APELLIDOSEsRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo es requerido.
        /// </summary>
        public static string Val_ArchivoEsRequerido {
            get {
                return ResourceManager.GetString("Val_ArchivoEsRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID ya esta ingresado.
        /// </summary>
        public static string Val_ElIDYaEstaIngresado {
            get {
                return ResourceManager.GetString("Val_ElIDYaEstaIngresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID es Requerido.
        /// </summary>
        public static string Val_IDEsRequerido {
            get {
                return ResourceManager.GetString("Val_IDEsRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRES es requerido.
        /// </summary>
        public static string Val_NOMBRESEsRequerido {
            get {
                return ResourceManager.GetString("Val_NOMBRESEsRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poliza Nro es requerido.
        /// </summary>
        public static string Val_PolizaNroEsrequerido {
            get {
                return ResourceManager.GetString("Val_PolizaNroEsrequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro. de poliza ya ingresado, verifique listado de polizas cargadas..
        /// </summary>
        public static string Val_Remote_Nro_Poliza {
            get {
                return ResourceManager.GetString("Val_Remote_Nro_Poliza", resourceCulture);
            }
        }
    }
}
