//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.CargarCursosCtta {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.CargarCursosCtta.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string Lbl_a {
            get {
                return ResourceManager.GetString("Lbl_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar Cursos.
        /// </summary>
        public static string Lbl_Cargar_Cursos {
            get {
                return ResourceManager.GetString("Lbl_Cargar_Cursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string Lbl_de {
            get {
                return ResourceManager.GetString("Lbl_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Lbl_Editar {
            get {
                return ResourceManager.GetString("Lbl_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN EDICIÓN.
        /// </summary>
        public static string Lbl_EN_EDICION {
            get {
                return ResourceManager.GetString("Lbl_EN_EDICION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Cargar Cursos.
        /// </summary>
        public static string Lbl_Listado_Cargar_Cursos {
            get {
                return ResourceManager.GetString("Lbl_Listado_Cargar_Cursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrando.
        /// </summary>
        public static string Lbl_Mostrando {
            get {
                return ResourceManager.GetString("Lbl_Mostrando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Curso.
        /// </summary>
        public static string Lbl_Nuevo_Curso {
            get {
                return ResourceManager.GetString("Lbl_Nuevo_Curso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENDIENTE.
        /// </summary>
        public static string Lbl_PENDIENTE {
            get {
                return ResourceManager.GetString("Lbl_PENDIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        public static string Lbl_Registros {
            get {
                return ResourceManager.GetString("Lbl_Registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONE ESTADO.
        /// </summary>
        public static string Lbl_SELECCIONE_ESTADO {
            get {
                return ResourceManager.GetString("Lbl_SELECCIONE_ESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALIDADO.
        /// </summary>
        public static string Lbl_VALIDADO {
            get {
                return ResourceManager.GetString("Lbl_VALIDADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charla.
        /// </summary>
        public static string Phl_Charla {
            get {
                return ResourceManager.GetString("Phl_Charla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Phl_Fecha {
            get {
                return ResourceManager.GetString("Phl_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participantes.
        /// </summary>
        public static string Phl_Participantes {
            get {
                return ResourceManager.GetString("Phl_Participantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charla.
        /// </summary>
        public static string Tblh_Charla {
            get {
                return ResourceManager.GetString("Tblh_Charla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Tblh_Editar {
            get {
                return ResourceManager.GetString("Tblh_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Tblh_Estado {
            get {
                return ResourceManager.GetString("Tblh_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Tblh_Fecha {
            get {
                return ResourceManager.GetString("Tblh_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participantes.
        /// </summary>
        public static string Tblh_Participantes {
            get {
                return ResourceManager.GetString("Tblh_Participantes", resourceCulture);
            }
        }
    }
}
