//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.Funcionarios {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Control_Laboral_Upload_Disputa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Control_Laboral_Upload_Disputa() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.Funcionarios._Control_Laboral_Upload_Dis" +
                            "puta", typeof(_Control_Laboral_Upload_Disputa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir Nueva Disputa.
        /// </summary>
        public static string Btn_AbrirDisputa {
            get {
                return ResourceManager.GetString("Btn_AbrirDisputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Btn_Cerrar {
            get {
                return ResourceManager.GetString("Btn_Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Disputa.
        /// </summary>
        public static string Btn_IngresarDisputa {
            get {
                return ResourceManager.GetString("Btn_IngresarDisputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disputa Documento.
        /// </summary>
        public static string Lbl_DisputaDocumento {
            get {
                return ResourceManager.GetString("Lbl_DisputaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        public static string Lbl_Documento {
            get {
                return ResourceManager.GetString("Lbl_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Documento.
        /// </summary>
        public static string Lbl_EstadoDocumento {
            get {
                return ResourceManager.GetString("Lbl_EstadoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final.
        /// </summary>
        public static string Lbl_FechaFin {
            get {
                return ResourceManager.GetString("Lbl_FechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        public static string Lbl_FechaInicio {
            get {
                return ResourceManager.GetString("Lbl_FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string Lbl_ID {
            get {
                return ResourceManager.GetString("Lbl_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Lbl_Nombres {
            get {
                return ResourceManager.GetString("Lbl_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string Lbl_Observaciones {
            get {
                return ResourceManager.GetString("Lbl_Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones Validador.
        /// </summary>
        public static string Lbl_ObservacionesValidador {
            get {
                return ResourceManager.GetString("Lbl_ObservacionesValidador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Documento.
        /// </summary>
        public static string Lbl_TipoDocumento {
            get {
                return ResourceManager.GetString("Lbl_TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Documento.
        /// </summary>
        public static string Lbl_VerDocumento {
            get {
                return ResourceManager.GetString("Lbl_VerDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo Rechazo.
        /// </summary>
        public static string Lgn_MotivoRechazo {
            get {
                return ResourceManager.GetString("Lgn_MotivoRechazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivos de Rechazo.
        /// </summary>
        public static string Lgn_MotivosRechazo {
            get {
                return ResourceManager.GetString("Lgn_MotivosRechazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Observaciones.
        /// </summary>
        public static string Phl_Observaciones {
            get {
                return ResourceManager.GetString("Phl_Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Observaciones.
        /// </summary>
        public static string Val_Required_Observaciones {
            get {
                return ResourceManager.GetString("Val_Required_Observaciones", resourceCulture);
            }
        }
    }
}
