//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.Funcionarios {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Control_Liquidaciones_Upload_Edit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Control_Liquidaciones_Upload_Edit() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.Funcionarios._Control_Liquidaciones_Uplo" +
                            "ad_Edit", typeof(_Control_Liquidaciones_Upload_Edit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string Btn_Actulizar {
            get {
                return ResourceManager.GetString("Btn_Actulizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo Cargado.
        /// </summary>
        public static string Lbl_ArchivoCargado {
            get {
                return ResourceManager.GetString("Lbl_ArchivoCargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bono IP.
        /// </summary>
        public static string Lbl_BonoIP {
            get {
                return ResourceManager.GetString("Lbl_BonoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bono IS.
        /// </summary>
        public static string Lbl_BonoIS {
            get {
                return ResourceManager.GetString("Lbl_BonoIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Liquidacion.
        /// </summary>
        public static string Lbl_EditarLiquidacion {
            get {
                return ResourceManager.GetString("Lbl_EditarLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string Lbl_ID {
            get {
                return ResourceManager.GetString("Lbl_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Liquidacion Actualizada Correctamente.
        /// </summary>
        public static string Lbl_LiquidacionActualizada {
            get {
                return ResourceManager.GetString("Lbl_LiquidacionActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto Imponible.
        /// </summary>
        public static string Lbl_MontoImponible {
            get {
                return ResourceManager.GetString("Lbl_MontoImponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto Liquido.
        /// </summary>
        public static string Lbl_MontoLlquido {
            get {
                return ResourceManager.GetString("Lbl_MontoLlquido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto Transferencia.
        /// </summary>
        public static string Lbl_MontoTransferencia {
            get {
                return ResourceManager.GetString("Lbl_MontoTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Lbl_Nombres {
            get {
                return ResourceManager.GetString("Lbl_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo.
        /// </summary>
        public static string Lbl_Periodo {
            get {
                return ResourceManager.GetString("Lbl_Periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Archivo.
        /// </summary>
        public static string Lbl_SelecioneArchivo {
            get {
                return ResourceManager.GetString("Lbl_SelecioneArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo Cargado.
        /// </summary>
        public static string Msg_ArchivoCargado {
            get {
                return ResourceManager.GetString("Msg_ArchivoCargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Bono IP.
        /// </summary>
        public static string Phl_BonoIP {
            get {
                return ResourceManager.GetString("Phl_BonoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Bono IS.
        /// </summary>
        public static string Phl_BonoIS {
            get {
                return ResourceManager.GetString("Phl_BonoIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Monto Imponible.
        /// </summary>
        public static string Phl_Monto_Imponible {
            get {
                return ResourceManager.GetString("Phl_Monto_Imponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Monto Liquido.
        /// </summary>
        public static string Phl_MontoLiquido {
            get {
                return ResourceManager.GetString("Phl_MontoLiquido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Monto Tranferencia.
        /// </summary>
        public static string Phl_MontoTranferencia {
            get {
                return ResourceManager.GetString("Phl_MontoTranferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Bono IP es requerido.
        /// </summary>
        public static string Val_Required_BonoIP {
            get {
                return ResourceManager.GetString("Val_Required_BonoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Bono IS es requerido.
        /// </summary>
        public static string Val_Required_BonoIS {
            get {
                return ResourceManager.GetString("Val_Required_BonoIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Monto Imponible es requerido.
        /// </summary>
        public static string Val_Required_MontoImponible {
            get {
                return ResourceManager.GetString("Val_Required_MontoImponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Monto Liquido es requerido.
        /// </summary>
        public static string Val_Required_MontoLiquido {
            get {
                return ResourceManager.GetString("Val_Required_MontoLiquido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Monto Transferencia es requerido.
        /// </summary>
        public static string Val_Required_MontoTransferencia {
            get {
                return ResourceManager.GetString("Val_Required_MontoTransferencia", resourceCulture);
            }
        }
    }
}
