//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.Funcionarios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Documentacion_Documentos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Documentacion_Documentos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.Funcionarios._Documentacion_Documentos", typeof(_Documentacion_Documentos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos C.  Laboral.
        /// </summary>
        public static string Lbl_DocumentosLaboral {
            get {
                return ResourceManager.GetString("Lbl_DocumentosLaboral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos Personales.
        /// </summary>
        public static string Lbl_DocumentosPersonales {
            get {
                return ResourceManager.GetString("Lbl_DocumentosPersonales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        public static string Lgn_Documentos {
            get {
                return ResourceManager.GetString("Lgn_Documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechas.
        /// </summary>
        public static string Tblh_Datos {
            get {
                return ResourceManager.GetString("Tblh_Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disputa.
        /// </summary>
        public static string Tblh_Disputa {
            get {
                return ResourceManager.GetString("Tblh_Disputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documneto.
        /// </summary>
        public static string Tblh_Documento {
            get {
                return ResourceManager.GetString("Tblh_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Tblh_Estado {
            get {
                return ResourceManager.GetString("Tblh_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OB.
        /// </summary>
        public static string Tblh_OB {
            get {
                return ResourceManager.GetString("Tblh_OB", resourceCulture);
            }
        }
    }
}
