//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.Funcionarios {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Modal_Disputas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Modal_Disputas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.Funcionarios.Modal_Disputas", typeof(Modal_Disputas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Mdl_Disputa_Btn_Cerrar {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Btn_Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Disputa.
        /// </summary>
        public static string Mdl_Disputa_Btn_IngresarDisputa {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Btn_IngresarDisputa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disputa de Documento.
        /// </summary>
        public static string Mdl_Disputa_Lbl_Documento {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Lbl_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string Mdl_Disputa_Lbl_Observaciones {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Lbl_Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones Validador.
        /// </summary>
        public static string Mdl_Disputa_Lbl_ObservacionesValidador {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Lbl_ObservacionesValidador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Adicionales Contrato.
        /// </summary>
        public static string Mdl_Disputa_Lgn_DatosAdicionalesContrato {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Lgn_DatosAdicionalesContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivos de Rechazo.
        /// </summary>
        public static string Mdl_Disputa_Lgn_MotivosRechazo {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Lgn_MotivosRechazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Observaciones.
        /// </summary>
        public static string Mdl_Disputa_Phl_Observaciones {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Phl_Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        public static string Mdl_Disputa_Tblb_Cargo {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Tblb_Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        public static string Mdl_Disputa_Tblb_Documento {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Tblb_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del Documento.
        /// </summary>
        public static string Mdl_Disputa_Tblb_EstadoDocumento {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Tblb_EstadoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string Mdl_Disputa_Tblb_ID {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Tblb_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Mdl_Disputa_Tblb_Nombres {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Tblb_Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operacion.
        /// </summary>
        public static string Mdl_Disputa_Tblb_Operacion {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Tblb_Operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salario.
        /// </summary>
        public static string Mdl_Disputa_Tblb_Salario {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Tblb_Salario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Contrato.
        /// </summary>
        public static string Mdl_Disputa_Tblb_TipoContrato {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Tblb_TipoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno.
        /// </summary>
        public static string Mdl_Disputa_Tblb_Turno {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Tblb_Turno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Documento.
        /// </summary>
        public static string Mdl_Disputa_Tblb_VerDocumento {
            get {
                return ResourceManager.GetString("Mdl_Disputa_Tblb_VerDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disputa Ingresada Correctamente.
        /// </summary>
        public static string Msg_DisputaIngresada {
            get {
                return ResourceManager.GetString("Msg_DisputaIngresada", resourceCulture);
            }
        }
    }
}
