//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mandante.AAQ_Puestos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Mandante.AAQ_Puestos.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A.
        /// </summary>
        public static string Lbl_A {
            get {
                return ResourceManager.GetString("Lbl_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ant.
        /// </summary>
        public static string Lbl_Ant {
            get {
                return ResourceManager.GetString("Lbl_Ant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        public static string Lbl_De {
            get {
                return ResourceManager.GetString("Lbl_De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de puestos.
        /// </summary>
        public static string Lbl_listadoPuestos {
            get {
                return ResourceManager.GetString("Lbl_listadoPuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrando.
        /// </summary>
        public static string Lbl_Mostrando {
            get {
                return ResourceManager.GetString("Lbl_Mostrando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paginación.
        /// </summary>
        public static string Lbl_Paginacion {
            get {
                return ResourceManager.GetString("Lbl_Paginacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sig.
        /// </summary>
        public static string Lbl_Pos {
            get {
                return ResourceManager.GetString("Lbl_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar - Puestos.
        /// </summary>
        public static string Lbl_Puestos {
            get {
                return ResourceManager.GetString("Lbl_Puestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TODOS.
        /// </summary>
        public static string Lbl_Puestos_Todos {
            get {
                return ResourceManager.GetString("Lbl_Puestos_Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros.
        /// </summary>
        public static string Lbl_Registros {
            get {
                return ResourceManager.GetString("Lbl_Registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar - Puestos.
        /// </summary>
        public static string Lnk_Puestos {
            get {
                return ResourceManager.GetString("Lnk_Puestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Msg_Btn_Cancelar {
            get {
                return ResourceManager.GetString("Msg_Btn_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Msg_Btn_Eliminar {
            get {
                return ResourceManager.GetString("Msg_Btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminación correcta.
        /// </summary>
        public static string Msg_EliminacionCorrecta {
            get {
                return ResourceManager.GetString("Msg_EliminacionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el proceso de eliminar.
        /// </summary>
        public static string Msg_EliminacionError {
            get {
                return ResourceManager.GetString("Msg_EliminacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro que deseas eliminar este puesto?.
        /// </summary>
        public static string Msg_Lbl_Eliminar {
            get {
                return ResourceManager.GetString("Msg_Lbl_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Tblb_Editar {
            get {
                return ResourceManager.GetString("Tblb_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Tblb_Eliminar {
            get {
                return ResourceManager.GetString("Tblb_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string Tblf_Activo {
            get {
                return ResourceManager.GetString("Tblf_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificado.
        /// </summary>
        public static string Tblf_Calificado {
            get {
                return ResourceManager.GetString("Tblf_Calificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        public static string Tblf_Categoria {
            get {
                return ResourceManager.GetString("Tblf_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Tblf_Descripcion {
            get {
                return ResourceManager.GetString("Tblf_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Tblf_Nombre {
            get {
                return ResourceManager.GetString("Tblf_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto.
        /// </summary>
        public static string Tblf_Puesto {
            get {
                return ResourceManager.GetString("Tblf_Puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string Tblh_Activo {
            get {
                return ResourceManager.GetString("Tblh_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificado.
        /// </summary>
        public static string Tblh_Calificado {
            get {
                return ResourceManager.GetString("Tblh_Calificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        public static string Tblh_Categoria {
            get {
                return ResourceManager.GetString("Tblh_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Tblh_Descripcion {
            get {
                return ResourceManager.GetString("Tblh_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Tblh_Editar {
            get {
                return ResourceManager.GetString("Tblh_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Tblh_Eliminar {
            get {
                return ResourceManager.GetString("Tblh_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Tblh_Nombre {
            get {
                return ResourceManager.GetString("Tblh_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto.
        /// </summary>
        public static string Tblh_Puesto {
            get {
                return ResourceManager.GetString("Tblh_Puesto", resourceCulture);
            }
        }
    }
}
