//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.ControlLaboral {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Modal_DisputaCrear {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Modal_DisputaCrear() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.ControlLaboralCtta._Modal_DisputaCrear", typeof(_Modal_DisputaCrear).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Btn_Cancelar {
            get {
                return ResourceManager.GetString("Btn_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Btn_Guardar {
            get {
                return ResourceManager.GetString("Btn_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acronimo.
        /// </summary>
        public static string Lbl_Acronimo {
            get {
                return ResourceManager.GetString("Lbl_Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo no existe.
        /// </summary>
        public static string Lbl_ArchivoNoExiste {
            get {
                return ResourceManager.GetString("Lbl_ArchivoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        public static string Lbl_Documento {
            get {
                return ResourceManager.GetString("Lbl_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Lbl_Empresa {
            get {
                return ResourceManager.GetString("Lbl_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del Documento.
        /// </summary>
        public static string Lbl_EstadoDocumento {
            get {
                return ResourceManager.GetString("Lbl_EstadoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivos de Rechazo.
        /// </summary>
        public static string Lbl_MotivosRechazo {
            get {
                return ResourceManager.GetString("Lbl_MotivosRechazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string Lbl_Observaciones {
            get {
                return ResourceManager.GetString("Lbl_Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente.
        /// </summary>
        public static string Lbl_Pendiente {
            get {
                return ResourceManager.GetString("Lbl_Pendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazado.
        /// </summary>
        public static string Lbl_Rechazado {
            get {
                return ResourceManager.GetString("Lbl_Rechazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disputa de Documento.
        /// </summary>
        public static string Lbl_Titulo {
            get {
                return ResourceManager.GetString("Lbl_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validado.
        /// </summary>
        public static string Lbl_Validado {
            get {
                return ResourceManager.GetString("Lbl_Validado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Documento.
        /// </summary>
        public static string Lbl_VerDocumento {
            get {
                return ResourceManager.GetString("Lbl_VerDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disputa guardada exitosamente.
        /// </summary>
        public static string Msg_DisputaGuardadaExitosamente {
            get {
                return ResourceManager.GetString("Msg_DisputaGuardadaExitosamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo DOC_ID no debe ser nulo.
        /// </summary>
        public static string Msg_DocIdNoNulo {
            get {
                return ResourceManager.GetString("Msg_DocIdNoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese las observaciones.
        /// </summary>
        public static string Phl_Observaciones {
            get {
                return ResourceManager.GetString("Phl_Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las Observaciones son requeridas.
        /// </summary>
        public static string Val_Required_Observaciones {
            get {
                return ResourceManager.GetString("Val_Required_Observaciones", resourceCulture);
            }
        }
    }
}
