//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.ControlLaboral {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CargaLiquidacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CargaLiquidacion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.ControlLaboralCtta.CargaLiquidacion", typeof(CargaLiquidacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Btn_Guardar {
            get {
                return ResourceManager.GetString("Btn_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        public static string Lbl_Advertencia {
            get {
                return ResourceManager.GetString("Lbl_Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede Descargar Formato de Carga desde Aqui..
        /// </summary>
        public static string Lbl_Descarga {
            get {
                return ResourceManager.GetString("Lbl_Descarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string Lbl_Documento {
            get {
                return ResourceManager.GetString("Lbl_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos Control Laboral.
        /// </summary>
        public static string Lbl_IndexPrincipal_Titulo {
            get {
                return ResourceManager.GetString("Lbl_IndexPrincipal_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion.
        /// </summary>
        public static string Lbl_Informacion {
            get {
                return ResourceManager.GetString("Lbl_Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Documentos Control Laboral.
        /// </summary>
        public static string Lbl_ListadoTitulo {
            get {
                return ResourceManager.GetString("Lbl_ListadoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string Lbl_Nuevo {
            get {
                return ResourceManager.GetString("Lbl_Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros Ingresados.
        /// </summary>
        public static string Lbl_RegistrosIngresados {
            get {
                return ResourceManager.GetString("Lbl_RegistrosIngresados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros Invalidos.
        /// </summary>
        public static string Lbl_RegistrosInvalidos {
            get {
                return ResourceManager.GetString("Lbl_RegistrosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros Leidos.
        /// </summary>
        public static string Lbl_RegistrosLeidos {
            get {
                return ResourceManager.GetString("Lbl_RegistrosLeidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros Repetidos.
        /// </summary>
        public static string Lbl_RegistrosRepetidos {
            get {
                return ResourceManager.GetString("Lbl_RegistrosRepetidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado de la Subida.
        /// </summary>
        public static string Lbl_ResultadoSubida {
            get {
                return ResourceManager.GetString("Lbl_ResultadoSubida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga Liquidacion.
        /// </summary>
        public static string Lbl_Titulo {
            get {
                return ResourceManager.GetString("Lbl_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos marcados con * son obligatorios.
        ///.
        /// </summary>
        public static string Msg_CamposAsterisco {
            get {
                return ResourceManager.GetString("Msg_CamposAsterisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de archivos excede al maximo: {{maxFiles}} .
        /// </summary>
        public static string Msg_Dropzone_CantidadArchivosExcedida {
            get {
                return ResourceManager.GetString("Msg_Dropzone_CantidadArchivosExcedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño actual {{filesize}} excede el maximo: {{maxFilesize}}.
        /// </summary>
        public static string Msg_Dropzone_ExcedeTamanioMaximo {
            get {
                return ResourceManager.GetString("Msg_Dropzone_ExcedeTamanioMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension invalida.
        /// </summary>
        public static string Msg_Dropzone_ExtensionInvalida {
            get {
                return ResourceManager.GetString("Msg_Dropzone_ExtensionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de archivo excede longitud maxima: ___MAX_LEN.
        /// </summary>
        public static string Msg_Dropzone_LongMaxExcedida {
            get {
                return ResourceManager.GetString("Msg_Dropzone_LongMaxExcedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Soltar archivos aqui o hacer click. &lt;/strong&gt;&lt;/br&gt;.
        /// </summary>
        public static string Msg_Dropzone_PorDefecto {
            get {
                return ResourceManager.GetString("Msg_Dropzone_PorDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitar.
        /// </summary>
        public static string Msg_Dropzone_Quitar {
            get {
                return ResourceManager.GetString("Msg_Dropzone_Quitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad guardada correctamente.
        /// </summary>
        public static string Msg_EntidadGuardadaCtte {
            get {
                return ResourceManager.GetString("Msg_EntidadGuardadaCtte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad a actualizar no existe.
        /// </summary>
        public static string Msg_EntidadNoExiste {
            get {
                return ResourceManager.GetString("Msg_EntidadNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad a crear ya existe.
        /// </summary>
        public static string Msg_EntidadYaExiste {
            get {
                return ResourceManager.GetString("Msg_EntidadYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de Lectura del archivo o no es el correcto.
        /// </summary>
        public static string Msg_ErrorLecturaSubida {
            get {
                return ResourceManager.GetString("Msg_ErrorLecturaSubida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension de archivo no permitida.
        /// </summary>
        public static string Msg_ExtensionArchivoNoPermitida {
            get {
                return ResourceManager.GetString("Msg_ExtensionArchivoNoPermitida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud maxima de nombre del archivo adjunto excedido(45).
        /// </summary>
        public static string Msg_LargoMaxNombreArchivoExcedido {
            get {
                return ResourceManager.GetString("Msg_LargoMaxNombreArchivoExcedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subida de Archivo Exitosa.
        /// </summary>
        public static string Msg_SubidaArchivoExitosa {
            get {
                return ResourceManager.GetString("Msg_SubidaArchivoExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño maximo de archivo excedido(4Mb).
        /// </summary>
        public static string Msg_TamanioMaximoArchivoExcedido {
            get {
                return ResourceManager.GetString("Msg_TamanioMaximoArchivoExcedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este proceso puede tomar un tiempo, si el archivo tuviera un tamaño mayor a 2 MB favor comuniquese con WebControl..
        /// </summary>
        public static string Msg_Tiempo {
            get {
                return ResourceManager.GetString("Msg_Tiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo adjunto es requerido.
        /// </summary>
        public static string Val_Required_Archivo {
            get {
                return ResourceManager.GetString("Val_Required_Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo adjunto es requerido.
        /// </summary>
        public static string Val_Required_Archivo2 {
            get {
                return ResourceManager.GetString("Val_Required_Archivo2", resourceCulture);
            }
        }
    }
}
