CREATE PROCEDURE [dbo].[V4MVC_A056_FORM301_DELETE_CONTROLLABORAL_CTTA]
(
  @IDEMPRESA		NVARCHAR(10)
 ,@ID_CERTIFICADO	INT
 ,@USUARIO			NVARCHAR(10)
 ,@DISPUTA_ID		INT
 ,@DISPUTA_EXISTE	INT OUTPUT
 ,@DISPUTA_EMPRESA	NVARCHAR(12) OUTPUT
 ,@DISPUTA_FECHA	NVARCHAR(8) OUTPUT
 ,@DISPUTA_USUARIO  NVARCHAR(10) OUTPUT
) AS
BEGIN
	DECLARE @CURR_FECHA NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 112) /* yyyymmdd */
	DECLARE @CURR_TIEMPOFULL NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 108) /* hh:mm:ss */

	DECLARE @F30_1_EXISTS BIT = 0
	DECLARE @F30_1_ID_CERTIFICADO INT
	DECLARE @F30_1_EMPRESA NVARCHAR(10)
	DECLARE @F30_1_REGION NVARCHAR(5)
	DECLARE @F30_1_INSPECCION NVARCHAR(4)
	DECLARE @F30_1_ANIO INT
	DECLARE @F30_1_CERTIFICADO BIGINT
	DECLARE @F30_1_CLAVE NVARCHAR(50)
	DECLARE @F30_1_TRA_DECL INT
	DECLARE @F30_1_TRA_DESV INT
	DECLARE @F30_1_TRA_VIGE INT
	DECLARE @F30_1_COT_PAG NVARCHAR(1)
	DECLARE @F30_1_COT_NPAG NVARCHAR(1)
	DECLARE @F30_1_ADJ_NOM NVARCHAR(1)
	DECLARE @F30_1_IND_AP_P INT
	DECLARE @F30_1_IND_AP_MTO INT
	DECLARE @F30_1_IND_AP_NP INT
	DECLARE @F30_1_IND_AS_P INT
	DECLARE @F30_1_IND_AS_MTO INT
	DECLARE @F30_1_IND_AS_NP INT
	DECLARE @F30_1_PERIODO_INI NVARCHAR(6)
	DECLARE @F30_1_PERIODO_FIN NVARCHAR(6)
	DECLARE @F30_1_FECHAMOD NVARCHAR(8)
	DECLARE @F30_1_HORAMOD NVARCHAR(8)
	DECLARE @F30_1_QUIEN NVARCHAR(10)
	DECLARE @F30_1_VALIDADO NVARCHAR(2)
	DECLARE @F30_1_ID_DOC INT
	DECLARE @F30_1_OBSERVACION NVARCHAR(500)
	DECLARE @F30_1_ID UNIQUEIDENTIFIER
	DECLARE @F30_1_PERIODO NVARCHAR(6)
	DECLARE @F30_1_USUARIO NVARCHAR(10)
	DECLARE @F30_1_FECHASUBE NVARCHAR(8)
	DECLARE @F30_1_HORASUBE NVARCHAR(8)
	DECLARE @F30_1_CERTUSUARIO NVARCHAR(10)
	DECLARE @F30_1_CERTFECHA NVARCHAR(8)
	DECLARE @F30_1_CERTHORA NVARCHAR(8)
	DECLARE @F30_1_OST NVARCHAR(50)

	DECLARE @F30_1_DET_ID_CERTIFICADO	NVARCHAR(10)
	DECLARE @F30_1_DET_PERIODO			NVARCHAR(8)
	DECLARE @F30_1_DET_NRO_TRAB_PAG		INT
	DECLARE @F30_1_DET_MONTO_PAGADO		BIGINT
	DECLARE @F30_1_DET_NRO_TRAB_NOPAG	INT
	DECLARE @F30_1_DET_EMPRESA			NVARCHAR(10)

	
	DECLARE @DSP_ID_DISPUTA INT
	DECLARE @DSP_ID_DOC INT
	DECLARE @DSP_ID UNIQUEIDENTIFIER
	DECLARE @DSP_HORA NVARCHAR(8)
	DECLARE @DSP_OBSERVACION NVARCHAR(1000)
	DECLARE @DSP_CERTUSUARIO NVARCHAR(10)
	DECLARE @DSP_CERTFECHA NVARCHAR(8)
	DECLARE @DSP_CERTHORA NVARCHAR(8)
	DECLARE @DSP_ESTADO	NVARCHAR(2)
	DECLARE @DSP_REVALUSUARIO NVARCHAR(10)
	DECLARE @DSP_REVALFECHA	NVARCHAR(8)
	DECLARE @DSP_REVALHORA	NVARCHAR(8)
	DECLARE @DSP_OBSERVACION_REVAL	NVARCHAR(1000)
	DECLARE @DSP_VALIDADO NVARCHAR(2)
	DECLARE @DSP_PERIODO NVARCHAR(6)
	DECLARE @DSP_ID_CERTIFICADO INT

	SET @DISPUTA_EXISTE = 0
	SET @DISPUTA_EMPRESA = ''
	SET @DISPUTA_FECHA = ''

	SELECT
		TOP 1
		@F30_1_EXISTS = 1,
		@F30_1_ID_CERTIFICADO = ID_CERTIFICADO,
		@F30_1_EMPRESA = EMPRESA,
		@F30_1_REGION = REGION,
		@F30_1_INSPECCION = INSPECCION,
		@F30_1_ANIO = ANIO,
		@F30_1_CERTIFICADO = CERTIFICADO,
		@F30_1_CLAVE = CLAVE,
		@F30_1_TRA_DECL = TRA_DECL,
		@F30_1_TRA_DESV = TRA_DESV,
		@F30_1_TRA_VIGE = TRA_VIGE,
		@F30_1_COT_PAG = COT_PAG,
		@F30_1_COT_NPAG = COT_NPAG,
		@F30_1_ADJ_NOM = ADJ_NOM,
		@F30_1_IND_AP_P = IND_AP_P,
		@F30_1_IND_AP_MTO = IND_AP_MTO,
		@F30_1_IND_AP_NP = IND_AP_NP,
		@F30_1_IND_AS_P = IND_AS_P,
		@F30_1_IND_AS_MTO = IND_AS_MTO,
		@F30_1_IND_AS_NP = IND_AS_NP,
		@F30_1_PERIODO_INI = PERIODO_INI,
		@F30_1_PERIODO_FIN = PERIODO_FIN,
		@F30_1_FECHAMOD = FECHAMOD,
		@F30_1_HORAMOD = HORAMOD,
		@F30_1_QUIEN = QUIEN,
		@F30_1_VALIDADO = VALIDADO,
		@F30_1_ID_DOC = ID_DOC,
		@F30_1_OBSERVACION = OBSERVACION,
		@F30_1_ID = ID,
		@F30_1_PERIODO = PERIODO,
		@F30_1_USUARIO = USUARIO,
		@F30_1_FECHASUBE = FECHASUBE,
		@F30_1_HORASUBE = HORASUBE,
		@F30_1_CERTUSUARIO = CERTUSUARIO,
		@F30_1_CERTFECHA = CERTFECHA,
		@F30_1_CERTHORA = CERTHORA,
		@F30_1_OST = OST
	FROM A056_FORM301
	WHERE
		EMPRESA = @IDEMPRESA AND
		ID_CERTIFICADO = @ID_CERTIFICADO
	
	IF(@F30_1_EXISTS = 1)
		BEGIN
			DECLARE cursor_f301 CURSOR
			FOR
			SELECT
				ID_CERTIFICADO,
				PERIODO,
				NRO_TRAB_PAG,
				MONTO_PAGADO,
				NRO_TRAB_NOPAG,
				EMPRESA
			FROM A056_FORM301_DET
			WHERE
				(EMPRESA = @IDEMPRESA) AND
				(ID_CERTIFICADO = @ID_CERTIFICADO)

			OPEN cursor_f301

			FETCH NEXT FROM cursor_f301 INTO 
				@F30_1_DET_ID_CERTIFICADO, 
				@F30_1_DET_PERIODO,
				@F30_1_DET_NRO_TRAB_PAG,
				@F30_1_DET_MONTO_PAGADO,
				@F30_1_DET_NRO_TRAB_NOPAG,
				@F30_1_DET_EMPRESA

			WHILE @@FETCH_STATUS = 0
				BEGIN
					INSERT INTO A056_FORM301_DET_LOG
							(
								ID_CERTIFICADO,
								PERIODO,
								NRO_TRAB_PAG,
								MONTO_PAGADO,
								NRO_TRAB_NOPAG,
								EMPRESA
							)
					VALUES
							(
								@F30_1_DET_ID_CERTIFICADO,
								@F30_1_DET_PERIODO,
								@F30_1_DET_NRO_TRAB_PAG,
								@F30_1_DET_MONTO_PAGADO,
								@F30_1_DET_NRO_TRAB_NOPAG,
								@F30_1_DET_EMPRESA
							)

					FETCH NEXT FROM cursor_f301 INTO 
						@F30_1_DET_ID_CERTIFICADO, 
						@F30_1_DET_PERIODO,
						@F30_1_DET_NRO_TRAB_PAG,
						@F30_1_DET_MONTO_PAGADO,
						@F30_1_DET_NRO_TRAB_NOPAG,
						@F30_1_DET_EMPRESA
				END

			CLOSE cursor_f301

			DEALLOCATE cursor_f301
			
			DELETE FROM A056_FORM301_DET
			WHERE
				(EMPRESA = @IDEMPRESA) AND
				(ID_CERTIFICADO = @ID_CERTIFICADO)

			INSERT INTO A056_FORM301_LOG
						(
							ID_CERTIFICADO,
							EMPRESA,
							REGION,
							INSPECCION,
							ANIO,
							CERTIFICADO,
							CLAVE,
							TRA_DECL,
							TRA_DESV,
							TRA_VIGE,
							COT_PAG,
							COT_NPAG,
							ADJ_NOM,
							IND_AP_P,
							IND_AP_MTO,
							IND_AP_NP,
							IND_AS_P,
							IND_AS_MTO,
							IND_AS_NP,
							PERIODO_INI,
							PERIODO_FIN,
							FECHAMOD,
							HORAMOD,
							QUIEN,
							VALIDADO,
							ID_DOC,
							OBSERVACION,
							ID,
							PERIODO,
							USUARIO,
							FECHASUBE,
							HORASUBE,
							CERTUSUARIO,
							CERTFECHA,
							CERTHORA,
							OST,
							USUARIODEL,
							FECHADEL,
							HORADEL
						)
			VALUES
						(
							@F30_1_ID_CERTIFICADO,
							@F30_1_EMPRESA,
							@F30_1_REGION,
							@F30_1_INSPECCION,
							@F30_1_ANIO,
							@F30_1_CERTIFICADO,
							@F30_1_CLAVE,
							@F30_1_TRA_DECL,
							@F30_1_TRA_DESV,
							@F30_1_TRA_VIGE,
							@F30_1_COT_PAG,
							@F30_1_COT_NPAG,
							@F30_1_ADJ_NOM,
							@F30_1_IND_AP_P,
							@F30_1_IND_AP_MTO,
							@F30_1_IND_AP_NP,
							@F30_1_IND_AS_P,
							@F30_1_IND_AS_MTO,
							@F30_1_IND_AS_NP,
							@F30_1_PERIODO_INI,
							@F30_1_PERIODO_FIN,
							@F30_1_FECHAMOD,
							@F30_1_HORAMOD,
							@F30_1_QUIEN,
							@F30_1_VALIDADO,
							@F30_1_ID_DOC,
							@F30_1_OBSERVACION,
							@F30_1_ID,
							@F30_1_PERIODO,
							@F30_1_USUARIO,
							@F30_1_FECHASUBE,
							@F30_1_HORASUBE,
							@F30_1_CERTUSUARIO,
							@F30_1_CERTFECHA,
							@F30_1_CERTHORA,
							@F30_1_OST,
							@USUARIO,
							@CURR_FECHA,
							@CURR_TIEMPOFULL
						)
			/*--------------------------*/
			
			SELECT
				TOP 1
				@DISPUTA_EXISTE = 1,
				@DSP_ID_DISPUTA = ID_DISPUTA,
				@DISPUTA_EMPRESA = EMPRESA,
				@DSP_ID_DOC = ID_DOC,
				@DSP_ID = ID,
				@DISPUTA_USUARIO = USUARIO,
				@DISPUTA_FECHA = FECHA,
				@DSP_HORA = HORA,
				@DSP_OBSERVACION = OBSERVACION,
				@DSP_CERTUSUARIO = CERTUSUARIO,
				@DSP_CERTFECHA = CERTFECHA,
				@DSP_CERTHORA = CERTHORA,
				@DSP_ESTADO = ESTADO,
				@DSP_REVALUSUARIO = REVALUSUARIO,
				@DSP_REVALFECHA = REVALFECHA,
				@DSP_REVALHORA = REVALHORA,
				@DSP_OBSERVACION_REVAL = OBSERVACION_REVAL,
				@DSP_VALIDADO = VALIDADO,
				@DSP_PERIODO = PERIODO,
				@DSP_ID_CERTIFICADO = ID_CERTIFICADO
			FROM DOCS_DISPUTA_CLABORAL
			WHERE
				ID_DISPUTA = @DISPUTA_ID AND
				ESTADO = 'NO'

			IF(@DISPUTA_EXISTE = 1)
				BEGIN
					INSERT INTO DOCS_DISPUTA_CLABORAL_LOG
							(
								ID_DISPUTA,
								EMPRESA,
								ID_DOC,
								ID,
								USUARIO,
								FECHA,
								HORA,
								OBSERVACION,
								CERTUSUARIO,
								CERTFECHA,
								CERTHORA,
								ESTADO,
								REVALUSUARIO,
								REVALFECHA,
								REVALHORA,
								OBSERVACION_REVAL,
								VALIDADO,
								PERIODO,
								ID_CERTIFICADO,
								USRMOD,
								FECHAMOD,
								HORAMOD,
								ACCION
							)
					VALUES (
								@DSP_ID_DISPUTA,
								@DISPUTA_EMPRESA,
								@DSP_ID_DOC,
								@DSP_ID,
								@DISPUTA_USUARIO,
								@DISPUTA_FECHA,
								@DSP_HORA,
								@DSP_OBSERVACION,
								@DSP_CERTUSUARIO,
								@DSP_CERTFECHA,
								@DSP_CERTHORA,
								@DSP_ESTADO,
								@DSP_REVALUSUARIO,
								@DSP_REVALFECHA,
								@DSP_REVALHORA,
								@DSP_OBSERVACION_REVAL,
								@DSP_VALIDADO,
								@DSP_PERIODO,
								@DSP_ID_CERTIFICADO,
								@USUARIO,
								@CURR_FECHA,
								@CURR_TIEMPOFULL,
								'ELIMINADO'
							)

					DELETE DOCS_DISPUTA_CLABORAL WHERE ID_DISPUTA = @DISPUTA_ID AND ESTADO = 'NO'
				END

			DELETE FROM A056_FORM301 WHERE (EMPRESA = @IDEMPRESA) AND (ID_CERTIFICADO = @ID_CERTIFICADO)

		END
END
