CREATE PROCEDURE [dbo].[V4MVC_TURNOS_UPDATE_PORTURNOOST_TURNOS_CTTA]
( @IDTURNO int = NULL
, @EMPRESA nvarchar(10) = NULL
, @TURNO nvarchar(20) = NULL
, @LOCAL nvarchar(50) = NULL
, @DIATRABAJO int = NULL
, @DIADESCANSO int = NULL
, @DDIURNO nvarchar(10) = NULL
, @DNOCHE nvarchar(10) = NULL
, @DDIURNO2 nvarchar(10) = NULL
, @DNOCHE2 nvarchar(10) = NULL
, @FECINICIO nvarchar(8) = NULL
, @TURDESCR nvarchar(100) = NULL
, @DOTTURNO int = NULL
, @CLASETUR nvarchar(15) = NULL
, @ESTADOTUR nvarchar(10) = NULL
, @OBSERVTUR nvarchar(100) = NULL
, @TIENEHE nvarchar(2) = NULL
, @HMAXDIANOR smallmoney = NULL
, @HMAXDIAHE smallmoney = NULL
, @HSEMANA smallmoney = NULL
, @HEXTRAS smallmoney = NULL
, @HINGRESO nvarchar(8) = NULL
, @HINDESDE nvarchar(8) = NULL
, @HINHASTA nvarchar(8) = NULL
, @HOUTDESDE nvarchar(8) = NULL
, @HOUTHASTA nvarchar(8) = NULL
, @HALIMI nvarchar(8) = NULL
, @HALIMS nvarchar(8) = NULL
, @FECHAMOD nvarchar(8) = NULL
, @HORAMOD nvarchar(8) = NULL
, @GRABO nvarchar(1) = NULL
, @TIENEFERIADO nvarchar(2) = NULL
, @HSALIDA nvarchar(8) = NULL
, @USUARIOMOD nvarchar(10) = NULL
, @VISIBLE nvarchar(2) = NULL
, @TIPO nvarchar(1) = NULL
, @HINGRESON nvarchar(8) = NULL
, @HINDESDEN nvarchar(8) = NULL
, @HINHASTAN nvarchar(8) = NULL
, @HSALIDAN nvarchar(8) = NULL
, @HOUTDESDEN nvarchar(8) = NULL
, @HOUTHASTAN nvarchar(8) = NULL
, @HALIMIN nvarchar(8) = NULL
, @HALIMSN nvarchar(8) = NULL
, @HSAL_ULIMODIA nvarchar(8) = NULL
, @FVIGENCIA nvarchar(8) = NULL
, @VALIDADO nvarchar(2) = NULL
, @EMPIEZANOCHEA nvarchar(10) = NULL
, @EMPIEZANOCHEB nvarchar(10) = NULL
, @EMPIEZA nvarchar(10) = NULL
, @OST nvarchar(14) = NULL
, @ID uniqueidentifier = NULL
, @USRSUBE nvarchar(10) = NULL
, @CERTUSUARIO nvarchar(20) = NULL
, @CERTFECHA nvarchar(8) = NULL
, @CERTHORA nvarchar(8) = NULL
, @OBS_RECHAZO text = NULL
, @HSAL_ULIMONOCHE nvarchar(8) = NULL) AS 
BEGIN

UPDATE [dbo].[TURNOS]
   SET [EMPRESA] = @EMPRESA
      ,[LOCAL] = @LOCAL
      ,[DIATRABAJO] = @DIATRABAJO
      ,[DIADESCANSO] = @DIADESCANSO
      ,[DDIURNO] = @DDIURNO
      ,[DNOCHE] = @DNOCHE
      ,[DDIURNO2] = @DDIURNO2
      ,[DNOCHE2] = @DNOCHE2
      ,[FECINICIO] = @FECINICIO
      ,[TURDESCR] = @TURDESCR
      ,[DOTTURNO] = @DOTTURNO
      ,[CLASETUR] = @CLASETUR
      ,[ESTADOTUR] = @ESTADOTUR
      ,[OBSERVTUR] = @OBSERVTUR
      ,[TIENEHE] = @TIENEHE
      ,[HMAXDIANOR] = @HMAXDIANOR
      ,[HMAXDIAHE] = @HMAXDIAHE
      ,[HSEMANA] = @HSEMANA
      ,[HEXTRAS] = @HEXTRAS
      ,[HINGRESO] = @HINGRESO
      ,[HINDESDE] = @HINDESDE
      ,[HINHASTA] = @HINHASTA
      ,[HOUTDESDE] = @HOUTDESDE
      ,[HOUTHASTA] = @HOUTHASTA
      ,[HALIMI] = @HALIMI
      ,[HALIMS] = @HALIMS
      ,[FECHAMOD] = @FECHAMOD
      ,[HORAMOD] = @HORAMOD
      ,[GRABO] = @GRABO
      ,[TIENEFERIADO] = @TIENEFERIADO
      ,[HSALIDA] = @HSALIDA
      ,[USUARIOMOD] = @USUARIOMOD
      ,[VISIBLE] = 'SI'
      ,[TIPO] = @TIPO
      ,[HINGRESON] = @HINGRESON
      ,[HINDESDEN] = @HINDESDEN
      ,[HINHASTAN] = @HINHASTAN
      ,[HSALIDAN] = @HSALIDAN
      ,[HOUTDESDEN] = @HOUTDESDEN
      ,[HOUTHASTAN] = @HOUTHASTAN
      ,[HALIMIN] = @HALIMIN
      ,[HALIMSN] = @HALIMSN
      ,[HSAL_ULIMODIA] = @HSAL_ULIMODIA
      ,[FVIGENCIA] = @FVIGENCIA
      ,[EMPIEZANOCHEA] = @EMPIEZANOCHEA
      ,[EMPIEZANOCHEB] = @EMPIEZANOCHEB
      ,[EMPIEZA] = @EMPIEZA
      ,[ID] = @ID
      ,[VALIDADO] = @VALIDADO
      ,[USRSUBE] = @USRSUBE
      ,[FECSUBE] = [dbo].[hoy](GETDATE())
      ,[HORASUBE] = [dbo].[ahora](GETDATE())      
      ,[CERTUSUARIO] = @CERTUSUARIO
      ,[CERTFECHA] = @CERTFECHA
      ,[CERTHORA] = @CERTHORA
      ,[OBS_RECHAZO] = @OBS_RECHAZO
      ,[HSAL_ULIMONOCHE] = @HSAL_ULIMONOCHE
 WHERE TURNO=@TURNO AND OST=@OST

END
