CREATE PROCEDURE [dbo].[V4MVC_PLANILLA_COTIZACION_SELECT_ONE_V3_CONTROLLABORAL_CTTA]
(
  @ID_DOC		INT
 ,@IDEMPRESA	NVARCHAR(10)
 ,@PERIODO		NVARCHAR(6)
 ,@DIVISION		NVARCHAR(4)
 ,@OST			NVARCHAR(20)
) AS
BEGIN
	SELECT
		 PERIODO,
		 EMPRESA,
		 MONTOIMP,
		 ID,
		 VALIDADO,
		 CANTFUNC,
		 OBSERVACION,
		 DIVISION,
		 OST,
		 COALESCE(
					(
						SELECT
							TOP 1
							E.ACRONIMO
						FROM ENTERPRISE E
						WHERE E.IDEMPRESA = @IDEMPRESA
					), ''
				) AS ACRO_EMPRESA,
		 [dbo].[V4MVC_FSTR_RUT](@IDEMPRESA) AS STRUT_EMPRESA,
		 COALESCE(
			(
				SELECT
					TOP 1
						DD.ID_DISPUTA
				FROM DOCS_DISPUTA_CLABORAL DD
				WHERE
					DD.EMPRESA = PLANILLA_COTIZACION.EMPRESA AND
					DD.PERIODO = PLANILLA_COTIZACION.PERIODO AND
					DD.ID_DOC = @ID_DOC AND
					DD.ID = PLANILLA_COTIZACION.ID
				ORDER BY DD.ID_DISPUTA DESC
			), -1
		 ) AS DISPUTA_ID,
		 IIF(EXISTS(
				SELECT * 
				FROM DOCS_DISPUTA_CLABORAL DD
				WHERE
					DD.EMPRESA = PLANILLA_COTIZACION.EMPRESA AND
					DD.PERIODO = PLANILLA_COTIZACION.PERIODO AND
					DD.ID_DOC = @ID_DOC AND
					DD.ID = PLANILLA_COTIZACION.ID
				ORDER BY DD.ID_DISPUTA DESC
				OFFSET 0 ROWS
		 ), 1 , 0) AS DISPUTA_EXISTE,
		 COALESCE(
			(
				SELECT
					TOP 1
					ARCHIVO
				FROM ARCHIVOS A
				WHERE A.ID = PLANILLA_COTIZACION.ID
			), NULL
		 ) AS ADJUNTO_CONTENIDO,
		 COALESCE(
			(
				SELECT
					TOP 1
					TIPOCONTENIDO
				FROM ARCHIVOS A
				WHERE A.ID = PLANILLA_COTIZACION.ID
			), NULL
		 ) AS ADJUNTO_TIPOCONTENIDO,
		 COALESCE(
			(
				SELECT
					TOP 1
					NOMBRE
				FROM ARCHIVOS A
				WHERE A.ID = PLANILLA_COTIZACION.ID
			), NULL
		 ) AS ADJUNTO_NOMBRE		 	
	FROM PLANILLA_COTIZACION
	WHERE
		EMPRESA = @IDEMPRESA AND
		PERIODO = @PERIODO AND
		DIVISION = @DIVISION AND
		OST = @OST
END
