CREATE PROCEDURE [dbo].[V4MVC_A036_CURSOPROG_SELECT_CHARLASYRESERVAS_INFORMEFUNCIONARIOS_CTTA]
(
  @RUT NVARCHAR(10)
) AS 
BEGIN

 SELECT DISTINCT COUNT(DISTINCT CR.RUT) AS PARTICIPANTES_REPORTE	,D.DIVISION			, D.DIVCOD			, CP.CODIGO																	
                 , CH.CHARLA										, CP.FECHA			,  CP.HORA			, CP.FINALIZADO		
				 , COUNT(CASE WHEN CR.NOTA>=CH.PORCENTAJE THEN 1 ELSE null END) AS CUENTASI_REPORTE    
				 , COUNT(CASE WHEN CR.NOTA<CH.PORCENTAJE  THEN 1 ELSE null END) AS CUENTANO_REPORTE 
 FROM A036_CURSORESERVA AS CR   INNER JOIN A036_CURSOPROG AS CP ON CR.CODIGO = CP.CODIGO   
                                INNER JOIN CHARLAS AS CH ON CP.CURSO = CH.IDCHARLA   
								INNER JOIN CHARLAS_DIVISION AS CHD ON CH.IDCHARLA = CHD.IDCHARLA   
								INNER JOIN A024_DIVISIONES AS D ON CHD.DIVISION = D.DIVCOD   
								INNER JOIN ENTERPRISE AS E ON CR.EMPRESA = E.IDEMPRESA 
 WHERE 1 = 1  AND CR.RUT = @RUT AND ASISTIO = 'SI' 
 GROUP BY D.DIVISION,D.DIVCOD, CP.CODIGO, CH.CHARLA, CP.FECHA, CP.HORA, CP.FINALIZADO  
 ORDER BY CP.FECHA, CP.HORA ASC 

END
