CREATE PROCEDURE [dbo].[V4MVC_DOCS_OST_PREVENCIONISTA_SELECT_ONE_CONTRATOST_CTTA]
(
  @NUM_SOLICITUD	INT
 ,@NROOST			NVARCHAR(14)
 ,@IDEMPRESA		NVARCHAR(10)
 ,@MADRE			NVARCHAR(10)
 ,@NIVEL			SMALLINT
 ,@SUBE_DOCUMENTO	INT OUTPUT
) AS
BEGIN
	
	SET @SUBE_DOCUMENTO = 1

	IF(COALESCE(
		(
			SELECT
				TOP 1 
				APORTE_ANGLO
			FROM DOCS_OST_PREVENCIONISTA
			WHERE
				ID = @NUM_SOLICITUD
		)
	  ,'') = 'SI')
		BEGIN
			SET @SUBE_DOCUMENTO = 0
		END

	IF(EXISTS(
			SELECT
				OS.FINICIO AS FECINICIO,
				OS.FTERMINO AS FECTERM,
				O.DESCRIPOST,
				O.DOTTRANS,
				O.DOTACION,
				O.VALIDADOR
			FROM OST O
			INNER JOIN OSTARBOL OS
				ON OS.OST = O.NROOST
			WHERE
				O.NROOST = @NROOST AND
				OS.EMPRESA = @IDEMPRESA AND
				OS.MADRE = @MADRE AND
				OS.NIVEL = @NIVEL)
	)
	BEGIN
		IF(@NUM_SOLICITUD = -1)
			BEGIN
				SET @SUBE_DOCUMENTO = 0
			END
	END

	SELECT
		SS.OST,
		SS.MADRE,
		SS.EMPRESA,
		SS.DOTACION,
		SS.APORTE_ANGLO,
		SS.MOTIVO,
		SS.RUT_PREVENCIONISTA,
		SS.USRSUBE,
		SS.FECHASUBE,
		SS.HORASUBE,
		SS.ID_ARCHIVO,
		SS.ESTADO,
		SS.OBSERVACION,
		SS.CERTUSUARIO,
		SS.CERTFECHA,
		SS.CERTHORA,
		SS.NOMBRES,
		SS.APELLIDOS,
		SS.FONO,
		SS.EMAIL,
		SS.APORTE_ANGLO,
		COALESCE(
			(
			SELECT
				CONCAT(W.NOMBRES, ' ', W.APELLIDOS)
			FROM WORKERS W
			WHERE W.RUT = SS.CERTUSUARIO
			), ''
		) AS CERT_FNOMBRES
	FROM
	(
		SELECT
			TOP 1
				DOP.OST,
				DOP.MADRE,
				DOP.EMPRESA,
				DOP.DOTACION,
				DOP.APORTE_ANGLO,
				ISNULL(DOP.MOTIVO, '') AS MOTIVO,
				ISNULL(DOP.RUT_PREVENCIONISTA, '') AS RUT_PREVENCIONISTA,
				DOP.USRSUBE,
				DOP.FECHASUBE,
				DOP.HORASUBE,
				DOP.ID_ARCHIVO,
				DOP.ESTADO,
				DOP.OBSERVACION,
				ISNULL(DOP.CERTUSUARIO, '') AS CERTUSUARIO,
				ISNULL(DOP.CERTFECHA, '') AS CERTFECHA,
				ISNULL(DOP.CERTHORA, '') AS CERTHORA,
				COALESCE(
					(
					SELECT
						TOP 1
							W.NOMBRES
						FROM WORKERS W
						LEFT JOIN DIRECCION D
							ON W.RUT = D.RUT
						WHERE W.RUT = DOP.RUT_PREVENCIONISTA
					), ''
				) AS NOMBRES,
				COALESCE(
					(
					SELECT
						TOP 1
							W.APELLIDOS
						FROM WORKERS W
						LEFT JOIN DIRECCION D
							ON W.RUT = D.RUT
						WHERE W.RUT = DOP.RUT_PREVENCIONISTA
					), ''
				) AS APELLIDOS,
				COALESCE(
					(
					SELECT
						TOP 1
							D.FONO
						FROM WORKERS W
						LEFT JOIN DIRECCION D
							ON W.RUT = D.RUT
						WHERE W.RUT = DOP.RUT_PREVENCIONISTA
					), ''
				) AS FONO,
				COALESCE(
					(
					SELECT
						TOP 1
							D.EMAIL
						FROM WORKERS W
						LEFT JOIN DIRECCION D
							ON W.RUT = D.RUT
						WHERE W.RUT = DOP.RUT_PREVENCIONISTA
					), ''
				) AS EMAIL
		FROM DOCS_OST_PREVENCIONISTA DOP
		WHERE DOP.ID = @NUM_SOLICITUD
	) SS

END

