CREATE PROCEDURE [dbo].[V4MVC_ENTERPRISE_SELECT_PASES_CTTA]  
(
  @IDEMPRESA    NVARCHAR(11)
 ,@OST			NVARCHAR(14)
) AS  
BEGIN  

	DECLARE @NIVEL SMALLINT = 1

	SELECT
		@NIVEL = OSC.NIVEL
	FROM OSTSUBC OSC
	WHERE
		(REPLACE(OSC.OST,' ','') = @OST) AND
		(OSC.EMPRESA = @IDEMPRESA)
	ORDER BY OSC.NIVEL ASC

	SELECT
		SS.IDEMPRESA,
		SS.ACRONIMO,
		SS.NIVEL,
		CONCAT(SS.ESPACIADO, SS.ACRONIMO) AS EOPCION
	FROM
	(
		SELECT
			DISTINCT
				O.EMPRESA AS IDEMPRESA,
				LTRIM(RTRIM(E.ACRONIMO)) AS ACRONIMO,
				CASE WHEN O.NIVEL > @NIVEL THEN (
										  CASE WHEN O.NIVEL > (@NIVEL + 1) THEN '      '
										  ELSE '   ' END 
										 )
				ELSE '' END AS ESPACIADO,
				O.NIVEL
		FROM OSTSUBC AS O, ENTERPRISE AS E
		WHERE
			REPLACE(O.OST,' ','') = @OST AND
			(O.EMPRESA = E.IDEMPRESA) AND
			(O.NIVEL > @NIVEL) AND 
			(O.FTERMINO >= dbo.HOY(GETDATE()))
		UNION
		SELECT
			DISTINCT
				O.EMPRESA AS IDEMPRESA,
				LTRIM(RTRIM(E.ACRONIMO)) AS ACRONIMO,
				CASE WHEN O.NIVEL > @NIVEL THEN (
										  CASE WHEN O.NIVEL > (@NIVEL + 1) THEN '      '
										  ELSE '   ' END 
										 )
				ELSE '' END AS ESPACIADO,
				O.NIVEL
		FROM OSTSUBC AS O, ENTERPRISE AS E
		WHERE
			REPLACE(O.OST,' ','') = @OST AND
			(O.EMPRESA = E.IDEMPRESA) AND
			(O.EMPRESA = @IDEMPRESA) AND
			(O.FTERMINO >= dbo.HOY(GETDATE()))
		ORDER BY 3, 2 OFFSET 0 ROWS	
	) SS
END  
  
