CREATE PROCEDURE [dbo].[V4MVC_WORKERSLOCAL_SELECT_BY_RUT_CTTA]
(
 @RUT		NVARCHAR(10) = NULL
,@DIVISION	NVARCHAR(MAX)  = NULL
)
AS
BEGIN

		IF(ISNULL(@DIVISION,'') = '')
		BEGIN
			SELECT TOP 1 EMPRESA 
			FROM WORKERSLOCAL 
			WHERE (dbo.hoy(GETDATE()) BETWEEN FINIPASE AND FFINPASE) 
			AND (AUTOR IN ('SI','NO')) 
			AND (RUT = @RUT)
		END
		ELSE
		BEGIN
			SELECT TOP 1 EMPRESA 
			FROM WORKERSLOCAL 
			WHERE (dbo.hoy(GETDATE()) BETWEEN FINIPASE AND FFINPASE) 
			AND (AUTOR IN ('SI','NO')) 
			AND (RUT = @RUT)
			AND DIVISION IN (SELECT VALUE FROM STRING_SPLIT(@DIVISION,','))
		END

END
