CREATE PROCEDURE [dbo].[V4MVC_CERT_TASAS_DELETE_CONTROLLABORAL_CTTA]
(
  @IDEMPRESA		NVARCHAR(10)
 ,@PERIODO			NVARCHAR(6)
 ,@USUARIO			NVARCHAR(10)
 ,@DISPUTA_ID		INT
 ,@DISPUTA_EXISTE	INT OUTPUT
 ,@DISPUTA_EMPRESA	NVARCHAR(12) OUTPUT
 ,@DISPUTA_FECHA	NVARCHAR(8) OUTPUT
) AS
BEGIN
	DECLARE @CURR_FECHA NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 112) /* yyyymmdd */
	DECLARE @CURR_TIEMPOFULL NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 108) /* hh:mm:ss */

	DECLARE @CT_EXISTS BIT = 0
	DECLARE @CT_EMPRESA NVARCHAR(10)
	DECLARE @CT_PERIODO NVARCHAR(6)

	DECLARE @CT_FOLIO BIGINT
	DECLARE @CT_NRO_ACCIDENTES INT
	DECLARE @CT_DIAS_ACCIDENTES INT
	DECLARE @CT_DIAS_ENFERMEDAD INT
	DECLARE @CT_NRO_ENFERMEDAD INT
	DECLARE @CT_DIAS_INCAPACIDAD INT
	DECLARE @CT_DIAS_FATALES INT 
	DECLARE @CT_TOTAL_PERDIDOS INT
	
	DECLARE @CT_VALIDADO NVARCHAR(2)
	DECLARE @CT_ID UNIQUEIDENTIFIER
	DECLARE @CT_OBSERVACION NVARCHAR(500)
	DECLARE @CT_USUARIO NVARCHAR(10)
	DECLARE @CT_FECHASUBE NVARCHAR(8)
	DECLARE @CT_HORASUBE NVARCHAR(8)
	DECLARE @CT_CERTUSUARIO NVARCHAR(10)
	DECLARE @CT_CERTFECHA NVARCHAR(8)
	DECLARE @CT_CERTHORA NVARCHAR(8)

	
	DECLARE @DSP_ID_DISPUTA INT
	DECLARE @DSP_ID_DOC INT
	DECLARE @DSP_ID UNIQUEIDENTIFIER
	DECLARE @DSP_USUARIO NVARCHAR(10)
	DECLARE @DSP_HORA NVARCHAR(8)
	DECLARE @DSP_OBSERVACION NVARCHAR(1000)
	DECLARE @DSP_CERTUSUARIO NVARCHAR(10)
	DECLARE @DSP_CERTFECHA NVARCHAR(8)
	DECLARE @DSP_CERTHORA NVARCHAR(8)
	DECLARE @DSP_ESTADO	NVARCHAR(2)
	DECLARE @DSP_REVALUSUARIO NVARCHAR(10)
	DECLARE @DSP_REVALFECHA	NVARCHAR(8)
	DECLARE @DSP_REVALHORA	NVARCHAR(8)
	DECLARE @DSP_OBSERVACION_REVAL	NVARCHAR(1000)
	DECLARE @DSP_VALIDADO NVARCHAR(2)
	DECLARE @DSP_PERIODO NVARCHAR(6)
	DECLARE @DSP_ID_CERTIFICADO INT

	SET @DISPUTA_EXISTE = 0
	SET @DISPUTA_EMPRESA = ''
	SET @DISPUTA_FECHA = ''

	SELECT
		TOP 1
		@CT_EXISTS = 1,
		@CT_EMPRESA = EMPRESA,
		@CT_PERIODO = PERIODO,

		@CT_FOLIO = FOLIO,
		@CT_NRO_ACCIDENTES = NRO_ACCIDENTES,
		@CT_DIAS_ACCIDENTES = DIAS_ACCIDENTES,
		@CT_DIAS_ENFERMEDAD = DIAS_ENFERMEDAD,
		@CT_NRO_ENFERMEDAD = NRO_ENFERMEDAD,
		@CT_DIAS_INCAPACIDAD = DIAS_INCAPACIDAD,
		@CT_DIAS_FATALES = DIAS_FATALES,
		@CT_TOTAL_PERDIDOS = TOTAL_PERDIDOS,

		@CT_VALIDADO = VALIDADO,
		@CT_ID = ID,
		@CT_OBSERVACION = OBSERVACION,
		@CT_USUARIO = USUARIO,
		@CT_FECHASUBE = FECHASUBE,
		@CT_HORASUBE = HORASUBE,
		@CT_CERTUSUARIO = CERTUSUARIO,
		@CT_CERTFECHA = CERTFECHA,
		@CT_CERTHORA = CERTHORA
	FROM CERT_TASAS
	WHERE
		EMPRESA = @IDEMPRESA AND
		PERIODO = @PERIODO

	IF(@CT_EXISTS = 1)
		BEGIN
			INSERT INTO CERT_TASAS_LOG
						(
							PERIODO,
							EMPRESA,
							FOLIO,
							NRO_ACCIDENTES,
							DIAS_ACCIDENTES,
							DIAS_ENFERMEDAD,
							NRO_ENFERMEDAD,
							DIAS_INCAPACIDAD,
							DIAS_FATALES,
							TOTAL_PERDIDOS,
							VALIDADO,
							ID,
							OBSERVACION,
							USUARIO,
							FECHASUBE,
							HORASUBE,
							CERTUSUARIO,
							CERTFECHA,
							CERTHORA,
							USUARIODEL,
							FECHADEL,
							HORADEL
						)
			VALUES
						(
							@CT_PERIODO,
							@CT_EMPRESA,
							@CT_FOLIO,
							@CT_NRO_ACCIDENTES,
							@CT_DIAS_ACCIDENTES,
							@CT_DIAS_ENFERMEDAD,
							@CT_NRO_ENFERMEDAD,
							@CT_DIAS_INCAPACIDAD,
							@CT_DIAS_FATALES,
							@CT_TOTAL_PERDIDOS,
							@CT_VALIDADO, 
							@CT_ID,
							@CT_OBSERVACION,
							@CT_USUARIO,
							@CT_FECHASUBE,
							@CT_HORASUBE,
							@CT_CERTUSUARIO,
							@CT_CERTFECHA,
							@CT_CERTHORA, 
							@USUARIO,
							@CURR_FECHA,
							@CURR_TIEMPOFULL
						)

			/*--------------------------*/

			
			SELECT
				TOP 1
				@DISPUTA_EXISTE = 1,
				@DSP_ID_DISPUTA = ID_DISPUTA,
				@DISPUTA_EMPRESA = EMPRESA,
				@DSP_ID_DOC = ID_DOC,
				@DSP_ID = ID,
				@DSP_USUARIO = USUARIO,
				@DISPUTA_FECHA = FECHA,
				@DSP_HORA = HORA,
				@DSP_OBSERVACION = OBSERVACION,
				@DSP_CERTUSUARIO = CERTUSUARIO,
				@DSP_CERTFECHA = CERTFECHA,
				@DSP_CERTHORA = CERTHORA,
				@DSP_ESTADO = ESTADO,
				@DSP_REVALUSUARIO = REVALUSUARIO,
				@DSP_REVALFECHA = REVALFECHA,
				@DSP_REVALHORA = REVALHORA,
				@DSP_OBSERVACION_REVAL = OBSERVACION_REVAL,
				@DSP_VALIDADO = VALIDADO,
				@DSP_PERIODO = PERIODO,
				@DSP_ID_CERTIFICADO = ID_CERTIFICADO
			FROM DOCS_DISPUTA_CLABORAL
			WHERE
				ID_DISPUTA = @DISPUTA_ID AND
				ESTADO = 'NO'

			IF(@DISPUTA_EXISTE = 1)
				BEGIN
					INSERT INTO DOCS_DISPUTA_CLABORAL_LOG
							(
								ID_DISPUTA,
								EMPRESA,
								ID_DOC,
								ID,
								USUARIO,
								FECHA,
								HORA,
								OBSERVACION,
								CERTUSUARIO,
								CERTFECHA,
								CERTHORA,
								ESTADO,
								REVALUSUARIO,
								REVALFECHA,
								REVALHORA,
								OBSERVACION_REVAL,
								VALIDADO,
								PERIODO,
								ID_CERTIFICADO,
								USRMOD,
								FECHAMOD,
								HORAMOD,
								ACCION
							)
					VALUES (
								@DSP_ID_DISPUTA,
								@DISPUTA_EMPRESA,
								@DSP_ID_DOC,
								@DSP_ID,
								@DSP_USUARIO,
								@DISPUTA_FECHA,
								@DSP_HORA,
								@DSP_OBSERVACION,
								@DSP_CERTUSUARIO,
								@DSP_CERTFECHA,
								@DSP_CERTHORA,
								@DSP_ESTADO,
								@DSP_REVALUSUARIO,
								@DSP_REVALFECHA,
								@DSP_REVALHORA,
								@DSP_OBSERVACION_REVAL,
								@DSP_VALIDADO,
								@DSP_PERIODO,
								@DSP_ID_CERTIFICADO,
								@USUARIO,
								@CURR_FECHA,
								@CURR_TIEMPOFULL,
								'ELIMINADO'
							)

					DELETE DOCS_DISPUTA_CLABORAL WHERE ID_DISPUTA = @DISPUTA_ID AND ESTADO = 'NO'
				END

			DELETE FROM CERT_TASAS WHERE PERIODO = @PERIODO AND EMPRESA = @IDEMPRESA

		END
END
