CREATE PROCEDURE [dbo].[V4MVC_A056_FORM301_SELECT_ONE_V4_CONTROLLABORAL_CTTA]
(
  @ID_DOC		INT
 ,@IDEMPRESA	NVARCHAR(10)
 ,@ID_CERTIFICADO INT
) AS
BEGIN
	SELECT
		REGION,
		INSPECCION,
		ANIO,
		CLAVE,
		CERTIFICADO,
		PERIODO_INI,
		PERIODO_FIN,
		TRA_DECL,
		TRA_DESV,
		TRA_VIGE,
		COT_PAG,
		COT_NPAG,
		ADJ_NOM,
		IND_AP_P,
		IND_AP_MTO,
		IND_AP_NP,
		IND_AS_P,
		IND_AS_MTO,
		IND_AS_NP,
		ID,
		PERIODO,
		OBSERVACION,
		OST,
		DIVISION,
		VALIDADO,
		ID_CERTIFICADO,
		COALESCE(
			(
				SELECT
					TOP 1
						O.DESCRIPOST
				FROM OST O
				WHERE O.NROOST = A056_FORM301.OST
			), ''
		) AS GLOSA,
		COALESCE(
				(
					SELECT
						TOP 1
						E.ACRONIMO
					FROM ENTERPRISE E
					WHERE E.IDEMPRESA = @IDEMPRESA
				), ''
			) AS ACRO_EMPRESA,
		[dbo].[V4MVC_FSTR_RUT](@IDEMPRESA) AS STRUT_EMPRESA,
		COALESCE(
			(
				SELECT
					TOP 1
						DD.ID_DISPUTA
				FROM DOCS_DISPUTA_CLABORAL DD
				WHERE
					DD.EMPRESA = A056_FORM301.EMPRESA AND
					DD.PERIODO = A056_FORM301.PERIODO AND
					DD.ID_DOC = @ID_DOC AND
					DD.ID = A056_FORM301.ID
				ORDER BY DD.ID_DISPUTA DESC
			), -1
		) AS DISPUTA_ID,
		IIF(EXISTS(
			SELECT * 
			FROM DOCS_DISPUTA_CLABORAL DD
			WHERE
				DD.EMPRESA = A056_FORM301.EMPRESA AND
				DD.PERIODO = A056_FORM301.PERIODO AND
				DD.ID_DOC = @ID_DOC AND
				DD.ID = A056_FORM301.ID
			ORDER BY DD.ID_DISPUTA DESC
			OFFSET 0 ROWS
		), 1 , 0) AS DISPUTA_EXISTE,
			COALESCE(
			(
				SELECT
					TOP 1
					D.NOMBRE
				FROM DOCS D
				WHERE D.ID_DOC = @ID_DOC
			),''
		) AS NOM_DOC,
		 COALESCE(
			(
				SELECT
					TOP 1
					ARCHIVO
				FROM ARCHIVOS A
				WHERE A.ID = A056_FORM301.ID
			), NULL
		 ) AS ADJUNTO_CONTENIDO,
		 COALESCE(
			(
				SELECT
					TOP 1
					TIPOCONTENIDO
				FROM ARCHIVOS A
				WHERE A.ID = A056_FORM301.ID
			), NULL
		 ) AS ADJUNTO_TIPOCONTENIDO,
		 COALESCE(
			(
				SELECT
					TOP 1
					NOMBRE
				FROM ARCHIVOS A
				WHERE A.ID = A056_FORM301.ID
			), NULL
		 ) AS ADJUNTO_NOMBRE
	FROM A056_FORM301
	WHERE
		ID_CERTIFICADO = @ID_CERTIFICADO
END
