CREATE PROCEDURE [dbo].[V4MVC_DIVISIONES_FICHA_EMPRESA_SELECT]  
(  
@IDEMPRESA NVARCHAR(10)  
)  
AS  
BEGIN  
  
DECLARE @MAXIMO INT  
DECLARE @CONTADOR INT  
DECLARE @DATO NVARCHAR(4)
DECLARE @DATO1 NVARCHAR(20)
DECLARE @DIVCOD NVARCHAR(4)  
DECLARE @FUNCIONARIOS INT  
DECLARE @ACREDITADOS INT  
DECLARE @VEHICULOS INT  
DECLARE @CONTRATOS INT  
  
	CREATE TABLE #TEMP_FICHA_EMPRESA  
	(  
	DIVISION		NVARCHAR(20)	COLLATE DATABASE_DEFAULT NOT NULL, 
	DIVCOD			NVARCHAR(4)		COLLATE DATABASE_DEFAULT NOT NULL,  
	FUNCIONARIOS	INT,  
	ACREDITADOS		INT,  
	VEHICULOS		INT,  
	CONTRATOS		INT  
	)  
    
	SELECT DIVISION,DIVCOD INTO #TEMP_FICHA  
	FROM A024_DIVISIONES  
	WHERE ACTIVO='SI'  
	ORDER BY DIVCOD  
  
	SELECT  ROW_NUMBER() OVER(ORDER BY DIVCOD ASC) AS ID , * INTO #TEMP_FICHA_DIVCOD FROM                  
	#TEMP_FICHA   
  
	SET @CONTADOR = 1;  
  
	SELECT @MAXIMO = MAX(ID) FROM #TEMP_FICHA_DIVCOD  
  
	WHILE(@CONTADOR <= @MAXIMO)  
	BEGIN  
  
	SELECT @DATO=DIVCOD, @DATO1=DIVISION FROM #TEMP_FICHA_DIVCOD  
	WHERE ID = @CONTADOR  
  
	SET @FUNCIONARIOS = (SELECT COUNT (DISTINCT RUT) FROM VW_WL_NOMINA WHERE     EMPRESA = @IDEMPRESA AND DIVISION =  @DATO)  
	SET @ACREDITADOS  = (SELECT COUNT (DISTINCT RUT) FROM VW_WL_ACREDITADO WHERE EMPRESA = @IDEMPRESA AND DIVISION =  @DATO)  
	SET @VEHICULOS    = (SELECT COUNT (PATENTE)      FROM TRANSPORT WHERE        EMPRESA = @IDEMPRESA AND AUTOR    <> 'BL')  
	SET @CONTRATOS    = (SELECT COUNT(DISTINCT OSTARBOL.OST)  
		  FROM OSTARBOL   
		  INNER JOIN  OSTDIVLOCAL ON OSTARBOL.OST = OSTDIVLOCAL.OST   
		  WHERE  (OSTARBOL.EMPRESA = @IDEMPRESA)   
		  AND (OSTDIVLOCAL.DIVISION = @DATO)   
		  AND (dbo.hoy(getdate()) BETWEEN OSTARBOL.FINICIO   
		  AND OSTARBOL.FTERMINO))  
  
	INSERT INTO #TEMP_FICHA_EMPRESA VALUES (@DATO1,@DATO,@FUNCIONARIOS,@ACREDITADOS,@VEHICULOS,@CONTRATOS)  
  
	SET @CONTADOR = @CONTADOR + 1  
  
	END  
  
	SELECT * FROM #TEMP_FICHA_EMPRESA  
  
END
