CREATE PROCEDURE [dbo].[V4MVC_GET_MOTIVO_ULTIMO]
(
@MOTIVO			NVARCHAR(20) = ''
,@RUT			NVARCHAR(10) = ''
,@IDEMPRESA		NVARCHAR(11) = ''
,@DIVCOD		NVARCHAR(4) = ''
,@ID_DOC		INT = NULL
,@ULTIMO		INT OUTPUT
)
AS
BEGIN
	IF(@DIVCOD IS NULL OR @DIVCOD = '')
		BEGIN
			IF EXISTS(
					SELECT MOTIVO
					FROM WORKERS_MOTIVOFINIQUITO WMF
					INNER JOIN (
						SELECT TOP 1 RUT, EMPRESA, ID FROM DOCS_WORKERS DW
						WHERE DW.RUT = @RUT AND DW.EMPRESA = @IDEMPRESA AND DW.ID_DOC = @ID_DOC
						ORDER BY ID_DOCS_WORKERS DESC
					) DW2
					ON WMF.RUT = DW2.RUT AND WMF.EMPRESA = DW2.EMPRESA AND WMF.IDARCHIVO = DW2.ID
					WHERE MOTIVO = @MOTIVO
				)
				BEGIN
					SET @ULTIMO = 1
				END
			ELSE
				BEGIN
					SET @ULTIMO = 0
				END
		END
	ELSE
		BEGIN
			IF EXISTS(
					SELECT MOTIVO
					FROM WORKERS_MOTIVOFINIQUITO WMF
					INNER JOIN (
						SELECT TOP 1 RUT, EMPRESA, ID FROM DOCS_WORKERS DW
						WHERE DW.RUT = @RUT AND DW.EMPRESA = @IDEMPRESA AND DW.ID_DOC = @ID_DOC AND DW.DIVISION = @DIVCOD
						ORDER BY ID_DOCS_WORKERS DESC
					) DW2
					ON WMF.RUT = DW2.RUT AND WMF.EMPRESA = DW2.EMPRESA AND WMF.IDARCHIVO = DW2.ID
					WHERE MOTIVO = @MOTIVO
				)
				BEGIN
					SET @ULTIMO = 1
				END
			ELSE
				BEGIN
					SET @ULTIMO = 0
				END
		END

END
