CREATE PROCEDURE [dbo].[V4MVC_LOTEPASES_UPDATE_PASES_CTTA]
(
  @LOTENUM					INT /*ID_PASE*/
 ,@IDEMPRESA				NVARCHAR(10)
 ,@EMAIL_AUT				NVARCHAR(50)
 ,@RUT_AUT					NVARCHAR(10)
 ,@ACTIVADO_DELEGADOS_OST	INT
 ,@RET_OK					INT OUTPUT
 ,@JSON_RET					NVARCHAR(MAX) OUTPUT
) AS
BEGIN
	DECLARE @LOTEFECHA NVARCHAR(8) = ''
	DECLARE @LOTEFINICIO NVARCHAR(8) = ''
	DECLARE @LOTEFFINAL NVARCHAR(8) = ''
	DECLARE @LOTEGLOSA NVARCHAR(50) = ''
	DECLARE @LOTEEMAIL NVARCHAR(50) = ''
	DECLARE @DIVISION NVARCHAR(2) = ''
	DECLARE @ENOMBRES NVARCHAR(50) = ''
	DECLARE @EAPELLIDOS NVARCHAR(50) = ''
	DECLARE @EFULL_NOMBRES NVARCHAR(100) = ''
	DECLARE @EMP_RUT_FRMT	NVARCHAR(20) = ''
	DECLARE @ADMEMAIL NVARCHAR(50) = ''
	DECLARE @OTHER_EMAILS NVARCHAR(MAX) = ''
	DECLARE @QUERY_EXISTS BIT = 0
	DECLARE @get_admin CURSOR
	DECLARE @SEP NVARCHAR(2) = ''
	DECLARE @EMP_NOMBRE NVARCHAR(50) = ''
	DECLARE @EMP_ACRONIMO NVARCHAR(50) = ''
	DECLARE @FEC_USER NVARCHAR(20) = ''
	DECLARE @EMAIL NVARCHAR(50) = ''

	SET @RET_OK = 0
	SET @JSON_RET = ''

	SELECT
		@QUERY_EXISTS = 1,
		@LOTEFECHA = LOTEFECHA,
		@LOTEFINICIO = LOTEFINICIO,
		@LOTEFFINAL = LOTEFFINAL,
		@LOTEGLOSA = LOTEGLOSA,
		@LOTEEMAIL = LOTEEMAIL,
		@DIVISION = DIVISION
	FROM LOTEPASES
	WHERE
		(LOTENUM =  @LOTENUM) AND
		(LOTEEMPRESA = @IDEMPRESA)
	IF(@QUERY_EXISTS = 1)
		BEGIN
			UPDATE LOTEPASES
			SET
				LOTEEMAIL = @LOTEEMAIL,
				LOTEESTADO = 'PE'
			WHERE LOTENUM = @LOTENUM

			SET @QUERY_EXISTS = 0

			SELECT
				@QUERY_EXISTS = 1,
				@ENOMBRES = W.NOMBRES,
				@EAPELLIDOS = W.APELLIDOS
			FROM WORKERS AS W,
				 ADMIN AS A
			WHERE
				(A.ADMEMAIL = @EMAIL_AUT) AND
				(A.ADMRUT = @RUT_AUT) AND
				W.RUT = A.ADMRUT

			IF(@QUERY_EXISTS = 1)
				BEGIN
					SET @EFULL_NOMBRES = CONCAT(@ENOMBRES, ' ', @EAPELLIDOS)
				END

			IF(@DIVISION = 'QV')
				BEGIN
					SET @EMAIL = 'opaquellaveco@angloamerican.com'
				END
			ELSE
				BEGIN
					SET @EMAIL = @LOTEEMAIL
				END

			SELECT
				@EMP_NOMBRE = E.NOMBRE,
				@EMP_ACRONIMO = E.ACRONIMO
			FROM ENTERPRISE E
			WHERE E.IDEMPRESA = @IDEMPRESA
			
			EXEC @EMP_RUT_FRMT = [dbo].[V4MVC_FSTR_RUT] @RAW_RUT = @IDEMPRESA
			

			IF(@ACTIVADO_DELEGADOS_OST = 1)
				BEGIN
					SET @get_admin = CURSOR FOR
					SELECT
						DISTINCT A.ADMEMAIL
					FROM OSTADMIN OA, ADMIN A, LOTEPASESFUN LPF
					WHERE
						OA.NROOST = LPF.OSTLT AND
						OA.ADMDELEG = A.ADMRUT AND
						LPF.NLOTEPROC = @LOTENUM AND
						OA.DIVISION = @DIVISION

					OPEN @get_admin
					FETCH NEXT
					FROM @get_admin INTO @ADMEMAIL

					SET @SEP = ''

					WHILE @@FETCH_STATUS = 0
						BEGIN
							SET @OTHER_EMAILS = CONCAT(@OTHER_EMAILS, @SEP, '''', @ADMEMAIL,  '''')
							FETCH NEXT
							FROM @get_admin INTO @ADMEMAIL

							SET @SEP = ','
						END
			
					CLOSE @get_admin
					DEALLOCATE @get_admin

					SET @OTHER_EMAILS = CONCAT('[', @OTHER_EMAILS, ']')

				END
			ELSE
				BEGIN
					SET @OTHER_EMAILS = '[]'
				END

			SET @RET_OK = 1

			SET @JSON_RET = '{'
			SET @JSON_RET = CONCAT(@JSON_RET, '''BODY_FULLNOM_AUT'':', '''', @EFULL_NOMBRES, '''')
			SET @JSON_RET = CONCAT(@JSON_RET, ',''BODY_NRO_PASE'':', CONVERT(NVARCHAR(20), @LOTENUM))
			SET @JSON_RET = CONCAT(@JSON_RET, ',''BODY_EMP_RUT_FRMT'':', '''', @EMP_RUT_FRMT, '''')
			SET @JSON_RET = CONCAT(@JSON_RET, ',''BODY_EMP_NOM'':', '''', @EMP_NOMBRE, '''')
			SET @JSON_RET = CONCAT(@JSON_RET, ',''BODY_EMP_ACRONIMO'':', '''', @EMP_ACRONIMO, '''')
			SET @JSON_RET = CONCAT(@JSON_RET, ',''BODY_LOTEEMAIL'':', '''', @LOTEEMAIL, '''')

			SET @JSON_RET = CONCAT(@JSON_RET, ',''FIRSTEMAIL_MAIL'':', '''', @EMAIL, '''')
			SET @JSON_RET = CONCAT(@JSON_RET, ',''NRO_PASE'':', CONVERT(NVARCHAR(20), @LOTENUM))
			SET @JSON_RET = CONCAT(@JSON_RET, ',''LOTEEMAIL'':', '''', @EMAIL, '''')
			SET @JSON_RET = CONCAT(@JSON_RET, ',''DELEGADOS_MAILS'':', @OTHER_EMAILS)

			SET @JSON_RET = CONCAT(@JSON_RET, '}')
		END
END
