CREATE PROCEDURE [dbo].[V4MVC_REMUNERACIONES_PROPIO_SELECT_ONE_V2_CONTROLLABORAL_CTTA]
(
  @IDEMPRESA	NVARCHAR(10)
 ,@PERIODO		NVARCHAR(6)
 ,@DIVISION		NVARCHAR(4)
 ,@OST			NVARCHAR(20)
) AS
BEGIN
	SELECT
		CERTUSUARIO,
		CERTFECHA,
		CERTHORA,
		VALIDADO,
		EMPRESA,
		PERIODO,
		DIVISION,
		OST
	FROM REMUNERACIONES_PROPIO
	WHERE
		EMPRESA = @IDEMPRESA AND
		PERIODO = @PERIODO AND
		DIVISION = @DIVISION AND
		OST = @OST
END
