CREATE PROCEDURE [dbo].[V4MVC_DOCS_FEC_SELECT_FUNCIONARIOS_CTTA]
(
  @RUT			NVARCHAR(8) = ''
 ,@DIVCOD		NVARCHAR(4) = ''
 ,@IDEMPRESA	NVARCHAR(11) = ''
)
AS
BEGIN
	DECLARE @ID_DOC INT = 18 /*FINIQUITO*/
	
	SELECT
		DF.*,
		[dbo].[V4MVC_FGET_FECHA_WORKER_LOCAL](DF.ID_DOC_FEC, @RUT, @DIVCOD, @IDEMPRESA, 1) AS FEC_WLOCAL
	FROM DOCS_FEC AS DF
	WHERE
		(DF.ID_DOC_DEPEND = @ID_DOC) AND 
		(DF.ACTIVO = 'SI') 
	--ORDER BY ORDEN
END
