CREATE PROCEDURE [dbo].[V4MVC_ENTERPRISE_INSERT_NEWENTERPRISECTTA]
(
 @IDEMPRESA NVARCHAR(10)
,@CLAVE NVARCHAR(10)
,@ACRONIMO NVARCHAR(50)
,@NOMBRE NVARCHAR(50)
,@DIRECCCION NVARCHAR(50)
,@PAIS NVARCHAR(50)
,@REGION NVARCHAR(5)
,@CIUDAD NVARCHAR(50)
,@TELEFONO NVARCHAR(50)
,@NRELEGAL NVARCHAR(50)
,@EMAIL NVARCHAR(150)
,@ADMINRUT NVARCHAR(10)
,@ADMINNOM NVARCHAR(50)
,@ADMINEMAIL NVARCHAR(150)
)
AS
BEGIN

	INSERT INTO [ENTERPRISE]
	(
		 IDEMPRESA		,CLAVE			,ACRONIMO		,NOMBRE
		,DIRECCCION		,PAIS			,REGION			,CIUDAD
		,TELEFONO		,NRELEGAL		,EMAIL			,ADMINRUT
		,ADMINNOM		,ADMINEMAIL
	)
	VALUES
	(
		@IDEMPRESA		,@CLAVE			,@ACRONIMO		,@NOMBRE
		,@DIRECCCION	,@PAIS			,@REGION		,@CIUDAD
		,@TELEFONO		,@NRELEGAL		,@EMAIL			,@ADMINRUT
		,@ADMINNOM		,@ADMINEMAIL
	)
END
