CREATE PROCEDURE [dbo].[V4MVC_DIRECCION_SELECT]  
(@RUT NVARCHAR(10) = NULL)  
AS  
BEGIN  
   SELECT WORKERS.NOMBRES  
  , WORKERS.APELLIDOS  
  , D.DIRECCION  
  , D.ZONA  
  , D.COMUNA  
  , D.CIUDAD  
  , D.REGION  
  , D.PAIS  
  , D.FONOHELP  
  , D.FONO  
  , D.CELULAR  
  , D.EMAIL  
  , WORKERS.RUT   
  , D.TIPO  
  , D.NOMCONTACTO  
  , D.CELCONTACTO  
 FROM  DIRECCION AS D  
 LEFT JOIN WORKERS ON WORKERS.RUT = D.RUT    
 WHERE (WORKERS.RUT = @RUT)  
END  
  
