CREATE PROCEDURE [dbo].[V4MVC_COLAB_WC_SUBMENU_SELECT_MENU]
( @TIPOUSUARIO	nvarchar(10) = NULL) AS
BEGIN
	
	IF(@TIPOUSUARIO = 'ADMIN')
		BEGIN
			SELECT CODMENU,DESCMENU,CODSUBMENU,LINK,LinkV4,ICONO,DESCRIPCION,ACTIVO,PERMISO,TIPOUSUARIO FROM A000_ECPANEL 
			WHERE  (PERMISO IN ('ADMIN','IDENT','TODOS') AND Activo = 'SI') 
			AND  (TIPOUSUARIO= @TIPOUSUARIO) 
			AND LinkV4 IS NOT NULL
			ORDER BY 7
		END
	ELSE
		BEGIN
			SELECT CODMENU,DESCMENU,CODSUBMENU,LINK,LinkV4,ICONO,DESCRIPCION,ACTIVO,PERMISO,TIPOUSUARIO FROM A000_ECPANEL 
			WHERE  (PERMISO IN ('IDENT','TODOS') AND Activo = 'SI') 
			AND  (TIPOUSUARIO= @TIPOUSUARIO) 
			AND LinkV4 IS NOT NULL
			ORDER BY 7
		END 

END
