CREATE PROCEDURE [dbo].[V4MVC_VIDEOS_SELECT_VIDEOS_MDTE]
AS
BEGIN
	SELECT
		V.ID AS ID,
		M.MODULO AS MODULO,
		V.VERSION AS VERSION,
		V.DESCRIPCION AS DESCRIPCION,
		V.ACTIVO AS ACTIVO
	FROM VIDEOS V
	LEFT JOIN LINKS_VIDEOS_V4 L
		ON V.ID = CONVERT(NUMERIC(18,0), L.ID_VIDEO)
	LEFT JOIN MODULOS_VIDEOS_V4 M
		ON V.MODULO_V4 = M.ID
END
