CREATE PROCEDURE [dbo].[V4MVC_CASINO_SELECT_CONSUMO_CASINO_MESACTUAL_INFORMEFUNCIONARIOS_CTTA]
(
  @RUT NVARCHAR(10)
) AS 
BEGIN

SELECT DISTINCT   C.SERVICIO			, C.LOCAL						, C.RUT			, C.EMPRESA
				, C.ACRONIMO			, C.FECHA						, C.HORA		, C.CANTIDAD AS CANTIDAD_REPORTE
				, (CASE WHEN ISNULL(C.ERROR, '') <> '' THEN ISNULL(M.MSG_REPORT, 'ERROR') ELSE '' END  ) AS ERROR
				, C.CCOSTO				, C.COD_PDA						, W.NOMBRES		, W.APELLIDOS
				, D.DIVISION			, D.DIVCOD						, C.COD_PDA		, C.USUARIO
				, ADMINOST				, EE.ACRONIMO AS CONTRATISTA	, C.OST			, W2.NOMBRES + ' ' + W2.APELLIDOS AS ADMINOSTNOM 
FROM WC3_VISTA_CASINO  AS C LEFT OUTER JOIN WORKERS AS W ON C.RUT = W.RUT 
                            LEFT OUTER JOIN MULTASTTO AS M ON C.ERROR = M.CODMULTA 
							INNER JOIN A024_DIVISIONES D ON C.DIVISION = D.DIVCOD 
							LEFT OUTER JOIN OSTDIVLOCAL AS O ON C.OST = O.OST AND C.DIVISION = O.DIVISION AND O.MANDANTE IN (SELECT MANDANTE FROM A027_MANDANTES WHERE ACTIVO = 'SI') 
							LEFT OUTER JOIN WORKERS AS W2 ON O.ADMINOST = W2.RUT 
							LEFT OUTER JOIN ENTERPRISE AS EE ON EE.IDEMPRESA = O.EMPRESA 
WHERE C.SERVICIO <> '' AND ISNULL(C.ERROR, '') = ''  AND (C.RUT = @RUT)  AND (C.FECHA  Like SUBSTRING(CONVERT(NVARCHAR(8),GETDATE(),112),1,6)+'%')   
ORDER BY C.SERVICIO, C.LOCAL, C.FECHA, C.HORA  ASC 
END
