CREATE PROCEDURE [dbo].[V4MVC_CERT_AUDITORIA_SELECT_CTTA]
(
 @IDEMPRESA NVARCHAR(10) = NULL
)
AS
BEGIN

	SELECT   T1.ID_CERT_AUDITORIA		,T1.IDEMPRESA			,T1.PERIODO					,T1.FECHA
			,T1.ID						,T1.TIPO_AUDITORIA		,T1.PORCENTAJE_APROBACION	,T1.CANT_PERSONAS
			,T1.VALIDADO				,T1.OBSERVACION			,T1.USUARIO					,T1.FECHASUBE
			,T1.HORASUBE				,T1.CERTUSUARIO			,T1.CERTFECHA				,T1.CERTHORA
			,T1.USUARIOMOD				,T1.FECHAMOD			,T1.HORAMOD					,T1.NCONTRATO
			,T1.DIVISION				,T1.COD_INTERNO_CERT	,T1.ID_FOLIO				,T2.ACRONIMO
	FROM CERT_AUDITORIA T1
	INNER JOIN ENTERPRISE T2 ON T1.IDEMPRESA = T2.IDEMPRESA
	WHERE T1.IDEMPRESA= @IDEMPRESA

END
