CREATE PROCEDURE [dbo].[V4MVC_WORKERSLOCAL_BONO_RESUMEN_SELECT_CTTA]
(
 @DIVISION		NVARCHAR(4 ) = NULL
,@EMPRESA		NVARCHAR(10) = NULL
,@RUT			NVARCHAR(10) = NULL
,@TIPO_BONO		NVARCHAR(20) = NULL
,@PERIODO		NVARCHAR(6 ) = NULL
,@BONO			NVARCHAR(2 ) = NULL
)
AS
BEGIN

	SELECT			WB.RUT						,W.NOMBRES					,W.APELLIDOS			,WB.EMPRESA
				   ,E.ACRONIMO					,WB.DIVISION AS DIVCOD		,D.DIVISION				,WB.OST
				   ,WB.TURNO					,WB.DIAS_TRABAJO			,WB.DIAS_FAENA			,WB.DIAS_LICENCIA
				   ,WB.TOTAL_ASISTENCIA			,WB.PORCEN_ASIS_FINAL		,WB.PORCEN_ASIS_MIN		,WB.BONO
				   ,WB.VALOR					,WB.PERIODO
	FROM			WORKERSLOCAL_BONO_RESUMEN	WB  
	INNER JOIN		WORKERS W					ON WB.RUT		=	W.RUT  
	INNER JOIN		ENTERPRISE E				ON WB.EMPRESA	=	E.IDEMPRESA 
	INNER JOIN		A024_DIVISIONES D			ON WB.DIVISION	=	D.DIVCOD  
	WHERE			D.DIVCOD			=		@DIVISION
	AND				WB.EMPRESA			=		@EMPRESA
	AND				WB.RUT				=		ISNULL(@RUT, WB.RUT)
	AND				TIPO_BONO			=		@TIPO_BONO
	AND				WB.PERIODO			=		@PERIODO
	AND				WB.BONO				=		ISNULL(@BONO, WB.BONO)
	ORDER BY W.NOMBRES

 END
