CREATE PROCEDURE [dbo].[V4MVC_DOCS_DISPUTA_CLABORAL_INSERT_CONTROLLABORAL_CTTA]
(
  @ID					UNIQUEIDENTIFIER
 ,@ID_DOC				INT
 ,@PERIODO				NVARCHAR(6)
 ,@IDEMPRESA			NVARCHAR(12)
 ,@DIVISION				NVARCHAR(4)
 ,@OST					NVARCHAR(20)
 ,@OBSERVACION			NVARCHAR(1000)
 ,@USUARIO				NVARCHAR(10)
 ,@CERTUSUARIO			NVARCHAR(10)
 ,@CERTFECHA			NVARCHAR(8)
 ,@CERTHORA				NVARCHAR(8)
 ,@VALIDADO				NVARCHAR(2)
 ,@CERTIFICADO_ID		INT
 ,@DISPUTA_ID			INT OUTPUT
) AS
BEGIN
	DECLARE @CURR_FECHA NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 112) /* yyyymmdd */
	DECLARE @CURR_TIEMPOFULL NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 108) /* hh:mm:ss */

	INSERT INTO DOCS_DISPUTA_CLABORAL
				(
					ID, ID_DOC, PERIODO, EMPRESA,
					DIVISION, OST, OBSERVACION,
					USUARIO, FECHA, HORA,
					CERTUSUARIO, CERTFECHA, CERTHORA,
					ESTADO, VALIDADO, ID_CERTIFICADO
				)
	VALUES
				(
					@ID, @ID_DOC, @PERIODO, @IDEMPRESA,
					@DIVISION, @OST, @OBSERVACION,
					@USUARIO, @CURR_FECHA, @CURR_TIEMPOFULL,
					@CERTUSUARIO, @CERTFECHA, @CERTHORA,
					'NO', @VALIDADO, @CERTIFICADO_ID
				)
	SET @DISPUTA_ID = SCOPE_IDENTITY()
END
