CREATE PROCEDURE [dbo].[V4MVC_ADMIN_SELECT]  
( @ADMRUT         nvarchar(10) = NULL ) AS  
BEGIN  
  
   SELECT ADM.ADMRUT        , ADM.ADMCLAVE  , ADM.ADMTIPO    , ADM.ADMEMAIL     
        , ADM.ADMRUTEMPRESA , ADM.ADMLOCAL  , ADM.ADMLUGAR   , ADM.ADMPUERTOS   
        , ADM.ADMUSERID     , ADM.ADMRUTVER , ADM.ADMSUP     , ADM.FECHAMOD     
        , ADM.HORAMOD       , ADM.GRABO     , ADM.ACTIVO     , ADM.ADMDIVISION  
        , ADM.FECHAVENCE    , ADM.IDSYNC    , ADM.ADMADLOGIN , ADM.APRUEBA_COND 
		, W.NOMBRES			, W.APELLIDOS
     FROM ADMIN ADM
	INNER JOIN WORKERS W ON ADM.ADMRUT = W.RUT
    WHERE ADM.ADMRUT = ISNULL( @ADMRUT, ADM.ADMRUT )  
  
END  
