CREATE PROCEDURE [dbo].[V4MVC_POLIZA_MUERTE_UPDATE_CONTROLLABORAL_CTTA]
(
  @PERIODO		NVARCHAR(6)
 ,@IDEMPRESA	NVARCHAR(10)
 ,@RET_CODE		INT OUTPUT
) AS
BEGIN
	
	SET @RET_CODE = -1

	IF(NOT EXISTS(
			SELECT
				PERIODO
			FROM POLIZA_MUERTE
			WHERE
				EMPRESA = @IDEMPRESA AND
				PERIODO = @PERIODO
	))
		BEGIN
			SET @RET_CODE = 2  /*ERROR LOGICO; NO EXISTE*/
			RETURN
		END
END
