CREATE PROCEDURE [dbo].[V4MVC_GET_WC3_VISTA_CTRLING_INFORME_CENSOACCESOS_DETALLE]
(
@FECHAINI  NVARCHAR(8)       = NULL,
@FECHAFIN  NVARCHAR(8)       = NULL,
@DIVCOD  NVARCHAR(4)         = NULL,
@EMPRESA  NVARCHAR(10)       = NULL
) AS
BEGIN

DECLARE @FECHA_INI DATE
DECLARE @FECHA_FIN DATE
DECLARE	@Servicio_Fecha NVARCHAR(MAX)
DECLARE	@Servicio_Fecha_Sum  NVARCHAR(MAX)
DECLARE	@Servicio_Fecha_Sum_Resumen  NVARCHAR(MAX)
DECLARE	@Servicio_Fecha_Sum_ResumenTotal  NVARCHAR(MAX)
DECLARE	@Nro  INT 
SET @Servicio_Fecha = ''
SET @Servicio_Fecha_Sum = ''
SET @Servicio_Fecha_Sum_Resumen = ''
SET @Servicio_Fecha_Sum_ResumenTotal = ''
SET @Nro = -1
SET @FECHA_INI =  @FECHAINI
SET @FECHA_FIN =  @FECHAFIN
WHILE DATEDIFF(DAY, @FECHA_INI, @FECHA_FIN) > -1
BEGIN  
	SET	@Nro = @Nro + 1
		If @Servicio_Fecha = '' 
		BEGIN
			SET @Servicio_Fecha = '[' + CONVERT(VARCHAR(8),@FECHA_INI,112) + ']'
			SET @Servicio_Fecha_Sum = ' CASE WHEN [' + CONVERT(VARCHAR(8),@FECHA_INI,112) +'] > 0 THEN 1 ELSE 0 END AS [' +CONVERT(VARCHAR(8),@FECHA_INI,112)  +' ]'
			SET @Servicio_Fecha_Sum_Resumen = 'SUM ([' +CONVERT(VARCHAR(8),@FECHA_INI,112)  + ']) AS [' + CONVERT(VARCHAR(8),@FECHA_INI,112)  + ']'
			SET @Servicio_Fecha_Sum_ResumenTotal = 'SUM ([' +CONVERT(VARCHAR(8),@FECHA_INI,112)  + '])'
        END
		ELSE
		BEGIN
			SET @Servicio_Fecha = @Servicio_Fecha +  ',[' + CONVERT(VARCHAR(8),@FECHA_INI,112)  + ']'
			SET @Servicio_Fecha_Sum = @Servicio_Fecha_Sum + ', CASE WHEN [' +CONVERT(VARCHAR(8),@FECHA_INI,112)  + '] > 0 THEN 1 ELSE 0 END AS [' +CONVERT(VARCHAR(8),@FECHA_INI,112)  + '] '
			SET @Servicio_Fecha_Sum_Resumen = @Servicio_Fecha_Sum_Resumen +', SUM ([' + CONVERT(VARCHAR(8),@FECHA_INI,112)  + ']) AS [' + CONVERT(VARCHAR(8),@FECHA_INI,112)  + ']'
			SET @Servicio_Fecha_Sum_ResumenTotal = @Servicio_Fecha_Sum_ResumenTotal +'+ SUM ([' + CONVERT(VARCHAR(8),@FECHA_INI,112)  + '])'
		END		
		
		SET @FECHA_INI = (SELECT DATEADD(DAY, 1, @FECHA_INI))
END  

DECLARE @strSQL as nvarchar(MAX)

SET @strSQL= '(SELECT DISTINCT WORK.NOMBRES, WORK.APELLIDOS, DETALLE.RUTINGRESO, DETALLE.OST, DETALLE.TIPOPASE, DETALLE.ACRONIMO, DETALLE.EMPRESA,DETALLE.DIVISION, DETALLE.OST, A.AREA, G.GERENCIA, ' 
SET @strSQL = @strSQL + @Servicio_Fecha_Sum_Resumen  
Set @strSQL = @strSQL + N', ('
SET @strSQL = @strSQL + @Servicio_Fecha_Sum_ResumenTotal  
Set @strSQL = @strSQL + N') AS TOTAL'
Set @strSQL = @strSQL + N' FROM ( SELECT pvt.RUTINGRESO, pvt.EMPRESA, pvt.ACRONIMO, pvt.TIPOPASE, pvt.OST, pvt.DIVISION, '
SET @strSQL = @strSQL + @Servicio_Fecha_Sum  
Set @strSQL = @strSQL + N' FROM (	SELECT DISTINCT W.RUTINGRESO, W.EMPRESA, W.ACRONIMO, SUM(INGRESO) AS ING, W.FECHA, W.TIPOPASE, W.OST, W.DIVISION' 
Set @strSQL = @strSQL + N' FROM TAB_TIPOPASE AS T INNER JOIN TAB_TIPOPASE_DIVISION AS D ON T.TIPOPASE = D.TIPOPASE INNER JOIN WC3_VISTA_CTRLING AS W'
Set @strSQL = @strSQL + N' ON D.DIVISION = W.DIVISION INNER JOIN OST AS O ON W.OST = O.NROOST WHERE (W.FECHA  BETWEEN ''' + @FECHAINI + ''' AND ''' + @FECHAFIN + ''') AND (W.DIVISION = ''' + @DIVCOD + ''') AND (W.EMPRESA = ''' + @EMPRESA + ''')GROUP BY W.RUTINGRESO, W.FECHA, W.EMPRESA, W.ACRONIMO, W.TIPOPASE, W.OST, W.DIVISION '
Set @strSQL = @strSQL + N' ) as datatable PIVOT ( SUM(ING) FOR [FECHA] IN ('
SET @strSQL = @strSQL + @Servicio_Fecha 
Set @strSQL = @strSQL + N' ) ) as pvt ) AS DETALLE INNER JOIN WORKERS AS WORK ON DETALLE.RUTINGRESO = WORK.RUT'
Set @strSQL = @strSQL + N' LEFT OUTER JOIN GERENCIA AS G ON WORK.IDGERENCIA = G.IDGERENCIA  LEFT OUTER JOIN A025_AREA AS A ON WORK.ID_AREA = A.ID_AREA'
Set @strSQL = @strSQL + N' GROUP BY DETALLE.RUTINGRESO, DETALLE.EMPRESA, DETALLE.ACRONIMO, DETALLE.DIVISION, DETALLE.OST, DETALLE.TIPOPASE, WORK.NOMBRES, WORK.APELLIDOS, A.AREA, G.GERENCIA'
Set @strSQL = @strSQL + N') UNION ALL ('
Set @strSQL = @strSQL + N'SELECT DISTINCT ''TOTAL'', '''', '''', '''', '''', '''', '''','''', '''', '''', '''', ' 
SET @strSQL = @strSQL + @Servicio_Fecha_Sum_Resumen  
Set @strSQL = @strSQL + N', ('
SET @strSQL = @strSQL + @Servicio_Fecha_Sum_ResumenTotal  
Set @strSQL = @strSQL + N') AS TOTAL'
Set @strSQL = @strSQL + N' FROM ( SELECT pvt.RUTINGRESO, pvt.EMPRESA, pvt.ACRONIMO, pvt.TIPOPASE, pvt.OST, pvt.DIVISION, '
SET @strSQL = @strSQL + @Servicio_Fecha_Sum  
Set @strSQL = @strSQL + N' FROM (	SELECT DISTINCT W.RUTINGRESO, W.EMPRESA, W.ACRONIMO, SUM(INGRESO) AS ING, W.FECHA, W.TIPOPASE, W.OST, W.DIVISION' 
Set @strSQL = @strSQL + N' FROM TAB_TIPOPASE AS T INNER JOIN TAB_TIPOPASE_DIVISION AS D ON T.TIPOPASE = D.TIPOPASE INNER JOIN WC3_VISTA_CTRLING AS W'
Set @strSQL = @strSQL + N' ON D.DIVISION = W.DIVISION INNER JOIN OST AS O ON W.OST = O.NROOST WHERE (W.FECHA  BETWEEN ''' + @FECHAINI + ''' AND ''' + @FECHAFIN + ''') AND (W.DIVISION = ''' + @DIVCOD + ''') AND (W.EMPRESA = ''' + @EMPRESA + ''')GROUP BY W.RUTINGRESO, W.FECHA, W.EMPRESA, W.ACRONIMO, W.TIPOPASE, W.OST, W.DIVISION '
Set @strSQL = @strSQL + N' ) as datatable PIVOT ( SUM(ING) FOR [FECHA] IN ('
SET @strSQL = @strSQL + @Servicio_Fecha 
Set @strSQL = @strSQL + N' ) ) as pvt ) AS DETALLE INNER JOIN WORKERS AS WORK ON DETALLE.RUTINGRESO = WORK.RUT'
Set @strSQL = @strSQL + N' LEFT OUTER JOIN GERENCIA AS G ON WORK.IDGERENCIA = G.IDGERENCIA  LEFT OUTER JOIN A025_AREA AS A ON WORK.ID_AREA = A.ID_AREA)'

 exec sp_executesql @strSQL  
 PRINT @strSQL
 
END	
