CREATE PROCEDURE [dbo].[V4MVC_TRANSPORT_DIVISION_ACTIVAVEHICULO_CTTA]
(@PATENTE			NVARCHAR(6) = NULL
,@IDEMPRESA			NVARCHAR(11) = NULL
,@DIVCOD			NVARCHAR(4) = NULL)
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM TRANSPORT_DIVISION WHERE PATENTE= @PATENTE AND DIVISION = @DIVCOD) 
		BEGIN 
		INSERT INTO TRANSPORT_DIVISION (PATENTE	, DIVISION	, AUTOR	, FECHAMOD				 , HORAMOD) 
								 VALUES(@PATENTE, @DIVCOD	, 'NO'	, [dbo].[hoy](GETDATE()) , [dbo].[ahora](GETDATE())) 
		END 
	ELSE 
		BEGIN  
			UPDATE TRANSPORT_DIVISION SET FECHAMOD= [dbo].[hoy](GETDATE()) 
										, HORAMOD= [dbo].[ahora](GETDATE()) 
			WHERE PATENTE= @PATENTE AND DIVISION= @DIVCOD
		END

	IF EXISTS(SELECT * FROM A024_DIVISIONES WHERE ISNULL(PASES_VEHICULARES,'NO') = 'SI' AND DIVCOD = @DIVCOD)
		BEGIN
			IF NOT EXISTS(SELECT * FROM TRANSPORT_DIVISION_PASES WHERE PATENTE = @PATENTE AND DIVISION =@DIVCOD AND LOTE = 0 AND EMPRESA = @IDEMPRESA)
				BEGIN 
				INSERT INTO TRANSPORT_DIVISION_PASES (PATENTE		, EMPRESA		, DIVISION				, AUTOR
													, LOTE			, TIPOPASE		, FINIPASE				, FFINPASE
													, OST			, FECHAMOD		, HORAMOD) 
												VALUES(@PATENTE		, @IDEMPRESA	, @DIVCOD	, 'NO'
													, 0				, 'TRABAJO'		, [dbo].[hoy](GETDATE()), [dbo].[HOY](DATEADD(MONTH,120,GETDATE()))
													, 'NOMINA'		,  [dbo].[hoy](GETDATE()),[dbo].[ahora](GETDATE())) 
				END 
			ELSE 
				BEGIN  
					UPDATE TRANSPORT_DIVISION_PASES SET TIPOPASE = 'TRABAJO'
														, FINIPASE = [dbo].[hoy](GETDATE())
														, FFINPASE = [dbo].[HOY](DATEADD(MONTH,120,GETDATE()))
														, AUTOR = 'NO'
														, OST = 'NOMINA' 
					WHERE PATENTE = @PATENTE AND DIVISION = @DIVCOD AND LOTE = 0 AND EMPRESA = @IDEMPRESA 
				END
		END
END
