CREATE PROCEDURE [dbo].[V4MVC_LOTEPASESFUN_SELECT_CONDUCCIONPASE]
( @RUT				nvarchar(10) = NULL
, @DIVCOD			nvarchar(30) = NULL
) AS 
BEGIN
	SELECT APELLIDOSLT,NOMBRESLT , EMPRESALT ,RUTLOTE , E.ACRONIMO , @DIVCOD AS DIVCOD
	FROM LOTEPASESFUN  AS LPF
	INNER JOIN ENTERPRISE AS E ON E.IDEMPRESA = LPF.EMPRESALT
	WHERE RUTLOTE = @RUT AND  
	NLOTEPROC IN (SELECT LOTE 
				 FROM WORKERSLOCAL 
				 WHERE (RUT = @RUT) AND 
				 (DIVISION = @DIVCOD) AND 
				 (FFINPASE >= DBO.HOY(GETDATE())) AND 
				 (AUTOR IN ('SI','NO')))			 
	ORDER BY NLOTEPROC
END


