CREATE PROCEDURE [dbo].[V4MVC_CASINO_LOCAL_SERVICIO_FECHA_CTTA]
(
 @EMPRESA	NVARCHAR(10)
,@LOCALES	NVARCHAR(MAX)
,@DIVCOD	NVARCHAR(4)
,@FECHAINI	NVARCHAR(8)
,@FECHAFIN	NVARCHAR(8)
)
AS
BEGIN

	SELECT VALUE AS LOCAL INTO #TEMP_SPLIT_LOCALES
	FROM STRING_SPLIT(@LOCALES,',')

	SELECT LOCAL,SERVICIO,FECHA,SUM(CANTIDAD) AS CANTIDAD FROM WC3_VISTA_CASINO
	WHERE EMPRESA = @EMPRESA
	AND FECHA BETWEEN @FECHAINI AND @FECHAFIN
	AND DIVISION = @DIVCOD
	AND ISNULL(ERROR,'') = ''
	AND LOCAL IN (SELECT LOCAL FROM #TEMP_SPLIT_LOCALES)
	GROUP BY LOCAL,SERVICIO,FECHA

END

--EXEC V4MVC_CASINO_LOCAL_SERVICIO_FECHA_CTTA '761264907','CAS_PCALDERA,CAS_CONFLUEN','LB','20190101','20201125'
