CREATE PROCEDURE [dbo].[V4MVC_WORKERS_INSERT_NEWENTERPRISECTTA]
(
 @RUT NVARCHAR(10)
,@EMPRESA NVARCHAR(10)
,@NOMBRES NVARCHAR(50)
,@APELLIDOS NVARCHAR(50)
)
AS
BEGIN

	INSERT INTO [WORKERS]
	(
		 RUT	,EMPRESA	,NOMBRES	,APELLIDOS	
	)
	VALUES
	(
		@RUT	,@EMPRESA	,@NOMBRES	,@APELLIDOS
	)
END
