CREATE PROCEDURE [dbo].[V4MVC_LOTEPASESFUN_DELETE_V2_PASES_CTTA]
( 
  @PASE_ID			INT
 ,@PATENTE			NVARCHAR(10)
) AS 
BEGIN
	DELETE
	FROM LOTEPASESFUN
	WHERE
		NLOTEPROC = @PASE_ID AND
		RUTLOTE = @PATENTE AND
		TIPORUT = 'VEHICULO'
END


