CREATE PROCEDURE [dbo].[V4MVC_LOTEPASESFUN_UPSERT_V2_PASES_CTTA]
(
  @PASE_ID			INT
 ,@PATENTE			NVARCHAR(10)
 ,@IDEMPRESA        NVARCHAR(10)
 ,@TIPO_VEH			INT
 ,@MARCA			NVARCHAR(50)
 ,@MODELO			NVARCHAR(50)
 ,@TIPO_PASE		NVARCHAR(9) = ''
 ,@ANIO				NVARCHAR(8)
 ,@OST				NVARCHAR(14) = ''
) AS 
BEGIN
	IF(
		(
			SELECT COUNT(*) 
			FROM LOTEPASESFUN
			WHERE
				NLOTEPROC = @PASE_ID AND
				RUTLOTE = @PATENTE AND
				TIPORUT = 'VEHICULO'
		) > 0
	  )
		BEGIN
			UPDATE LOTEPASESFUN 
			SET
				NOMBRESLT = @MARCA,
				APELLIDOSLT = @MODELO,
				TIPOVEHI = @TIPO_VEH,
				FNACIMLT = @ANIO
			WHERE
				NLOTEPROC = @PASE_ID AND
				RUTLOTE = @PATENTE AND
				TIPORUT = 'VEHICULO'
		END
	ELSE
		BEGIN
			INSERT LOTEPASESFUN
					(
					 NLOTEPROC,
					 RUTLOTE,
					 EMPRESALT,
					 TIPORUT,
					 SINOLT,
					 NOMBRESLT,
					 APELLIDOSLT,
					 TIPOVEHI,
					 FNACIMLT,
					 TIPOLT,
					 OSTLT)
			VALUES
					(
					 @PASE_ID,
					 @PATENTE,
					 @IDEMPRESA,
					 'VEHICULO',
					 'SI',
					 @MARCA,
					 @MODELO,
					 @TIPO_VEH,
					 @ANIO,
					 @TIPO_PASE,
					 @OST
					)
		END

END

