CREATE PROCEDURE [dbo].[V4MVC_TRANSPORT_SELECT_ONE_PASES_CTTA]
(
  @PATENTE		NVARCHAR(10)
 ,@IDPASE		INT
 ,@DIVCOD		NVARCHAR(4) = ''
 ,@ID_EMPRESA	NVARCHAR(10) = ''
 ,@FEC_INI		NVARCHAR(8) = '19000101'
 ,@FEC_FIN		NVARCHAR(8) = '19000101'
) AS 
BEGIN
	
	SELECT
		SS.PATENTE,
		SS.MARCA,
		SS.MODELO,
		SS.ANOFAB,
		SS.TIPO,
		COALESCE(
				(
				 SELECT TOP 1 TT.DSCTIPOV
				 FROM TYPETRANS TT
				 WHERE TT.IDTIPO = SS.TIPO
				 ), '') AS TIPO_TXT,
		SS.AUTOR,
		SS.EMPRESA,
		COALESCE(
			(
				SELECT
					TOP 1
					E.ACRONIMO
				FROM ENTERPRISE E
				WHERE E.IDEMPRESA = SS.EMPRESA
			),
		'') AS NOMBRE_EMPRESA,
		SS.PERTENECE_NOMINA,
		SS.PASES_ACTIVOS,
		SS.SINOLT
	FROM
	(
		SELECT
			ISNULL(T.PATENTE, '') AS PATENTE,
			ISNULL(T.MARCA, '') AS MARCA,
			ISNULL(T.MODELO, '') AS MODELO,
			ISNULL(T.ANOFAB, '') AS ANOFAB,
			ISNULL(T.TIPO, 0) AS TIPO,
			ISNULL(T.AUTOR, '') AS AUTOR,
			COALESCE(
			(
				SELECT
					TOP 1
					ISNULL(TDP.EMPRESA, '')
				FROM TRANSPORT_DIVISION_PASES TDP
				WHERE
					TDP.PATENTE = @PATENTE AND
					(dbo.hoy(GETDATE()) BETWEEN TDP.FINIPASE AND TDP.FFINPASE) AND
					(TDP.AUTOR IN ('SI','NO'))
				ORDER BY TDP.LOTE DESC
			), ISNULL(T.EMPRESA, '')) AS EMPRESA,
			(CASE
				WHEN CONVERT(NVARCHAR(10), @ID_EMPRESA) = T.EMPRESA THEN 1
				ELSE 0 END
			) AS PERTENECE_NOMINA,
			(
			  SELECT
				COUNT(*)
			  FROM TRANSPORT_DIVISION_PASES TDP1
			  WHERE 
					(TDP1.PATENTE = T.PATENTE) AND
					(TDP1.LOTE) <> '0' AND
					(TDP1.AUTOR) = 'SI' AND
					(TDP1.DIVISION = @DIVCOD) AND
					(TDP1.LOTE <> @IDPASE) AND 
					(
					  (@FEC_INI BETWEEN TDP1.FINIPASE AND TDP1.FFINPASE) OR
					  (@FEC_FIN BETWEEN TDP1.FINIPASE AND TDP1.FFINPASE) OR
					  (@FEC_INI < TDP1.FINIPASE AND TDP1.FFINPASE < @FEC_FIN)
					)
			) AS PASES_ACTIVOS,
			'SI' AS SINOLT
		FROM TRANSPORT T
		WHERE (T.PATENTE = @PATENTE)
	) SS
END


