CREATE PROCEDURE [dbo].[V4MVC_TAB_COMBUSTIBLE_SELECT]
( @IDCOMBUSTIBLE  int = NULL ) AS
BEGIN

   SELECT IDCOMBUSTIBLE , COMBUSTIBLE
     FROM TAB_COMBUSTIBLE
    WHERE IDCOMBUSTIBLE = ISNULL( @IDCOMBUSTIBLE, IDCOMBUSTIBLE )
	ORDER BY COMBUSTIBLE

END

