CREATE PROCEDURE [dbo].[V4MVC_OST_SELECT_ONE_CONTRATOST_CTTA]
(
  @NROOST			NVARCHAR(14)
 ,@IDEMPRESA		NVARCHAR(10)
 ,@MADRE			NVARCHAR(10)
 ,@NIVEL			SMALLINT
) AS
BEGIN
	DECLARE @CANT_DOCS_PENDIENTE INT = -1
	DECLARE @NUM_SOLICITUD BIGINT = -1
	DECLARE @ESTADO_PREV NVARCHAR(2) = ''
	DECLARE @VALIDA_PREV NVARCHAR(2) = 'NO'

	SELECT
		@CANT_DOCS_PENDIENTE = COUNT(DOCS_OST2.VALIDADO)
	FROM DOCS_OST2
	INNER JOIN DOCS D
	ON D.ID_DOC = DOCS_OST2.ID_DOC AND
		D.ID_DOC_OPCION = '1' AND
		D.ACTIVO = 'SI'
	WHERE
		(DOCS_OST2.OST = @NROOST) AND
		(DOCS_OST2.MADRE = @MADRE) AND
		(DOCS_OST2.EMPRESA = @IDEMPRESA) AND
		(DOCS_OST2.NIVEL = @NIVEL) AND
		(ISNULL(DOCS_OST2.VALIDADO,'NO') = 'NO')

	SELECT
		TOP 1
			@NUM_SOLICITUD = ID,
			@ESTADO_PREV = ESTADO,
			@VALIDA_PREV = 'SI'
	FROM DOCS_OST_PREVENCIONISTA
	WHERE
		OST = @NROOST AND
		MADRE = @MADRE AND
		EMPRESA = @IDEMPRESA

	/********************************************/


	SELECT
		O.ID_INSTALACION_FAENA,
		O.ID_INF_RECEPCION,
		O.ID_FORM_RECEPCION,
		O.EDIFICIO_INSTALACION,
		ISNULL(OS.VALIDA_CARRANQUE,'NO') AS VALIDA_CARRANQUE,
		OS.FINICIO AS FECINICIO,
		OS.FTERMINO AS FECTERM,
		O.DESCRIPOST,
		O.VALIDADOR,
		O.DOTTRANS,
		O.DOTACION,
		@CANT_DOCS_PENDIENTE AS CANT_DOCS_PENDIENTE,
		@NUM_SOLICITUD AS NUM_SOLICITUD,
		@ESTADO_PREV AS ESTADO_PREV,
		@VALIDA_PREV AS VALIDA_PREV
	FROM OST O
	INNER JOIN OSTARBOL OS
		ON OS.OST = O.NROOST
	WHERE
		O.NROOST = @NROOST AND 
		OS.EMPRESA = @IDEMPRESA AND
		OS.MADRE = @MADRE AND
		OS.NIVEL = @NIVEL
END

