CREATE PROCEDURE [dbo].[V4MVC_TRANSPORT_COUNT_BUSCADORCTTA]        
(        
@SEARCH_PATENTE NVARCHAR(8) = NULL,        
@SEARCH_MARCA NVARCHAR(50) = NULL,        
@SEARCH_MODELO NVARCHAR(50) = NULL,  
@SEARCH_TIPO NVARCHAR(20) = NULL,
@SEARCH_ANOFAB NVARCHAR(4) = NULL
)        
AS        
BEGIN  

    DECLARE @QUERY NVARCHAR(MAX)
    SET @QUERY  = 'SELECT  COUNT(T.PATENTE) AS COUNT_TRANSPORT                        
    FROM TRANSPORT AS T
    LEFT JOIN TYPETRANS AS TT ON TT.IDTIPO = T.TIPO WHERE 1=1 '
	
    IF @SEARCH_PATENTE IS NOT NULL BEGIN SET @QUERY = @QUERY + ' AND T.PATENTE LIKE ' + '''%' + @SEARCH_PATENTE + '%''' END
    IF @SEARCH_MARCA IS NOT NULL BEGIN SET @QUERY = @QUERY + ' AND T.MARCA LIKE ' + '''%' + @SEARCH_MARCA + '%''' END
    IF @SEARCH_MODELO IS NOT NULL BEGIN SET @QUERY = @QUERY + ' AND T.MODELO LIKE ' + '''%' + @SEARCH_MODELO + '%''' END
    IF @SEARCH_TIPO IS NOT NULL BEGIN SET @QUERY = @QUERY + ' AND TT.DSCTIPOV LIKE ' + '''%' + @SEARCH_TIPO + '%''' END
    IF @SEARCH_ANOFAB IS NOT NULL BEGIN SET @QUERY = @QUERY + ' AND T.ANOFAB LIKE ' + '''%' + @SEARCH_ANOFAB + '%''' END

    EXEC(@QUERY)
       
END    
    
