CREATE PROCEDURE [dbo].[V4MVC_CASINO_FECHAS_CTTA]
(
 @FECHAINI NVARCHAR(8)
,@FECHAFIN NVARCHAR(8)
)
AS
BEGIN

	CREATE TABLE #FECHAS
	(
		FECHA NVARCHAR(8)  COLLATE DATABASE_DEFAULT NOT NULL
	)

	DECLARE @CONTADOR		INT   
	DECLARE @DATE1			DATETIME
	DECLARE @DATE2			DATETIME
	DECLARE @DATE_DIF		INT
	DECLARE @FECHA			NVARCHAR(8)

	SET		@DATE1		=	@FECHAINI
	SET		@DATE2		=	@FECHAFIN
	SET		@DATE_DIF	=	(SELECT DATEDIFF(DAY, @DATE1,@DATE2))

	SET @CONTADOR = 0
	WHILE ( @CONTADOR <= @DATE_DIF )
	BEGIN

		SET @FECHA = CONVERT(NVARCHAR(8), @DATE1,112)
		INSERT INTO #FECHAS VALUES (@FECHA)
		SET @DATE1 = (SELECT DATEADD(DAY,1,@DATE1))
		SET @CONTADOR = @CONTADOR +1  

	END

	SELECT FECHA FROM #FECHAS
	ORDER BY FECHA ASC

END

