CREATE PROCEDURE [dbo].[V4MVC_LOTEPASESFUN_SELECT_FUNCIONARIO_INFORMECONSULTARAPIDA_CTTA]
(
  @NLOTEPROC INT 
) AS 
BEGIN

SELECT RUTLOTE		, NOMBRESLT			, APELLIDOSLT	, SINOLT
     , EMPRESALT	, ALOJAMIENTOLT		, CASINOLT		, LICONDLT
	 , [dbo].[fn_WL_Certificado] (RUTLOTE, EMPRESALT , TIPOLT, 'CH', dbo.hoy(getdate())) AS CERT
	 , [dbo].[fn_WL_Conductor] (RUTLOTE, 'CH',  dbo.hoy(getdate())) AS CONDUC 
	 FROM LOTEPASESFUN 
	 WHERE NLOTEPROC = @NLOTEPROC AND TIPORUT = 'FUNCIONARIO' 
	 ORDER BY RUTLOTE ASC

END
