CREATE PROCEDURE [dbo].[V4MVC_PLANILLA_COTIZACION_UPDATE_CONTROLLABORAL_CTTA]
(
  @PERIODO		NVARCHAR(6)
 ,@IDEMPRESA	NVARCHAR(10)
 ,@DIVISION		NVARCHAR(4)
 ,@OST			NVARCHAR(20)
 ,@RET_CODE		INT OUTPUT
) AS
BEGIN
	SET @RET_CODE = -1

	IF(NOT EXISTS(
			SELECT
				PERIODO
			FROM PLANILLA_COTIZACION
			WHERE
				EMPRESA = @IDEMPRESA AND
				PERIODO = @PERIODO AND
				DIVISION = @DIVISION AND
				OST = @OST
	))
		BEGIN
			SET @RET_CODE = 2  /*ERROR LOGICO; NO EXISTE*/
			RETURN
		END
END
