CREATE PROCEDURE [dbo].[V4MVC_DOCS_FEC_TIPOPASE_SELECT_DIVISION]
(
@DIVCOD NVARCHAR(4)
)
AS
BEGIN

SELECT DISTINCT DF.CAMPO_BD FROM  DOCS_FEC AS DF 
	INNER JOIN DOCS_FEC_TIPOPASE AS DFT ON DF.ID_DOC_FEC = DFT.ID_DOC_FEC   
	WHERE  (DFT.TIPOPASE = 'TRABAJO') 
	AND (DFT.DIVISION = @DIVCOD)  
	ORDER BY DF.CAMPO_BD 

END
