CREATE PROCEDURE [dbo].[V4MVC_INFORME_CONTRATOSCARRANQUE_OSTARBOL_CTTA]
(
 @EMPRESA	NVARCHAR(10) = NULL
,@MADRE		NVARCHAR(10) = NULL
,@NIVEL		INT			 = NULL
,@OST		NVARCHAR(14) = NULL
)
AS
BEGIN

		SELECT T1.OST	,T1.MADRE		,(SELECT ACRONIMO FROM ENTERPRISE WHERE IDEMPRESA = T1.MADRE) AS ACRONIMO_MANDANTE	
						,T1.EMPRESA		,(SELECT ACRONIMO FROM ENTERPRISE WHERE IDEMPRESA = T1.EMPRESA) AS ACRONIMO		
						,T1.FINICIO		,T1.FTERMINO	,T1.NIVEL 
		FROM OSTARBOL T1
		WHERE T1.FTERMINO >= DBO.HOY(GETDATE())
		AND T1.EMPRESA=ISNULL(@EMPRESA,T1.EMPRESA)
		AND T1.OST= ISNULL(@OST,T1.OST)

END


--V4MVC_INFORME_CONTRATOSCARRANQUE_OSTARBOL_CTTA '761264907',NULL,NULL,null
