CREATE PROCEDURE [dbo].[V4MVC_GETDOCS_TIPO_RECHAZO_LIQUIDACION_FUNCIONARIOSCTTA]
(@RUT	  NVARCHAR(10) = NULL
,@FECHA	  NVARCHAR(6) = NULL
,@EMPRESA NVARCHAR(10) = NULL) AS
BEGIN
	SELECT tr.TIPO_RECHAZO 
	FROM DOCS_WORKERS_RECHAZO dw 
	INNER JOIN DOCS_TIPO_RECHAZO tr ON tr.ID_TIPO_RECHAZO = dw.ID_TIPO_RECHAZO 
	INNER JOIN LIQUIDACION l ON l.ID = dw.ID 
	WHERE l.RUT = @RUT AND l.FECHA = @FECHA AND l.EMPRESA = @EMPRESA
END
