CREATE PROCEDURE [dbo].[V4MVC_DOCS_WORKERS_SELECT_FUNCIONARIOS_CTTA]
(
  @RUT	NVARCHAR(10) = NULL
) AS
BEGIN
	DECLARE @ID_DOC INT = 18; /*FINIQUITO*/
	DECLARE @PRIM_FILTERED_ID INT

	SELECT
		TOP 1
		@PRIM_FILTERED_ID = DW.ID_DOCS_WORKERS
	FROM DOCS_WORKERS DW
	INNER JOIN A024_DIVISIONES D
		ON D.DIVCOD = DW.DIVISION
	WHERE
		(DW.RUT = @RUT) AND
		(DW.ID_DOC = @ID_DOC) AND
		(DW.VALIDADO = 'RE')
	ORDER BY DW.ID_DOCS_WORKERS DESC

	SELECT 
		DW.EMPRESA,
		DW.FECHA_MOD,
		DW.HORA_MOD,
		DW.USUARIO,
		DW.ID,
		DW.VALIDADO,
		DW.CERTFECHA,
		DW.CERTHORA,
		DW.CERTUSUARIO,
		DW.FECHASUBE,
		DW.HORASUBE,
		DW.DIVISION,
		D.GLOSA AS NOMDIVISION,
		DW.RUT,
		IIF(DW.VALIDADO = 'RE' AND DW.ID_DOCS_WORKERS = @PRIM_FILTERED_ID,
			 [dbo].[V4MVC_FGET_MSG_AGREGADO_RECHAZO](DW.ID), '') AS REC_MSG
	FROM DOCS_WORKERS DW
	INNER JOIN A024_DIVISIONES D
		ON D.DIVCOD = DW.DIVISION
	WHERE
		(DW.RUT = @RUT) AND 
		(DW.ID_DOC = @ID_DOC)
	ORDER BY DW.ID_DOCS_WORKERS DESC
END

