CREATE PROCEDURE [dbo].[V4MVC_COMPROBANTE_SUELDO_SELECT_ONE_V2_CONTROLLABORAL_CTTA]
(
  @IDEMPRESA	NVARCHAR(10)
 ,@PERIODO		NVARCHAR(6)
) AS
BEGIN
	SELECT
		CERTUSUARIO,
		CERTFECHA,
		CERTHORA,
		VALIDADO
	FROM COMPROBANTE_SUELDO
	WHERE
		EMPRESA = @IDEMPRESA AND
		PERIODO = @PERIODO
END
