  
CREATE PROCEDURE [dbo].[V4MVC_APROBACION_SUBCONTRATOS_SELECT_PENDIENTES]
(@IDEMPRESA		NVARCHAR(11) = NULL)
AS
BEGIN
	SELECT	 A.EMPRESA	, A.OST			, A.FINICIO	, A.FTERMINO
			,A.MONTO	, A.DOTACION	, A.ID		, E.ACRONIMO
			,A.NIVEL    , A.MADRE
	FROM APROBACION_SUBCONTRATOS AS A 
	INNER JOIN ENTERPRISE AS E ON E.IDEMPRESA = A.EMPRESA 
	WHERE ISNULL(ADM_VALIDA,'')='' 
	AND A.MADRE = @IDEMPRESA 
END
