CREATE PROCEDURE [dbo].[V4MVC_LOTEPASES_SELECT_ONE_PASES_CTTA]
(
  @LOTENUM	INT = NULL
) AS
BEGIN
	DECLARE @CURR_FECHA NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 112) /* yyyymmdd */
	DECLARE @NOMBRES NVARCHAR(50) = ''
	DECLARE @APELLIDOS NVARCHAR(50) = ''
	DECLARE @WNOM NVARCHAR(100) = ''
	DECLARE @WOST NVARCHAR(20) = ''
	DECLARE @WEMAIL NVARCHAR(50) = ''
	DECLARE @WADMIN NVARCHAR(10) = ''
	DECLARE @QUERY_AUT_EXISTS BIT = 0


	SELECT
		DISTINCT
			@QUERY_AUT_EXISTS = 1,
			@WOST = LPF.OSTLT,
			@WEMAIL = L.LOTEEMAIL,
			@NOMBRES = W.NOMBRES,
			@APELLIDOS = W.APELLIDOS,
			@WADMIN = A.ADMRUT
		FROM LOTEPASES L
		INNER JOIN A024_DIVISIONES D
			ON L.DIVISION = D.DIVCOD, LOTEPASESFUN AS LPF, OST AS O
		INNER JOIN OSTDIVLOCAL AS OA
			ON O.NROOST = OA.OST, ADMIN AS A
		INNER JOIN WORKERS W
			ON A.ADMRUT = W.RUT
		WHERE
			L.LOTENUM = @LOTENUM AND
			L.LOTENUM = LPF.NLOTEPROC AND
			L.LOTEEMAIL = A.ADMEMAIL AND
			LPF.OSTLT = O.NROOST AND
			O.FECTERM >= @CURR_FECHA AND
			OA.ACTIVO = 'SI'

		IF(@QUERY_AUT_EXISTS = 1)
			BEGIN
				SET @WNOM = CONCAT(@NOMBRES, ' ', @APELLIDOS)
			END

	SELECT
			SS.LOTENUM,
			SS.LOTEFECHA,
			SS.LOTEESTADO,
			SS.LOTEFINICIO,
			SS.LOTEFFINAL,
			SS.LOTEGLOSA,
			SS.DIVCOD,
			SS.DIVISION,
			SS.OSTLT,
			SS.LOTEEMAIL,
			SS.ADMRUT,
			SS.NOMBRES,
			SS.APELLIDOS,
			SS.FECINICIO,
			SS.FECTERM,
			SS.DESCRIPOST,
			SS.RUTLOTE,
			SS.NOMBRESLT,
			SS.TIPOLT,
			SS.TIPO_PASE,
			SS.ACRONIMO,
			SS.DESC_ESTADO,
			(
			  CASE
				WHEN @QUERY_AUT_EXISTS = 1 THEN @WOST
				ELSE SS.OSTLT END
			) AS W_OST,
			(
			  CASE
				WHEN @QUERY_AUT_EXISTS = 1 THEN @WNOM
				ELSE CONCAT(SS.NOMBRES, ' ', SS.APELLIDOS) END
			) AS W_NOMBRES,
			(
			  CASE
				WHEN @QUERY_AUT_EXISTS = 1 THEN @WEMAIL
				ELSE SS.LOTEEMAIL END
			) AS W_EMAIL,
			(
			  CASE
				WHEN @QUERY_AUT_EXISTS = 1 THEN @WADMIN
				ELSE SS.ADMRUT END
			) AS W_ADMIN,

			(SELECT COUNT(TIPORUT) FROM LOTEPASESFUN WHERE NLOTEPROC = @LOTENUM AND TIPORUT = 'FUNCIONARIO') AS FUN,
			(SELECT COUNT(TIPORUT) FROM LOTEPASESFUN WHERE NLOTEPROC = @LOTENUM AND TIPORUT = 'EMPRESA') AS EMP,
			(SELECT COUNT(TIPORUT) FROM LOTEPASESFUN WHERE NLOTEPROC = @LOTENUM AND TIPORUT = 'VEHICULO') AS VEH,
			(SELECT COUNT(TIPORUT) FROM LOTEPASESFUN WHERE NLOTEPROC = @LOTENUM) AS TOD
	FROM
	(
		SELECT
			DISTINCT
			L.LOTENUM,
			L.LOTEFECHA,
			L.LOTEESTADO,
			L.LOTEFINICIO,
			L.LOTEFFINAL,
			L.LOTEGLOSA,
			D.DIVCOD,
			D.DIVISION,
			LPF.OSTLT,
			L.LOTEEMAIL,
			A.ADMRUT,
			W.NOMBRES,
			W.APELLIDOS,
			O.FECINICIO,
			O.FECTERM,
			O.DESCRIPOST,
			LPF1.RUTLOTE,
			LPF1.NOMBRESLT,
			LPF1.TIPOLT,
			COALESCE(
				(
					SELECT TOP 1 LPF.TIPOLT
					FROM LOTEPASESFUN LPF
					WHERE (LPF.NLOTEPROC = L.LOTENUM) AND (LPF.TIPORUT = 'EMPRESA')
				), ''
			) AS TIPO_PASE,
			COALESCE(
				(
					SELECT TOP 1 LPF2.NOMBRESLT
					FROM LOTEPASESFUN LPF2
					WHERE (LPF2.NLOTEPROC = L.LOTENUM) AND (LPF2.TIPORUT = 'EMPRESA')
				), ''
			) AS ACRONIMO,
			COALESCE(
				(
					SELECT TOP 1 TEP.DESC_ESTADO
					FROM TAB_ESTADO_PASE TEP
					WHERE TEP.ESTADO_PASE = L.LOTEESTADO
				), L.LOTEESTADO
			) AS DESC_ESTADO

		FROM LOTEPASES L 
		INNER JOIN (SELECT RUTLOTE, NOMBRESLT, TIPOLT,NLOTEPROC FROM LOTEPASESFUN WHERE TIPORUT = 'EMPRESA') LPF1
			ON LPF1.NLOTEPROC = L.LOTENUM
		INNER JOIN A024_DIVISIONES D
			ON L.DIVISION = D.DIVCOD , LOTEPASESFUN AS LPF, OST AS O, ADMIN AS A 
		INNER JOIN WORKERS W
			ON A.ADMRUT = W.RUT  
		WHERE
			L.LOTENUM = @LOTENUM AND 
			L.LOTENUM = LPF.NLOTEPROC AND 
			L.LOTEEMAIL = A.ADMEMAIL AND 
			LPF.OSTLT = O.NROOST
	) SS
END
