CREATE PROCEDURE [dbo].[V4MVC_DOCS_SELECT_DEPENDENCIA_CTTA]
(@RUT		NVARCHAR(10) = NULL
,@ID_DOC	INT = NULL
,@DIVCOD	NVARCHAR(50) = NULL
,@IDEMPRESA	NVARCHAR(10) = NULL) AS
BEGIN
	SELECT DP.ID_DOC_DEPEND , D.COMUN_DIV , D.NOMBRE, D.COMUN , D.ID_DOC 
		   , CASE WHEN D.COMUN = 0
				THEN (SELECT TOP 1 VALIDADO 
					FROM DOCS_WORKERS 
					WHERE (RUT = @RUT) 
					AND (ID_DOC = DP.ID_DOC_DEPEND) 
					AND (DIVISION = (CASE WHEN D.COMUN_DIV = 'SI' THEN DIVISION ELSE @DIVCOD END )) 
					AND (EMPRESA = @IDEMPRESA)
					ORDER BY FECHASUBE DESC, HORASUBE DESC )
			ELSE
					(SELECT TOP 1 VALIDADO 
					FROM DOCS_WORKERS 
					WHERE (RUT = @RUT) 
					AND (ID_DOC = DP.ID_DOC_DEPEND) 
					AND (DIVISION = (CASE WHEN D.COMUN_DIV = 'SI' THEN DIVISION ELSE @DIVCOD END ))
					ORDER BY FECHASUBE DESC, HORASUBE DESC) 
				END AS VALIDADO
	INTO #TEMP
	FROM DOCS D 
	INNER JOIN DOCS_DEPEND DP ON DP.ID_DOC_DEPEND = D.ID_DOC 
	WHERE DP.ID_DOC = @ID_DOC AND 
	DP.ACTIVO = 'SI' AND 
	DIVISION = @DIVCOD 

	SELECT * FROM #TEMP WHERE VALIDADO <> 'SI'
END
