CREATE PROCEDURE [dbo].[V4MVC_OSTSUBC_SELECT_POLIZAS_CTTA]   
(
@EMPRESA NVARCHAR(10) = NULL
) AS           
BEGIN    
  
	SELECT DISTINCT OST 
	FROM OSTSUBC 
	WHERE (EMPRESA=@EMPRESA OR MADRE= @EMPRESA) 
	AND FTERMINO >= GETDATE() 
	AND AUTOR='SI'
  
END
/****** Object:  StoredProcedure [dbo].[V4MVC_POLIZAS_DELETE_EDITAR_DATATABLE_POLIZAS_CTTA]    Script Date: 9/11/2020 14:49:42 ******/
SET ANSI_NULLS ON
