CREATE PROCEDURE [dbo].[V4MVC_DOCS_TRANSPORT_RECHAZO_SELECT_DISPUTA]
(@ID			UNIQUEIDENTIFIER = NULL) AS
BEGIN

SELECT tr.TIPO_RECHAZO, d.ID_DOC 
FROM DOCS_TRANSPORT_RECHAZO dt 
INNER JOIN DOCS_TIPO_RECHAZO tr ON tr.ID_TIPO_RECHAZO = dt.ID_TIPO_RECHAZO 
INNER JOIN DOCS_TRANSPORT d ON d.ID = dt.ID WHERE dt.ID = @ID
END
