CREATE PROCEDURE [dbo].[V4MVC_INFORME_DOCS_PENDIENTES_EMPRESA_CTTA]
(
 @FECHAINI	NVARCHAR(8)		= NULL
,@FECHAFIN	NVARCHAR(8)		= NULL
,@EMPRESA	NVARCHAR(10)	= NULL
)
AS
BEGIN

	SELECT	 IDEMPRESA		,ACRONIMO		,ID_DOC		,NOMBRE
			,FECHASUBE		,HORASUBE
	FROM	 DOCS_PENDIENTE_EMP
	WHERE	 IDEMPRESA = @EMPRESA
	AND		 FECHASUBE BETWEEN ISNULL(@FECHAINI,FECHASUBE) AND ISNULL(@FECHAFIN,FECHASUBE)	 
	OR		 ISNULL(@FECHAINI,FECHASUBE) IS NULL AND ISNULL(@FECHAFIN,FECHASUBE) IS NULL

END
