CREATE PROCEDURE [dbo].[V4MVC_TAB_TIPOEXSICO_SELECT]
(
 @ID	NUMERIC(18,0) = NULL
)
AS
BEGIN

	SELECT		 ID			,DESCRIPCION	,ACTIVO		,FECHAMOD
				,HORAMOD	,USUARIOMOD		,DURACION

	FROM		TAB_TIPOEXSICO
	WHERE		ID	=  ISNULL(@ID,ID)

END
