CREATE PROCEDURE [dbo].[V4MVC_GETLIQUIDACION_FUNCIONARIOSCTTA]
(@RUT	  NVARCHAR(10) = NULL
,@FECHA	  NVARCHAR(6) = NULL
,@EMPRESA NVARCHAR(10) = NULL) AS
BEGIN
	SELECT RUT, FECHA, NOMBRE_ARCHIVO, TIPO_CONTENIDO, ARCHIVO, FECHASUBE, HORASUBE, USUARIO, VALIDADO, CERTUSUARIO, 
	       CERTFECHA, CERTHORA, IDRECHAZO, ID, IMPONIBLE, LIQUIDO, TRANSFERIDO, EMPRESA, BONOIP, BONOIS, FECHACSV, HORACSV, USUARIOCSV 
	FROM LIQUIDACION 
	WHERE RUT = @RUT AND FECHA = @FECHA AND EMPRESA = @EMPRESA
END
