CREATE PROCEDURE [dbo].[V4MVC_REMUNERACIONES_PROPIO_INSERT_CONTROLLABORAL_CTTA]
(
  @PERIODO		NVARCHAR(6)
 ,@IDEMPRESA	NVARCHAR(10)
 ,@DIVISION		NVARCHAR(4)
 ,@OST			NVARCHAR(20)
 ,@MONTOIMP		INT
 ,@RET_CODE		INT OUTPUT
) AS
BEGIN
	SET @RET_CODE = -1

	IF(EXISTS(
			SELECT
				PERIODO
			FROM REMUNERACIONES_PROPIO
			WHERE
				EMPRESA = @IDEMPRESA AND
				PERIODO = @PERIODO AND
				DIVISION = @DIVISION AND
				OST = @OST
	))
		BEGIN
			SET @RET_CODE = 1  /*ERROR LOGICO; YA EXISTE*/
			RETURN
		END
	INSERT INTO REMUNERACIONES_PROPIO(PERIODO, EMPRESA, DIVISION, OST, MONTOIMP)
	VALUES (@PERIODO, @IDEMPRESA, @DIVISION, @OST, @MONTOIMP)
END
