CREATE PROCEDURE [dbo].[V4MVC_OST_SELECT_CONTROLLABORAL_CTTA]
(
  @IDEMPRESA	NVARCHAR(10)
 ,@PERIODO		NVARCHAR(6)
) AS
BEGIN
	SELECT
		NROOST
	FROM OST
	WHERE
		LEFT(CONVERT(NVARCHAR(8), DATEADD(MM,1,FECTERM),112),6) = @PERIODO AND
		IDEMPRESA = @IDEMPRESA
END
