CREATE PROCEDURE [dbo].[V4MVC_A141_CURSOS_SELECT_CTTA]  
( 
 @ORADOR        NVARCHAR(11) = NULL   
,@IDEMPRESA		NVARCHAR(11) = NULL  
) 
AS  
BEGIN  

	 SELECT DISTINCT	ACUR.CODIGO		,ACUR.FECHA			,ACUR.HORA			,ACUR.LUGAR,   
						ACUR.SALA		,ACUR.CHARLA		,ACUR.CAPACIDAD		,ACUR.CANTIDAD
						,ACUR.CURSO,    ISNULL(ACUR.TIPOCURSO,'PUBLICO') AS TIPOCURSO--,CE.EMPRESA,ACUR.ORADOR  
						,STUFF((SELECT ',' + DP.DIVISION   
									FROM (SELECT DISTINCT D.DIVISION  
									FROM CHARLAS_DIVISION AS CD  
									INNER JOIN A024_DIVISIONES AS D ON D.DIVCOD = CD.DIVISION  
									WHERE  CD.IDCHARLA = ACUR.CURSO  
								) AS DP  
							   ORDER BY DP.DIVISION  
							   FOR XML PATH('')  
							   ), 1, 1, '' ) AS DIVISIONES  
  
	 FROM A141_CURSOS AS ACUR    
	 LEFT JOIN CURSOS_EMPHABILITADAS CE ON ACUR.CODIGO= CE.IDCURSOPROG 
	 AND CE.EMPRESA = @IDEMPRESA  
	 WHERE CASE WHEN (ISNULL(ACUR.TIPOCURSO,'PUBLICO') ='PRIVADO' 
	 AND CE.EMPRESA IS NULL 
	 AND ( ACUR.ORADOR <> @ORADOR OR ACUR.ORADOR IS NULL)) THEN '0' ELSE '1' END <>'0' 
	 AND (FECHA + HORA  >= [dbo].[hoy](GETDATE()) + [dbo].[ahora](GETDATE())) 
	 AND ACUR.ACTIVO='SI' 
 
END
