CREATE PROCEDURE [dbo].[V4MVC_LICENCIAS_SELECT_CONDUCTORES_CTTA]
(@RUT			NVARCHAR(10))AS
BEGIN

	SELECT L.LICENCIAS
		 , L.DESCRIPCION 
		 , CASE WHEN WL.LICENCIAS IS NULL THEN 'false' ELSE 'true' END AS CHECKED
	FROM LICENCIAS AS L
	LEFT JOIN WORKERS_LICENCIAS AS WL ON WL.LICENCIAS = L.LICENCIAS AND WL.RUT = @RUT
	ORDER BY L.LICENCIAS

END

