CREATE PROCEDURE [dbo].[V4MVC_DOCS_WORKERS_SELECT_DATOS_DISPUTA]
(@ID			UNIQUEIDENTIFIER= NULL
,@DIVCOD		NVARCHAR(50) = NULL
,@ID_DISPUTA	INT = NULL) AS
BEGIN
	IF @ID_DISPUTA <= 0
		BEGIN
			SELECT DW.RUT, W.NOMBRES, W.APELLIDOS, V.GLOSA, D.NOMBRE, DW.VALIDADO , D.ID_DOC
			, DW.ID , D.COMUN_DIV , CASE WHEN DW.VALIDADO = 'RE' THEN 'RECHAZADO' WHEN DW.VALIDADO = 'SI' THEN 'VALIDADO' ELSE 'PENDIENTE' END AS DESCVALIDADO
			, 0 AS ID_DISPUTA , D.ID_DOC_OPCION , DW.DIVISION
			FROM DOCS_WORKERS DW 
			INNER JOIN A024_DIVISIONES V ON V.DIVCOD = DW.DIVISION 
			INNER JOIN WORKERS W ON W.RUT = DW.RUT 
			INNER JOIN DOCS D ON D.ID_DOC = DW.ID_DOC 
			WHERE 
			DW.DIVISION = (CASE WHEN D.COMUN_DIV = 'SI' THEN  DW.DIVISION ELSE @DIVCOD END) AND 
			DW.ID = @ID
		END
	ELSE
		BEGIN
			SELECT DW.RUT,D.COMUN_DIV, W.NOMBRES, W.APELLIDOS, V.GLOSA, D.NOMBRE
			, DW.VALIDADO, DW.ID, DW.ID_DOC, DW.DIVISION, DD.ESTADO , D.ID_DOC_OPCION
			, DD.OBSERVACION, DD.OBSERVACION_REVAL, DW.EMPRESA ,DD.ID_DISPUTA , DW.DIVISION
			, CASE WHEN DW.VALIDADO = 'RE' THEN 'RECHAZADO' WHEN DW.VALIDADO = 'SI' THEN 'VALIDADO' ELSE 'PENDIENTE' END AS DESCVALIDADO
			FROM DOCS_WORKERS DW 
			INNER JOIN A024_DIVISIONES V ON V.DIVCOD = DW.DIVISION 
			INNER JOIN WORKERS W ON W.RUT = DW.RUT 
			INNER JOIN DOCS D ON D.ID_DOC = DW.ID_DOC 
			LEFT OUTER JOIN DOCS_DISPUTA DD ON DD.ID = DW.ID 
											AND DD.DIVISION = (CASE WHEN D.COMUN_DIV='SI' THEN DD.DIVISION ELSE DW.DIVISION END) 
											AND DD.RUT = DW.RUT 
											AND DD.ID_DOC = DW.ID_DOC 
											AND DW.EMPRESA = DD.EMPRESA 
			WHERE DD.ID_DISPUTA = @ID_DISPUTA
		END
END

