CREATE PROCEDURE [dbo].[V4MVC_DOCS_FEC_WORKERS_SELECT_BY_ID_DOC_FEC_CTTA]
(
 @RUT					NVARCHAR(10)
,@DIVISION				NVARCHAR(4)
,@EMPRESA				NVARCHAR(10)
,@ID_DOCUMENTO			INT
,@ID_DOC_FEC			INT
,@COMUN					INT
,@VALIDADO_MAYOR_HOY	INT
,@EMPRESACOMUN			INT
)
AS
BEGIN

	DECLARE @QUERY NVARCHAR(MAX) = ''

	SET @QUERY = @QUERY + 'SELECT * FROM DOCS_FEC_WORKERS'
	SET @QUERY = @QUERY + ' WHERE RUT = ''' + @RUT + ''' '
	SET @QUERY = @QUERY + ' AND ID_DOC_FEC = ' + CAST(@ID_DOC_FEC AS VARCHAR) + ' '
	IF(@COMUN = 0) BEGIN SET @QUERY = @QUERY + ' AND DIVISION = ''' + @DIVISION +''' ' END 
	IF(@EMPRESACOMUN = 0) BEGIN SET @QUERY = @QUERY + ' AND EMPRESA = ''' + @EMPRESA + ''' ' END
	IF(@VALIDADO_MAYOR_HOY = 1 OR @ID_DOCUMENTO = 152 OR @ID_DOCUMENTO = 160) BEGIN SET @QUERY = @QUERY + ' AND FECHA >= ''' + DBO.HOY(GETDATE()) + ''' ' END

	PRINT(@QUERY)

END
