CREATE PROCEDURE [dbo].[V4MVC_LOTEPASESFUN_DELETE_PASES_CTTA]
( 
  @PASE_ID		INT
 ,@RUT			NVARCHAR(10)
) AS 
BEGIN
	DELETE
	FROM LOTEPASESFUN
	WHERE
		NLOTEPROC = @PASE_ID AND
		RUTLOTE = @RUT AND
		TIPORUT = 'FUNCIONARIO'
END


