CREATE PROCEDURE [dbo].[V4MVC_WORKERS_DATATABLES_ENTERPRISE_CTTA]                
(             
@IDEMPRESA			NVARCHAR(10)	= NULL,
@IDISPLAYSTART		INT				= NULL,              
@IDISPLAYLENGTH		INT				= NULL,              
@SEARCH_RUT			NVARCHAR(10)	= NULL,        
@SEARCH_NOMBRES		NVARCHAR(50)	= NULL,        
@SEARCH_APELLIDOS	NVARCHAR(50)	= NULL,     
@SORT_COLUMN		NVARCHAR(4)		= NULL,        
@SORT_DIRECTION		NVARCHAR(4)		= NULL        
) AS                
BEGIN            

	DECLARE @QUERY NVARCHAR(MAX)
	SET @QUERY  = 'SELECT DISTINCT W.RUT, W.NOMBRES, W.APELLIDOS, WL.EMPRESA, E.ACRONIMO              
	FROM WORKERS W
	INNER JOIN WORKERSLOCAL WL ON WL.RUT = W.RUT
	INNER JOIN ENTERPRISE E ON E.IDEMPRESA = WL.EMPRESA 
	WHERE WL.EMPRESA = ''' + @IDEMPRESA +''' AND (WL.AUTOR IN (''SI'',''NO'') OR WL.AUTOR IS NULL)'
	
	IF @SEARCH_RUT IS NOT NULL BEGIN SET @QUERY = @QUERY + ' AND W.RUT LIKE ' + '''%' + @SEARCH_RUT + '%''' END
	IF @SEARCH_NOMBRES IS NOT NULL BEGIN SET @QUERY = @QUERY + ' AND W.NOMBRES LIKE ' + '''%' + @SEARCH_NOMBRES + '%''' END
	IF @SEARCH_APELLIDOS IS NOT NULL BEGIN SET @QUERY = @QUERY + ' AND W.APELLIDOS LIKE ' + '''%' + @SEARCH_APELLIDOS + '%''' END
	
	     
	IF @SORT_COLUMN='0' BEGIN SET @QUERY = @QUERY + ' ORDER BY W.NOMBRES, W.APELLIDOS ' +  @SORT_DIRECTION END   
	IF @SORT_COLUMN='1' BEGIN SET @QUERY = @QUERY + ' ORDER BY NOMBRES ' + @SORT_DIRECTION END   
	IF @SORT_COLUMN='2' BEGIN SET @QUERY = @QUERY + ' ORDER BY APELLIDOS '  + @SORT_DIRECTION END 
	
	SET @QUERY = @QUERY + ' OFFSET ' + CAST(@IDISPLAYSTART AS VARCHAR) + ' ROWS FETCH NEXT ' + CAST(@IDISPLAYLENGTH AS VARCHAR) + ' ROWS ONLY'

	EXEC(@QUERY)
	--PRINT(@QUERY)

END   


--EXEC V4MVC_WORKERS_DATATABLES_ENTERPRISE_CTTA '761264907',10,10,NULL,NULL,NULL,0,'ASC'


--SELECT DISTINCT W.RUT, W.NOMBRES, W.APELLIDOS, WL.EMPRESA, E.ACRONIMO              
--	FROM WORKERS W
--	INNER JOIN WORKERSLOCAL WL ON WL.RUT = W.RUT
--	INNER JOIN ENTERPRISE E ON E.IDEMPRESA = WL.EMPRESA 
--	WHERE WL.EMPRESA = '761264907' 
--	AND (WL.AUTOR IN ('SI','NO') OR WL.AUTOR IS NULL) 
--	ORDER BY W.NOMBRES, W.APELLIDOS ASC 
--	OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
