
CREATE PROCEDURE [dbo].[V4MVC_WORKERS_EXISTENOMINA_CTTA]
( @RUT	NVARCHAR(10) = NULL )
AS
BEGIN

	SELECT TOP 1 WL.RUT, W.NOMBRES, W.APELLIDOS, WL.EMPRESA
			   , E.ACRONIMO, WL.FINIPASE, WL.FFINPASE 
	FROM WORKERSLOCAL WL 
	INNER JOIN WORKERS W ON WL.RUT = W.RUT
	INNER JOIN ENTERPRISE E ON WL.EMPRESA = E.IDEMPRESA
	WHERE WL.RUT = @RUT
	AND WL.FFINPASE >= DBO.HOY(GETDATE())
	AND WL.AUTOR <> 'BL'
	AND WL.EMPRESA NOT IN ('999999999')
	ORDER BY WL.LOTE DESC 
	
END