CREATE PROCEDURE [dbo].[V4MVC_WORKERS_ZONA_PASE_DELETE_PASES_CTTA]
(
  @ID_PASE					INT
 ,@RUT						NVARCHAR(10)
 ,@CS_LOCALES_EXISTENTES	NVARCHAR(MAX)
) AS 
BEGIN
	DELETE
	FROM WORKERS_ZONA_PASE
	WHERE
		LOTENUM = @ID_PASE AND
		RUT = @RUT AND
		CHARINDEX(@CS_LOCALES_EXISTENTES, CONCAT('#', LOCAL, '#')) <= 0
END


