CREATE PROCEDURE [dbo].[V4MVC_A056_FORM301_DET_SELECT_CONTROLLABORAL_CTTA]
(
  @EMPRESA			NVARCHAR(10)
 ,@ID_CERTIFICADO	NVARCHAR(10)
) AS
BEGIN
	SELECT
		PERIODO,
		NRO_TRAB_PAG,
		MONTO_PAGADO,
		NRO_TRAB_NOPAG
	FROM A056_FORM301_DET
	WHERE
		(EMPRESA = @EMPRESA) AND
		(ID_CERTIFICADO = @ID_CERTIFICADO )
	ORDER BY PERIODO
END
