CREATE PROCEDURE [dbo].[V4MVC_DOCS_WORKERS_SELECT_HISTORICO_DOCUMENTOS_CTTA]
(@RUT		NVARCHAR(10) = NULL
,@ID_DOC	INT = NULL
,@DIVCOD	NVARCHAR(50) = NULL
,@COMUN_DIV	NVARCHAR(2) = NULL
,@COMUN		INT = NULL
,@IDEMPRESA	NVARCHAR(10) = NULL) AS
BEGIN
	IF @COMUN = 0
		BEGIN
			SELECT E.ACRONIMO AS EMPRESA, DW.FECHA_MOD, DW.HORA_MOD, DW.USUARIO, DW.ID, DW.VALIDADO, DW.CERTFECHA, DW.CERTHORA, DW.CERTUSUARIO, DW.FECHASUBE, DW.HORASUBE 
			FROM DOCS_WORKERS AS DW
			LEFT JOIN ENTERPRISE AS E ON E.IDEMPRESA = DW.EMPRESA
			WHERE (DW.RUT = @RUT) AND 
			(DW.ID_DOC = @ID_DOC) AND 
			(DW.DIVISION = (CASE WHEN @COMUN_DIV = 'SI' THEN DW.DIVISION ELSE @DIVCOD END)) AND 
			(DW.EMPRESA = @IDEMPRESA) 
			ORDER BY ID_DOCS_WORKERS DESC
		END
	ELSE
		BEGIN 
			SELECT E.ACRONIMO AS EMPRESA, DW.FECHA_MOD, DW.HORA_MOD, DW.USUARIO, DW.ID, DW.VALIDADO, DW.CERTFECHA, DW.CERTHORA, DW.CERTUSUARIO, DW.FECHASUBE, DW.HORASUBE 
			FROM DOCS_WORKERS AS DW
			LEFT JOIN ENTERPRISE AS E ON E.IDEMPRESA = DW.EMPRESA
			WHERE (DW.RUT = @RUT) AND 
			(DW.ID_DOC = @ID_DOC) AND 
			(DW.DIVISION = (CASE WHEN @COMUN_DIV = 'SI' THEN DW.DIVISION ELSE @DIVCOD END))
			ORDER BY ID_DOCS_WORKERS DESC
		END
END

