CREATE PROCEDURE [dbo].[V4MVC_POLIZAS_SELECT_EDITAR_DATATABLE_POLIZAS_CTTA]
(
  @IDDOC INT            = NULL
, @DIVISION NVARCHAR(4) = NULL
) AS
BEGIN

    DECLARE @strSQL as nvarchar(MAX)
	SET @strSQL= 'SELECT  T1.NROPOLIZA,					T1.IDDOC,			T1.FECINI,				T1.FECFIN,
						  T1.EMPRESA,					T1.DIVISION,		T1.ID,					T1.VALIDADO,
						  T1.CERTFECHA,					T1.CERTHORA,		T1.CERTUSUARIO,			T1.OBSERVACION,
						  ISNULL(T1.OST,'''') AS OST,	T1.USUARIOMOD,		T2.NOMBRE,				T3.ACRONIMO,
						  STUFF((
								SELECT ' + '''' + ',' + '''' + ' + ' + ' DOCS_EXT.EXTENSION
								FROM DOCS_FORMATO, DOCS_EXT 
								WHERE 
								(DOCS_FORMATO.ID_DOC = T1.IDDOC) AND
								(DOCS_FORMATO.ID_DOC_EXT = DOCS_EXT.ID_DOC_EXT)
								FOR XML PATH('''')
								),1,1, '''') AS EXTENSIONES
	FROM POLIZAS T1
	INNER JOIN DOCS T2 ON T1.IDDOC = T2.ID_DOC
	INNER JOIN ENTERPRISE T3 ON T1.EMPRESA = T3.IDEMPRESA
	WHERE T1.IDDOC= ''' + CONVERT(VARCHAR(10),@IDDOC) + ''' '
  

	IF @DIVISION <> '' OR @DIVISION <> NULL
	BEGIN
	 SET @strSQL = @strSQL + N' AND T1.DIVISION = ''' + @DIVISION + ''''
	END
 
	SET @strSQL = @strSQL + N' ORDER BY T1.FECFIN DESC, T1.VALIDADO'
	EXEC sp_executesql @strSQL  

END