CREATE PROCEDURE [dbo].[V4MVC_WORKERS_SELECT_DATOSPERSONALES_CTTA]    
(    
 @IDEMPRESA	NVARCHAR(10) = NULL    
,@RUT		NVARCHAR(10) = NULL    
)    
AS    
BEGIN    
    
	SELECT	 Rut AS RUT		,NOMBRES		,APELLIDOS			,Correo_Electronico  AS EMAIL  
			,CELULAR		,FONO			,FONOHELP			,PAIS  
			,REGION			,CIUDAD			,COMUNA				,ZONA    
			,DIRECCION    
	FROM [A007_USER_EC]    
	WHERE IdEmpresa = @IDEMPRESA   
	AND Rut = @RUT 
    
END
