CREATE PROCEDURE [dbo].[V4MVC_TIMELINE_SELECT_CONTROLLABORAL_CTTA]
AS
BEGIN
	SELECT
		DIAMES,
		DESCRIPCION,
		AUTHOR,
		ESPACIOATRAS,
		ESPACIODELANTE,
		DATEPART(DAY, GETDATE()) AS DIAHOY,
		DATENAME(MONTH, GETDATE()) AS MESHOY
	FROM TIMELINE
	ORDER BY DIAMES
END
