CREATE PROCEDURE [dbo].[V4MVC_APROBACION_SUBCONTRATOS_SELECT_ENPROCESO]    
(@IDEMPRESA  NVARCHAR(11) = NULL)    
AS    
BEGIN    
 SELECT  A.EMPRESA			,A.OST				,A.FINICIO											,A.FTERMINO  
   ,A.MONTO					,A.DOTACION			,A.ID												,E.ACRONIMO  
   ,A.NIVEL					,A.VALIDADO			,ISNULL(ADM_VALIDA_ESTADO,'NO') ADM_VALIDA_ESTADO	,ISNULL(ADM_SUPCHAIN_ESTADO,'NO')  ADM_SUPCHAIN_ESTADO
   ,ISNULL(ADM_GSEGURIDAD_ESTADO,'NO') ADM_GSEGURIDAD_ESTADO
 FROM APROBACION_SUBCONTRATOS A   
 INNER JOIN ENTERPRISE E ON E.IDEMPRESA = A.EMPRESA  
 WHERE ISNULL(A.ADM_VALIDA,'')<>'' AND ISNULL(A.ADM_GSEGURIDAD_VALIDA,'')='' AND A.MADRE=@IDEMPRESA  

 
END