CREATE PROCEDURE [dbo].[V4MVC_POLIZAS_PAGO_DELETE_DATATABLE_POLIZAS_CTTA]
(
  @ID INT               = NULL
, @NROPOLIZA NVARCHAR(50)  = NULL
, @USUARIOMOD NVARCHAR(10) = NULL
, @EXITOSO BIT  OUTPUT
, @MENSAJE NVARCHAR(500) OUTPUT
) AS
BEGIN
 BEGIN TRANSACTION;
    SAVE TRANSACTION ELIMINACION_POLIZA;

    BEGIN TRY
	--ELIMINA PAGO
	INSERT INTO POLIZAS_PAGO_DEL (NROPOLIZA			,IDDOC					,PERINI						,PERFIN
								 ,IDPAGO			,VALIDADO				,CERTFECHA					,CERTHORA
								 ,CERTUSUARIO		, OBSERVACION			,USUARIOMOD					,FECHAMOD
								 ,HORAMOD			,FECHADEL				,HORADEL					,USUARIODEL) 
						   SELECT NROPOLIZA			,IDDOC					,PERINI						,PERFIN
								 ,IDPAGO			,VALIDADO				,CERTFECHA					,CERTHORA
								 ,CERTUSUARIO		,OBSERVACION			,USUARIOMOD					,FECHAMOD
								 ,HORAMOD			,[dbo].[hoy](GETDATE())	,[dbo].[ahora](GETDATE())	,@USUARIOMOD 
						   FROM POLIZAS_PAGO WHERE ID=@ID 

	DELETE FROM POLIZAS_PAGO WHERE ID=@ID 
			
        COMMIT TRANSACTION 
		SET @EXITOSO = 1																													
		SET @MENSAJE = 'EXITOSO'
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
        BEGIN
            ROLLBACK TRANSACTION ELIMINACION_POLIZA;
			SET @EXITOSO = 0																													
			SET @MENSAJE = 'Ocurrio un error'
        END
    END CATCH

END
