CREATE PROCEDURE [dbo].[V4MVC_DIVISIONES_SELECT_PASES_CTTA]  
(  
 @IDEMPRESA		NVARCHAR(10)  
)  
AS  
BEGIN
	DECLARE @CURR_FECHA NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 112) /* yyyymmdd */
	SELECT
		DIVISION,
		DIVCOD
	FROM A024_DIVISIONES
	WHERE DIVCOD IN(
					SELECT OS.DIVISION
					FROM OSTDIVLOCAL OS, OSTSUBC OSC, OST
					WHERE
						OSC.EMPRESA = @IDEMPRESA AND
						OST.NROOST = OS.OST AND
						OST.FECTERM >= @CURR_FECHA AND
						OSC.OST = OST.NROOST 
					GROUP BY OS.DIVISION)
END
