CREATE PROCEDURE [dbo].[V4MVC_DOCS_CONTROLACCESO_LABORAL_SELECT_DISPUTA_FUNCIONARIOSCTTA]
(@RUT		    NVARCHAR(10) = NULL 
,@FECHA_INI		NVARCHAR(8) = NULL 
,@FECHA_FIN	    NVARCHAR(8) = NULL 
,@ID_DOC	INT = NULL) AS
BEGIN

SELECT L.RUT, L.FECHA_INI, L.FECHA_FIN, W.NOMBRES, W.APELLIDOS, D.NOMBRE, L.VALIDADO, L.ID_ARCHIVO ,L.EMPRESA, L.ID_DOC
FROM DOCS_CONTROLACCESO_LABORAL L INNER JOIN WORKERS W ON W.RUT = L.RUT 
                                  INNER JOIN DOCS D ON D.ID_DOC = L.ID_DOC 
WHERE L.RUT = @RUT AND L.FECHA_INI = @FECHA_INI AND L.FECHA_FIN = @FECHA_FIN AND L.ID_DOC = @ID_DOC
END
