CREATE PROCEDURE [dbo].[V4MVC_DOCS_TRANSPORT_INSERT_HISTORICO_VEHICULULOSCTTA]
( @PATENTE nvarchar(10)= NULL
 ,@NOMBRE_ARCHIVO nvarchar(50)= NULL
 ,@TIPO_CONTENIDO nvarchar(20)= NULL
 ,@EMPRESA nvarchar(20)= NULL
 ,@DIVISION nvarchar(4)= NULL
 ,@ID_DOC int= NULL
 ,@USUARIO nvarchar(10)= NULL
 ,@ID uniqueidentifier= NULL
 ,@COMBUSTIBLE  int= NULL
 ,@CILINDRADA  nvarchar(50)= NULL
 ,@TRACCION  int= NULL
 ,@COLOR nvarchar(30)= NULL
 ,@POTENCIA nvarchar(50)= NULL) AS
BEGIN



INSERT INTO DOCS_TRANSPORT ( PATENTE,    NOMBRE_ARCHIVO,    TIPO_CONTENIDO,    EMPRESA,    DIVISION,    ID_DOC,   FECHA_MOD,                HORA_MOD,                 USUARIO,       ID,   VALIDADO,  FECHASUBE,              HORASUBE) 
                    VALUES ( @PATENTE,   @NOMBRE_ARCHIVO,   @TIPO_CONTENIDO,   @EMPRESA,   @DIVISION,   @ID_DOC,  [dbo].[hoy](GETDATE()),   [dbo].[ahora](GETDATE()), @USUARIO,      @ID,  'NO',      [dbo].[hoy](GETDATE()), [dbo].[ahora](GETDATE()))




IF @ID_DOC = 11 
BEGIN
  UPDATE TRANSPORT 
  SET COMBUSTIBLE = @COMBUSTIBLE,
      CILINDRADA = @CILINDRADA,
      TRACCION = @TRACCION, 
      COLOR = @COLOR
  WHERE PATENTE =@PATENTE
END
ELSE IF @ID_DOC = 14
BEGIN
	UPDATE TRANSPORT 
	SET POTENCIA =@POTENCIA 
	WHERE PATENTE = @PATENTE
END

END



