CREATE PROCEDURE [dbo].[V4MVC_DOCS_FEC_SELECT_FECHASDOC_CTTA]
(@RUT			NVARCHAR(10) = NULL
,@ID_DOC		INT = NULL
,@DIVCOD		NVARCHAR(20) = NULL
,@IDEMPRESA		NVARCHAR(11) = NULL
) AS
BEGIN
	SELECT DISTINCT DF.ID_DOC_FEC
		 , DF.NOMBRE
		 , DF.ID_DOC_DEPEND
		 , (CASE WHEN EXISTS(SELECT DFT.TIPOPASE 
						FROM DOCS_FEC_TIPOPASE AS DFT WHERE DFT.ID_DOC_FEC = DF.ID_DOC_FEC AND (DFT.DIVISION = @DIVCOD))
					  THEN 'OBLIGATORIO' ELSE '' END) AS TIPOPASE
		 , DF.VALIDO_MAYOR_HOY
		 , '19000101' AS FECHA 
		 , [dbo].[hoy](GETDATE()) AS FECHAHOY
	INTO #TEMP
	FROM DOCS_FEC AS DF
	WHERE (DF.ID_DOC_DEPEND = @ID_DOC) AND 
	(DF.ACTIVO = 'SI') 

	DECLARE @ID_DOC_FEC			INT,
			@NOMBRE				NVARCHAR(100),
			@FECHA				NVARCHAR(8)
	DECLARE Fechas_DocsCtta CURSOR FOR
	SELECT ID_DOC_FEC , NOMBRE , FECHA    FROM #TEMP 
	OPEN Fechas_DocsCtta

	FETCH Fechas_DocsCtta INTO    @ID_DOC_FEC , @NOMBRE , @FECHA 

	WHILE (@@FETCH_STATUS = 0 )
		BEGIN

			DECLARE @EMP_COMUN INT
			DECLARE @DIV_COMUN INT
			SELECT @EMP_COMUN = D.COMUN 
				, @DIV_COMUN = DF.COMUN 
			FROM DOCS_FEC AS DF 
			INNER JOIN DOCS AS D ON DF.ID_DOC_DEPEND = D.ID_DOC 
			WHERE (DF.ID_DOC_FEC = @ID_DOC_FEC)

			DECLARE @VAL_FECHA NVARCHAR(8) = ''
				
					IF(@EMP_COMUN = 0)
						BEGIN
							IF(@DIV_COMUN =0)
								BEGIN
									SELECT TOP 1 @VAL_FECHA = FECHA 
									FROM DOCS_FEC_WORKERS 
									WHERE (RUT = @RUT) AND 
									(ID_DOC_FEC = @ID_DOC_FEC) AND 
									(DIVISION = @DIVCOD) AND 
									(EMPRESA = @IDEMPRESA)
									ORDER BY FECHA DESC
								END
							ELSE
								BEGIN
									SELECT TOP 1 @VAL_FECHA = FECHA 
									FROM DOCS_FEC_WORKERS 
									WHERE (RUT = @RUT) AND 
									(ID_DOC_FEC = @ID_DOC_FEC) AND 
									(EMPRESA = @IDEMPRESA)
									ORDER BY FECHA DESC
								END
						END
					ELSE
						BEGIN
							IF(@DIV_COMUN =0)
								BEGIN
									SELECT TOP 1 @VAL_FECHA = FECHA 
									FROM DOCS_FEC_WORKERS 
									WHERE (RUT = @RUT) AND 
									(ID_DOC_FEC = @ID_DOC_FEC) AND 
									(DIVISION = @DIVCOD)
									ORDER BY FECHA DESC
								END
							ELSE
								BEGIN
									SELECT TOP 1 @VAL_FECHA = FECHA 
									FROM DOCS_FEC_WORKERS 
									WHERE (RUT = @RUT) AND 
									(ID_DOC_FEC = @ID_DOC_FEC)
									ORDER BY FECHA DESC
								END
						END
				
			UPDATE #TEMP SET FECHA = @VAL_FECHA
							, VALIDO_MAYOR_HOY = ISNULL((SELECT VALIDO_MAYOR_HOY FROM DOCS_FEC WHERE (ID_DOC_FEC = @ID_DOC_FEC)),0)
			WHERE ID_DOC_FEC = @ID_DOC_FEC

			FETCH Fechas_DocsCtta INTO @ID_DOC_FEC , @NOMBRE , @FECHA 
		END
	CLOSE Fechas_DocsCtta
	DEALLOCATE Fechas_DocsCtta

	SELECT *  FROM #TEMP
	
END
