CREATE PROCEDURE [dbo].[V4MVC_WORKERS_ZONA_PASE_UPSERT_PASES_CTTA]
(
  @ID_PASE			INT
 ,@RUT			    NVARCHAR(10)
 ,@LOCAL			NVARCHAR(12)
 ,@IDEMPRESA		NVARCHAR(10)
 ,@USUARIO			NVARCHAR(10)
) AS 
BEGIN
	DECLARE @CURR_FECHA NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 112) /* yyyymmdd */
	DECLARE @CURR_TIEMPOFULL NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 108) /* hh:mm:ss */

	IF(EXISTS(
		SELECT *
		FROM WORKERS_ZONA_PASE WZP
		WHERE
			WZP.LOTENUM = @ID_PASE AND
			WZP.RUT = @RUT AND
			WZP.EMPRESA = @IDEMPRESA AND
			WZP.LOCAL = @LOCAL
	))
		BEGIN
			UPDATE WORKERS_ZONA_PASE
			SET
				FECHAMOD = @CURR_FECHA,
				HORAMOD = @CURR_TIEMPOFULL,
				USUARIOMOD = @USUARIO
			WHERE
				LOTENUM = @ID_PASE AND
				RUT = @RUT AND
				EMPRESA = @IDEMPRESA AND
				LOCAL = @LOCAL
		END
	ELSE
		BEGIN
			INSERT INTO WORKERS_ZONA_PASE
			(
			  LOTENUM, RUT, EMPRESA, LOCAL, FECHACREACION, HORACREACION,
			  USUARIOCREACION, FECHAMOD, HORAMOD, USUARIOMOD)
			VALUES
			(
			  @ID_PASE, @RUT, @IDEMPRESA, @LOCAL, @CURR_FECHA,
			  @CURR_TIEMPOFULL, @USUARIO, @CURR_FECHA, @CURR_TIEMPOFULL, @USUARIO)
		END
END


