CREATE PROCEDURE [dbo].[V4MVC_A056_FORM30_INSERT_CONTROLLABORAL_CTTA]
(
  @PERIODO			NVARCHAR(6)
 ,@IDEMPRESA		NVARCHAR(10)
 ,@INSPECCION		NVARCHAR(4)
 ,@ANIO				INT
 ,@CERTIFICADO		BIGINT
 ,@USUARIO			NVARCHAR(10)
 ,@CLAVE			NVARCHAR(30)
 ,@REGION			NVARCHAR(3)
 ,@VIGENCIA			NVARCHAR(8)
 ,@MULT_NEJ			INT
 ,@MULT_EJ			INT
 ,@SANC_6M			INT
 ,@SANC_12M			INT
 ,@DP_NRO			INT
 ,@DP_MTO_UTM		FLOAT
 ,@DP_MTO_PESO		INT
 ,@RM_NRO			INT
 ,@RM_MTO_PESO		INT
 ,@RET_CODE			INT OUTPUT
) AS
BEGIN
	DECLARE @CURR_FECHA NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 112) /* yyyymmdd */
	DECLARE @CURR_TIEMPOFULL NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 108) /* hh:mm:ss */
	
	SET @RET_CODE = -1

	IF(EXISTS(
			SELECT
				*
			FROM A056_FORM30
			WHERE
				EMPRESA = @IDEMPRESA AND
				PERIODO = @PERIODO AND
				INSPECCION = @INSPECCION AND
				ANIO = @ANIO AND
				CERTIFICADO = @CERTIFICADO
	))
		BEGIN
			SET @RET_CODE = 1  /*ERROR LOGICO; YA EXISTE*/
			RETURN
		END
	
	INSERT INTO A056_FORM30
			(
				EMPRESA,
				REGION,
				INSPECCION,
				ANIO,
				CERTIFICADO,
				CLAVE,
				VIGENCIA,
				MULT_NEJ,
				MULT_EJ,
				SANC_6M,
				SANC_12M,
				DP_NRO,
				DP_MTO_UTM,
				DP_MTO_PESO,
				RM_NRO,
				RM_MTO_PESO,
				FECHAMOD,
				HORAMOD,
				QUIEN,
				ID,
				PERIODO,
				VALIDADO,
				USUARIO,
				FECHASUBE,
				HORASUBE
			)
	VALUES
			(
				@IDEMPRESA,
				@REGION,
				@INSPECCION,
				@ANIO,
				@CERTIFICADO,
				@CLAVE,
				@VIGENCIA,
				@MULT_NEJ,
				@MULT_EJ,
				@SANC_6M,
				@SANC_12M,
				@DP_NRO,
				@DP_MTO_UTM,
				@DP_MTO_PESO,
				@RM_NRO,
				@RM_MTO_PESO,
				@CURR_FECHA,
				@CURR_TIEMPOFULL,
				@USUARIO,
				NULL,
				@PERIODO,
				'NO',
				@USUARIO,
				@CURR_FECHA,
				@CURR_TIEMPOFULL
			)
END
