CREATE PROCEDURE [dbo].[V4MVC_A400_AUDITORIA_SELECT_ONE_CONTROLLABORAL_CTTA]
(
  @EMPRESA	NVARCHAR(20)  = ''
 ,@PERIODO	NVARCHAR(6)   = ''
 ,@DIVISION	NVARCHAR(2)   = ''
 ,@OST		NVARCHAR(20)  = ''
 ,@IDDOC	INT			  = 0
) AS
BEGIN
	SELECT
		*
	FROM dbo.Evaluacion_auditoria(@EMPRESA, @PERIODO, @DIVISION, @OST, @IDDOC)
END
