CREATE PROCEDURE [dbo].[V4MVC_OST_UPDATE_CONTRATOST_CTTA]   
(
  @ID_ARCHIVO	UNIQUEIDENTIFIER
 ,@INDEX		INT
 ,@NROOST		NVARCHAR(14)
) AS           
BEGIN
	IF(@INDEX = 1)
		BEGIN
			UPDATE OST
			SET
				ID_INF_RECEPCION = @ID_ARCHIVO
			WHERE NROOST = @NROOST
		END
	ELSE IF(@INDEX = 2)
		BEGIN
			UPDATE OST
			SET
				ID_FORM_RECEPCION = @ID_ARCHIVO
			WHERE NROOST = @NROOST
		END
END
