CREATE PROCEDURE [dbo].[V4MVC_POLIZAS_NOMINA_SELECT_DATATABLE_POLIZAS_CTTA]
(
  @IDDOC INT              = NULL
, @NROPOLIZA NVARCHAR(50) = NULL
) AS
BEGIN

	SELECT P.RUT, NOMBRES, APELLIDOS, P.VALIDADO,  ROW_NUMBER() OVER(ORDER BY W.RUT ASC) ROWNUMBER--ROW_NUMBER() OVER(ORDER BY W.RUT ASC) ROWNUMBER
	FROM POLIZAS_NOMINA P INNER JOIN WORKERS W ON P.RUT=W.RUT 
	WHERE NROPOLIZA=@NROPOLIZA AND IDDOC=@IDDOC 

END
/****** Object:  StoredProcedure [dbo].[V4MVC_POLIZAS_PAGO_INSERT_POLIZAS_CTTA]    Script Date: 9/11/2020 14:51:01 ******/
SET ANSI_NULLS ON
