CREATE PROCEDURE [dbo].[V4MVC_A407_DOTACION_DOCS_EMP_2_SELECT_INFORME_DOCUMENTOSCARGADOSAUDITORIALABORALMENSUAL_INFORME_CONTROLLABAROAL_CTTA]
(
@PERIODO  NVARCHAR(6)       = NULL,
@EMPRESA  NVARCHAR(10)       = NULL
) AS
BEGIN

DECLARE @FECHA NVARCHAR(8);
DECLARE @PERIODOA NVARCHAR(6);
DECLARE @strSQL as nvarchar(MAX)

SET @FECHA = @PERIODO + '01'
SET @PERIODOA = SUBSTRING(CONVERT(NVARCHAR(8),DATEADD(MONTH,-1,@FECHA ),112),0,7)

 SET @strSQL='SELECT	 A.OST						,A.DIVISION			,A.PERIODO						,A.DOTACION			,A.REMPREVIRED
						,A.PORC_CALC_REMU			,A.IVA				,A.EMPRESA						,A.PERIODO			,A.DIVISION
						,A.F_29						,A.F_29_DOC			,A.F_30							,A.F_30_DOC			,A.F_30_1
						,A.F_30_1_DOC				,A.PAGO_BANCO		,A.PAGO_BANCO_DOC				,A.IMPOSICION		,A.IMPOSICION_DOC
						,A.FOLIADO					,A.FOLIADO_DOC		,A.BONOITC						,A.BONOIS			,A.BONOIP
						,A.POLSALUD					,A.POLSALUD_DOC		,A.POLMUERTE					,A.POLMUERTE_DOC	,A.POLNATURAL
						,A.PORC_AUDITORIA			,A.PROC_EJEC		,A.VALIDA_JEFE					,E.ACRONIMO			,O.NIVEL
						,A.FINIQUITOS 
						,(SELECT TOP 1 UPPER([TIPO_AUDITORIA]) AS TIPO_AUDITORIA FROM CERT_AUDITORIA WHERE PERIODO = ''' + @PERIODO + ''' AND IDEMPRESA = ''' + @EMPRESA + ''' AND NCONTRATO = A.OST AND DIVISION = A.DIVISION ORDER BY TIPO_AUDITORIA) AS TIPO_AUDITORIA
						,(SELECT TOP 1 [PORCENTAJE_APROBACION] FROM CERT_AUDITORIA WHERE PERIODO = ''' + @PERIODO + ''' AND IDEMPRESA = ''' + @EMPRESA + ''' AND NCONTRATO = A.OST AND DIVISION = A.DIVISION ORDER BY TIPO_AUDITORIA) AS PORCENTAJE_APROBACION
						,(SELECT TOP 1 ID FROM CERT_AUDITORIA WHERE PERIODO = ''' + @PERIODO + ''' AND IDEMPRESA = ''' + @EMPRESA + ''' AND NCONTRATO = A.OST AND DIVISION = A.DIVISION ORDER BY TIPO_AUDITORIA) AS ID
						,(SELECT TOP 1 VALIDA_JEFE FROM CERT_AUDITORIA WHERE PERIODO = ''' + @PERIODO + ''' AND IDEMPRESA = ''' + @EMPRESA + ''' AND NCONTRATO = A.OST AND DIVISION = A.DIVISION ORDER BY TIPO_AUDITORIA) AS VALIDA_JEFE
FROM A400_AUDITORIA A INNER JOIN ENTERPRISE E ON A.EMPRESA = E.IDEMPRESA 
                      INNER JOIN OSTSUBC AS O ON A.OST = O.OST AND A.EMPRESA = O.EMPRESA 
WHERE PERIODO= ''' + @PERIODO + ''''

	IF @EMPRESA <> '' OR @EMPRESA <> NULL
	BEGIN
		Set @strSQL = @strSQL + N' AND A.EMPRESA = ''' + @EMPRESA + ''''
	END			           

	exec sp_executesql @strSQL  
	PRINT @strSQL
 
END	

