CREATE PROCEDURE [dbo].[V4MVC_COLAB_WC_SUBMENU_SELECT_EMPUSUARIOS_CTTA]
(
  @RUT NVARCHAR(10)
)
AS
BEGIN
	SELECT
		DISTINCT
		DescMenu,
		Descripcion,
		Activo
	FROM dbo.A000_PANELECUSER
	WHERE
		(Permiso = 'TODOS') OR
		(Rut = @RUT)
	ORDER BY 1, 2
END
