CREATE PROCEDURE [dbo].[V4MVC_DOCS_ENTERPRISE_INSERT_EMPRESA_CTTA]
( 
  @ID_DOC		INT
 ,@ID_EMPRESA	NVARCHAR(10)
 ,@EXTENSION	NVARCHAR(10)
 ,@USUARIO		NVARCHAR(10)
 ,@RET			BIT OUTPUT
 ,@NUEVO_ID		UNIQUEIDENTIFIER OUTPUT
) AS 
BEGIN
	DECLARE @CURR_FECHA NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 112) /* yyyymmdd */
	DECLARE @CURR_TIEMPOFULL NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 108) /* hh:mm:ss */
	SET @RET = 0
	SET @NUEVO_ID = NULL
	IF(EXISTS(
		SELECT
			DOCS_EXT.ID_DOC_EXT
		FROM DOCS_FORMATO, DOCS_EXT
		WHERE
			(DOCS_FORMATO.ID_DOC = @ID_DOC) AND
			(DOCS_EXT.EXTENSION = @EXTENSION) AND
			(DOCS_FORMATO.ID_DOC_EXT = DOCS_EXT.ID_DOC_EXT)
		))
		BEGIN
			SET @RET = 1
			SET @NUEVO_ID = NEWID()
			IF(NOT EXISTS(
				SELECT
					ID
				FROM DOCS_ENTERPRISE
				WHERE
					(IDEMPRESA = @ID_EMPRESA) AND
					(ID_DOC = @ID_DOC)
			))
				BEGIN
					INSERT INTO DOCS_ENTERPRISE
						(
						 IDEMPRESA, ID_DOC, FECHA_MOD, HORA_MOD,
						 USUARIO, ID, VALIDADO, FECHASUBE, HORASUBE)
					VALUES
					    (
						 @ID_EMPRESA, @ID_DOC, @CURR_FECHA, @CURR_TIEMPOFULL,
						 @USUARIO, @NUEVO_ID, 'NO', @CURR_FECHA, @CURR_TIEMPOFULL)
				END
			ELSE
				BEGIN
					UPDATE DOCS_ENTERPRISE
					SET
						FECHASUBE = @CURR_FECHA,
						HORASUBE = @CURR_TIEMPOFULL,
						USUARIO = @USUARIO,
						FECHA_MOD = @CURR_FECHA,
						HORA_MOD = @CURR_TIEMPOFULL,
						VALIDADO = 'NO',
						ID = @NUEVO_ID
					WHERE
						(IDEMPRESA = @ID_EMPRESA) AND
						(ID_DOC = @ID_DOC)
				END
		END
END

