CREATE PROCEDURE [dbo].[V4MVC_RESERVAS_EXSICO_SELECT_CTTA]
(
 @FECHARES  NVARCHAR(8)  = NULL
)
AS
BEGIN

	SELECT			 T1.ID				,T1.EMPRESA			,T1.RUT			,T1.FECHARES
					,T1.HORAINICIO		,T1.HORATERMINO		,T1.TIPO		,T1.ASISTIO
					,T1.MOTIVO			,T1.FECHASOL		,T1.HORASOL		,T1.USUARIOSOL
					,T1.FECHAMOD		,T1.HORAMOD			,T1.APROBO		,T2.NOMBRES
					,T2.APELLIDOS		,T3.DESCRIPCION		

	FROM			RESERVAS_EXSICO			T1
	INNER JOIN		WORKERS					T2		ON		T1.RUT		=	T2.RUT
	INNER JOIN		TAB_TIPOEXSICO			T3		ON		T1.TIPO		=	T3.ID

	WHERE			T1.FECHARES		=		@FECHARES
	AND				T1.FECHASOL		=		T1.FECHAMOD
	AND				T1.HORASOL		=		T1.HORAMOD

END
