CREATE PROCEDURE [dbo].[V4MVC_INFORME_DOCS_PENDIENTES_DISPUTA_CTTA]
(
 @FECHAINI	NVARCHAR(8)		= NULL
,@FECHAFIN	NVARCHAR(8)		= NULL
,@RUT		NVARCHAR(10)	= NULL
,@EMPRESA	NVARCHAR(10)	= NULL
)
AS
BEGIN

	SELECT		DIVISION	,EMPRESA	,ACRONIMO	,RUT
				,NOMBRES	,APELLIDOS	,NOMBRE		,ID_TIPO_PROPIETARIO
				,VALIDADO	,FECHA		,HORA
	FROM		V_DOCS_DISPUTA_LISTA
	WHERE		EMPRESA	=	@EMPRESA
	AND			RUT		=	ISNULL(@RUT,RUT)
	AND			FECHA	BETWEEN		ISNULL(@FECHAINI,FECHA) AND ISNULL(@FECHAFIN,FECHA)

END
