CREATE PROCEDURE [dbo].[V4MVC_LOG_CERT_AUDITORIA_SELECT_CTTA]    
(    
@ID_CERT_AUDITORIA INT    
)    
AS    
BEGIN    

	SELECT  T1.ID_CERT_AUDITORIA			,T2.NOMBRE				,T1.IDEMPRESA			,T1.PERIODO    
			,T1.FECHA						,T1.TIPO_AUDITORIA		,T1.CANT_PERSONAS		,T2.ID    
			,T1.PORCENTAJE_APROBACION		,T1.VALIDADO			,T3.DIVISION			,T1.NCONTRATO    
			,T1.COD_INTERNO_CERT			,T1.OBSERVACION			,T1.USUARIO				,T1.FECHASUBE     
			,T1.HORASUBE					,T1.CERTUSUARIO			,T1.CERTFECHA			,T1.CERTHORA          
			,T1.ACCION						,T1.USUARIOMOD			,T1.FECHAMOD			,(SELECT NOMBRES+' '+APELLIDOS FROM WORKERS WHERE RUT=T1.USUARIO) AS USER_ADD  
			,(SELECT NOMBRES+' '+APELLIDOS FROM WORKERS WHERE RUT=T1.USUARIOMOD) AS USER_MOD  
	FROM LOG_CERT_AUDITORIA T1    
	LEFT JOIN ARCHIVOS T2 ON T2.ID = T1.ID     
	INNER JOIN A024_DIVISIONES T3 ON T3.DIVCOD = T1.DIVISION     
	WHERE ID_CERT_AUDITORIA = @ID_CERT_AUDITORIA 
	ORDER BY T1.FECHAMOD DESC, T1.HORAMOD DESC

END
