CREATE PROCEDURE [dbo].[V4MVC_LIQUIDACION_UPDATE_FUNCIONARIOSCTTA]
(
 @RUT nvarchar(10) = NULL
,@FECHA nvarchar(6)  = NULL
,@EMPRESA nvarchar(10)  = NULL
,@IMPONIBLE int  = NULL
,@LIQUIDO int  = NULL
,@TRANSFERIDO int  = NULL
,@BONOIP int  = NULL
,@BONOIS int  = NULL
,@ID uniqueidentifier  = NULL
,@USUARIO nvarchar(10)  = NULL
,@CARGO_ARCHIVO BIT  = NULL) AS
BEGIN
DECLARE @VALIDADO VARCHAR(2)
BEGIN TRAN

		 INSERT INTO LIQUIDACION_LOG (RUT, FECHA, NOMBRE_ARCHIVO, TIPO_CONTENIDO,ARCHIVO, FECHASUBE, HORASUBE, USUARIO, VALIDADO, CERTUSUARIO, CERTFECHA, CERTHORA,IDRECHAZO, ID, IMPONIBLE, LIQUIDO, TRANSFERIDO, EMPRESA, BONOIP, BONOIS, FECHACSV, HORACSV, USUARIOCSV, USUARIODEL, FECHADEL, HORADEL)
						 SELECT TOP 1 RUT, FECHA, NOMBRE_ARCHIVO, TIPO_CONTENIDO, ARCHIVO, FECHASUBE, HORASUBE, USUARIO, VALIDADO, CERTUSUARIO, CERTFECHA, CERTHORA, IDRECHAZO, ID, IMPONIBLE, LIQUIDO, TRANSFERIDO, EMPRESA, BONOIP, BONOIS, FECHACSV, HORACSV, USUARIOCSV, @USUARIO,[dbo].[hoy](GETDATE()), [dbo].[ahora](GETDATE())
						 FROM LIQUIDACION 
						 WHERE RUT = @RUT AND FECHA = @FECHA AND EMPRESA = @EMPRESA
	IF( @CARGO_ARCHIVO=1)
	BEGIN
         UPDATE LIQUIDACION 
		 SET ID = @ID, 
		     USUARIO = @USUARIO,
			 FECHASUBE = [dbo].[hoy](GETDATE()),
			 HORASUBE =  [dbo].[ahora](GETDATE()),
			 VALIDADO = 'NO' 
			 WHERE RUT = @RUT AND FECHA = @FECHA
	END

		UPDATE LIQUIDACION 
		SET IMPONIBLE = @IMPONIBLE, 
		LIQUIDO = @LIQUIDO, 
		TRANSFERIDO = @TRANSFERIDO,
		BONOIP = @BONOIP, 
		BONOIS = @BONOIS
		WHERE RUT = @RUT AND FECHA = @FECHA AND EMPRESA = @EMPRESA

COMMIT TRAN
 SET @VALIDADO = 'SI'
TratarError:
If @@Error<>0 
BEGIN
 SET @VALIDADO = 'NO'
 ROLLBACK TRAN
END		
SELECT @VALIDADO VALIDADO
END
