CREATE PROCEDURE [dbo].[V4MVC_A056_FORM30_UPDATE_V2_CONTROLLABORAL_CTTA]
(
  @EMPRESA				NVARCHAR(10)
 ,@ID_CERTIFICADO		INT
 ,@ID					UNIQUEIDENTIFIER
 ,@USUARIO				NVARCHAR(10)
 ,@DISPUTA_ID			INT
 ,@DISPUTA_EXISTE		INT OUTPUT
 ,@DISPUTA_EMPRESA		NVARCHAR(12) OUTPUT
 ,@DISPUTA_FECHA		NVARCHAR(8) OUTPUT
) AS
BEGIN
	DECLARE @CURR_FECHA NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 112) /* yyyymmdd */
	DECLARE @CURR_TIEMPOFULL NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 108) /* hh:mm:ss */

	DECLARE @DDC_ID_DISPUTA INT
	DECLARE @DDC_ID_DOC INT
	DECLARE @DDC_ID UNIQUEIDENTIFIER
	DECLARE @DDC_USUARIO NVARCHAR(10)
	DECLARE @DDC_HORA NVARCHAR(8)
	DECLARE @DDC_OBSERVACION NVARCHAR(1000)
	DECLARE @DDC_CERTUSUARIO NVARCHAR(10)
	DECLARE @DDC_CERTFECHA NVARCHAR(8)
	DECLARE @DDC_CERTHORA NVARCHAR(8)
	DECLARE @DDC_ESTADO NVARCHAR(2)
	DECLARE @DDC_REVALUSUARIO NVARCHAR(10)
	DECLARE @DDC_REVALFECHA NVARCHAR(8)
	DECLARE @DDC_REVALHORA NVARCHAR(8)
	DECLARE @DDC_OBSERVACION_REVAL NVARCHAR(1000)
	DECLARE @DDC_VALIDADO NVARCHAR(2)
	DECLARE @DDC_PERIODO NVARCHAR(6)
	DECLARE @DDC_ID_CERTIFICADO INT

	DECLARE @AF30_EXISTE BIT = 0
	DECLARE @AF30_ID_CERTIFICADO INT
	DECLARE @AF30_EMPRESA NVARCHAR(10)
	DECLARE @AF30_REGION NVARCHAR(3)
	DECLARE @AF30_INSPECCION NVARCHAR(4)
	DECLARE @AF30_ANIO INT
	DECLARE @AF30_CERTIFICADO BIGINT
	DECLARE @AF30_CLAVE NVARCHAR(30)
	DECLARE @AF30_VIGENCIA NVARCHAR(8)
	DECLARE @AF30_MULT_NEJ INT
	DECLARE @AF30_MULT_EJ INT
	DECLARE @AF30_SANC_12M INT
	DECLARE @AF30_DP_NRO INT
	DECLARE @AF30_DP_MTO_PESO INT
	DECLARE @AF30_RM_NRO INT
	DECLARE @AF30_RM_MTO_PESO INT
	DECLARE @AF30_FECHAMOD NVARCHAR(8)
	DECLARE @AF30_HORAMOD NVARCHAR(8)
	DECLARE @AF30_QUIEN NVARCHAR(10)
	DECLARE @AF30_VALIDADO NVARCHAR(2)
	DECLARE @AF30_ID_DOC INT
	DECLARE @AF30_OBSERVACION NVARCHAR(500)
	DECLARE @AF30_ID UNIQUEIDENTIFIER
	DECLARE @AF30_PERIODO NVARCHAR(6)
	DECLARE @AF30_USUARIO NVARCHAR(10)
	DECLARE @AF30_FECHASUBE NVARCHAR(8)
	DECLARE @AF30_HORASUBE NVARCHAR(8)
	DECLARE @AF30_CERTUSUARIO NVARCHAR(10)
	DECLARE @AF30_CERTFECHA NVARCHAR(8)
	DECLARE @AF30_CERTHORA NVARCHAR(8)

	SET @DISPUTA_EXISTE = 0

	SELECT
		TOP 1
		@AF30_EXISTE = 1,
		@AF30_ID_CERTIFICADO = ID_CERTIFICADO,
		@AF30_EMPRESA = EMPRESA,
		@AF30_REGION = REGION,
		@AF30_INSPECCION = INSPECCION,
		@AF30_ANIO = ANIO,
		@AF30_CERTIFICADO = CERTIFICADO,
		@AF30_CLAVE = CLAVE,
		@AF30_VIGENCIA = VIGENCIA,
		@AF30_MULT_NEJ = MULT_NEJ,
		@AF30_MULT_EJ = MULT_EJ,
		@AF30_SANC_12M = SANC_12M,
		@AF30_DP_NRO = DP_NRO,
		@AF30_DP_MTO_PESO = DP_MTO_PESO,
		@AF30_RM_NRO = RM_NRO,
		@AF30_RM_MTO_PESO = RM_MTO_PESO,
		@AF30_FECHAMOD = FECHAMOD,
		@AF30_HORAMOD = HORAMOD,
		@AF30_QUIEN = QUIEN,
		@AF30_VALIDADO = VALIDADO,
		@AF30_ID_DOC = ID_DOC,
		@AF30_OBSERVACION = OBSERVACION,
		@AF30_ID = ID,
		@AF30_PERIODO = PERIODO,
		@AF30_USUARIO = USUARIO,
		@AF30_FECHASUBE = FECHASUBE,
		@AF30_HORASUBE = HORASUBE,
		@AF30_CERTUSUARIO = CERTUSUARIO,
		@AF30_CERTFECHA = CERTFECHA,
		@AF30_CERTHORA = CERTHORA
	FROM A056_FORM30
	WHERE
		EMPRESA = @EMPRESA AND
		ID_CERTIFICADO = @ID_CERTIFICADO

	IF(@AF30_EXISTE = 1)
		BEGIN
			INSERT INTO A056_FORM30_LOG
					(
						ID_CERTIFICADO,
						EMPRESA,
						REGION,
						INSPECCION,
						ANIO,
						CERTIFICADO,
						CLAVE,
						VIGENCIA,
						MULT_NEJ,
						MULT_EJ,
						SANC_12M,
						DP_NRO,
						DP_MTO_PESO,
						RM_NRO,
						RM_MTO_PESO,
						FECHAMOD,
						HORAMOD,
						QUIEN,
						VALIDADO,
						ID_DOC,
						OBSERVACION,
						ID,
						PERIODO,
						USUARIO,
						FECHASUBE,
						HORASUBE,
						CERTUSUARIO,
						CERTFECHA,
						CERTHORA,
						USUARIODEL,
						FECHADEL,
						HORADEL
					
				    )
					VALUES(
						@AF30_ID_CERTIFICADO,
						@AF30_EMPRESA,
						@AF30_REGION,
						@AF30_INSPECCION,
						@AF30_ANIO,
						@AF30_CERTIFICADO,
						@AF30_CLAVE,
						@AF30_VIGENCIA,
						@AF30_MULT_NEJ,
						@AF30_MULT_EJ,
						@AF30_SANC_12M,
						@AF30_DP_NRO,
						@AF30_DP_MTO_PESO,
						@AF30_RM_NRO,
						@AF30_RM_MTO_PESO,
						@AF30_FECHAMOD,
						@AF30_HORAMOD,
						@AF30_QUIEN,
						@AF30_VALIDADO,
						@AF30_ID_DOC,
						@AF30_OBSERVACION,
						@AF30_ID,
						@AF30_PERIODO,
						@AF30_USUARIO,
						@AF30_FECHASUBE,
						@AF30_HORASUBE,
						@AF30_CERTUSUARIO,
						@AF30_CERTFECHA,
						@AF30_CERTHORA,
						@AF30_USUARIO,
						@CURR_FECHA,
						@CURR_TIEMPOFULL
					)			
		END

	SELECT
		TOP 1
		@DISPUTA_EXISTE = 1,
		@DDC_ID_DISPUTA = ID_DISPUTA,
		@DISPUTA_EMPRESA = EMPRESA,
		@DDC_ID_DOC = ID_DOC,
		@DDC_ID = ID,
		@DDC_USUARIO = USUARIO,
		@DISPUTA_FECHA = FECHA,
		@DDC_HORA = HORA,
		@DDC_OBSERVACION = OBSERVACION,
		@DDC_CERTUSUARIO = CERTUSUARIO,
		@DDC_CERTFECHA = CERTFECHA,
		@DDC_CERTHORA = CERTHORA,
		@DDC_ESTADO = ESTADO,
		@DDC_REVALUSUARIO = REVALUSUARIO,
		@DDC_REVALFECHA = REVALFECHA,
		@DDC_REVALHORA = REVALHORA,
		@DDC_OBSERVACION_REVAL = OBSERVACION_REVAL,
		@DDC_VALIDADO = VALIDADO,
		@DDC_PERIODO = PERIODO,
		@DDC_ID_CERTIFICADO = ID_CERTIFICADO
	FROM DOCS_DISPUTA_CLABORAL
	WHERE
		ID_DISPUTA = @DISPUTA_ID AND
		ESTADO = 'NO'

	IF(@DISPUTA_EXISTE = 1)
		BEGIN
			INSERT INTO DOCS_DISPUTA_CLABORAL_LOG
				(
					ID_DISPUTA,
					EMPRESA,
					ID_DOC,
					ID,
					USUARIO,
					FECHA,
					HORA,
					OBSERVACION,
					CERTUSUARIO,
					CERTFECHA,
					CERTHORA,
					ESTADO,
					REVALUSUARIO,
					REVALFECHA,
					REVALHORA,
					OBSERVACION_REVAL,
					VALIDADO,
					PERIODO,
					ID_CERTIFICADO,
					USRMOD,
					FECHAMOD,
					HORAMOD,
					ACCION
				)
			VALUES 
				(
					@DDC_ID_DISPUTA,
					@DISPUTA_EMPRESA,
					@DDC_ID_DOC,
					@DDC_ID,
					@DDC_USUARIO,
					@DISPUTA_FECHA,
					@DDC_HORA,
					@DDC_OBSERVACION,
					@DDC_CERTUSUARIO,
					@DDC_CERTFECHA,
					@DDC_CERTHORA,
					@DDC_ESTADO,
					@DDC_REVALUSUARIO,
					@DDC_REVALFECHA,
					@DDC_REVALHORA,
					@DDC_OBSERVACION_REVAL,
					@DDC_VALIDADO,
					@DDC_PERIODO,
					@DDC_ID_CERTIFICADO,
					@USUARIO,
					@CURR_FECHA,
					@CURR_TIEMPOFULL,
					'ELIMINADO'
				)

			DELETE DOCS_DISPUTA_CLABORAL
			WHERE
				ID_DISPUTA = @DISPUTA_ID AND
				ESTADO = 'NO'
		END

		DELETE FROM ARCHIVOS
		WHERE ID = @ID

		UPDATE A056_FORM30
		SET
			ID = NULL,
			VALIDADO = 'NO'
		WHERE
			ID_CERTIFICADO = @ID_CERTIFICADO

END
