CREATE PROCEDURE [dbo].[V4MVC_INFORMES_CAPACITACIONES_DETALLE_CTTA]
(
 @EMPRESA		NVARCHAR(10)	= NULL
,@DIVCOD		NVARCHAR(4)		= NULL
,@FINALIZADO	NVARCHAR(2)		= NULL
,@IDCHARLA		INT				= NULL
,@CODIGO		INT				= NULL
,@FECHAINI		NVARCHAR(8)		= NULL
,@FECHAFIN		NVARCHAR(8)		= NULL
,@RUT			NVARCHAR(10)	= NULL
)
AS
BEGIN

	DECLARE @QUERY NVARCHAR(MAX)

	IF(@IDCHARLA > 0)
	BEGIN
		SET @QUERY = 'SELECT DISTINCT W.RUT,		W.NOMBRES,		W.APELLIDOS,		VC.ASISTIO
				                ,VC.NOTA,		CH.CHARLA,		CH.PORCENTAJE,		VC.FECHA
								,VC.HORA,		VC.FINALIZADO,	VC.EXPIRA,			E.IDEMPRESA,  
								E.ACRONIMO,	CH.HORAS,		CASE CH.OBLIGATORIO WHEN ' + N'''SI''' + ' THEN ' + N'''OBLIGATORIO''' +' ELSE ' +N'''OPCIONAL''' +' END AS OBLIGATORIO
		FROM WC3_VISTA_CURSOS AS VC 
		INNER JOIN WORKERS AS W ON VC.RUT = W.RUT 
		INNER JOIN ENTERPRISE AS E ON VC.EMPRESA = E.IDEMPRESA 
		INNER JOIN CHARLAS AS CH ON VC.CURSO = CH.IDCHARLA 
		WHERE VC.EMPRESA =''' + @EMPRESA + '''
		AND VC.DIVISION = ' + N'''' + @DIVCOD + N'''' +'
		AND VC.ASISTIO=''' + 'SI' + ''' '
		IF (ISNULL(@FECHAINI,'') != '' AND ISNULL(@FECHAFIN,'') != '') BEGIN SET @QUERY = @QUERY + ' AND VC.FECHA BETWEEN ' + @FECHAINI +' AND ' + @FECHAFIN END
		IF (ISNULL(@RUT,'')!='') BEGIN SET @QUERY = @QUERY + ' AND VC.RUT= ''' + @RUT +N''' ' END
		IF (@FINALIZADO = 'SI') BEGIN SET @QUERY = @QUERY + ' AND VC.NOTA >= CH.PORCENTAJE ' END
		IF (@FINALIZADO = 'NO') BEGIN SET @QUERY = @QUERY + ' AND VC.NOTA < CH.PORCENTAJE ' END
		IF (@IDCHARLA > 0) BEGIN SET @QUERY = @QUERY + ' AND VC.CURSO = ' + CAST(@IDCHARLA AS VARCHAR) END
	END
	ELSE
	BEGIN
		SET @QUERY = 'SELECT	D.DIVISION		,E.ACRONIMO			,W.RUT	 		,W.NOMBRES
				,W.APELLIDOS	,CH.CHARLA		,CH.PORCENTAJE		,VC.FINALIZADO	
				,VC.ASISTIO		,VC.NOTA		,VC.EXPIRA			,VC.HORA		
				,VC.FECHA		,CH.HORAS		,CASE CH.OBLIGATORIO WHEN ' + N'''SI''' + ' THEN ' + N'''OBLIGATORIO''' + ' ELSE ' + N'''OPCIONAL''' +' END AS OBLIGATORIO 
		FROM WC3_VISTA_CURSOS AS VC 
		INNER JOIN A024_DIVISIONES AS D ON VC.DIVISION = D.DIVCOD 
		INNER JOIN CHARLAS AS CH ON VC.CURSO = CH.IDCHARLA 
		INNER JOIN ENTERPRISE AS E ON VC.EMPRESA = E.IDEMPRESA 
		INNER JOIN WORKERS AS W ON VC.RUT = W.RUT 
		WHERE 1 = 1
		AND VC.EMPRESA =''' + @EMPRESA + '''
		AND VC.ASISTIO=''' + 'SI' + ''' '
		IF (ISNULL(@FECHAINI,'') != '' AND ISNULL(@FECHAFIN,'') != '') BEGIN SET @QUERY = @QUERY + ' AND VC.FECHA BETWEEN ' + @FECHAINI +' AND ' + @FECHAFIN END
		IF (ISNULL(@RUT,'')!='') BEGIN SET @QUERY = @QUERY + ' AND VC.RUT= ''' + @RUT +N''' ' END
		IF (ISNULL(@DIVCOD,'')!='') BEGIN SET @QUERY = @QUERY + ' AND VC.DIVISION= ''' + @DIVCOD +N''' ' END
		IF (@FINALIZADO = 'SI') BEGIN SET @QUERY = @QUERY + ' AND VC.NOTA >= CH.PORCENTAJE ' END
		IF (@FINALIZADO = 'NO') BEGIN SET @QUERY = @QUERY + ' AND VC.NOTA < CH.PORCENTAJE ' END
		IF (@IDCHARLA > 0) BEGIN SET @QUERY = @QUERY + ' AND VC.CURSO = ' + CAST(@IDCHARLA AS VARCHAR) END 
		IF (@CODIGO > 0) BEGIN SET @QUERY = @QUERY + 'AND VC.CODIGO = ' + CAST(@CODIGO AS VARCHAR) END 
	    --SET @QUERY = @QUERY + ' ORDER BY  E.ACRONIMO, W.NOMBRES, W.APELLIDOS'
		SET @QUERY = @QUERY + ' ORDER BY  VC.FECHA'

	END

	EXEC(@QUERY)
	PRINT(@QUERY)

END



--EXEC V4MVC_INFORMES_CAPACITACIONES_DETALLE_CTTA '761264907',null,null,0,null,null,null,null



