CREATE PROCEDURE [dbo].[V4MVC_INSTALACION_FAENA_SELECT_ONE_V2_CONTRATOST_CTTA]
(
  @NROOST			NVARCHAR(14)
 ,@IDEMPRESA		NVARCHAR(10)
 ,@MADRE			NVARCHAR(10)
 ,@NIVEL			SMALLINT
) AS
BEGIN
	DECLARE @CANT_DOCS_PENDIENTE INT = -1
	DECLARE @NUM_SOLICITUD BIGINT = -1
	DECLARE @ESTADO_PREV NVARCHAR(2) = ''
	DECLARE @VALIDA_PREV NVARCHAR(2) = 'NO'

	DECLARE @ID_DOC NVARCHAR(500) = ''
	DECLARE @INFO_ARCHIVO NVARCHAR(500) = ''
	DECLARE @NOMBRE_ARCHIVO NVARCHAR(50) = '' 

	SELECT
		@CANT_DOCS_PENDIENTE = COUNT(DOCS_OST2.VALIDADO)
	FROM DOCS_OST2
	INNER JOIN DOCS D
	ON D.ID_DOC = DOCS_OST2.ID_DOC AND
		D.ID_DOC_OPCION = '1' AND
		D.ACTIVO = 'SI'
	WHERE
		(DOCS_OST2.OST = @NROOST) AND
		(DOCS_OST2.MADRE = @MADRE) AND
		(DOCS_OST2.EMPRESA = @IDEMPRESA) AND
		(DOCS_OST2.NIVEL = @NIVEL) AND
		(ISNULL(DOCS_OST2.VALIDADO,'NO') = 'NO')

	SELECT
		TOP 1
		@NUM_SOLICITUD = ID,
		@ESTADO_PREV = ESTADO,
		@VALIDA_PREV = 'SI'
	FROM DOCS_OST_PREVENCIONISTA
	WHERE
		OST = @NROOST AND
		MADRE = @MADRE AND
		EMPRESA = @IDEMPRESA

	SELECT
		TOP 1
		@ID_DOC = Valor2,
		@INFO_ARCHIVO = Valor3
	FROM PARAMETROS_V2
	WHERE DESCRIPCION = 'Validacion Docs Prevencionistas'

	IF(@ID_DOC IS NOT NULL  AND @ID_DOC <> '')
		BEGIN
			SELECT
				TOP 1
				@NOMBRE_ARCHIVO = NOMBRE
			FROM DOCS
			WHERE ID_DOC = CONVERT(INT, @ID_DOC)
		END

	/********************************************/


	SELECT
		ISNULL(OS.VALIDA_CARRANQUE,'NO') AS VALIDA_CARRANQUE,
		@CANT_DOCS_PENDIENTE AS CANT_DOCS_PENDIENTE,
		@NUM_SOLICITUD AS NUM_SOLICITUD,
		@ESTADO_PREV AS ESTADO_PREV,
		@VALIDA_PREV AS VALIDA_PREV,
		@ID_DOC AS ID_DOC,
		@INFO_ARCHIVO AS INFO_ARCHIVO,
		@NOMBRE_ARCHIVO AS NOMBRE_ARCHIVO
	FROM OST O
	INNER JOIN OSTARBOL OS
		ON OS.OST = O.NROOST
	WHERE
		O.NROOST = @NROOST AND 
		OS.EMPRESA = @IDEMPRESA AND
		OS.MADRE = @MADRE AND
		OS.NIVEL = @NIVEL
END

