CREATE PROCEDURE [dbo].[V4MVC_RESERVAS_EXSICO_INSERT_CTTA]
(
 @IDEMPRESA					NVARCHAR(10)
,@USUARIO					NVARCHAR(10)
,@LIST_RUT					NVARCHAR(MAX)
,@FECHARES					NVARCHAR(8)
,@HORAINICIO				NVARCHAR(8)
,@HORATERMINO				NVARCHAR(8)
,@TIPO						DECIMAL(18,2)
)
AS
BEGIN

	CREATE TABLE #LISTA_WORKERS
	(
	 RUT					NVARCHAR(10)    COLLATE DATABASE_DEFAULT NOT NULL,
	 MSG_EXISTE				NVARCHAR(MAX)   COLLATE DATABASE_DEFAULT NOT NULL,
	 MSG_TIENE				NVARCHAR(MAX)   COLLATE DATABASE_DEFAULT NOT NULL,
	 MSG_TIENE_FECHA		NVARCHAR(8)	    COLLATE DATABASE_DEFAULT NOT NULL,
	 MSG_RESERVA			NVARCHAR(MAX)   COLLATE DATABASE_DEFAULT NOT NULL
	)

	SELECT value AS RUT INTO #TEMP_SPLIT_LIST_RUT      
	FROM string_split(@LIST_RUT,',')   

	SELECT  ROW_NUMBER() OVER(ORDER BY RUT ASC) AS ID , * INTO #TEMP_SPLIT_B from                     
	#TEMP_SPLIT_LIST_RUT     
	
	DECLARE @CONTADOR		INT 
	DECLARE @MAXIMO			INT 
	DECLARE @RUT			VARCHAR(10) 
	DECLARE @A				DATETIME  
	DECLARE @B				DATETIME  
	DECLARE @C				NVARCHAR(8)  
	DECLARE @MES			NVARCHAR(2)
	DECLARE @FECHA_EXSICO	NVARCHAR(8)
	DECLARE @QUERY			NVARCHAR(MAX)

	SET @MES = (SELECT TIEMPORENUEVA FROM TAB_RESERVASICO WHERE ACTIVO='SI')

	SET @CONTADOR = 1    
	SELECT @MAXIMO = MAX(ID) FROM  #TEMP_SPLIT_B  

	WHILE ( @CONTADOR <= @MAXIMO )                     
	BEGIN        

		SELECT @RUT = RUT FROM #TEMP_SPLIT_B                
		WHERE ID = @CONTADOR 

		IF EXISTS(
			SELECT * FROM RESERVAS_EXSICO 
			WHERE EMPRESA=@IDEMPRESA 
			AND RUT= @RUT
			AND ASISTIO='NO' 
			AND MOTIVO IS NULL AND (FECHARES>dbo.HOY(GETDATE()) OR (FECHARES=dbo.HOY(GETDATE()) AND HORATERMINO>dbo.AHORA(GETDATE())))
		)
		BEGIN
			INSERT INTO #LISTA_WORKERS VALUES (@RUT,'No puede realizarse la reserva por poseer ya una vigente.(Puede cancelar la reserva y hacer una nueva)',NULL,NULL,NULL)
		END
		ELSE
		BEGIN
		
			SET @FECHA_EXSICO = (SELECT TOP 1 FECHA FROM DOCS_FEC_WORKERS WHERE RUT = @RUT AND DIVISION='ES' AND ID_DOC_FEC='32' ORDER BY FECHA DESC)

			IF EXISTS(
				SELECT FECHA FROM DOCS_FEC_WORKERS WHERE (RUT = @RUT) AND DIVISION='ES' AND ID_DOC_FEC='32'
			)

			BEGIN
				INSERT INTO #LISTA_WORKERS VALUES (@RUT,NULL,'No puede realizarse la reserva por tener Examen Vigente.Puede solicitar una Reserva, '+ @MES +' mes(es) antes del vencimiento)', @FECHA_EXSICO ,NULL)
			END
			ELSE
			BEGIN

					SET @A = CAST(@FECHA_EXSICO AS DATETIME)   
					SET @B = DATEADD(MONTH, -(SELECT TIEMPORENUEVA FROM TAB_RESERVASICO WHERE ACTIVO='SI'), @A)  
					SET @C = CONVERT(VARCHAR(8), @B, 112); 

					INSERT INTO RESERVAS_EXSICO (
									EMPRESA			,RUT				,FECHARES			,HORAINICIO
								,HORATERMINO		,TIPO				,FECHASOL			,HORASOL 
								,USUARIOSOL			,FECHAMOD			,HORAMOD
							)
											
					VALUES (
									@IDEMPRESA			,@RUT				,@FECHARES			,@HORAINICIO
									,@HORATERMINO		,@TIPO				,DBO.HOY(GETDATE())	,DBO.AHORA(GETDATE())
									,@USUARIO			,DBO.HOY(GETDATE())	,DBO.AHORA(GETDATE())
							)

				INSERT INTO #LISTA_WORKERS VALUES (@RUT,NULL,NULL,NULL,'Reserva realizada Correctamente, ademas se envio correo para la notificacion')

			END
		END

		SET @CONTADOR = @CONTADOR + 1

	END
	SELECT * FROM #LISTA_WORKERS

END

