CREATE PROCEDURE [dbo].[V4MVC_REMUNERACIONES_PROPIO_UPDATE_V3_CONTROLLABORAL_CTTA]
(
  @ID			UNIQUEIDENTIFIER = NULL
 ,@USUARIO		NVARCHAR(10)
 ,@PERIODO		NVARCHAR(6)
 ,@IDEMPRESA	NVARCHAR(10)
 ,@DIVISION		NVARCHAR(4)
 ,@OST			NVARCHAR(20)
 ,@MONTOIMP		INT
) AS
BEGIN
	DECLARE @CURR_FECHA NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 112) /* yyyymmdd */
	DECLARE @CURR_TIEMPOFULL NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 108) /* hh:mm:ss */
	
	IF(@ID IS NOT NULL)
		BEGIN
			UPDATE REMUNERACIONES_PROPIO
			SET
				ID = @ID,
				VALIDADO = 'NO',
				MONTOIMP = @MONTOIMP,
				USUARIO = @USUARIO,
				FECHAMOD = @CURR_FECHA,
				HORAMOD = @CURR_TIEMPOFULL
			WHERE
				(EMPRESA = @IDEMPRESA) AND
				(PERIODO = @PERIODO) AND
				(DIVISION = @DIVISION) AND
				(OST = @OST)
		END
	ELSE
		BEGIN
			UPDATE REMUNERACIONES_PROPIO
			SET
				VALIDADO = 'NO',
				MONTOIMP = @MONTOIMP,
				USUARIO = @USUARIO,
				FECHAMOD = @CURR_FECHA,
				HORAMOD = @CURR_TIEMPOFULL
			WHERE
				(EMPRESA = @IDEMPRESA) AND
				(PERIODO = @PERIODO) AND
				(DIVISION = @DIVISION) AND
				(OST = @OST)
		END
END
