CREATE PROCEDURE [dbo].[V4MVC_DOCS_SELECT_GRID2_INFORME_FICHAFUNCIONARIODET_INFORMESFUNCIONARIOS_CTTA]
(
 @DIVCOD	NVARCHAR(4)	 = NULL,
 @TIPOPASE	NVARCHAR(9)	 = NULL,
 @RUT		NVARCHAR(10) = NULL,
 @IDEMPRESA	NVARCHAR(20)	= NULL
)
AS
BEGIN

SELECT DISTINCT 
D.NOMBRE,
		(CASE D.SUBEDOC WHEN 'SI' THEN
				CASE D.COMUN WHEN 1 THEN
							CASE WHEN EXISTS(SELECT TOP 1 ID, VALIDADO FROM DOCS_WORKERS WHERE (RUT = @RUT) AND (ID_DOC = D.ID_DOC) AND (DIVISION = (CASE WHEN D.COMUN_DIV = 'SI' THEN DIVISION ELSE @DIVCOD END )) ORDER BY ID_DOCS_WORKERS DESC)  THEN
								(SELECT TOP 1 VALIDADO FROM DOCS_WORKERS WHERE (RUT = @RUT) AND (ID_DOC = D.ID_DOC) AND (DIVISION = (CASE WHEN D.COMUN_DIV = 'SI' THEN DIVISION ELSE @DIVCOD END )) ORDER BY ID_DOCS_WORKERS DESC)
							ELSE
							    'NO EXISTE'
							END 
				 ELSE 
							CASE WHEN EXISTS(SELECT TOP 1 ID, VALIDADO FROM DOCS_WORKERS WHERE (RUT = @RUT) AND (ID_DOC = D.ID_DOC) AND (DIVISION = (CASE WHEN D.COMUN_DIV = 'SI' THEN DIVISION ELSE @DIVCOD END )) AND (EMPRESA = @IDEMPRESA) ORDER BY ID_DOCS_WORKERS DESC)  THEN
								(SELECT TOP 1  VALIDADO FROM DOCS_WORKERS WHERE (RUT = @RUT) AND (ID_DOC = D.ID_DOC) AND (DIVISION = (CASE WHEN D.COMUN_DIV = 'SI' THEN DIVISION ELSE @DIVCOD END )) AND (EMPRESA = @IDEMPRESA) ORDER BY ID_DOCS_WORKERS DESC)
							ELSE
								'NO EXISTE'
							END 
				 END
		 ELSE 
                    ''
		 END) AS ESTADO,
D.ID_DOC,		D.SUBEDOC,		D.ORDEN,
D.COMUN_DIV,	D.COMUN ,		D.CONFIDENCIAL,
							 (CASE WHEN EXISTS(SELECT DT.TIPOPASE 
											FROM  DOCS_TIPOPASE AS DT 
											WHERE D.ID_DOC = DT.ID_DOC
											AND (DT.DIVISION = @DIVCOD)
											AND DT.TIPOPASE<>'OPCIONAL') THEN 'OBLIGATORIO' ELSE '' END) AS TIPOPASE,
(SELECT TOP 1 LICONDLT FROM LOTEPASESFUN 
			  						WHERE RUTLOTE = @RUT AND 
									NLOTEPROC IN (SELECT LOTE FROM WORKERSLOCAL WHERE (RUT = @RUT) AND (DIVISION = @DIVCOD) AND (FFINPASE >=  CONVERT(NVARCHAR(8),GETDATE(),112)) AND (AUTOR IN ('SI','NO'))) 
									ORDER BY NLOTEPROC)	AS LICONDLT,
(SELECT ENTREGADO FROM WORKERS_LIC_ENTREGA WHERE RUT = @RUT AND DIVISION = @DIVCOD)	AS ENTREGADO,
(SELECT TOP 1  [dbo].[fn_WL_Conductor] ('"& Rut  &"', '"& Division &"', dbo.hoy(getdate())) AS CERT FROM TAB_TIPOPASE_DIVISION) AS CERT																		   
FROM  DOCS AS D INNER JOIN  DOCS_TIPOPASE AS DT ON D.ID_DOC = DT.ID_DOC 
WHERE (D.ACTIVO = 'SI') AND (D.ID_DOC_OPCION = 1) AND (D.ID_TIPO_PROPIETARIO = 1) AND (DT.DIVISION = @DIVCOD)  
ORDER BY D.ORDEN

END
