CREATE PROCEDURE [dbo].[V4MVC_GET_WC3_VISTA_CTRLING_INFORME_ACCESOSZONASCONTROLADAS]
(
@LOCAL  NVARCHAR(12)         = NULL,
@OPCION  NVARCHAR(1)         = NULL,
@FECHAINI  NVARCHAR(8)       = NULL,
@FECHAFIN  NVARCHAR(8)       = NULL,
@DIVCOD  NVARCHAR(4)         = NULL,
@EMPRESA  NVARCHAR(10)       = NULL
) AS
BEGIN


		    IF @OPCION='1'
			BEGIN

					IF @LOCAL = 'TODOS'
					BEGIN
												  SELECT 
												  COUNT(C.FECHA) OVER() TOTALREGISTROS,
												  ROW_NUMBER() OVER(ORDER BY C.FECHA ASC) ROWNUMBER,
												  SUM(C.INGRESO) AS ING, SUM(C.SALIDA) AS SAL, SUM(C.ERRIN) AS ERRIN, SUM(C.ERROUT) AS ERROUT, SUM(C.VEHIN) AS VEHIN, SUM(C.VEHOUT) AS VEHOUT, C.FECHA 
												  FROM WC3_VISTA_CTRLING AS C 
												  WHERE (C.FECHA  BETWEEN @FECHAINI AND @FECHAFIN) AND (C.DIVISION = @DIVCOD) AND (C.EMPRESA = @EMPRESA)
												  GROUP BY C.FECHA 
					END
					ELSE
					BEGIN
												  SELECT 
												  COUNT(C.FECHA) OVER() TOTALREGISTROS,
												  ROW_NUMBER() OVER(ORDER BY C.FECHA ASC) ROWNUMBER,
												  SUM(C.INGRESO) AS ING, SUM(C.SALIDA) AS SAL, SUM(C.ERRIN) AS ERRIN, SUM(C.ERROUT) AS ERROUT, SUM(C.VEHIN) AS VEHIN, SUM(C.VEHOUT) AS VEHOUT, C.FECHA 
												  FROM WC3_VISTA_CTRLING AS C 
												  WHERE (C.FECHA  BETWEEN @FECHAINI AND @FECHAFIN) AND (C.DIVISION = @DIVCOD) AND (C.LOCAL IN (@LOCAL)) AND (C.EMPRESA = @EMPRESA)
												  GROUP BY C.FECHA  
					END

			END
			ELSE IF  @OPCION='2'
			BEGIN
					IF @LOCAL = 'TODOS'
					BEGIN
												  SELECT 
												  COUNT(C.ACRONIMO) OVER() TOTALREGISTROS,
												  ROW_NUMBER() OVER(ORDER BY C.ACRONIMO ASC) ROWNUMBER,
												  SUM(C.INGRESO) AS ING, SUM(C.SALIDA) AS SAL, SUM(C.ERRIN) AS ERRIN, SUM(C.ERROUT) AS ERROUT, SUM(C.VEHIN) AS VEHIN, SUM(C.VEHOUT) AS VEHOUT, C.ACRONIMO, C.EMPRESA 
												  FROM WC3_VISTA_CTRLING AS C 
												  WHERE  (C.FECHA  BETWEEN @FECHAINI AND @FECHAFIN) AND (C.DIVISION = @DIVCOD) AND (C.EMPRESA = @EMPRESA)
												  GROUP BY C.ACRONIMO, C.EMPRESA  
					END
					ELSE
					BEGIN
												  SELECT 
												  COUNT(C.ACRONIMO) OVER() TOTALREGISTROS,
												  ROW_NUMBER() OVER(ORDER BY C.ACRONIMO ASC) ROWNUMBER,
												  SUM(C.INGRESO) AS ING, SUM(C.SALIDA) AS SAL, SUM(C.ERRIN) AS ERRIN, SUM(C.ERROUT) AS ERROUT, SUM(C.VEHIN) AS VEHIN, SUM(C.VEHOUT) AS VEHOUT, C.ACRONIMO, C.EMPRESA 
												  FROM WC3_VISTA_CTRLING AS C 
												  WHERE  (C.FECHA  BETWEEN @FECHAINI AND @FECHAFIN) AND (C.DIVISION = @DIVCOD) AND (C.LOCAL IN (@LOCAL)) AND (C.EMPRESA = @EMPRESA)
												  GROUP BY C.ACRONIMO, C.EMPRESA 
					END

			END
			ELSE IF  @OPCION='3'
			BEGIN
					IF @LOCAL = 'TODOS'
					BEGIN
												 SELECT 
												 COUNT(C.DSCTIPOV) OVER() TOTALREGISTROS,
												 ROW_NUMBER() OVER(ORDER BY C.DSCTIPOV ASC) ROWNUMBER,
												 SUM(C.INGRESO) AS ING, SUM(C.SALIDA) AS SAL, SUM(C.ERRIN) AS ERRIN, SUM(C.ERROUT) AS ERROUT, SUM(C.VEHIN) AS VEHIN, SUM(C.VEHOUT) AS VEHOUT,  C.DSCTIPOV 
												 FROM WC3_VISTA_CTRLING AS C 
												 WHERE  (C.FECHA  BETWEEN @FECHAINI AND @FECHAFIN) AND (C.DIVISION = @DIVCOD) AND (C.EMPRESA = @EMPRESA)
												 GROUP BY C.DSCTIPOV 
					END
					ELSE
					BEGIN
												 SELECT 
												 COUNT(C.DSCTIPOV) OVER() TOTALREGISTROS,
												 ROW_NUMBER() OVER(ORDER BY C.DSCTIPOV ASC) ROWNUMBER,
												 SUM(C.INGRESO) AS ING, SUM(C.SALIDA) AS SAL, SUM(C.ERRIN) AS ERRIN, SUM(C.ERROUT) AS ERROUT, SUM(C.VEHIN) AS VEHIN, SUM(C.VEHOUT) AS VEHOUT,  C.DSCTIPOV 
												 FROM WC3_VISTA_CTRLING AS C 
												 WHERE  (C.FECHA  BETWEEN @FECHAINI AND @FECHAFIN) AND (C.DIVISION = @DIVCOD) AND (C.LOCAL IN (@LOCAL)) AND (C.EMPRESA = @EMPRESA)
												 GROUP BY C.DSCTIPOV 
					END
			END
			ELSE IF  @OPCION='4'
			BEGIN
					IF @LOCAL = 'TODOS'
					BEGIN
												SELECT 
												 COUNT(C.FECHA) OVER() TOTALREGISTROS,
												 ROW_NUMBER() OVER(ORDER BY C.FECHA ASC) ROWNUMBER,
												SUM(C.INGRESO) AS ING, SUM(C.SALIDA) AS SAL, SUM(C.ERRIN) AS ERRIN, SUM(C.ERROUT) AS ERROUT, SUM(C.VEHIN) AS VEHIN, SUM(C.VEHOUT) AS VEHOUT, C.FECHA 
												FROM WC3_VISTA_CTRLING AS C 
												WHERE (C.FECHA  BETWEEN @FECHAINI AND @FECHAFIN) AND (C.DIVISION = @DIVCOD) AND (C.EMPRESA = @EMPRESA) AND (VEHICULO = 'S') 
												GROUP BY C.FECHA  
					END
					ELSE
					BEGIN
												SELECT 
												 COUNT(C.FECHA) OVER() TOTALREGISTROS,
												 ROW_NUMBER() OVER(ORDER BY C.FECHA ASC) ROWNUMBER,
												SUM(C.INGRESO) AS ING, SUM(C.SALIDA) AS SAL, SUM(C.ERRIN) AS ERRIN, SUM(C.ERROUT) AS ERROUT, SUM(C.VEHIN) AS VEHIN, SUM(C.VEHOUT) AS VEHOUT, C.FECHA 
												FROM WC3_VISTA_CTRLING AS C 
												WHERE (C.FECHA  BETWEEN @FECHAINI AND @FECHAFIN) AND (C.DIVISION = @DIVCOD) AND (C.LOCAL IN (@LOCAL)) AND (C.EMPRESA = @EMPRESA) AND (VEHICULO = 'S') 
												GROUP BY C.FECHA 
					END



			END
			ELSE IF  @OPCION='5'
			BEGIN
					IF @LOCAL = 'TODOS'
					BEGIN
												SELECT
												COUNT(C.OST) OVER() TOTALREGISTROS,
												ROW_NUMBER() OVER(ORDER BY C.OST ASC) ROWNUMBER,
												 SUM(C.INGRESO) AS ING, SUM(C.SALIDA) AS SAL, SUM(C.ERRIN) AS ERRIN, SUM(C.ERROUT) AS ERROUT, SUM(C.VEHIN) AS VEHIN, SUM(C.VEHOUT) AS VEHOUT, C.OST 
												FROM WC3_VISTA_CTRLING AS C 
												WHERE (C.FECHA  BETWEEN @FECHAINI AND @FECHAFIN) AND (C.DIVISION = @DIVCOD) AND (C.EMPRESA = @EMPRESA)
												GROUP BY C.OST 
					END
					ELSE
					BEGIN
												SELECT
												COUNT(C.OST) OVER() TOTALREGISTROS,
												ROW_NUMBER() OVER(ORDER BY C.OST ASC) ROWNUMBER,
												 SUM(C.INGRESO) AS ING, SUM(C.SALIDA) AS SAL, SUM(C.ERRIN) AS ERRIN, SUM(C.ERROUT) AS ERROUT, SUM(C.VEHIN) AS VEHIN, SUM(C.VEHOUT) AS VEHOUT, C.OST 
												FROM WC3_VISTA_CTRLING AS C 
												WHERE (C.FECHA  BETWEEN @FECHAINI AND @FECHAFIN) AND (C.DIVISION = @DIVCOD) AND (C.LOCAL IN (@LOCAL)) AND (C.EMPRESA = @EMPRESA)
												GROUP BY C.OST 
					END
			END
			ELSE IF  @OPCION='6'
			BEGIN
					IF @LOCAL = 'TODOS'
					BEGIN
												SELECT 
												COUNT(C.TIPOPASE) OVER() TOTALREGISTROS,
												ROW_NUMBER() OVER(ORDER BY C.TIPOPASE ASC) ROWNUMBER,				
												SUM(C.INGRESO) AS ING, SUM(C.SALIDA) AS SAL, SUM(C.ERRIN) AS ERRIN, SUM(C.ERROUT) AS ERROUT, SUM(C.VEHIN) AS VEHIN, SUM(C.VEHOUT) AS VEHOUT, C.TIPOPASE 
												FROM WC3_VISTA_CTRLING AS C 
												WHERE (C.FECHA  BETWEEN @FECHAINI AND @FECHAFIN) AND (C.DIVISION = @DIVCOD) AND (C.EMPRESA = @EMPRESA)
												GROUP BY C.TIPOPASE 
					END
					ELSE
					BEGIN
												SELECT 
												COUNT(C.TIPOPASE) OVER() TOTALREGISTROS,
												ROW_NUMBER() OVER(ORDER BY C.TIPOPASE ASC) ROWNUMBER,				
												SUM(C.INGRESO) AS ING, SUM(C.SALIDA) AS SAL, SUM(C.ERRIN) AS ERRIN, SUM(C.ERROUT) AS ERROUT, SUM(C.VEHIN) AS VEHIN, SUM(C.VEHOUT) AS VEHOUT, C.TIPOPASE 
												FROM WC3_VISTA_CTRLING AS C 
												WHERE (C.FECHA  BETWEEN @FECHAINI AND @FECHAFIN) AND (C.DIVISION = @DIVCOD) AND (C.LOCAL IN (@LOCAL)) AND (C.EMPRESA = @EMPRESA)
												GROUP BY C.TIPOPASE 
					END
			END 
END	


