CREATE PROCEDURE [dbo].[V4MVC__F29_INSERT_CONTROLLABORAL_CTTA]
(
  @PERIODO			NVARCHAR(6)
 ,@IDEMPRESA		NVARCHAR(10)
 ,@VENTAS			BIGINT
 ,@COMPRAS			BIGINT
 ,@PPM				BIGINT
 ,@REMANENTE		BIGINT
 ,@IRENTA			BIGINT
 ,@BHONORARIOS		BIGINT
 ,@IMP_PAGADO		BIGINT
 ,@REMMESANT		BIGINT
 ,@MULTAS			BIGINT
 ,@ESTADOCERT		NVARCHAR(20)
 ,@POSTERGADO		INT
 ,@RET_CODE			INT OUTPUT
) AS
BEGIN
	SET @RET_CODE = -1
	IF(EXISTS(
			SELECT
				PERIODO
			FROM _F29
			WHERE
				EMPRESA = @IDEMPRESA AND
				PERIODO = @PERIODO
	))
		BEGIN
			SET @RET_CODE = 1  /*ERROR LOGICO; YA EXISTE*/
			RETURN
		END
	
	INSERT INTO _F29
			(
				EMPRESA,
				PERIODO,
				VENTAS,
				COMPRAS,
				PPM,
				REMANENTE,
				IRENTA,
				BHONORARIOS,
				IMP_PAGADO,
				REMMESANT,
				MULTAS,
				ESTADOCERT,
				POSTERGADO
			)
	VALUES
			(
				@IDEMPRESA,
				@PERIODO,
				@VENTAS,
				@COMPRAS,
				@PPM,
				@REMANENTE,
				@IRENTA,
				@BHONORARIOS,
				@IMP_PAGADO,
				@REMMESANT,
				@MULTAS,
				@ESTADOCERT,
				@POSTERGADO
			)
END
