CREATE PROCEDURE [dbo].[V4MVC_SERVICIO_SELECT_DIVISION]
(
 @DIVISION NVARCHAR(20)
)
AS
BEGIN

	SELECT				T2.LOCAL		,T1.SERVICIO	,T1.DESCRIPCION		,T1.VALOR	
						,T1.HORAINI		,T1.HORAFIN
	FROM				SERVICIO		AS T1
	INNER JOIN	LOCAL	T2				ON T1.LOCAL		= T2.LOCAL
	WHERE				T2.LOCALL						= 'CASINO'
	AND					T2.DIVISION						= @DIVISION
	ORDER BY			T1.LOCAL		,T1.HORAINI

END
