CREATE PROCEDURE [dbo].[V4MVC_CASINO_SUBTOTAL_CTTA]
(
 @EMPRESA	NVARCHAR(10)
,@LOCALES	NVARCHAR(MAX)
,@DIVCOD	NVARCHAR(4)
,@FECHAINI	NVARCHAR(8)
,@FECHAFIN	NVARCHAR(8)
)
AS
BEGIN

	SELECT VALUE AS LOCAL INTO #TEMP_SPLIT_LOCALES
	FROM STRING_SPLIT(@LOCALES,',')
	
	SELECT LOCAL,FECHA,SUM(CANTIDAD) AS CANTIDAD FROM WC3_VISTA_CASINO
	WHERE EMPRESA = @EMPRESA
	AND FECHA BETWEEN @FECHAINI AND @FECHAFIN
	AND DIVISION = @DIVCOD
	AND ISNULL(ERROR,'') = ''
	AND LOCAL IN (SELECT LOCAL FROM #TEMP_SPLIT_LOCALES)
	GROUP BY LOCAL,FECHA
	ORDER BY LOCAL ASC

END
