CREATE PROCEDURE [dbo].[V4MVC_ENTERPRISE_COUNT_FILTRO]    
(    
@SEARCH_IDEMPRESA NVARCHAR(10) = NULL,  
@SEARCH_ACRONIMO NVARCHAR(50) = NULL,  
@SEARCH_NOMBRE NVARCHAR(50) = NULL       
)    
AS    
BEGIN    
    
IF ISNULL(@SEARCH_IDEMPRESA,'') != '' OR ISNULL(@SEARCH_ACRONIMO,'') != '' OR ISNULL(@SEARCH_NOMBRE,'') != ''  
BEGIN       

IF ISNULL(@SEARCH_IDEMPRESA,'') != '' AND ISNULL(@SEARCH_ACRONIMO,'') = '' AND ISNULL(@SEARCH_NOMBRE,'') = ''  
 BEGIN  
  SELECT COUNT(IDEMPRESA) AS COUNT_ENTERPRISES                    
  FROM ENTERPRISE            
  WHERE (AUTOR='SI')  
  AND IDEMPRESA LIKE '%' + @SEARCH_IDEMPRESA + '%'  
 END  
  
 IF ISNULL(@SEARCH_IDEMPRESA,'') = '' AND ISNULL(@SEARCH_ACRONIMO,'') != '' AND ISNULL(@SEARCH_NOMBRE,'') = ''  
 BEGIN  
  SELECT COUNT(IDEMPRESA) AS COUNT_ENTERPRISES                           
  FROM ENTERPRISE            
  WHERE (AUTOR='SI')  
  AND ACRONIMO LIKE '%' + @SEARCH_ACRONIMO + '%'  
 END  
  
 IF ISNULL(@SEARCH_IDEMPRESA,'') = '' AND ISNULL(@SEARCH_ACRONIMO,'') = '' AND ISNULL(@SEARCH_NOMBRE,'') != ''  
 BEGIN  
  SELECT COUNT(IDEMPRESA) AS COUNT_ENTERPRISES                        
  FROM ENTERPRISE            
  WHERE (AUTOR='SI')  
  AND NOMBRE LIKE '%' + @SEARCH_NOMBRE + '%'  
 END  
  
 IF ISNULL(@SEARCH_IDEMPRESA,'') = '' AND ISNULL(@SEARCH_ACRONIMO,'') != '' AND ISNULL(@SEARCH_NOMBRE,'') != ''  
 BEGIN  
  SELECT COUNT(IDEMPRESA) AS COUNT_ENTERPRISES                        
  FROM ENTERPRISE            
  WHERE (AUTOR='SI')  
  AND ACRONIMO LIKE '%' + @SEARCH_ACRONIMO + '%'  
  AND NOMBRE LIKE '%' + @SEARCH_NOMBRE + '%'    
 END  
  
 IF ISNULL(@SEARCH_IDEMPRESA,'') != '' AND ISNULL(@SEARCH_ACRONIMO,'') != '' AND ISNULL(@SEARCH_NOMBRE,'') != ''  
 BEGIN  
  SELECT COUNT(IDEMPRESA) AS COUNT_ENTERPRISES                         
  FROM ENTERPRISE            
  WHERE (AUTOR='SI')  
  AND IDEMPRESA LIKE '%' + @SEARCH_IDEMPRESA + '%'  
  AND ACRONIMO LIKE '%' + @SEARCH_ACRONIMO + '%'  
  AND NOMBRE LIKE '%' + @SEARCH_NOMBRE + '%'   
 END  
  
 IF ISNULL(@SEARCH_IDEMPRESA,'') != '' AND ISNULL(@SEARCH_ACRONIMO,'') != '' AND ISNULL(@SEARCH_NOMBRE,'') = ''  
 BEGIN  
  SELECT COUNT(IDEMPRESA) AS COUNT_ENTERPRISES                     
  FROM ENTERPRISE            
  WHERE (AUTOR='SI')  
  AND IDEMPRESA LIKE '%' + @SEARCH_IDEMPRESA + '%'  
  AND ACRONIMO LIKE '%' + @SEARCH_ACRONIMO + '%'   
 END  
  
 IF ISNULL(@SEARCH_IDEMPRESA,'') != '' AND ISNULL(@SEARCH_ACRONIMO,'') = '' AND ISNULL(@SEARCH_NOMBRE,'') != ''  
 BEGIN  
  SELECT COUNT(IDEMPRESA) AS COUNT_ENTERPRISES                        
  FROM ENTERPRISE            
  WHERE (AUTOR='SI')  
  AND IDEMPRESA LIKE '%' + @SEARCH_IDEMPRESA + '%'  
  AND NOMBRE LIKE '%' + @SEARCH_NOMBRE + '%'  
 END

END
ELSE
BEGIN

 SELECT COUNT(IDEMPRESA) AS COUNT_ENTERPRISES 
 FROM ENTERPRISE    
 WHERE (AUTOR='SI')

END
   
END
