CREATE PROCEDURE [dbo].[V4MVC_WORKERS_SELECT_GRID_ADMINCOLABORADORRESUMEN_INFORMECONSULTARAPIDA_CTTA]
(
  @EMPRESA NVARCHAR(20)
) AS 
BEGIN
SELECT distinct CU.RUT, CU.CORREO_ELECTRONICO, W.NOMBRES, W.APELLIDOS FROM COLAB_USUARIO as CU INNER JOIN WORKERS AS W ON CU.RUT = W.RUT WHERE IDEMPRESA = @EMPRESA
END
