CREATE PROCEDURE [dbo].[V4MVC_A142_RESERVAS_SELECT]      
(  
@CODIGO INT    
)  
AS  
BEGIN      

	SELECT		RUT			,NOMBRES	,APELLIDOS  ,ACRONIMO  
				,FECHARES	,HORARES	,ACTIVO		,CODIGO
				,EMPRESA
	FROM A142_RESERVAS  
	WHERE CODIGO = @CODIGO  

END 
