CREATE PROCEDURE [dbo].[V4MVC_A036_CURSOPROG_DOCS_SELECT]
(
 @CODIGO	INT	= NULL
)
AS
BEGIN

	SELECT ID_DOC_CHARLA, ID, NOMBRE, BYTES, CODIGO
	FROM A036_CURSOPROG_DOCS 
	WHERE CODIGO = ISNULL(@CODIGO, CODIGO)

END
