CREATE PROCEDURE [dbo].[V4MVC_COLAB_USUARIO_DELETE_EMPUSUARIOS_CTTA]
(
@RUT NVARCHAR(10),
@IDEMPRESA NVARCHAR(10),
@USUARIO NVARCHAR(10)
)
AS
BEGIN
	DECLARE @CURR_FECHA NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 112) /* yyyymmdd */
	DECLARE @CURR_TIEMPOFULL NVARCHAR(8) = convert(NVARCHAR(8), getdate(), 108) /* hh:mm:ss */

	DELETE FROM COLAB_USUARIO WHERE (Rut = @RUT)
	IF(NOT EXISTS(
		SELECT ACCION
		FROM COLAB_USUARIOSHIST
		WHERE
			EMPRESA = @IDEMPRESA AND
			USUARIO = @RUT AND
			FECHA = @CURR_FECHA AND
			HORA = @CURR_TIEMPOFULL
	))
		BEGIN
			INSERT INTO COLAB_USUARIOSHIST (EMPRESA, USUARIO, FECHA, HORA, QUIEN, ACCION)
			VALUES (@IDEMPRESA, @RUT, @CURR_FECHA, @CURR_TIEMPOFULL, @USUARIO, 'DEL')
		END
END
