CREATE PROCEDURE [dbo].[V4MVC_TAB_TRACCION_SELECT]
( @IDTRACCION  int = NULL ) AS
BEGIN

   SELECT IDTRACCION , TRACCION
     FROM TAB_TRACCION
    WHERE IDTRACCION = ISNULL( @IDTRACCION, IDTRACCION )
	ORDER BY TRACCION
END

