CREATE PROCEDURE [dbo].[V4MVC_POLIZAS_PAGO_INSERT_POLIZAS_CTTA]
(
  @IDDOC INT               = NULL
, @NROPOLIZA NVARCHAR(50)  = NULL
, @PERINI NVARCHAR(6)      = NULL
, @PERFIN NVARCHAR(6)      = NULL
, @USUARIOMOD NVARCHAR(10) = NULL
, @IDPAGO UNIQUEIDENTIFIER = NULL
) AS
BEGIN

  INSERT INTO POLIZAS_PAGO( NROPOLIZA		,IDDOC			,PERINI			,PERFIN		
                           ,VALIDADO		,USUARIOMOD		,FECHAMOD		,HORAMOD					
						   ,IDPAGO) 
					VALUES( @NROPOLIZA		,@IDDOC			,@PERINI		,@PERFIN	
						   ,'NO'			,@USUARIOMOD	,[dbo].[hoy](GETDATE()),[dbo].[ahora](GETDATE())	
						   ,@IDPAGO)

END
