CREATE PROCEDURE [dbo].[V4MVC_GET_FECHA_WORKER_LOCAL]  
(  
@ID_DOC_FEC  INT = NULL  
,@RUT   NVARCHAR(9) = ''  
,@DIVCOD   NVARCHAR(4) = ''  
,@IDEMPRESA   NVARCHAR(10) = ''  
,@FEC_WLOCAL  NVARCHAR(8) OUTPUT  
)  
AS  
BEGIN  
 DECLARE @EMP_COMUN INT = 0  
 DECLARE @DIV_COMUN INT = 0  
  
 SELECT @EMP_COMUN = D.COMUN, @DIV_COMUN = DF.COMUN    
 FROM DOCS_FEC AS DF   
 INNER JOIN DOCS AS D ON DF.ID_DOC_DEPEND = D.ID_DOC   
 WHERE  (DF.ID_DOC_FEC = @ID_DOC_FEC)  
  
 IF(@EMP_COMUN = 0)  
  
  BEGIN  
   IF(@DIV_COMUN = 0)  
   
     
    BEGIN  
     SELECT TOP 1 @FEC_WLOCAL = FECHA FROM DOCS_FEC_WORKERS WHERE (RUT = @RUT ) AND (ID_DOC_FEC = @ID_DOC_FEC) AND (DIVISION = @DIVCOD) AND (EMPRESA = @IDEMPRESA) ORDER BY FECHA DESC  
    END  
   ELSE  
    BEGIN  
     SELECT TOP 1 @FEC_WLOCAL = FECHA FROM DOCS_FEC_WORKERS WHERE (RUT = @RUT ) AND (ID_DOC_FEC = @ID_DOC_FEC) AND (EMPRESA = @IDEMPRESA) ORDER BY FECHA DESC  
    END  
  END  
 ELSE  
  BEGIN  
   IF(@DIV_COMUN = 0)  
    BEGIN  
     SELECT TOP 1 @FEC_WLOCAL = FECHA FROM DOCS_FEC_WORKERS WHERE (RUT = @RUT ) AND (ID_DOC_FEC = @ID_DOC_FEC) AND (DIVISION = @DIVCOD) ORDER BY FECHA DESC  
    END  
   ELSE  
    BEGIN  
     SELECT TOP 1 @FEC_WLOCAL = FECHA FROM DOCS_FEC_WORKERS WHERE (RUT = @RUT ) AND (ID_DOC_FEC = @ID_DOC_FEC) ORDER BY FECHA DESC  
    END  
  END  
END
