CREATE PROCEDURE [dbo].[V4MVC_A056_FORM30_SELECT_CONTROLLABORAL_CTTA]
(
  @IDEMPRESA	NVARCHAR(11)
) AS
BEGIN
	DECLARE @ID_DOC INT = 92
	SELECT
		SS.ID,
		SS.TIPOCONTENIDO,
		SS.ID_CERTIFICADO,
		SS.EMPRESA,
		SS.ACRONIMO,
		SS.REGION,
		SS.INSPECCION,
		SS.ANIO,
		SS.CERTIFICADO,
		SS.CLAVE,
		SS.VIGENCIA,
		SS.VALIDADO,
		SS.PERIODO,
		SS.UNIQUE_ID,
		SS.DOC_ID,
		COALESCE(
			(
				SELECT
					TOP 1
						DD.ID_DISPUTA
				FROM DOCS_DISPUTA_CLABORAL DD
				WHERE
					DD.EMPRESA = SS.EMPRESA AND
					DD.PERIODO = SS.PERIODO AND
					DD.ID_DOC = @ID_DOC AND
					DD.ID = SS.UNIQUE_ID
				ORDER BY DD.ID_DISPUTA DESC
			), -1
		) AS DISPUTA_ID,
		COALESCE(
			(
				SELECT
					TOP 1
						DD.ESTADO
				FROM DOCS_DISPUTA_CLABORAL DD
				WHERE
					DD.EMPRESA = SS.EMPRESA AND
					DD.PERIODO = SS.PERIODO AND
					DD.ID_DOC = @ID_DOC AND
					DD.ID = SS.UNIQUE_ID
				ORDER BY DD.ID_DISPUTA DESC
			), ''
		) AS DISPUTA_ESTADO,
		IIF(EXISTS(
				SELECT * 
				FROM DOCS_DISPUTA_CLABORAL DD
				WHERE
					DD.EMPRESA = SS.EMPRESA AND
					DD.PERIODO = SS.PERIODO AND
					DD.ID_DOC = @ID_DOC AND
					DD.ID = SS.UNIQUE_ID
				ORDER BY DD.ID_DISPUTA DESC
				OFFSET 0 ROWS
		), 1 , 0) AS DISPUTA_EXISTE		
	FROM
	(
		SELECT
			F30D.ID,
			F30D.TIPOCONTENIDO,
			F30.ID_CERTIFICADO,
			F30.EMPRESA,
			VE.ACRONIMO,
			F30.REGION,
			F30.INSPECCION,
			F30.ANIO,
			F30.CERTIFICADO,
			F30.CLAVE,
			F30.VIGENCIA,
			F30.VALIDADO,
			F30.PERIODO,
			IIF(F30D.ID IS NULL OR CONVERT(NVARCHAR(40), F30D.ID) = '', NULL, F30D.ID) AS UNIQUE_ID,
			IIF(F30D.ID IS NULL OR CONVERT(NVARCHAR(40), F30D.ID) = '', NULL, F30D.ID) AS DOC_ID
		FROM A056_FORM30 F30
		INNER JOIN V_ENTERPRISE VE
			ON F30.EMPRESA = VE.IDEMPRESA
		LEFT OUTER JOIN ARCHIVOS F30D
			ON F30.ID = F30D.ID
		WHERE F30.EMPRESA = @IDEMPRESA
		ORDER BY F30.CERTIFICADO ASC
		OFFSET 0 ROWS
	) SS	
END
