CREATE PROCEDURE [dbo].[V4MVC_CHARLAS_SELECT_DIVISION_CTTA]
(
 @DIVCOD	NVARCHAR(4)	= NULL
)
AS
BEGIN

	SELECT DISTINCT  CH.IDCHARLA,	CH.CHARLA,	CHD.DIVISION 
	FROM  dbo.CHARLAS AS CH,  dbo.CHARLAS_DIVISION AS CHD 
	WHERE CH.IDCHARLA = CHD.IDCHARLA
	AND CHD.DIVISION = @DIVCOD

END
