CREATE PROCEDURE [dbo].[V4MVC_DOCS_SELECT_ONE_GETACCESOFAENA_INFORMEFUNCIONARIOS_CTTA]
(
	@RUT AS NVARCHAR(10)
   ,@EMPRESA AS NVARCHAR(10)
   ,@TIPO_PASE AS NVARCHAR(12)
   ,@DIVISION AS NVARCHAR(12)
)
AS
BEGIN
	SELECT
		COALESCE(
			(
				SELECT
					TOP 1
						[dbo].[fn_WL_Certificado] (@RUT, @EMPRESA, @TIPO_PASE, @DIVISION, dbo.hoy(getdate()))
				FROM TAB_TIPOPASE_DIVISION
			)
		,0)
END

