CREATE PROCEDURE [dbo].[V4MVC_DOCS_TRANSPORT_SELECT_VALIDADO]
(@DIVCOD	NVARCHAR(4) = NULL
,@PATENTE	NVARCHAR(6) = NULL
,@ID_DOC	INT	= NULL
,@COMUN_DIV	NVARCHAR(2) = NULL
,@COMUN     INT = NULL
,@IDEMPRESA NVARCHAR(11) = NULL) AS
BEGIN
	IF(@COMUN = 1)
		BEGIN
			IF(@COMUN_DIV = 'NO')
				BEGIN
					SELECT CASE WHEN @ID_DOC = 145 THEN NULL ELSE ID END AS ID, VALIDADO 
					FROM DOCS_TRANSPORT 
					WHERE (PATENTE = @PATENTE) AND 
					((DIVISION = @DIVCOD) OR (ISNULL(DIVISION, 'AA') = 'AA')) AND 
					(ID_DOC = @ID_DOC) 
					ORDER BY ID_DOCS_VEH DESC
				END
			ELSE
				BEGIN
					SELECT CASE WHEN @ID_DOC = 145 THEN NULL ELSE ID END AS ID, VALIDADO 
					FROM DOCS_TRANSPORT 
					WHERE (PATENTE = @PATENTE) AND 
					(ID_DOC = @ID_DOC) 
					ORDER BY ID_DOCS_VEH DESC
				END
		END
	ELSE
		BEGIN
			IF(@COMUN_DIV = 'NO')
				BEGIN
					SELECT CASE WHEN @ID_DOC = 145 THEN NULL ELSE ID END AS ID, VALIDADO 
					FROM DOCS_TRANSPORT 
					WHERE (PATENTE = @PATENTE) AND 
					( (DIVISION = @DIVCOD) OR (ISNULL(DIVISION, 'AA') = 'AA')) AND 
					(ID_DOC = @ID_DOC) AND 
					(EMPRESA = @IDEMPRESA) 
					ORDER BY ID_DOCS_VEH DESC
				END
			ELSE
				BEGIN
					SELECT CASE WHEN @ID_DOC = 145 THEN NULL ELSE ID END AS ID, VALIDADO FROM DOCS_TRANSPORT 
					WHERE (PATENTE = @PATENTE) AND 
					(ID_DOC = @ID_DOC) AND 
					(EMPRESA = @IDEMPRESA) 
					ORDER BY ID_DOCS_VEH DESC
				END
		END
END		

