CREATE PROCEDURE [dbo].[V4MVC_ARCHIVOS_SELECT]
(@ID	 uniqueidentifier = NULL ) AS
BEGIN

   SELECT ID      , NOMBRE  , TIPOCONTENIDO , FECHAMOD
        , HORAMOD , USUARIO , ARCHIVO      
    FROM ARCHIVOS
	WHERE ID = @ID

END

