CREATE PROCEDURE [dbo].[V4MVC_LOTEPASESFUN_SELECT_VEHICULO_INFORMECONSULTARAPIDA_CTTA]
(
  @NLOTEPROC INT 
) AS 
BEGIN

SELECT RUTLOTE			, NOMBRESLT			, APELLIDOSLT		, SINOLT
     , EMPRESALT		, ALOJAMIENTOLT		, CASINOLT			, LICONDLT
	 , FNACIMLT			, TIPOLT			,  [dbo].[fn_WL_Certificado] (RUTLOTE, EMPRESALT , TIPOLT, 'CH', dbo.hoy(getdate())) AS CERT 
	 FROM LOTEPASESFUN  
	 WHERE NLOTEPROC = @NLOTEPROC AND TIPORUT = 'VEHICULO'
	 ORDER BY RUTLOTE ASC

END
