CREATE PROCEDURE [dbo].[V4MVC_A036_CURSOPARAMETROS_BY_PARAMETRO_CTTA]
(
 @PARAMETRO		INT
)
AS
BEGIN

	SELECT	ID_PARAMETRO	,NOMBRE		,VALOR
	FROM	A036_CURSOPARAMETROS 
	WHERE	ID_PARAMETRO = @PARAMETRO

END
