CREATE PROCEDURE [dbo].[V4MVC_DOCS_SELECT_CONTRATOST_CTTA]
(
  @NROOST		NVARCHAR(50)
 ,@MADRE		NVARCHAR(10)
 ,@IDEMPRESA	NVARCHAR(10)
 ,@NIVEL		SMALLINT
) AS
BEGIN
	SELECT
		SS.NOMBRE,
		SS.ID_DOC_OPCION,
		SS.RUTA,
		SS.ID_DOC,
		SS.CAMPO,
		SS.ID_ARCHIVO,
		SS.NONE_NULL,
		(CASE
		WHEN (SS.NONE_NULL = 1) THEN (
					IIF(EXISTS(
								SELECT DO.ID_ARCHIVO
								FROM DOCS_OST2 DO
								WHERE
									(DO.OST = @NROOST) AND
									(DO.MADRE = @MADRE) AND
									(DO.EMPRESA = @IDEMPRESA) AND
									(DO.ID_DOC = SS.ID_DOC) AND
									(DO.NIVEL = @NIVEL)
							), 1, 0)
					)
		ELSE 0 END) AS EXISTE_DOC_OST,
		SS.VVALIDADO,
		SS.VALIDADO_ADMINOST,
		SS.ID_ARCHIVO2,
		SS.EEXT,
		(COALESCE(
			(
				SELECT
					TOP 1
					A.NOMBRE
				FROM ARCHIVOS A
				WHERE A.ID = SS.ID_ARCHIVO2
			)
			, '')
		) AS NOM_ARCHIVO2
	FROM
	(
		SELECT
			D.NOMBRE,
			D.ID_DOC_OPCION,
			D.RUTA,
			D.ID_DOC,
			D.CAMPO,
			DFC.ID_ARCHIVO,
			IIF(
				@NROOST IS NULL OR
				@MADRE IS NULL OR
				@IDEMPRESA IS NULL OR
				D.ID_DOC IS NULL OR
				@NIVEL IS NULL
				, 0, 1) AS NONE_NULL,
			COALESCE(
				(
					SELECT
						TOP 1
						ISNULL(DO2.VALIDADO,'NO')
					FROM DOCS_OST2 DO2
					WHERE 
						(DO2.OST = @NROOST) AND
						(DO2.MADRE = @MADRE) AND
						(DO2.EMPRESA = @IDEMPRESA) AND
						(DO2.ID_DOC = D.ID_DOC) AND
						(DO2.NIVEL = @NIVEL)
				), ''
			) AS VVALIDADO,
			COALESCE(
				(
					SELECT
						TOP 1
						ISNULL(DO2.VALIDADO_ADMINOST,'NO')
					FROM DOCS_OST2 DO2
					WHERE 
						(DO2.OST = @NROOST) AND
						(DO2.MADRE = @MADRE) AND
						(DO2.EMPRESA = @IDEMPRESA) AND
						(DO2.ID_DOC = D.ID_DOC) AND
						(DO2.NIVEL = @NIVEL)
				), ''
			) AS VALIDADO_ADMINOST,
			COALESCE(
				(
					SELECT
						TOP 1
						DO2.ID_ARCHIVO
					FROM DOCS_OST2 DO2
					WHERE 
						(DO2.OST = @NROOST) AND
						(DO2.MADRE = @MADRE) AND
						(DO2.EMPRESA = @IDEMPRESA) AND
						(DO2.ID_DOC = D.ID_DOC) AND
						(DO2.NIVEL = @NIVEL)
				), NULL
			) AS ID_ARCHIVO2,
			SUBSTRING( 
						(
							SELECT ' ' + DX.EXTENSION
							FROM DOCS_FORMATO DF
							INNER JOIN DOCS_EXT DX
								ON DF.ID_DOC_EXT = DX.ID_DOC_EXT 
							WHERE
								DF.ID_DOC = D.ID_DOC
							FOR XML PATH('') 
						), 2, 9999
			) AS EEXT
		FROM DOCS D
		LEFT JOIN DOCS_FORMATO_CARGA DFC
			ON DFC.ID_DOC = D.ID_DOC
		WHERE
			(D.ACTIVO = 'SI') AND
			(D.VALIDAMANDANTE = 'SI') AND
			(D.ID_TIPO_PROPIETARIO = '2')
	) SS
END

