CREATE PROCEDURE [dbo].[V4MVC_SELECT_OSTARBOL_CONTRATOSEMPRESA_INFORMESEMPRESAS_CTTA]
(
 @EMPRESA	NVARCHAR(10) = NULL,
 @DIVISION	NVARCHAR(2) = NULL
)
AS
BEGIN

SELECT OD.OST, OD.ADMINOST, OA.NIVEL, OD.MANDANTE, OA.FINICIO, OA.FTERMINO,
--(SELECT COUNT(DISTINCT RUT) FROM VW_WL_ACREDITADOOST WHERE (EMPRESA = @EMPRESA) AND (OST = OD.OST) AND (DIVISION = @DIVISION)) AS CUENTA 
'0' AS CUENTA
FROM OSTARBOL OA INNER JOIN OSTDIVLOCAL OD ON OA.OST = OD.OST 
WHERE OA.EMPRESA = @EMPRESA AND OD.DIVISION = @DIVISION AND (dbo.hoy(GETDATE()) BETWEEN OA.FINICIO AND OA.FTERMINO) 

END
