CREATE PROCEDURE [dbo].[V4MVC_WORKERS_SELECT_GRID_MOVIMIENTOS_FICHARUT_INFORMECONSULTARAPIDA_CTTA]
(
  @RUT	NVARCHAR(10)
) AS 
BEGIN

 SELECT U.RUT, U.[IN], U.OUT, U.LOCAL, U.FECHAIN, U.HORAIN, U.FECHACASINO, U.HORACASINO, U.LOCALCASINO  , U.HORAOUT, U.FECHAOUT, D.DIVISION, U.HORAINZ, U.HORAOUTZ, U.INZ, U.OUTZ, U.ZONA
 , U.FECHAINZ, U.FECHAOUTZ, U.DIVISIONZ   , CASE WHEN (U.FECHAIN + U.HORAIN > U.FECHAOUT + U.HORAOUT OR  U.FECHACASINO + U.HORACASINO > U.FECHAOUT + U.HORAOUT) THEN 1 ELSE 0 END AS IN_CAS  
  FROM  WC3_VISTA_ULT_INOUT AS U LEFT OUTER JOIN A024_DIVISIONES AS D ON U.DIVISION = D.DIVCOD   WHERE RUT = @RUT

END
