CREATE PROCEDURE [dbo].[V4MVC_MODULOS_VIDEOS_V4_INSERT_VIDEOS_MDTE]
(
  @NOMBRE_MODULO	NVARCHAR(50)
 ,@GLOSA			NVARCHAR(50)
 ,@ACTIVO			NVARCHAR(2)
 ,@RET_RESULTADO	INT OUTPUT
 ,@NUEVO_ID			INT OUTPUT
) AS
BEGIN
	SET @RET_RESULTADO = -1
	IF(NOT EXISTS(SELECT TOP 1 * FROM MODULOS_VIDEOS_V4 WHERE MODULO = @NOMBRE_MODULO))
		BEGIN
			INSERT INTO MODULOS_VIDEOS_V4(MODULO, GLOSA, ACTIVO) VALUES(@NOMBRE_MODULO, @GLOSA, @ACTIVO)
			SET @NUEVO_ID = SCOPE_IDENTITY()
		END
	ELSE
		BEGIN
			SET @RET_RESULTADO = 1
		END
END
