CREATE PROCEDURE [dbo].[V4MVC_CTRLING_SELECT_MOVIMIENTO_INGSAL_MESACTUAL_INFORMEFUNCIONARIOS_CTTA]
(
  @RUTINGRESO NVARCHAR(10)
) AS 
BEGIN

SELECT SUM(INGRESO) AS INGRESO,			SUM(SALIDA) AS SALIDA,		SUM(ERRIN) AS ALERTAIN,		SUM(ERROUT) AS ALERTAOUT,
	   C.RUTINGRESO						, W.NOMBRES					, W.APELLIDOS  
FROM WC3_VISTA_CTRLING  AS C LEFT OUTER JOIN WORKERS AS W ON C.RUTINGRESO = W.RUT  
                             INNER JOIN   A024_DIVISIONES AS D ON C.DIVISION = D.DIVCOD   
WHERE (C.RUTINGRESO = @RUTINGRESO) AND (SUBSTRING(FECHA, 1, 6) = SUBSTRING(CONVERT(NVARCHAR(8),GETDATE(),112),1,6)) GROUP BY C.RUTINGRESO, W.NOMBRES, W.APELLIDOS

END
