CREATE PROCEDURE [dbo].[V4MVC_OSTARBOL_SELECT_POREMPRESA_TURNOS_CTTA]    
(@IDEMPRESA            NVARCHAR(10) = NULL) AS           
BEGIN    
  
	SELECT DISTINCT OST 
	FROM OSTARBOL 
	WHERE (MADRE = @IDEMPRESA OR EMPRESA = @IDEMPRESA) AND FTERMINO >= GETDATE() 
	ORDER BY 1 
  
END
