CREATE PROCEDURE [dbo].[V4MVC_DOCS_WORKERS_SELECT_ESTADODOC_CTTA]
(@RUT		NVARCHAR(10) = NULL
,@ID_DOC	INT = NULL
,@DIVISION	NVARCHAR(50) = NULL
,@COMUN		INT = NULL
,@COMUN_DIV	NVARCHAR(2) = NULL
,@EMPRESA	NVARCHAR(10) = NULL) AS
BEGIN
	IF @COMUN = 1
	BEGIN
		SELECT ID
			 , VALIDADO 
		FROM DOCS_WORKERS 
		WHERE (RUT = @RUT) AND 
		(ID_DOC = @ID_DOC) AND 
		(DIVISION = (CASE WHEN @COMUN_DIV = 'SI' THEN DIVISION ELSE @DIVISION END)) 
		ORDER BY ID_DOCS_WORKERS DESC
	END
	ELSE
	BEGIN
		SELECT ID, VALIDADO 
		FROM DOCS_WORKERS 
		WHERE (RUT = @RUT) AND 
		(ID_DOC = @ID_DOC) AND 
		(DIVISION = (CASE WHEN @COMUN_DIV = 'SI' THEN DIVISION ELSE @DIVISION END)) AND 
		(EMPRESA = @EMPRESA) 
		ORDER BY ID_DOCS_WORKERS DESC
	END
END

