CREATE PROCEDURE [dbo].[V4MVC_CASINO_SELECT_SERVICIOEMPRESA_CTTA]
(
 @FECHAINI		NVARCHAR(8)		= NULL
,@FECHAFIN		NVARCHAR(8)		= NULL
,@DIVCOD		NVARCHAR(4)		= NULL
,@LOCALES		NVARCHAR(MAX)	= NULL
,@IDEMPRESA		NVARCHAR(10)	= NULL
,@OPTION		NVARCHAR(1)		= NULL
)
AS
BEGIN

	SELECT value AS ID_LOCAL INTO #TEMP_SPLIT_LOCALES      
	FROM string_split(@LOCALES,',')   

	IF(@OPTION = 'B')
	BEGIN

		(SELECT  SERVICIO, COUNT(CANTIDAD) AS CANTIDAD
		FROM WC3_VISTA_CASINO 
		WHERE  (FECHA BETWEEN @FECHAINI AND @FECHAFIN) 
		AND (ISNULL(ERROR, '') = '') 
		AND EMPRESA = @IDEMPRESA
		AND DIVISION = @DIVCOD
		AND LOCAL IN (SELECT ID_LOCAL FROM #TEMP_SPLIT_LOCALES)
		GROUP BY EMPRESA, ACRONIMO, SERVICIO)
		UNION ALL
		(SELECT 'TOTAL', COUNT(CANTIDAD) AS CANTIDAD
		FROM WC3_VISTA_CASINO 
		WHERE  (FECHA BETWEEN @FECHAINI AND @FECHAFIN) 
		AND (ISNULL(ERROR, '') = '') 
		AND EMPRESA = @IDEMPRESA
		AND DIVISION = @DIVCOD
		AND LOCAL IN (SELECT ID_LOCAL FROM #TEMP_SPLIT_LOCALES))
		UNION ALL
		(SELECT 'ERROR' , SUM(CANTIDAD) AS CANTIDAD
		FROM WC3_VISTA_CASINO
		WHERE (FECHA BETWEEN @FECHAINI AND @FECHAFIN) 
		AND SERVICIO = 'ERROR'
		AND EMPRESA = @IDEMPRESA
		AND DIVISION = @DIVCOD
		AND LOCAL IN (SELECT ID_LOCAL FROM #TEMP_SPLIT_LOCALES))
		ORDER BY SERVICIO

	END

END
