CREATE PROCEDURE [dbo].[V4MVC_A056_FORM301_SELECT_CONTROLLABORAL_CTTA]
(
  @IDEMPRESA	NVARCHAR(11)
) AS
BEGIN
	DECLARE @ID_DOC INT = 93
	SELECT
		SS.ID,
		SS.ID_CERTIFICADO,
		SS.EMPRESA,
		SS.ACRONIMO,
		SS.REGION,
		SS.INSPECCION,
		SS.ANIO,
		SS.CERTIFICADO,
		SS.CLAVE,
		SS.PERIODO_INI,
		SS.PERIODO_FIN,
		SS.VALIDADO,
		SS.PERIODO,
		SS.OST,
		SS.DIVISION,
		SS.UNIQUE_ID,
		SS.DOC_ID,
		COALESCE(
			(
				SELECT
					TOP 1
						DD.ID_DISPUTA
				FROM DOCS_DISPUTA_CLABORAL DD
				WHERE
					DD.EMPRESA = SS.EMPRESA AND
					DD.PERIODO = SS.PERIODO AND
					DD.ID_DOC = @ID_DOC AND
					DD.ID = SS.UNIQUE_ID
				ORDER BY DD.ID_DISPUTA DESC
			), -1
		) AS DISPUTA_ID,
		COALESCE(
			(
				SELECT
					TOP 1
						DD.ESTADO
				FROM DOCS_DISPUTA_CLABORAL DD
				WHERE
					DD.EMPRESA = SS.EMPRESA AND
					DD.PERIODO = SS.PERIODO AND
					DD.ID_DOC = @ID_DOC AND
					DD.ID = SS.UNIQUE_ID
				ORDER BY DD.ID_DISPUTA DESC
			), ''
		) AS DISPUTA_ESTADO,
		IIF(EXISTS(
				SELECT * 
				FROM DOCS_DISPUTA_CLABORAL DD
				WHERE
					DD.EMPRESA = SS.EMPRESA AND
					DD.PERIODO = SS.PERIODO AND
					DD.ID_DOC = @ID_DOC AND
					DD.ID = SS.UNIQUE_ID
				ORDER BY DD.ID_DISPUTA DESC
				OFFSET 0 ROWS
		), 1 , 0) AS DISPUTA_EXISTE		
	FROM
	(
		SELECT
			F301D.ID,
			F301.ID_CERTIFICADO,
			F301.EMPRESA,
			VE.ACRONIMO,
			F301.REGION,
			F301.INSPECCION,
			F301.ANIO,
			F301.CERTIFICADO,
			F301.CLAVE,
			F301.PERIODO_INI,
			F301.PERIODO_FIN,
			F301.VALIDADO,
			F301.PERIODO,
			F301.OST,
			F301.DIVISION,
			IIF(F301D.ID IS NULL OR CONVERT(NVARCHAR(40), F301D.ID) = '', NULL, F301D.ID) AS UNIQUE_ID,
			IIF(F301D.ID IS NULL OR CONVERT(NVARCHAR(40), F301D.ID) = '', NULL, F301D.ID) AS DOC_ID
			FROM A056_FORM301 F301
			INNER JOIN V_ENTERPRISE VE
				ON F301.EMPRESA = VE.IDEMPRESA
			LEFT OUTER JOIN ARCHIVOS F301D
				ON F301.ID = F301D.ID
			WHERE (F301.EMPRESA = @IDEMPRESA)
			ORDER BY F301.CERTIFICADO ASC
		OFFSET 0 ROWS
	) SS	
END
