CREATE PROCEDURE [dbo].[V4MVC_POLIZAS_SELECT_DATATABLE_POLIZAS_CTTA]
AS
BEGIN

	SELECT DISTINCT D.NOMBRE,T.COMUN,T.ID_DOC AS IDDOC, DF.ID_DOC_EXT
	,(SELECT TOP 1 VALIDADO FROM POLIZAS WHERE IDDOC = D.ID_DOC ORDER BY FECHAMOD+HORAMOD DESC) AS POLIZA_VALIDADO
	,(SELECT DISTINCT TOP 1 PP.VALIDADO AS POLIZAPAGO_VALIDADO  
	FROM TAB_POLIZA T 
	INNER JOIN DOCS D ON T.ID_DOC=D.ID_DOC 
	LEFT JOIN  POLIZAS P  ON  P.IDDOC=D.ID_DOC
	LEFT JOIN  POLIZAS_PAGO PP ON PP.NROPOLIZA=P.NROPOLIZA AND PP.IDDOC=D.ID_DOC 
	WHERE T.ACTIVO='SI' AND P.IDDOC = D.ID_DOC) AS POLIZAPAGO_VALIDADO
	, CASE WHEN (SELECT TOP 1 FECFIN FROM POLIZAS WHERE IDDOC = D.ID_DOC ORDER BY FECHAMOD+HORAMOD DESC)<GETDATE() THEN 'SI' ELSE 'NO' END AS POLIZA_VENCIDA  
	, CASE WHEN (SELECT TOP 1 PP.PERINI FROM POLIZAS_PAGO PP INNER JOIN POLIZAS P ON PP.NROPOLIZA=P.NROPOLIZA
	WHERE PP.IDDOC= D.ID_DOC ORDER BY PERFIN DESC)<=LEFT(CONVERT(varchar, GetDate(),112),6) AND (SELECT TOP 1 PP.PERFIN FROM POLIZAS_PAGO PP INNER JOIN POLIZAS P ON PP.NROPOLIZA=P.NROPOLIZA
	WHERE PP.IDDOC= D.ID_DOC ORDER BY PERFIN DESC)>=LEFT(CONVERT(varchar, GetDate(),112),6) THEN 'SI' ELSE 'NO' END AS PAGOALDIA ,
	STUFF((
	      SELECT ',' + DOCS_EXT.EXTENSION
		   FROM DOCS_FORMATO, DOCS_EXT 
		   WHERE 
		   (DOCS_FORMATO.ID_DOC = T.ID_DOC) AND
		   (DOCS_FORMATO.ID_DOC_EXT = DOCS_EXT.ID_DOC_EXT)
       FOR XML PATH('')
	),1,1, '') AS EXTENSIONES
	FROM TAB_POLIZA T INNER JOIN DOCS D ON T.ID_DOC=D.ID_DOC 
	INNER JOIN DOCS_FORMATO DF ON T.ID_DOC = DF.ID_DOC
	WHERE T.ACTIVO='SI'

END