CREATE PROCEDURE [dbo].[V4MVC_PARAMETROS_V2_CURSOS_RESTRICCIONES_CTTA]
( @CODIGO   INT = NULL)
AS
BEGIN
	DECLARE @QUERY NVARCHAR(MAX)
	DECLARE @VAR1 NVARCHAR(500) = ''
	DECLARE @VAR2 NVARCHAR(500) = ''
	SELECT	@VAR1 = Valor1 FROM	PARAMETROS_V2 WHERE	DESCRIPCION = 'Cursos A1'
    SELECT	@VAR2 = Valor1 FROM	PARAMETROS_V2 WHERE	DESCRIPCION = 'Cursos Persona Nueva'
    SET @QUERY = 'DECLARE @RESTRICCION INT = 0
				  IF '''+ @VAR1 +''' IS NOT NULL
					IF EXISTS(SELECT * FROM A141_CURSOS WHERE (CODIGO = '+ CAST(@CODIGO AS NVARCHAR) + ') AND (CURSO IN ( '+ @VAR1 +')))
						SET @RESTRICCION = 1
				  IF '''+ @VAR2 +''' IS NOT NULL
					IF EXISTS(SELECT * FROM A141_CURSOS WHERE (CODIGO = ' + CAST(@CODIGO AS NVARCHAR) + ') AND (CURSO IN ('+ @VAR1 +')))
						SET @RESTRICCION = 2
				  SELECT @RESTRICCION AS RESTRICCION'
	EXEC(@QUERY)

END