CREATE PROCEDURE [dbo].[V4MVC_A141_CURSOS_SELECT]    
(
@CODIGO INT  
)
AS
BEGIN    
	SELECT T1.CODIGO		,T1.CURSO			,T1.FECHA			,T1.HORA
		  ,T1.LUGAR			,T1.SALA			,T1.ACTIVO			,T1.CAPACIDAD
		  ,T1.UBICACION		,T1.ACTIVA			,T1.CHARLA			,T1.DESCRIP
		  ,T1.HORAS			,T1.VENCIMIENTO		,T1.CANTIDAD		,T1.REALIZADO
		  ,T1.ORADOR		,T1.HORATERMINO		,T1.FINALIZADO		,T1.OBSERVACION
		  ,T1.OBLIGATORIO	,T1.NOTAORADOR		,T1.DIVISION		,T1.TIPOCURSO
		  ,STUFF((    SELECT ',' + DP.DIVISION   
			   FROM (SELECT DISTINCT D.DIVISION  
				 FROM CHARLAS_DIVISION AS CD  
				 INNER JOIN A024_DIVISIONES AS D ON D.DIVCOD = CD.DIVISION  
				 WHERE  CD.IDCHARLA = T1.CURSO  
				) AS DP  
			   ORDER BY DP.DIVISION  
			   FOR XML PATH('')  
			   ), 1, 1, '' ) AS DIVISIONES  
	FROM A141_CURSOS AS T1 
	WHERE T1.CODIGO = @CODIGO
END 
