CREATE PROCEDURE [dbo].[V4MVC_WORKERS_COUNT_BUSCADORCTTA]      
(      
@SEARCH_RUT			NVARCHAR(10) = NULL,  
@SEARCH_NOMBRES		NVARCHAR(50) = NULL,  
@SEARCH_APELLIDOS	NVARCHAR(50) = NULL,
@SEARCH_EMPRESA		NVARCHAR(50) = NULL,
@IDEMPRESA			NVARCHAR(11) = NULL
)      
AS      
BEGIN      
     
	 DECLARE @QUERY NVARCHAR(MAX)
	SET @QUERY  = 'SELECT COUNT(DISTINCT W.RUT) AS COUNT_WORKERS                             
	FROM WORKERS AS W
	INNER JOIN WORKERSLOCAL AS WL ON WL.RUT = W.RUT
	INNER JOIN ENTERPRISE AS E ON E.IDEMPRESA = WL.EMPRESA 
	WHERE (WL.AUTOR IN (''SI'',''NO'') OR WL.AUTOR IS NULL) 
		  AND WL.EMPRESA =''' + @IDEMPRESA + ''''
	IF @SEARCH_RUT IS NOT NULL BEGIN SET @QUERY = @QUERY + ' AND W.RUT LIKE ' + '''%' + @SEARCH_RUT + '%''' END
	IF @SEARCH_NOMBRES IS NOT NULL BEGIN SET @QUERY = @QUERY + ' AND W.NOMBRES LIKE ' + '''%' + @SEARCH_NOMBRES + '%''' END
	IF @SEARCH_APELLIDOS IS NOT NULL BEGIN SET @QUERY = @QUERY + ' AND W.APELLIDOS LIKE ' + '''%' + @SEARCH_APELLIDOS + '%''' END
	IF @SEARCH_EMPRESA IS NOT NULL BEGIN SET @QUERY = @QUERY + ' AND E.ACRONIMO LIKE ' + '''%' + @SEARCH_EMPRESA + '%''' END
	PRINT (@QUERY)
	EXEC(@QUERY)

   
END 