CREATE PROCEDURE [dbo].[V4MVC_WORKERSLOCAL_SELECT_ONE_RUT_CTTA]
/*
EXEC V4MVC_WORKERSLOCAL_SELECT_ONE_RUT_CTTA '06641086',0
EXEC V4MVC_WORKERSLOCAL_SELECT_ONE_RUT_CTTA '89526892',0
*/
(
 @RUT			NVARCHAR(20) = NULL
,@RESTRICCIONES	INT
)
AS
BEGIN
DECLARE @DIVISION	NVARCHAR(MAX)
DECLARE @EMPRESA	NVARCHAR(20)
DECLARE @NOMBRE		NVARCHAR(100)
DECLARE @APELLIDOS	NVARCHAR(100)
DECLARE @AUTOR		NVARCHAR(4)

CREATE TABLE #WORKES (
EMPRESA				NVARCHAR(20)
,NOMBRES			NVARCHAR(100)
,APELLIDOS			NVARCHAR(100)
,AUTOR				NVARCHAR(4)
,PUEDE_PEDIR_PASE	NVARCHAR(10)
,RESTRICCION		INT
)
	IF EXISTS (
	SELECT  EMPRESA FROM WORKERS WHERE RUT = @RUT)
	BEGIN
		IF (@RESTRICCIONES <> 0 ) 
		BEGIN 
			SELECT @DIVISION = VALOR1 FROM PARAMETROS_V2 WHERE DESCRIPCION = 'Cursos Reserva Restricciones'
			DECLARE @QUERY		NVARCHAR (MAX)
			SET @QUERY = (' 
				INSERT INTO #WORKES
				(EMPRESA)
				SELECT   EMPRESA 
				FROM WORKERSLOCAL 
				WHERE (dbo.hoy(GETDATE()) BETWEEN FINIPASE AND FFINPASE) 
				AND (AUTOR IN (''SI'',''NO'')) 
				AND (RUT =  '''+  CAST(@RUT AS NVARCHAR)  + ''') AND ( DIVISION IN ( '+ @DIVISION +') )  
				')
				EXEC (@QUERY)
				IF EXISTS (
					SELECT EMPRESA FROM #WORKES
				)
					UPDATE #WORKES SET  EMPRESA  = @EMPRESA
				ELSE
					INSERT INTO #WORKES (EMPRESA) VALUES ('108')
				
		END
		ELSE
		BEGIN
			IF EXISTS (
				SELECT EMPRESA  FROM WORKERSLOCAL 
				WHERE (dbo.hoy(GETDATE()) BETWEEN FINIPASE AND FFINPASE) 
				AND (AUTOR IN ('SI','NO')) 
				AND (RUT =   @RUT) ) 
			BEGIN 
				INSERT INTO #WORKES
				(EMPRESA)
				SELECT TOP 1 EMPRESA  FROM WORKERSLOCAL 
				WHERE (dbo.hoy(GETDATE()) BETWEEN FINIPASE AND FFINPASE) 
				AND (AUTOR IN ('SI','NO')) 
				AND (RUT =   @RUT) 
			END
			ELSE	
				INSERT INTO #WORKES (EMPRESA) VALUES ('108') 
		END
		SELECT @NOMBRE=NOMBRES		,@APELLIDOS=APELLIDOS	,@AUTOR=AUTOR 
		FROM WORKERS WHERE RUT = @RUT

		UPDATE #WORKES
		SET NOMBRES = @NOMBRE     ,APELLIDOS=@APELLIDOS			,AUTOR= @AUTOR

		IF ( @AUTOR ='SI' OR @AUTOR = 'XX')
		BEGIN
			UPDATE #WORKES SET PUEDE_PEDIR_PASE = 'FALSE'
		END
		UPDATE #WORKES SET RESTRICCION = @RESTRICCIONES
		SELECT* , DBO.HOY(GETDATE()) AS FECHA , DBO.AHORA(GETDATE()) AS HORA  FROM #WORKES

	END
	ELSE
		SELECT '' AS Empresa ,DBO.HOY(GETDATE()) AS FECHA , DBO.AHORA(GETDATE()) AS HORA
END
