CREATE PROCEDURE [dbo].[V4MVC_A056_FORM301_SELECT_ONE_V2_CONTROLLABORAL_CTTA]
(
  @ID_CERTIFICADO INT
) AS
BEGIN
	SELECT
		CERTUSUARIO,
		CERTFECHA,
		CERTHORA,
		VALIDADO,
		ID_CERTIFICADO
	FROM A056_FORM301
	WHERE
		ID_CERTIFICADO = @ID_CERTIFICADO
END
