
CREATE PROCEDURE [dbo].[V4MVC_OSTARBOL_SELECT_BYEMPRESA_CTTA]    
(@EMPRESA            NVARCHAR(11) = NULL) AS           
BEGIN    
  
	SELECT OST	,NIVEL,FINICIO,FTERMINO
	FROM OSTARBOL 
	WHERE  EMPRESA = @EMPRESA AND FTERMINO >= GETDATE() 
	ORDER BY NIVEL ASC

  
END

