CREATE PROCEDURE [dbo].[V4MVC_CHECKINGINGHEAD_SELECT_INFORME_CHECKLIST_TESTVEHICULO_INFORME_CHECKLIST_CTTA]
(
@PATENTE  NVARCHAR(50) = NULL,
@TIPOVEHICULO INT = NULL,
@ID_CHECK INT = NULL,
@FECHAINI  NVARCHAR(8)       = NULL,
@FECHAFIN  NVARCHAR(8)       = NULL,
@EMPRESA  NVARCHAR(10)       = NULL,
@ESTADO  NVARCHAR(2)       = NULL
) AS
BEGIN

DECLARE @strSQL as nvarchar(MAX)

 SET @strSQL='SELECT  
    COUNT(CHKNGH.ID_CHECKINGHEAD) OVER() TOTALREGISTROS
  ,ROW_NUMBER() OVER(ORDER BY CHKNGH.FECCREA) ROWNUMBER
  ,CHKNGH.ID_CHECKINGHEAD
  , TR.EMPRESA
  , E.ACRONIMO
  , CHKNGH.USRCREA
  , W.NOMBRES
  , W.APELLIDOS
  , CHKNGH.ID_TIPO
  , TP.NOMBRE AS TIPO
  , CHKNGH.ID_CHECKING
  , CHKNGH.ID_CHECK
  , CHK.NOMBRE AS CHECKLIST
  , CHKNGH.IDENTIFICADOR
  , TR.TIPO AS TIPOVEHICULO
  , TY.DSCTIPOV AS NOMBRE_IDENTIFICADOR
  , CHKNGH.FECHA
  , CASE WHEN (SELECT COUNT(*) FROM CHECK_DETAIL CHKDET1 
       INNER JOIN [CHECK_CHECKINGDETAIL] CHKNGDET1 ON CHKDET1.ID_TIPO = CHKNGDET1.ID_TIPO AND CHKDET1.ID_CHECK = CHKNGDET1.ID_CHECK AND CHKDET1.ID_CHECKDET = CHKNGDET1.ID_CHECKINGDET 
       WHERE CHKNGDET1.ID_TIPO = CHKNGH.ID_TIPO AND CHKNGDET1.ID_CHECK = CHKNGH.ID_CHECK AND CHKNGDET1.ID_CHECKING = CHKNGH.ID_CHECKING AND CHKNGDET1.ID_CHECKINGHEAD = CHKNGH.ID_CHECKINGHEAD)
	   =(SELECT COUNT(*) AS CANT FROM CHECK_DETAIL CHKDET2 
       INNER JOIN [CHECK_CHECKINGDETAIL] CHKNGDET2 ON CHKDET2.ID_TIPO = CHKNGDET2.ID_TIPO AND CHKDET2.ID_CHECK = CHKNGDET2.ID_CHECK AND CHKDET2.ID_CHECKDET = CHKNGDET2.ID_CHECKINGDET 
       WHERE CHKNGDET2.ID_TIPO = CHKNGH.ID_TIPO AND CHKNGDET2.ID_CHECK = CHKNGH.ID_CHECK AND CHKNGDET2.ID_CHECKING = CHKNGH.ID_CHECKING AND CHKNGDET2.ID_CHECKINGHEAD = CHKNGH.ID_CHECKINGHEAD AND CHKNGDET2.VALOR=''SI'') THEN ''SI'' ELSE ''NO'' END AS CORRECTO
  , ISNULL(CHKNGH.VALIDADO, ''N'') AS VALIDADO
   ,(SELECT MIN(HORA) + ''  - '' + MAX(HORA) FROM [CHECK_CHECKINGDETAIL] WHERE ID_TIPO = CHKNGH.ID_TIPO AND ID_CHECK = CHKNGH.ID_CHECK AND ID_CHECKING = CHKNGH.ID_CHECKING AND ID_CHECKINGHEAD = CHKNGH.ID_CHECKINGHEAD ) AS HORA 
	FROM TYPETRANS AS TY INNER JOIN 
	TRANSPORT AS TR ON TY.IDTIPO = TR.TIPO RIGHT OUTER JOIN 
	CHECK_CHECKINGINGHEAD AS CHKNGH INNER JOIN 
	[CHECK] AS CHK ON CHKNGH.ID_TIPO = CHK.ID_TIPO AND CHKNGH.ID_CHECK = CHK.ID_CHECK INNER JOIN 
	CHECK_TIPO AS TP ON CHK.ID_TIPO = TP.ID_TIPO ON TR.PATENTE = CHKNGH.IDENTIFICADOR LEFT OUTER JOIN 
	WORKERS AS W ON CHKNGH.USRCREA = W.RUT LEFT OUTER JOIN 
	ENTERPRISE AS E ON TR.EMPRESA = E.IDEMPRESA 
	WHERE CHKNGH.ID_TIPO=''TDV''' 

		            IF @ESTADO <> '' OR @ESTADO <> NULL
		            BEGIN
		            	Set @strSQL = @strSQL + N' AND (SELECT [dbo].[ValidaCheckListItems](CHKNGH.ID_TIPO,CHKNGH.ID_CHECK,CHKNGH.ID_CHECKING,CHKNGH.ID_CHECKINGHEAD))= ''' + @ESTADO + ''''
		            END	
		            IF @PATENTE <> '' OR @PATENTE <> NULL
		            BEGIN
		            	Set @strSQL = @strSQL + N' AND IDENTIFICADOR = ''' + @PATENTE + ''''
		            END		
		            IF @TIPOVEHICULO <> '' OR @TIPOVEHICULO <> NULL
		            BEGIN
		            	Set @strSQL = @strSQL + N' AND TR.TIPO = ''' + CONVERT(NVARCHAR(10),@TIPOVEHICULO) + ''''
		            END							
		            IF @ID_CHECK <> '' OR @ID_CHECK <> NULL
		            BEGIN
		            	Set @strSQL = @strSQL + N' AND CHKNGH.ID_CHECK = ''' + CONVERT(NVARCHAR(10),@ID_CHECK)  + ''''
		            END	

					Set @strSQL = @strSQL + N' AND (FECHA  BETWEEN ''' + @FECHAINI + ''' AND ''' +  @FECHAFIN + ''')'	
					Set @strSQL = @strSQL + N' AND TR.EMPRESA = ''' + @EMPRESA + ''''	

					exec sp_executesql @strSQL  
					PRINT @strSQL




 
END	
