CREATE PROCEDURE [dbo].[V4MVC_ACREDITACION_VEHICULAR_SELECT_FECHAS_ACREDITACIONVEHICULARCTTA]
(
@EMPRESA  NVARCHAR(10) = NULL
) AS
BEGIN
DECLARE @HorasD1 INT,@HorasD2 INT,@HorasM2 INT,@HorasT2 INT,@EXPD INT,@HORAINI NVARCHAR(8),@HORAINI_COL NVARCHAR(8),@HORAFIN NVARCHAR(8),@HORAFIN_COL NVARCHAR(8),@LUN NVARCHAR(4),@MAR NVARCHAR(4),@MIE NVARCHAR(4)
       ,@JUE NVARCHAR(4),@VIE NVARCHAR(4),@SAB NVARCHAR(4),@DOM NVARCHAR(4),@LIMITE NVARCHAR(8),@strSQL as nvarchar(MAX),@DIAS NVARCHAR(100)

SELECT @EXPD=EXPD
      ,@HORAINI=HORAINI
	  ,@HORAINI_COL=HORAINI_COL
	  ,@HORAFIN=HORAFIN
	  ,@HORAFIN_COL=HORAFIN_COL 
	  ,@LUN=LUN 
	  ,@MAR=MAR 
	  ,@MIE=MIE 
	  ,@JUE=JUE 
	  ,@VIE=VIE 
	  ,@SAB=SAB 
      ,@DOM=DOM 
FROM TAB_REVISIONVEH WHERE ACTIVO='SI'
SET @LIMITE = CONVERT(varchar,DATEADD(hour,1,GETDATE()),8)
SET @DIAS = '0'


		SET @HorasD1 = (DATEDIFF(HOUR,@HORAINI,@HORAINI_COL) + DATEDIFF(HOUR,@HORAFIN_COL,@HORAFIN) )*@EXPD 
		IF @HORAINI<@LIMITE And @HORAINI_COL<@LIMITE
		BEGIN
			SET @HorasM2=0
		END
		ELSE
		BEGIN
			IF @HORAINI<@LIMITE And @LIMITE<@HORAINI_COL 
			BEGIN	
				SET @HorasM2=DATEDIFF(HOUR,@LIMITE,@HORAINI_COL) 
			END
			ELSE
			BEGIN
				SET @HorasM2=DATEDIFF(HOUR,@HORAINI,@HORAINI_COL)
			END
		END
		
		IF @HORAFIN_COL<@LIMITE And @HORAFIN< @LIMITE 
		BEGIN
			SET @HorasT2=0
		END
		ELSE
		BEGIN
			IF @HORAFIN_COL<@LIMITE And @LIMITE<@HORAFIN 
			BEGIN
				SET @HorasT2 = DATEDIFF(HOUR,@LIMITE,@HORAFIN)
			END
			ELSE
			BEGIN
				SET @HorasT2 = DATEDIFF(HOUR,@HORAFIN_COL,@HORAFIN)
			END
		END
		SET @HorasD2 = (@HorasM2+@HorasT2)*@EXPD 
	
SET @strSQL='SELECT DISTINCT CONVERT(VARCHAR(8),X.[Date],112) AS FECHARES, CONVERT(VARCHAR(8),X.[Date],112) AS FECHARES_LETRA,
    CASE WHEN GETDATE() = X.[Date] THEN ' + convert(varchar(10),@HorasD2) + '-ISNULL(SUM(t.MINUTOS),0)/60
         ELSE ' + convert(varchar(10),@HorasD1) + '-ISNULL(SUM(t.MINUTOS),0)/60 END AS DISPONIBLES,
		 COUNT(t2.ID) AS COUNT_RESERVAS,X.[Date]
    FROM 
    (SELECT [Date] = DATEADD(Day,Number,GETDATE())  
    FROM  master..spt_values  
    WHERE Type=''P''
    AND DATEADD(day,Number,GETDATE()) <= DATEADD(YEAR,1,GETDATE())'
    IF @LUN = 'SI'
	BEGIN
		Set @DIAS = @DIAS + N',1'
	END	
    IF @MAR = 'SI'
	BEGIN
		Set @DIAS = @DIAS + N',2'
	END	
    IF @MIE = 'SI'
	BEGIN
		Set @DIAS = @DIAS + N',3'
	END	
    IF @JUE = 'SI'
	BEGIN
	    Set @DIAS = @DIAS + N',4'
	END	
    IF @VIE = 'SI'
	BEGIN
		Set @DIAS = @DIAS + N',5'
	END	
    IF @SAB = 'SI'
	BEGIN
		Set @DIAS = @DIAS + N',6'
	END	
    IF @DOM = 'SI'
	BEGIN
		Set @DIAS = @DIAS + N',7'
	END	
	Set @strSQL = @strSQL + N' AND DATEPART(DW, DATEADD(Day,Number,GETDATE())) IN (' + @DIAS + ')'
	Set @strSQL = @strSQL + N' AND NOT EXISTS(SELECT * FROM TABFERIADOS WHERE FECHA LIKE ''20%''+FORMAT(DATEADD(Day,Number,GETDATE()),''MMdd''))'
 	Set @strSQL = @strSQL + N' )X LEFT JOIN  RESERVAS_REVISION_VEHICULAR t ON CONVERT(VARCHAR(8),X.[Date],112) = t.FECHARES
	                              LEFT JOIN  RESERVAS_REVISION_VEHICULAR t2 ON CONVERT(VARCHAR(8),X.[Date],112) = t2.FECHARES AND t2.EMPRESA=''' + @EMPRESA + ''' AND t2.FECHASOL=t2.FECHAMOD AND t2.HORASOL=t2.HORAMOD
								  GROUP BY X.[Date],t2.ID
								  ORDER BY X.[Date] ASC'
	
    exec sp_executesql @strSQL  
	PRINT @strSQL


END

