CREATE PROCEDURE [dbo].[V4MVC_WORKERS_SEARCHER_MDTE]
(@START			INT				= NULL
,@LENGTH		INT				= NULL
,@RUT			NVARCHAR(10)	= NULL
,@NOMBRES		NVARCHAR(50)	= NULL
,@APELLIDOS		NVARCHAR(50)	= NULL
,@ACRONIMO		NVARCHAR(50)	= NULL
,@COLUMN		NVARCHAR(4)		= NULL
,@DIRECTION		NVARCHAR(4)		= NULL)
AS
BEGIN

	DECLARE @QUERY NVARCHAR(MAX) = ''
	
	CREATE TABLE #TEMPWORKERS
	(RUT			NVARCHAR(10)	COLLATE DATABASE_DEFAULT NULL
	,NOMBRES		NVARCHAR(50)	COLLATE DATABASE_DEFAULT NULL
	,APELLIDOS		NVARCHAR(50)	COLLATE DATABASE_DEFAULT NULL
	,EMPRESA		NVARCHAR(10)	COLLATE DATABASE_DEFAULT NULL
	,[COUNT]		INT)

	SET @QUERY = @QUERY + '
	SELECT W.RUT ,W.NOMBRES ,W.APELLIDOS ,W.EMPRESA ,COUNT(*) OVER() AS [COUNT]
	FROM V_WORKERS W
	WHERE AUTOR <> ' + '''' + 'XX' + ''''
	IF @RUT			IS NOT NULL	BEGIN SET @QUERY = @QUERY + ' AND W.RUT LIKE ' + '''%' + @RUT + '%''' END
	IF @NOMBRES		IS NOT NULL	BEGIN SET @QUERY = @QUERY + ' AND W.NOMBRES LIKE ' + '''%' + @NOMBRES + '%''' END
	IF @APELLIDOS	IS NOT NULL	BEGIN SET @QUERY = @QUERY + ' AND W.APELLIDOS LIKE ' + '''%' + @APELLIDOS + '%''' END
	IF @ACRONIMO	IS NOT NULL	BEGIN SET @QUERY = @QUERY + ' AND W.RUT IN (SELECT DISTINCT RUT 
																			FROM WORKERSLOCAL AS W, 
																			ENTERPRISE AS E 
																			WHERE W.EMPRESA = E.IDEMPRESA 
																			AND E.ACRONIMO LIKE ' + '''%' + @ACRONIMO + '%''' + ')' END

	IF @COLUMN='0' BEGIN SET @QUERY = @QUERY + ' ORDER BY W.RUT ' +  @DIRECTION END   
	IF @COLUMN='1' BEGIN SET @QUERY = @QUERY + ' ORDER BY W.NOMBRES ' + @DIRECTION END   
	IF @COLUMN='2' BEGIN SET @QUERY = @QUERY + ' ORDER BY W.APELLIDOS '  + @DIRECTION END 
	IF @COLUMN='3' BEGIN SET @QUERY = @QUERY + ' ORDER BY ACRONIMO ' + @DIRECTION END

	SET @QUERY = @QUERY + ' OFFSET ' + CAST(@START AS VARCHAR) + ' ROWS FETCH NEXT ' + CAST(@LENGTH AS VARCHAR) + ' ROWS ONLY '

	INSERT INTO #TEMPWORKERS
	EXEC(@QUERY)

	SELECT TW.RUT ,TW.NOMBRES ,TW.APELLIDOS ,TW.EMPRESA ,TW.[COUNT]
	,ISNULL((SELECT STUFF((SELECT DISTINCT ',' + E.ACRONIMO  
							FROM WORKERSLOCAL WL
							INNER JOIN ENTERPRISE E ON WL.EMPRESA = E.IDEMPRESA
							WHERE  WL.AUTOR <> 'BL'
							AND WL.RUT = TW.RUT
							AND dbo.hoy(GETDATE()) BETWEEN WL.FINIPASE AND WL.FFINPASE 
							FOR XML PATH('')
							),1,1, ''))
			,'SIN EMPRESA') AS ACRONIMO
	FROM #TEMPWORKERS TW

END