//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewEnterpriseCtta {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewEnterpriseCtta() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.General.Login.NewEnterpriseCtta", typeof(NewEnterpriseCtta).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Btn_Cancelar {
            get {
                return ResourceManager.GetString("Btn_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string Btn_Ingresar {
            get {
                return ResourceManager.GetString("Btn_Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso Nueva Empresa.
        /// </summary>
        public static string Lgn_IngresaNuevaEmpresa {
            get {
                return ResourceManager.GetString("Lgn_IngresaNuevaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Estado de la empresa ACRONIMO ingresada con ID.
        /// </summary>
        public static string Msg_EstadoEmpresaAcronimo {
            get {
                return ResourceManager.GetString("Msg_EstadoEmpresaAcronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Está con estado Falta Documentación, No puede acceder a faena, Es necesario comunicarse con el entidad certificadora del mandante..
        /// </summary>
        public static string Msg_EstadoEmpresaAcronimo2 {
            get {
                return ResourceManager.GetString("Msg_EstadoEmpresaAcronimo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Estado de la empresa ingresada con ID.
        /// </summary>
        public static string Msg_EstadoID {
            get {
                return ResourceManager.GetString("Msg_EstadoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Esta BLOQUEADA INDEFINIDAMENTE, No puede acceder a faena por ningún motivo..
        /// </summary>
        public static string Msg_EstadoID2 {
            get {
                return ResourceManager.GetString("Msg_EstadoID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se detecto un estado de la empresa no reconocido. Es necesario comunicarse con el entidad certificadora del mandante..
        /// </summary>
        public static string Msg_EstadoNoReconocido {
            get {
                return ResourceManager.GetString("Msg_EstadoNoReconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ID debe ingresarse, sin puntos ni guiones..
        /// </summary>
        public static string Msg_IngresarID {
            get {
                return ResourceManager.GetString("Msg_IngresarID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para solicitar pases de manera satisfactoria debe estar registrado como empresa en nuestra base de datos. Si no está registrado ingrese su rut de empresa y haga clic en el botón Ingresar..
        /// </summary>
        public static string Msg_SolicitarPases {
            get {
                return ResourceManager.GetString("Msg_SolicitarPases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Empresa.
        /// </summary>
        public static string Phl_IDEmpresa {
            get {
                return ResourceManager.GetString("Phl_IDEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Empresa debe tener 8 caracteres como mínimo.
        /// </summary>
        public static string Val_IDEmpresa8caracteres {
            get {
                return ResourceManager.GetString("Val_IDEmpresa8caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Empresa debe tener 9 caracteres como máximo.
        /// </summary>
        public static string Val_IDEmpresa9Caracteres {
            get {
                return ResourceManager.GetString("Val_IDEmpresa9Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Empresa inválido.
        /// </summary>
        public static string Val_IDEmpresaInválido {
            get {
                return ResourceManager.GetString("Val_IDEmpresaInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Empresa es requerido.
        /// </summary>
        public static string Val_IdEmpresaRequerido {
            get {
                return ResourceManager.GetString("Val_IdEmpresaRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo números, letras y sin espacios en blanco.
        /// </summary>
        public static string Val_SoloNumeroLetrasSinEspacio {
            get {
                return ResourceManager.GetString("Val_SoloNumeroLetrasSinEspacio", resourceCulture);
            }
        }
    }
}
