//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.Aprobasion_SubContratos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _EnProceso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _EnProceso() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.Aprobacion_SubContratos._EnProceso", typeof(_EnProceso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptado.
        /// </summary>
        public static string Tblb_Aceptado {
            get {
                return ResourceManager.GetString("Tblb_Aceptado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin AA.
        /// </summary>
        public static string Tblb_Admin {
            get {
                return ResourceManager.GetString("Tblb_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string Tblb_Btn_Ver {
            get {
                return ResourceManager.GetString("Tblb_Btn_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gerencia Seguridad.
        /// </summary>
        public static string Tblb_Gerencia {
            get {
                return ResourceManager.GetString("Tblb_Gerencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente.
        /// </summary>
        public static string Tblb_Pendiente {
            get {
                return ResourceManager.GetString("Tblb_Pendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazada.
        /// </summary>
        public static string Tblb_Rechazada {
            get {
                return ResourceManager.GetString("Tblb_Rechazada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supply Chain.
        /// </summary>
        public static string Tblb_Supply {
            get {
                return ResourceManager.GetString("Tblb_Supply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acronimo Sub contratista.
        /// </summary>
        public static string Tblf_Acronimo {
            get {
                return ResourceManager.GetString("Tblf_Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato.
        /// </summary>
        public static string Tblf_Contrato {
            get {
                return ResourceManager.GetString("Tblf_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Tblf_Estado {
            get {
                return ResourceManager.GetString("Tblf_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        public static string Tblf_Fecha_Inicio {
            get {
                return ResourceManager.GetString("Tblf_Fecha_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Termino.
        /// </summary>
        public static string Tblf_Fecha_Termino {
            get {
                return ResourceManager.GetString("Tblf_Fecha_Termino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Sub Contratista.
        /// </summary>
        public static string Tblf_ID {
            get {
                return ResourceManager.GetString("Tblf_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string Tblf_Nivel {
            get {
                return ResourceManager.GetString("Tblf_Nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acronimo Sub contratista.
        /// </summary>
        public static string Tblh_Acronimo {
            get {
                return ResourceManager.GetString("Tblh_Acronimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato.
        /// </summary>
        public static string Tblh_Contrato {
            get {
                return ResourceManager.GetString("Tblh_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Tblh_Estado {
            get {
                return ResourceManager.GetString("Tblh_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        public static string Tblh_Fecha_Inicio {
            get {
                return ResourceManager.GetString("Tblh_Fecha_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Termino.
        /// </summary>
        public static string Tblh_Fecha_Termino {
            get {
                return ResourceManager.GetString("Tblh_Fecha_Termino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Sub Contratista.
        /// </summary>
        public static string Tblh_ID {
            get {
                return ResourceManager.GetString("Tblh_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string Tblh_Nivel {
            get {
                return ResourceManager.GetString("Tblh_Nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string Tblh_Ver {
            get {
                return ResourceManager.GetString("Tblh_Ver", resourceCulture);
            }
        }
    }
}
