//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mandante.CursosProgramados {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CrearEditar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrearEditar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Mandante.CursosProgramados.CrearEditar", typeof(CrearEditar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVADO.
        /// </summary>
        public static string Item_Privado {
            get {
                return ResourceManager.GetString("Item_Privado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUBLICO.
        /// </summary>
        public static string Item_Publico {
            get {
                return ResourceManager.GetString("Item_Publico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPETIR PROGRAMA.
        /// </summary>
        public static string Item_RepetirPrograma {
            get {
                return ResourceManager.GetString("Item_RepetirPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONE TIPO CURSO.
        /// </summary>
        public static string Item_TipoCurso {
            get {
                return ResourceManager.GetString("Item_TipoCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Lbl_Activo {
            get {
                return ResourceManager.GetString("Lbl_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charla.
        /// </summary>
        public static string Lbl_Charla {
            get {
                return ResourceManager.GetString("Lbl_Charla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Curso Programado .
        /// </summary>
        public static string Lbl_EditarCursoProgramado {
            get {
                return ResourceManager.GetString("Lbl_EditarCursoProgramado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Lbl_Fecha {
            get {
                return ResourceManager.GetString("Lbl_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string Lbl_Hora {
            get {
                return ResourceManager.GetString("Lbl_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar.
        /// </summary>
        public static string Lbl_Lugar {
            get {
                return ResourceManager.GetString("Lbl_Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Curso Programado.
        /// </summary>
        public static string Lbl_NuevoCursoProgramado {
            get {
                return ResourceManager.GetString("Lbl_NuevoCursoProgramado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orador.
        /// </summary>
        public static string Lbl_Orador {
            get {
                return ResourceManager.GetString("Lbl_Orador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizado.
        /// </summary>
        public static string Lbl_Realizado {
            get {
                return ResourceManager.GetString("Lbl_Realizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir Programa.
        /// </summary>
        public static string Lbl_RepetirPrograma {
            get {
                return ResourceManager.GetString("Lbl_RepetirPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala.
        /// </summary>
        public static string Lbl_Sala {
            get {
                return ResourceManager.GetString("Lbl_Sala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Curso.
        /// </summary>
        public static string Lbl_TipoCurso {
            get {
                return ResourceManager.GetString("Lbl_TipoCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado Cursos Programados.
        /// </summary>
        public static string Lnk_CursosProgramados {
            get {
                return ResourceManager.GetString("Lnk_CursosProgramados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHARLA.
        /// </summary>
        public static string Phl_Charla {
            get {
                return ResourceManager.GetString("Phl_Charla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA.
        /// </summary>
        public static string Phl_Fecha {
            get {
                return ResourceManager.GetString("Phl_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORA.
        /// </summary>
        public static string Phl_Hora {
            get {
                return ResourceManager.GetString("Phl_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUGAR.
        /// </summary>
        public static string Phl_Lugar {
            get {
                return ResourceManager.GetString("Phl_Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORADOR.
        /// </summary>
        public static string Phl_Orador {
            get {
                return ResourceManager.GetString("Phl_Orador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALA.
        /// </summary>
        public static string Phl_Sala {
            get {
                return ResourceManager.GetString("Phl_Sala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string Rdo_No {
            get {
                return ResourceManager.GetString("Rdo_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        public static string Rdo_Si {
            get {
                return ResourceManager.GetString("Rdo_Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charla es Requerida.
        /// </summary>
        public static string Val_Charla {
            get {
                return ResourceManager.GetString("Val_Charla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha es Requerida.
        /// </summary>
        public static string Val_Fecha {
            get {
                return ResourceManager.GetString("Val_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora es requerida.
        /// </summary>
        public static string Val_Hora {
            get {
                return ResourceManager.GetString("Val_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar es requerido.
        /// </summary>
        public static string Val_Lugar {
            get {
                return ResourceManager.GetString("Val_Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orador es requerido.
        /// </summary>
        public static string Val_Orador {
            get {
                return ResourceManager.GetString("Val_Orador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Repetir Programa.
        /// </summary>
        public static string Val_RepetirPrograma {
            get {
                return ResourceManager.GetString("Val_RepetirPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala es Requerida.
        /// </summary>
        public static string Val_Sala {
            get {
                return ResourceManager.GetString("Val_Sala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Tipo Curso.
        /// </summary>
        public static string Val_TipoCurso {
            get {
                return ResourceManager.GetString("Val_TipoCurso", resourceCulture);
            }
        }
    }
}
