//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.InformesFuncionarios {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InformeFichaFuncionarios_Detalle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformeFichaFuncionarios_Detalle() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.InformesFuncionarios.InformeFichaFuncion" +
                            "arios_Detalle", typeof(InformeFichaFuncionarios_Detalle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Resultado Certificación y Fechas Funcionario.
        /// </summary>
        public static string Lbl_DetalleResultadoCertificacionYFechasFuncionario {
            get {
                return ResourceManager.GetString("Lbl_DetalleResultadoCertificacionYFechasFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota.
        /// </summary>
        public static string Msg_Nota {
            get {
                return ResourceManager.GetString("Msg_Nota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos del reporte corresponden a la Fecha Actual que se muestra en la parte superior del informe.
        /// </summary>
        public static string Msg_NotaMensaje {
            get {
                return ResourceManager.GetString("Msg_NotaMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Tblb_Datos_Empresa {
            get {
                return ResourceManager.GetString("Tblb_Datos_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string Tblb_Datos_ID {
            get {
                return ResourceManager.GetString("Tblb_Datos_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Tblb_Datos_Nombre {
            get {
                return ResourceManager.GetString("Tblb_Datos_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación.
        /// </summary>
        public static string Tblb_Datos_Operación {
            get {
                return ResourceManager.GetString("Tblb_Datos_Operación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Pase.
        /// </summary>
        public static string Tblb_Datos_TipoPase {
            get {
                return ResourceManager.GetString("Tblb_Datos_TipoPase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencia Entregada.
        /// </summary>
        public static string Tblb_DocumentosConductores_LicenciaEntregada {
            get {
                return ResourceManager.GetString("Tblb_DocumentosConductores_LicenciaEntregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite Conducción en Faena.
        /// </summary>
        public static string Tblb_DocumentosConductores_PermiteConduccionEnFaena {
            get {
                return ResourceManager.GetString("Tblb_DocumentosConductores_PermiteConduccionEnFaena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posee Pase Condución en Faena.
        /// </summary>
        public static string Tblb_DocumentosConductores_PoseePaseConducionEnFaena {
            get {
                return ResourceManager.GetString("Tblb_DocumentosConductores_PoseePaseConducionEnFaena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite Acceso a Faena.
        /// </summary>
        public static string Tblb_DocumentosFuncionarios_PermiteAccesoAFaena {
            get {
                return ResourceManager.GetString("Tblb_DocumentosFuncionarios_PermiteAccesoAFaena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        public static string Tblh_DocumentosConductores_Documento {
            get {
                return ResourceManager.GetString("Tblh_DocumentosConductores_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos y Fechas Conductores en Faena.
        /// </summary>
        public static string Tblh_DocumentosConductores_DocumentosYFechasConductoresEnFaena {
            get {
                return ResourceManager.GetString("Tblh_DocumentosConductores_DocumentosYFechasConductoresEnFaena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Tblh_DocumentosConductores_Estado {
            get {
                return ResourceManager.GetString("Tblh_DocumentosConductores_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Tblh_DocumentosConductores_Fecha {
            get {
                return ResourceManager.GetString("Tblh_DocumentosConductores_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        public static string Tblh_DocumentosFuncionarios_Documento {
            get {
                return ResourceManager.GetString("Tblh_DocumentosFuncionarios_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos y Fechas Funcionarios Según Operación.
        /// </summary>
        public static string Tblh_DocumentosFuncionarios_DocumentosYFechasFuncionariosSegunOperacion {
            get {
                return ResourceManager.GetString("Tblh_DocumentosFuncionarios_DocumentosYFechasFuncionariosSegunOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Tblh_DocumentosFuncionarios_Estado {
            get {
                return ResourceManager.GetString("Tblh_DocumentosFuncionarios_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Tblh_DocumentosFuncionarios_Fecha {
            get {
                return ResourceManager.GetString("Tblh_DocumentosFuncionarios_Fecha", resourceCulture);
            }
        }
    }
}
