//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratista.InformesContratosCarpetaArranque {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V4mvc.Presentation.Resources.Contratista.InformesContratosCarpetaArranque.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener Informe.
        /// </summary>
        public static string Btn_Obtener_Informe {
            get {
                return ResourceManager.GetString("Btn_Obtener_Informe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string Lbl_Informacion {
            get {
                return ResourceManager.GetString("Lbl_Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos marcados con (*) son obligatorios.
        /// </summary>
        public static string Lbl_InformacionObligatoria {
            get {
                return ResourceManager.GetString("Lbl_InformacionObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificaciones de Contrato.
        /// </summary>
        public static string Lbl_Modificaciones_de_Contrato {
            get {
                return ResourceManager.GetString("Lbl_Modificaciones de Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OST.
        /// </summary>
        public static string Lbl_OST {
            get {
                return ResourceManager.GetString("Lbl_OST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informes de Carpeta de Arranque.
        /// </summary>
        public static string Lnk_Informe_Carpeta_Arranque {
            get {
                return ResourceManager.GetString("Lnk_Informe_Carpeta_Arranque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        public static string Phl_OST {
            get {
                return ResourceManager.GetString("Phl_OST", resourceCulture);
            }
        }
    }
}
